Jenkinsfile

HOP-4144: fix build script

---

Jenkinsfile

HOP-4144: fix the build

---

Jenkinsfile
docker/Dockerfile.dataflowTemplate
docker/Dockerfile.web-fatjar

HOP-4144: fix filepath and simplify buildscript

---

engine/src/main/java/org/apache/hop/resource/ResourceUtil.java
integration-tests/transforms/0047-multiway-merge-join.hpl
integration-tests/transforms/datasets/data-set-filename.csv
integration-tests/transforms/main-0047-multiway-join.hwf
integration-tests/transforms/metadata/dataset/golden-multiway-join.json
integration-tests/transforms/metadata/pipeline-run-configuration/local.json
integration-tests/transforms/metadata/unit-test/0047-multiway-merge-join UNIT.json
plugins/transforms/multimerge/src/main/java/org/apache/hop/pipeline/transforms/multimerge/MultiMergeJoin.java

HOP-4165, HOP-4489

---

docs/hop-dev-manual/modules/ROOT/pages/integration-testing.adoc

fix: typo in Running tests locally section

---

pom.xml

HOP-4549: Update maven-jar-plugin from 2.6 to 3.2

---

assemblies/plugins/transforms/regexeval/src/assembly/assembly.xml
plugins/transforms/regexeval/src/main/java/org/apache/hop/pipeline/transforms/regexeval/RegexEvalDialog.java

Add ColumnResizer
Fix column type can select only existing type
Fix assembly base directory

HOP-4558 Regex Transform - Format needs to be wider sizer

---

docs/hop-user-manual/modules/ROOT/pages/workflow/actions/pgpencryptfiles.adoc

Clarifying the requirements of the GnuPG package for this to function …

(DOC) - Update pgpencryptfiles.adoc to clarify GnuPG dependency 

---

Jenkinsfile.hop-web-selenium
integration-tests/hopweb/Dockerfile
integration-tests/hopweb/docker-compose.yml
integration-tests/hopweb/pom.xml
integration-tests/hopweb/src/test/java/org/apache/hop/ui/hopgui/HopWebTest.java
integration-tests/hopweb/src/test/java/org/apache/hop/ui/hopgui/ScreenshotUtil.java
integration-tests/hopweb/src/test/resources/hopwebtest-docker.properties
integration-tests/hopweb/src/test/resources/hopwebtest.properties
integration-tests/hopweb/src/test/resources/run-tests.sh
integration-tests/hopweb/src/test/resources/transforms.csv

initial PR for a first version of Selenium tests. This PR creates a new pipeline and walks through a list of transforms. For each transform, the transform is added to the pipeline, its dialog is opened and closed, and finally the transform is deleted. 
If a test fails, Hop Web is refreshed and a new pipeline is created before the transform loop continues. 
There currently are 44 out of 164 test failures that need to be investigated (there may/will be issues in the test code, most of the failures are dialogs issues that need to be looked into. 
All test can (should) be run in Docker Compose via integration-tests/hopweb/docker-compose.yml.
for the change (usually before you start working on it).  Trivial …

HOP-4550 - initial version of Selenium tests 

---

Jenkinsfile.hop-web-selenium

HOP-4550: fix error in Jenkinsfile

---

Jenkinsfile.hop-web-selenium

HOP-4550: fix file paths

---

integration-tests/hopweb/Dockerfile

HOP-4550: fix copy in reference to new context

---

integration-tests/hopweb/docker-compose.yml

HOP-4550: fix mount point

---

integration-tests/hopweb/docker-compose.yml

HOP-4550: link compose containers, remove host binding

---

Jenkinsfile.hop-web-selenium
integration-tests/hopweb/docker-compose.yml
integration-tests/hopweb/src/test/resources/run-tests.sh

HOP-4550: Attempt to get it working in jenkins

---

Jenkinsfile.hop-web-selenium

HOP-4550: add sleep to avoid collecting open files

---

.gitignore
Jenkinsfile.hop-web-selenium

HOP-4550: move images before compressing

---

Jenkinsfile.hop-web-selenium

HOP-4550: move image files before compressing

---

Jenkinsfile.hop-web-selenium
integration-tests/hopweb/src/test/resources/transforms.bak

HOP-4550: fixing png files

---

Jenkinsfile.hop-web-selenium

HOP-4550: fix image gathering

---

Jenkinsfile.hop-web-selenium

HOP-4550: escape literal

---

Jenkinsfile.hop-web-selenium

HOP-4550: allow empty

---

Jenkinsfile.hop-web-selenium
integration-tests/hopweb/Dockerfile
integration-tests/hopweb/docker-compose.yml
integration-tests/hopweb/pom.xml
integration-tests/hopweb/src/test/java/org/apache/hop/ui/hopgui/HopWebTest.java
integration-tests/hopweb/src/test/resources/hopwebtest-docker.properties
integration-tests/hopweb/src/test/resources/hopwebtest.properties
integration-tests/hopweb/src/test/resources/run-tests.sh

HOP-4550: change way tests are run

---

Jenkinsfile.hop-web-selenium

HOP-4550: gather images

---

integration-tests/hopweb/src/test/java/org/apache/hop/ui/hopgui/HopWebTest.java

HOP-4550: increase wait times

---

integration-tests/hopweb/src/test/java/org/apache/hop/ui/hopgui/HopWebTest.java
integration-tests/hopweb/src/test/resources/transforms.csv

HOP-4550: tweak waittime and enable all transforms

---

docker/integration-tests/integration-tests-cassandra.yaml
docker/integration-tests/resource/cassandra/cassandra.yaml

HOP-3955: increase cassandra wait times for integration tests

---

docs/hop-user-manual/modules/ROOT/pages/hop-run/index.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-conf/hop-conf.adoc
engine/src/main/java/org/apache/hop/run/HopRun.java
plugins/misc/projects/src/main/java/org/apache/hop/projects/project/ManageProjectsOptionPlugin.java
plugins/misc/projects/src/main/java/org/apache/hop/projects/var/ManageConfigFileOptionPlugin.java

HOP-4574, HOP-4627

---

docker/integration-tests/resource/cassandra/cassandra.yaml

[IT] Increase Cassandra waittimes

---

integration-tests/cassandra/disabled.txt
integration-tests/scripts/run-tests-docker.sh

[IT] Disable cassandra tests

---

assemblies/plugins/databases/postgresql-assemblies/pom.xml
docs/hop-user-manual/modules/ROOT/pages/database/databases/postgresql.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/getting-started-with-beam.adoc
plugins/databases/postgresql/pom.xml
plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/HopPipelineMetaToBeamPipelineConverter.java
plugins/transforms/pgbulkloader/pom.xml

HOP-4630: fix jobnames for regular beam jobs

---

.asf.yaml
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml
.github/pull_request_template.md

[GITHUB] activate issues and add templates

---

assemblies/lib/pom.xml
assemblies/plugins/actions/getpop/pom.xml
assemblies/plugins/actions/getpop/src/assembly/assembly.xml
assemblies/plugins/actions/mail/pom.xml
assemblies/plugins/actions/mail/src/assembly/assembly.xml
assemblies/plugins/transforms/javascript/pom.xml
assemblies/plugins/transforms/javascript/src/assembly/assembly.xml
assemblies/plugins/transforms/mail/pom.xml
assemblies/plugins/transforms/mail/src/assembly/assembly.xml
assemblies/plugins/transforms/mailinput/pom.xml
assemblies/plugins/transforms/mailinput/src/assembly/assembly.xml

Move Jakarta activation to main lib as it was duplicated 6 times

HOP-4642: move jakarta mail to main lib

---

engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransform.java
engine/src/test/java/org/apache/hop/workflow/action/ActionSerializationTestUtil.java
plugins/actions/repeat/src/main/java/org/apache/hop/workflow/actions/repeat/RepeatDialog.java
plugins/engines/beam/src/main/java/org/apache/hop/beam/gui/PipelineExecutionViewerUpdateXP.java
plugins/misc/async/src/main/java/org/apache/hop/www/async/xp/ActionLogIconClickedExtensionPoint.java
plugins/misc/projects/src/main/java/org/apache/hop/projects/environment/LifecycleEnvironmentDialog.java
plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/gui/DataProbeGuiPlugin.java
plugins/misc/testing/src/main/java/org/apache/hop/testing/gui/TestingGuiPlugin.java
plugins/misc/testing/src/main/java/org/apache/hop/testing/xp/LocationMouseDoubleClickExtensionPoint.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/actions/cypherscript/CypherScript.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/execution/NeoExecutionInfoLocation.java
plugins/tech/neo4j/src/test/java/org/apache/hop/neo4j/actions/cypherscript/CypherScriptTest.java
plugins/tech/neo4j/src/test/resources/cypher-script-action.xml
ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataManager.java
ui/src/main/java/org/apache/hop/ui/core/widget/MetaSelectionLine.java
ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
ui/src/main/java/org/apache/hop/ui/hopgui/context/metadata/MetadataContextHandler.java
ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiAuditDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/dialog/MetadataExplorerDialog.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/ExecutionPerspective.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java
ui/src/main/java/org/apache/hop/ui/hopgui/search/HopGuiMetadataSearchable.java
ui/src/main/java/org/apache/hop/ui/hopgui/shared/BaseExecutionViewer.java
ui/src/main/java/org/apache/hop/ui/www/service/WebServiceGuiPlugin.java

Fixes #1850 : Workflow executor causes exception saving Execution Information
Fixes #1851 : Some SWT dialogs aren't correctly parented
HOP-4432 : Cleanup XML of action Neo4j Cypher

Code hardening: #1850, #1851, HOP-4432

---

.dockerignore

[IT] fix gcp key in docker context

---

.asf.yaml

change notification scheme

---

.asf.yaml

fix notification scheme

---

docs/hop-dev-manual/antora.yml
docs/hop-tech-manual/antora.yml
docs/hop-user-manual/antora.yml

[RELEASE] update documentation tags

---

CONTRIBUTING.md
README.md
assemblies/static/src/main/resources/README.txt
docs/hop-dev-manual/modules/ROOT/pages/apache-release/creating-a-release.adoc
docs/hop-dev-manual/modules/ROOT/pages/integration-testing.adoc
docs/hop-dev-manual/modules/ROOT/pages/internationalisation.adoc
docs/hop-dev-manual/modules/ROOT/pages/setup-dev-environment.adoc
docs/hop-tech-manual/modules/ROOT/pages/hop-vs-kettle/if-you-know-kettle.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/pipeline-run-configurations/beam-dataflow-pipeline-engine.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/beamkinesisconsume.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/beamkinesisproduce.adoc
pom.xml

#1923: move references from Jira to GitHub

---

ui/src/main/java/org/apache/hop/ui/hopgui/welcome/WelcomeDialogOptions.java
ui/src/main/resources/org/apache/hop/ui/hopgui/messages/messages_en_US.properties
ui/src/main/resources/org/apache/hop/ui/hopgui/messages/messages_it_IT.properties
ui/src/main/resources/org/apache/hop/ui/hopgui/welcome/messages/messages_en_US.properties
ui/src/main/resources/org/apache/hop/ui/hopgui/welcome/messages/messages_it_IT.properties

Fixed some italian translations that got  broken after latest code changes/additions

[TRANSLATIONS] Fixed some italian translations

---

ui/src/main/java/org/apache/hop/ui/core/PropsUi.java

Fix #2018: Add tweak for Windows dark theme

---

integration-tests/hopweb/src/test/resources/transforms.bak
integration-tests/hopweb/src/test/resources/transforms.csv

#2023 : remove other failing transforms for now

---

docs/hop-user-manual/modules/ROOT/pages/hop-run/index.adoc

- [] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

added tabs sections for Windows and Linux/MacOS samples #2044

---

core/src/main/java/org/apache/hop/core/Condition.java
integration-tests/transforms/0057-filter-rows-basic-old.hpl
integration-tests/transforms/datasets/golden-filter-rows-old.csv
integration-tests/transforms/main-0057-filter-rows.hwf
integration-tests/transforms/metadata/dataset/golden-filter-rows-old.json
integration-tests/transforms/metadata/unit-test/0057-filter-rows-basic-old UNIT.json

Fix Filter rows regression issue

Fix #2060: regression on filter rows

---

integration-tests/actions/main-0005-run-pipeline-unit-test-with-not-exist-file.hwf
integration-tests/actions/main-0007-run-pipeline-unit-test-with-not-exist-file.hwf

adds integration test for NPE running UnitTest

#2064: adds integration test for NPE running UnitTest

---

docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/getting-started/hop-tools.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-run/index.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-server/index.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-conf/hop-conf-projects.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-conf/hop-conf-run-hpl-hwf.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-conf/hop-conf.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-encrypt.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-import.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-search.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-translator.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/beam-samples-flink.adoc
docs/hop-user-manual/modules/ROOT/pages/plugins/projects/projects.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/hop-tools/hop-import.adoc

#2072 - updated examples, tabs for windows and linux/mac 

---

.asf.yaml

add karta020500 (brianh) as collaborator

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml
.github/workflows/self_assign.yml

[GHA] add self-assign option

---

.github/issue-rules.yml
.github/workflows/issue_tagger.yml

[GHA] Add auto priority labels

---

assemblies/plugins/transforms/xml/pom.xml
assemblies/plugins/transforms/xml/src/assembly/assembly.xml
core/src/main/java/org/apache/hop/core/row/IValueMeta.java
integration-tests/xml/0004-xsl-transformation.hpl
integration-tests/xml/files/wellFormed1.xml
integration-tests/xml/files/wellFormed2.xml
integration-tests/xml/files/xsl.xsl
integration-tests/xml/main-0004-xsl-transformation.hwf

- Add missing dependency
- Fix wrong translations lookup

Fix #2067 and #2087

---

docker/integration-tests/integration-tests-base.yaml
docker/integration-tests/resource/dummyfile
integration-tests/scripts/run-tests-docker.sh

fix #2096: add sane default for GCP_KEY

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml
.github/issue-rules.yml
.github/pr-rules.yml
.github/workflows/pr_tagger.yml

Expand the Issue tagger and add a PR Tagger. Add some extra information about the commands you can use

[BUILD] Issue tagger, PR Tagger and commands

---

plugins/transforms/streamschemamerge/src/main/resources/org/apache/hop/pipeline/transforms/streamschemamerge/messages/messages_it_IT.properties

[FIX] Fixed wrong filename and performed the translation of its content to italian

---

docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/community-blogs/index.adoc

initial version of community docs page #2164

---

.github/pull_request_template.md

fixed typo licenced -> licensed

---

assemblies/plugins/databases/hive-assemblies/pom.xml
assemblies/plugins/databases/hive-assemblies/src/assembly/assembly.xml
docker/integration-tests/integration-tests-spark.yaml
docker/integration-tests/spark/scripts/master.sh
integration-tests/spark/0003-read-hive-date.hpl
integration-tests/spark/0003-write-hive-date.hpl
integration-tests/spark/dev-env-config.json
integration-tests/spark/main-0002-test-hive-connection.hwf
integration-tests/spark/main-0003-test-hive-write-read.hwf
integration-tests/spark/metadata/rdbms/hive.json
plugins/databases/hive/pom.xml

#2143 - hive standalone dependency + integration tests 

---

plugins/actions/writetolog/src/main/java/org/apache/hop/workflow/actions/writetolog/ActionWriteToLogDialog.java

Already implemented in TextVar

Fix #2156 : Insert a variable in Write to log action with Ctrl+Space

---

docs/hop-user-manual/modules/ROOT/pages/hop-run/index.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-search/index.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-conf/hop-conf.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-import.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-search.adoc
engine/src/main/java/org/apache/hop/config/HopConfig.java
engine/src/main/java/org/apache/hop/core/HopVersionProvider.java
engine/src/main/java/org/apache/hop/imp/HopImport.java
engine/src/main/java/org/apache/hop/run/HopRun.java
engine/src/main/java/org/apache/hop/search/HopSearch.java
ui/src/main/java/org/apache/hop/ui/hopgui/dialog/AboutDialog.java

Add option -v --version to print version in the CLI:
- hop-conf
- hop-run
- hop-search
- hop-import

Add option -v --version to print version in the CLI #2153

---

core/src/main/java/org/apache/hop/core/logging/LogLevel.java
plugins/actions/pipeline/src/main/java/org/apache/hop/workflow/actions/pipeline/ActionPipeline.java
plugins/actions/pipeline/src/main/java/org/apache/hop/workflow/actions/pipeline/ActionPipelineDialog.java
plugins/actions/workflow/src/main/java/org/apache/hop/workflow/actions/workflow/ActionWorkflow.java
plugins/actions/workflow/src/main/java/org/apache/hop/workflow/actions/workflow/ActionWorkflowDialog.java
plugins/actions/workflow/src/main/java/org/apache/hop/workflow/actions/workflow/ActionWorkflowRunner.java
ui/src/main/java/org/apache/hop/ui/core/widget/MetaSelectionLine.java
ui/src/main/java/org/apache/hop/ui/workflow/actions/ActionBaseDialog.java
ui/src/main/resources/org/apache/hop/ui/workflow/actions/messages/messages_en_US.properties

- Cleanup XML of action Workflow #2002 and Pipeline #1986
- Use MetaSelectionLine for RunConfiguration in Workflow and Pipeline action #2075
- Implement IEnumHasCodeAndDescription to LogLevel class

Cleanup XML of action Workflow #2002 and Pipeline #1986

---

docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/metadata-types/pipeline-probe.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/pipeline-data-probe.adoc
plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/transform/PipelineDataProbeMeta.java
plugins/misc/reflection/src/main/samples/metadata/pipeline-probe/pipeline-probe-example.json
plugins/misc/reflection/src/main/samples/pipeline-probe/pipeline-probe-example.hpl
plugins/misc/reflection/src/main/samples/pipeline-probe/pipeline-probe-generate-fake-books.hpl

#2150 - pipeline probe documentation and samples

---

plugins/actions/columnsexist/src/main/java/org/apache/hop/workflow/actions/columnsexist/ActionColumnsExist.java

fix #2149: columnexists not working correctly

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/enhancedjsonoutput.adoc

Some spellings were wrong, and the resulting data was not following the configuration provided just before.

enhancedjsonoutput.adoc: Fix grammar and examples

---

.github/issue-rules.yml

[INFRA] Add label rule for Actions

---

NOTICE

fix #2166: update year number in Notice

---

assemblies/plugins/databases/hive-assemblies/pom.xml
assemblies/plugins/databases/hive-assemblies/src/assembly/assembly.xml
plugins/databases/hive/pom.xml

fix regression issue due to #2143

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/getting-started-with-beam.adoc

[DOC] update Beam version info for new release

---

docs/hop-dev-manual/antora.yml
docs/hop-tech-manual/antora.yml
docs/hop-user-manual/antora.yml

[RELEASE] Update doc versions

---

docs/hop-user-manual/modules/ROOT/pages/community-blogs/index.adoc

updated header, heading levels. fixes #2204

---

docs/hop-user-manual/modules/ROOT/pages/community-blogs/index.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-run/index.adoc

2214 - add possible hop-run exit codes to the docs

---

plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_de_DE.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_en_US.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_es_AR.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_es_ES.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_fr_FR.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_it_IT.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_ja_JP.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_ko_KR.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_nl_NL.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_no_NO.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_pt_BR.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_pt_PT.properties
plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_zh_CN.properties

Add empty translation files

---

docs/hop-user-manual/modules/ROOT/pages/projects/index.adoc

[DOC] remove variable notation from HOP_CONFIG_FOLDER

---

docs/hop-user-manual/modules/ROOT/pages/workflow/actions/workflow.adoc

updated workflow action docs, fixes #2145

---

integration-tests/hop_server/0004-repeat_pipeline.hpl

#2187 Add header to pipeline

---

.asf.yaml

[INFRA] Move PR mails to issues@

---

plugins/transforms/regexeval/src/main/java/org/apache/hop/pipeline/transforms/regexeval/RegexEvalHelperDialog.java
ui/src/main/java/org/apache/hop/ui/core/gui/GuiResource.java

- Replace widget background colors with icons
- Remove TabFolder
- Add dark red and green colors
- Use fixed font

Refactor Regexp Test UI #2280

---

docs/hop-user-manual/modules/ROOT/pages/hop-server/index.adoc
engine/src/main/java/org/apache/hop/www/HopServer.java

fix #2393 Hop Server no longer can be started by name

---

engine/src/main/java/org/apache/hop/execution/remote/RemoteExecutionInfoLocation.java
engine/src/main/java/org/apache/hop/server/HopServer.java
engine/src/main/java/org/apache/hop/www/HopServer.java
engine/src/main/java/org/apache/hop/www/RegisterExecutionInfoServlet.java
integration-tests/hop_server/0005-read-from-remote-location.hpl
integration-tests/hop_server/0005-verify-executions-logged.hpl
integration-tests/hop_server/main-0005-remote-execution-location.hwf
integration-tests/hop_server/metadata/pipeline-run-configuration/local-remote-location.json
integration-tests/hop_server/metadata/pipeline-run-configuration/remote-no-linked-resources.json

Fix for issue #2320 : The Execution Information Perspective from Remote Location returns a HopException

Fix for issue #2320 : Execution Information Perspective for Remote Location fails

---

docker/Dockerfile.web
docker/resources/run-web.sh
docs/hop-user-manual/modules/ROOT/pages/hop-gui/hop-web.adoc

Hop Web: projects and environment startup options, fixed CLI tools #2432, #2433

---

plugins/transforms/detectemptystream/src/main/samples/transforms/detect-empty-stream-basic.hpl
plugins/transforms/dynamicsqlrow/src/main/samples/transforms/dynamic-sql-row.hpl

dynamic sql row and detect empty stream samples #2237

---

docs/hop-tech-manual/modules/ROOT/pages/docker-container.adoc

updated java 11 reference, removed duplicate hop server port reference #2391

---

core/src/main/java/org/apache/hop/core/Const.java
pom.xml

Specification-Version: 2.4
Implementation-Version: 2.4.0-SNAPSHOT (2023-02-13 08.50.52)

Maven add the build date in the MANIFEST.MF file to complete issue #2153

---

plugins/transforms/blockuntiltransformsfinish/src/main/java/org/apache/hop/pipeline/transforms/blockuntiltransformsfinish/BlockUntilTransformsFinish.java

Code hardening for a race condition.

fix for issue #2461

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/verticabulkloader.adoc
integration-tests/vertica/0003-vertica-bulk-load-truncate.hpl
integration-tests/vertica/main-0003-vertica-bulk-load-truncate.hwf
plugins/transforms/verticabulkloader/src/main/java/org/apache/hop/pipeline/transforms/vertica/bulkloader/VerticaBulkLoader.java
plugins/transforms/verticabulkloader/src/main/java/org/apache/hop/pipeline/transforms/vertica/bulkloader/VerticaBulkLoaderDialog.java
plugins/transforms/verticabulkloader/src/main/java/org/apache/hop/pipeline/transforms/vertica/bulkloader/VerticaBulkLoaderMeta.java
plugins/transforms/verticabulkloader/src/main/resources/org/apache/hop/pipeline/transforms/vertica/bulkloader/messages/messages_en_US.properties

added truncate table and truncate on first row options #2111

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
plugins/transforms/formula/src/main/resources/org/apache/hop/pipeline/transforms/formula/function/functions.xml

removed yesterday function from formula plugin and docs. fixes #2464

---

ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java

Add Border to the workflow graph like the pipeline graph.

Remove orange from pipeline execution result panel #2477

---

plugins/databases/duckdb/src/main/java/org/apache/hop/databases/duckdb/DuckDBDatabaseMeta.java

added timestamp support. fixes #2475

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/project/ManageProjectsOptionPlugin.java

added missing ProjectsConfig.saveConfig() to modifyProject. fixes #2494

---

integration-tests/actions/0008-zip-action-archive-files.hwf
integration-tests/actions/0008-zip-action-generate-files-to-zip.hpl
integration-tests/actions/main-0008-zip-files.hwf
plugins/actions/zipfile/src/main/java/org/apache/hop/workflow/actions/zipfile/ActionZipFile.java

fixed zip action close order  + integration test #2498

---

assemblies/lib-beam/pom.xml
assemblies/plugins/tech/google/pom.xml
docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/getting-started-with-beam.adoc
engine-beam/pom.xml
plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/fatjar/FatJarBuilder.java
pom.xml

Update Beam to 2.45.0, fixes #2500

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc

corrected comma instead of semicolon. fixes #2493

---

pom.xml

reverted jetty upgrade. fixes #2521

---

assemblies/plugins/databases/cache-assemblies/pom.xml
assemblies/plugins/databases/cache-assemblies/src/assembly/assembly.xml

remove empty caché jdbc driver, fixes #2496

---

integration-tests/spreadsheet/0008-read-large-xlsx-file.hpl
integration-tests/spreadsheet/main-0008-read-large-xlsx.hwf
plugins/transforms/excel/src/main/java/org/apache/hop/pipeline/transforms/excelinput/staxpoi/StaxPoiWorkbook.java

Allow reading of large xlsx files, fixes #2307

---

integration-tests/samples/metadata/pipeline-run-configuration/local.json
integration-tests/vertica/metadata/pipeline-run-configuration/local.json

cleanup incorrect references, fixes #2535

---

integration-tests/beam_directrunner/0007-group-by-validation.hpl
integration-tests/beam_directrunner/0009-stream-lookup-validation.hpl

Integration tests were using incorrect conversion mask, #2474

---

docker/integration-tests/integration-tests-mongo.yaml
integration-tests/mongo/dev-env-config.json
integration-tests/mongo/metadata/mongodb-connection/mongo.json
integration-tests/mongo/tests/mongo-delete/delete-3-customers-json-test.hpl
integration-tests/mongo/tests/mongo-delete/delete-5-customers-test.hpl
plugins/transforms/mongodb/src/main/java/org/apache/hop/mongo/metadata/MongoDbConnection.java

This included the fixing of the unit-tests, mongo hasn't been working for a while it seems.

Allow usage of Encrypted password in mongo connection, fixes #2241

---

engine/src/main/java/org/apache/hop/base/BaseHopMeta.java
engine/src/main/java/org/apache/hop/pipeline/PipelineHopMeta.java
engine/src/main/java/org/apache/hop/workflow/WorkflowHopMeta.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/context/HopGuiWorkflowHopContext.java

Fix Start Action can have conditional output #2545

---

assemblies/plugins/databases/hive-assemblies/pom.xml
docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/technology/memgraph/index.adoc
docs/hop-user-manual/modules/ROOT/pages/technology/technology.adoc
plugins/databases/hive/pom.xml
plugins/misc/projects/src/main/java/org/apache/hop/projects/config/ProjectsConfigOptionPlugin.java

memgraph initial doc version, eap project/environment options #2566 #2511

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml

Allow multiple component selection, fixes #2575

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml
.github/issue-rules.yml

Add API component to GitHub Templates, fixes #2599

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
plugins/transforms/formula/src/main/resources/check-doc-vs-functions.hpl
plugins/transforms/formula/src/main/resources/org/apache/hop/pipeline/transforms/formula/function/functions.xml
plugins/transforms/formula/src/main/samples/transforms/formula-datetime.hpl

#2571 formula cleanup: removed nonimplemented functions, check functions.xml vs docs

---

plugins/actions/pipeline/src/main/java/org/apache/hop/workflow/actions/pipeline/ActionPipeline.java
plugins/actions/pipeline/src/main/java/org/apache/hop/workflow/actions/pipeline/ActionPipelineDialog.java
plugins/actions/workflow/src/main/java/org/apache/hop/workflow/actions/workflow/ActionWorkflow.java
plugins/actions/workflow/src/main/java/org/apache/hop/workflow/actions/workflow/ActionWorkflowDialog.java

fix parameters for #2002 and #1986

---

integration-tests/hopweb/pom.xml
integration-tests/hopweb/src/test/java/org/apache/hop/ui/hopgui/HopWebTest.java

selenium upgrade, extra option flag to get chrome working, fixes #2760

---

engine/src/main/java/org/apache/hop/execution/ExecutionState.java
engine/src/main/java/org/apache/hop/execution/ExecutionStateBuilder.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/execution/NeoExecutionInfoLocation.java
plugins/transforms/execinfo/src/main/java/org/apache/hop/pipeline/transforms/execinfo/ExecInfo.java
plugins/transforms/execinfo/src/main/java/org/apache/hop/pipeline/transforms/execinfo/ExecInfoMeta.java
rest/src/main/java/org/apache/hop/rest/v1/resources/PluginsResource.java

Issue #2544 : Execution state doesn't contain an end date

---

integration-tests/transforms/0042-formula-datetime.hpl
plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/Formula.java

Added an extra Timestamp field to the integration test to verify that "double" POI date calculations can convert to Timestamp as well as Date (as was already tested).

Fix for issue #2767 : Formula should be able to convert from doubles to Timestamp

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/getting-started-with-beam.adoc

[DOC] update beam version in docs

---

plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_de_DE.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_en_US.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_es_AR.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_es_ES.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_fr_FR.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_it_IT.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_ja_JP.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_ko_KR.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_nl_NL.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_no_NO.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_pt_BR.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_pt_PT.properties
plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_zh_CN.properties

[TRANSLATIONS] add empty message files for validator

---

plugins/transforms/calculator/src/main/java/org/apache/hop/pipeline/transforms/calculator/Calculator.java

Enable binary encode/decode in Calculator
- [] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

FIX #2776 Enable binary encode/decode in Calculator

---

ui/src/main/java/org/apache/hop/ui/core/database/dialog/GetPreviewTableProgressDialog.java
ui/src/main/java/org/apache/hop/ui/pipeline/dialog/PipelinePreviewProgressDialog.java

do not show progress dialog in hop web. fixes #2736

---

docs/hop-dev-manual/modules/ROOT/pages/apache-release/promoting-a-release.adoc

[DOC] add dataflow template to release notes

---

docs/hop-dev-manual/modules/ROOT/pages/apache-release/promoting-a-release.adoc

[DOC] fix dataflow release docs

---

plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/graph/GraphOutputMeta.java

added default batch size of 1000 to Neo4j Graph Output. fixes #2782

---

docs/hop-user-manual/modules/ROOT/pages/index.adoc

On the front page of the user manual, JIRA was still mentioned. It is replaced by a link to github issues.

[Doc] Replace Jira ticket by Github issue

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/filterrows.adoc
plugins/transforms/filterrows/src/main/samples/metadata-injection/filter-rows-mdi-child.hpl
plugins/transforms/filterrows/src/main/samples/metadata-injection/filter-rows-mdi-parent.hpl

added metadata injection samples, extended documentation. fixes #2784

---

plugins/engines/beam/src/main/java/org/apache/hop/beam/transforms/bq/BeamBQInputDialog.java
plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/bq/messages/messages_en_US.properties

add extra check and message when table not found, fixes #2808

---

docs/hop-dev-manual/modules/ROOT/pages/apache-release/promoting-a-release.adoc

[DOC] add hop-web Beam version to release documentation

---

plugins/transforms/propertyinput/src/main/java/org/apache/hop/pipeline/transforms/propertyinput/PropertyInputDialog.java

check nulll values before opening dialog. fixes #2825

---

docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/workflow/actions/getpop.adoc

updated documatation for pop3/imap action. fixes #2659

---

assemblies/plugins/actions/snowflake/pom.xml
assemblies/plugins/databases/snowflake-assemblies/pom.xml
assemblies/plugins/tech/azure/pom.xml
assemblies/plugins/transforms/json/pom.xml
assemblies/plugins/transforms/snowflake/pom.xml
integration-tests/json/0003-json-test-block-size.hpl
integration-tests/json/0003-json-write-block-size.hpl
integration-tests/json/0004-json-write-block-size-in-field.hpl
integration-tests/json/main-0003-json-test-block-size.hwf
integration-tests/json/main-0004-json-test-block-size-in-field.hwf
plugins/transforms/json/pom.xml
plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutput/JsonOutput.java
plugins/transforms/snowflake/pom.xml
pom.xml

fix json input transform error #2870, update snowflake jdbc driver #2871, Json output fix #2839

---

docker/integration-tests/integration-tests-neo4j.yaml
integration-tests/neo4j/dev-env-config.json
integration-tests/neo4j/metadata/neo4j-graph-model/model-2812.json
integration-tests/neo4j/tests/neo4j-2812-graph-model-with-spaces-in-key-names/2812-check-graph.hpl
integration-tests/neo4j/tests/neo4j-2812-graph-model-with-spaces-in-key-names/2812-model-with-spaces-in-key-names.hpl
integration-tests/neo4j/tests/neo4j-2812-graph-model-with-spaces-in-key-names/main-2812-model-with-spaces-in-key-names.hwf
integration-tests/samples/read-samples-build-hop-run.hpl
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/graph/GraphOutput.java

special characters in graph properties, exclude child hpl/hwf from samples IT #2812 #2237

---

CONTRIBUTING.md
docs/hop-user-manual/modules/ROOT/pages/installation-configuration.adoc
docs/hop-user-manual/modules/ROOT/pages/supported-jvms.adoc

changed JIRA links to GitHub issues links. fixes #2891

---

docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/how-to-guides/workflows-parallel-execution.adoc

fixed xref link, added navigation. #2336

---

docs/hop-user-manual/modules/ROOT/pages/hop-gui/perspective-execution-information.adoc
engine/src/main/java/org/apache/hop/execution/ExecutionStateBuilder.java
engine/src/main/java/org/apache/hop/execution/IExecutionInfoLocation.java
engine/src/main/java/org/apache/hop/execution/local/FileExecutionInfoLocation.java
engine/src/main/java/org/apache/hop/execution/remote/RemoteExecutionInfoLocation.java
engine/src/main/java/org/apache/hop/pipeline/Pipeline.java
engine/src/main/java/org/apache/hop/pipeline/engines/local/LocalPipelineEngine.java
engine/src/main/java/org/apache/hop/run/HopRun.java
engine/src/main/java/org/apache/hop/www/GetExecutionInfoServlet.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/execution/NeoExecutionInfoLocation.java
ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/configuration/tabs/ConfigGeneralOptionsTab.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/PipelineExecutionViewer.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/WorkflowExecutionViewer.java
ui/src/main/java/org/apache/hop/ui/hopgui/shared/BaseExecutionViewer.java
ui/src/main/resources/org/apache/hop/ui/core/dialog/messages/messages_en_US.properties

Tested on local, remote and neo4j location with large logging sizes and large numbers of executions (>30k).
Fix for issue #2845 : improve loading time for execution information perspective with large number of executions
Fix for issue #2868 : hop-run exits too quickly to properly handle all finished listeners

Issues #2845, #2868

---

plugins/actions/writetolog/src/main/java/org/apache/hop/workflow/actions/writetolog/ActionWriteToLog.java
plugins/actions/writetolog/src/main/java/org/apache/hop/workflow/actions/writetolog/ActionWriteToLogDialog.java
plugins/transforms/writetolog/src/test/java/org/apache/pipeline/transforms/writetolog/WriteToLogMetaSymmetric.java

Cleanup XML of action Write To Log #2004

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/jdbcmetadata.adoc

- [] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

fixed url. fixes #2932

---

integration-tests/mdi/0027-bug-inject-metadata-parent.hpl
integration-tests/mdi/0027-bug-read-file-template-child.hpl
integration-tests/mdi/main-0027-inject-switch-case.hwf
plugins/transforms/metainject/src/main/java/org/apache/hop/pipeline/transforms/metainject/MetaInject.java
plugins/transforms/switchcase/src/main/java/org/apache/hop/pipeline/transforms/switchcase/SwitchCaseTarget.java

- Reset IO Meta after injection
- Fix metadata property translation

IndexOutOfBoundsException for Metadata Injection in Switch/Case #2934

---

plugins/databases/duckdb/pom.xml

upgraded duckdb dependency to 0.8.0. fixes #2948

---

core/src/main/java/org/apache/hop/core/Const.java
core/src/test/java/org/apache/hop/core/ConstTest.java
plugins/actions/sql/src/main/java/org/apache/hop/workflow/actions/sql/ActionSql.java
plugins/actions/sql/src/main/java/org/apache/hop/workflow/actions/sql/ActionSqlDialog.java
plugins/actions/sql/src/test/java/org/apache/hop/workflow/actions/sql/WorkflowActionSqlTest.java

I have change the Const.toBoolean() method to supports the value 'T' as TRUE for backwards compatibility with SQL Action serialization when switching to HopMetadateProperty.

Cleanup XML of action SQL #1994

---

plugins/tech/parquet/pom.xml
plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/output/ParquetOutputMeta.java

parquet version update and updated defaults. fixes #2902

---

assemblies/plugins/databases/sqlite-assemblies/pom.xml
assemblies/plugins/tech/cassandra/pom.xml
pom.xml

Update dependencies that we have controle over. fixes #2957

---

pom.xml
rap/pom.xml

Update SWT version, fixes #2975

---

pom.xml

fix broken jetty, fixes #2979

---

assemblies/plugins/engines/beam/pom.xml
assemblies/plugins/engines/beam/src/assembly/assembly.xml
docker/integration-tests/integration-tests-flink.yaml
plugins/engines/beam/pom.xml
plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/fatjar/FatJarBuilder.java
pom.xml

Apache Beam upgraded to 2.48.0. fixes #2981

---

engine/src/main/java/org/apache/hop/pipeline/PipelineMeta.java
engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransformMeta.java
engine/src/main/java/org/apache/hop/pipeline/transform/ITransformMeta.java
engine/src/test/java/org/apache/hop/history/AuditManagerTest.java
engine/src/test/java/org/apache/hop/pipeline/PipelineMetaTest.java
integration-tests/transforms/0044-join-rows-same-fields.hpl
integration-tests/transforms/datasets/golden-join-rows-same-fields-data.csv
integration-tests/transforms/datasets/golden-join-rows-same-fields-meta.csv
integration-tests/transforms/main-0044-join-rows.hwf
integration-tests/transforms/metadata/dataset/golden-join-rows-same-fields-data.json
integration-tests/transforms/metadata/dataset/golden-join-rows-same-fields-meta.json
integration-tests/transforms/metadata/unit-test/0044-join-rows-same-fields UNIT.json
plugins/transforms/joinrows/src/main/java/org/apache/hop/pipeline/transforms/joinrows/JoinRowsMeta.java

Fix for issue #2793 : Cartesian Product does not work on flows with the same row names

---

plugins/misc/projects/src/main/resources/org/apache/hop/projects/config/messages/messages_fr_FR.properties
plugins/misc/projects/src/main/resources/org/apache/hop/projects/config/messages/messages_it_IT.properties

[TRANS] Fixed some missing translations due to new features in rel 2.5

---

docs/hop-dev-manual/antora.yml
docs/hop-tech-manual/antora.yml
docs/hop-user-manual/antora.yml

[DOC] Update version

---

plugins/misc/debug/src/main/java/org/apache/hop/debug/action/ActionDebugGuiPlugin.java
plugins/misc/debug/src/main/java/org/apache/hop/debug/transform/TransformDebugGuiPlugin.java
plugins/misc/import/src/main/java/org/apache/hop/imports/gui/HopImportGuiPlugin.java
plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java
plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopGuiStartProjectLoad.java
plugins/misc/testing/src/main/java/org/apache/hop/testing/gui/TestingGuiPlugin.java
plugins/misc/testing/src/main/java/org/apache/hop/testing/xp/LocationMouseDoubleClickExtensionPoint.java
ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataManager.java
ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiAuditDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiFileDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineClipboardDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineHopDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineTransformDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowActionDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowClipboardDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/PipelineExecutionViewer.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/WorkflowExecutionViewer.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/search/HopSearchPerspective.java
ui/src/main/java/org/apache/hop/ui/www/service/WebServiceEditor.java

select shell on active display for popup dialogs. #2944

---

ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java

additional display checks for pipeline and workflow graphs. #2944

---

docs/hop-user-manual/modules/ROOT/assets/files/how-to-guides/apache-airflow/docker-compose.yaml
docs/hop-user-manual/modules/ROOT/pages/how-to-guides/run-hop-in-apache-airflow.adoc

fix unescaped variable, add missing docker.sock mount #3023

---

docs/hop-user-manual/modules/ROOT/pages/database/databases/googlebigquery.adoc

add missing jar to include list bigquery connection, #2739

---

plugins/transforms/json/pom.xml

[DEPENDABOT] add missing guava

---

.asf.yaml

[INFRA] make mail messages more readable

---

.asf.yaml

[INFRA] move the yaml to the correct location

---

assemblies/plugins/actions/snowflake/src/assembly/assembly.xml
docker/integration-tests/integration-tests-snmp.yaml
integration-tests/snmp/001-check-log.hpl
integration-tests/snmp/dev-env-config.json
integration-tests/snmp/hop-config.json
integration-tests/snmp/main-001-snmp-trap-test.hwf
integration-tests/snmp/metadata/pipeline-run-configuration/local.json
integration-tests/snmp/metadata/workflow-run-configuration/local.json
integration-tests/snmp/project-config.json
plugins/actions/snmptrap/src/main/java/org/apache/hop/workflow/actions/snmptrap/ActionSNMPTrap.java
plugins/actions/snmptrap/src/main/java/org/apache/hop/workflow/actions/snmptrap/ActionSNMPTrapDialog.java
plugins/actions/snmptrap/src/test/java/org/apache/hop/workflow/actions/snmptrap/ActionSNMPTrapTest.java
plugins/actions/snmptrap/src/test/java/org/apache/hop/workflow/actions/snmptrap/WorkflowActionSNMPTrapTest.java
plugins/actions/snmptrap/src/test/resources/snmp-trap-action.xml

task #1992 Cleanup XML of action SNMP Trap

---

assemblies/plugins/databases/h2-assemblies/pom.xml
assemblies/plugins/tech/cassandra/pom.xml
plugins/tech/cassandra/pom.xml

solve dependabot tickets

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/setvariable.adoc

It would be great to have some examples of default values here too

Update setvariable.adoc to define what a default value is

---

plugins/transforms/httppost/src/main/java/org/apache/hop/pipeline/transforms/httppost/HttpPostDialog.java

fix empty fieldlist, fixes #3018

---

integration-tests/hopweb/src/test/resources/transforms.csv
plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodbdelete/MongoDbDeleteDialog.java

mongoDb Delete widget disposed error and enable test, fixes #2971

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleImport.java

fix #2256 Kettle import: Formula step not migrated correctly
fix #3043 Kettle import is not migrating correctly the Set Variable Action

fix #2256, #3043

---

plugins/transforms/dorisbulkloader/src/main/java/org/apache/hop/pipeline/transforms/dorisbulkloader/DorisBulkLoaderMeta.java

fix #2121 the data field not save correctly

fix #2121 the data field not save correctly

---

docs/hop-user-manual/modules/ROOT/pages/hop-gui/shortcuts.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getvariable.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/variables/control-space.adoc
docs/hop-user-manual/modules/ROOT/pages/variables.adoc

document available variables in CTRL-Space popup. fixes #3080

---

docker/integration-tests/integration-tests-snmp.yaml

[IT] fix snmp test

---

plugins/misc/testing/src/main/java/org/apache/hop/testing/gui/TestingGuiPlugin.java

rollback use of getActiveDisplay. #2944

---

helm/hop/Chart.yaml

update chart for next release , #3047

---

plugins/transforms/pipelineexecutor/src/main/java/org/apache/hop/pipeline/transforms/pipelineexecutor/PipelineExecutorMeta.java
plugins/transforms/workflowexecutor/src/main/java/org/apache/hop/pipeline/transforms/workflowexecutor/WorkflowExecutorMeta.java

updates doc links for pipeline, workflow executor. #3083

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/setvariable.adoc
docs/hop-user-manual/modules/ROOT/pages/variables.adoc

updated variables and set variables doc pages #3095

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopGuiFileDefaultFolder.java
ui/src/main/java/org/apache/hop/ui/core/PropsUi.java

Add file history to vfs-dialog, fixes #2222

---

plugins/transforms/dimensionlookup/src/main/java/org/apache/hop/pipeline/transforms/dimensionlookup/DimensionLookup.java

Reinforce the code to avoid NPE, I don't know if this solves the bug, but I'd like to see if @kleysonr can test a build.

Dimension lookup/update cache issue #2978

---

plugins/transforms/sortedmerge/src/main/java/org/apache/hop/pipeline/transforms/sortedmerge/SortedMergeDialog.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/DragViewZoomBase.java

More intuitive zoom and changed default for sorted merge

---

plugins/transforms/mergejoin/src/main/java/org/apache/hop/pipeline/transforms/mergejoin/MergeJoinDialog.java
ui/src/main/java/org/apache/hop/ui/core/ConstUi.java

Replace CCombo with Combo widget

Merge join transform: select key from incoming fields #3141

---

plugins/transforms/insertupdate/src/main/java/org/apache/hop/pipeline/transforms/insertupdate/InsertUpdateDialog.java

change default for update boolean when not specifying, fixes #3145

---

ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiFileDelegate.java

fix issue introduced in #3109

---

assemblies/lib-beam/pom.xml
assemblies/lib/pom.xml
assemblies/plugins/engines/beam/pom.xml
assemblies/plugins/engines/beam/src/assembly/assembly.xml
assemblies/plugins/tech/aws/pom.xml
assemblies/plugins/tech/azure/pom.xml
assemblies/plugins/tech/azure/src/assembly/assembly.xml
assemblies/plugins/tech/cassandra/src/assembly/assembly.xml
assemblies/plugins/tech/neo4j/pom.xml
assemblies/plugins/transforms/fake/pom.xml
assemblies/plugins/transforms/fake/src/assembly/assembly.xml
assemblies/plugins/transforms/yamlinput/pom.xml
assemblies/plugins/transforms/yamlinput/src/assembly/assembly.xml
plugins/engines/beam/pom.xml
plugins/tech/neo4j/pom.xml
plugins/transforms/fake/pom.xml
plugins/transforms/yamlinput/pom.xml
pom.xml

Removing some duplicate dependencies and upgrade some to cleanup trivy report

[DEP] Update dependencies and remove some duplicates

---

assemblies/lib-beam/pom.xml
engine-beam/pom.xml

there were 2 grpc dependencies in lib/beam, removed one of them

[DEP] remove duplicate dependency

---

integration-tests/gcp/disabled.txt

[IT] disable google tests for now

---

assemblies/plugins/engines/beam/pom.xml
docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/getting-started-with-beam.adoc
plugins/engines/beam/pom.xml
pom.xml

beam and bigtable version updates. fixes #3188

---

assemblies/plugins/tech/google/pom.xml
assemblies/plugins/tech/google/src/assembly/assembly.xml
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/google-sheets-input.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/google-sheets-output.adoc
integration-tests/spreadsheet/0009-read-google-sheet.hpl
integration-tests/spreadsheet/0010-write-google-sheet.hpl
plugins/misc/import/src/main/java/org/apache/hop/imports/gui/HopImportGuiPlugin.java
plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
plugins/tech/google/pom.xml
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsCredentials.java
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsInput.java
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsInputDialog.java
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsInputMeta.java
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsOutput.java
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsOutputDialog.java
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsOutputMeta.java

google sheets - additional options, doc updates and updates/fixes #3034

---

plugins/databases/oracle/src/main/java/org/apache/hop/databases/oracle/OracleDatabaseMeta.java
plugins/databases/oracle/src/test/java/org/apache/hop/databases/oracle/OracleDatabaseMetaTest.java

Add support for all PROCEDURE, FUNCTION and PACKAGE

Improve the way we get the list of DB procedures for oracle #3202

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/google-analytics.adoc
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googleanalytics/GoogleAnalytics.java

allow limit size 0 to fetch all rows. fixes #3205

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getvariable.adoc

Update getvariable.adoc - Adding whitespace

---

assemblies/static/src/main/resources/LICENSE

[RELEASE] License file update

---

docs/hop-dev-manual/antora.yml
docs/hop-tech-manual/antora.yml
docs/hop-user-manual/antora.yml

Update Doc versions

---

plugins/transforms/snowflake/src/main/java/org/apache/hop/pipeline/transforms/snowflake/bulkloader/SnowflakeBulkLoaderDialog.java

Connection is not visible in Snowflake bulk loader #3244

---

integration-tests/transforms/0042-formula-use-fields-created-in-previous-formula.hpl
integration-tests/transforms/datasets/golden-formula-use-fields-created-in-previous-formula.csv
integration-tests/transforms/main-0042-formula-use-fields-created-in-previous-formula.hwf
integration-tests/transforms/metadata/dataset/golden-formula-use-fields-created-in-previous-formula.json
integration-tests/transforms/metadata/unit-test/0042-formula-use-fields-created-in-previous-formula UNIT.json
plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/Formula.java

allow formula transform to use fields created in previous transforms.… #3239

---

plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsInputDialog.java
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsOutput.java
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsOutputDialog.java
plugins/tech/google/src/main/resources/org/apache/hop/pipeline/transforms/googlesheets/messages/messages_en_US.properties

variables resolution and i18n fixes in Google Sheets transfroms #3252

---

assemblies/lib-jdbc/pom.xml

lower monetdb driver to working version, #2129

---

assemblies/plugins/misc/git/pom.xml
assemblies/plugins/tech/parquet/pom.xml
docs/hop-user-manual/modules/ROOT/pages/database/databases/monetdb.adoc
engine-beam/pom.xml
plugins/misc/git/pom.xml
pom.xml

This PR contains some dependency upgrades to reduce the number of CVE's we are exposed to.

Documentation fix and dependency upgrades

---

integration-tests/transforms/0042-formula-nested-replace.hpl
integration-tests/transforms/datasets/golden-formula-nested-replace.csv
integration-tests/transforms/main-0042-formula-nested-replace.hwf
integration-tests/transforms/metadata/dataset/golden-formula-nested-replace.json
integration-tests/transforms/metadata/unit-test/0042-formula-nested-replace UNIT.json
plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/Formula.java
plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/util/FormulaParser.java

fixes to allow nested formulas on previously replaced fields #3239

---

assemblies/lib-jdbc/pom.xml
plugins/databases/duckdb/pom.xml

duckdb upgraded to 0.9.0. fixes #3256

---

pom.xml

Fix some High CVE warnings

---

ui/src/main/java/org/apache/hop/ui/pipeline/dialog/PipelineDialog.java
ui/src/main/java/org/apache/hop/ui/workflow/dialog/WorkflowDialog.java
ui/src/main/resources/org/apache/hop/ui/pipeline/dialog/messages/messages_en_US.properties
ui/src/main/resources/org/apache/hop/ui/workflow/dialog/messages/messages_en_US.properties

prevent creating unnamed parameters. fixes #3240

---

assemblies/plugins/transforms/drools/pom.xml
plugins/transforms/drools/pom.xml

Update Drools dependencies, fixes #3298

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/beam-samples-flink.adoc

[DOC] fix broken anchor

---

assemblies/lib-jdbc/pom.xml
plugins/databases/duckdb/pom.xml

duckdb upgrade to 0.9.1. fixes #3317

---

assemblies/plugins/transforms/excel/pom.xml
assemblies/plugins/transforms/formula/pom.xml
core/pom.xml
plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/redshift/bulkloader/RedshiftBulkLoader.java
plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/redshift/bulkloader/RedshiftBulkLoaderDialog.java
plugins/transforms/excel/pom.xml
plugins/transforms/excel/src/main/java/org/apache/hop/pipeline/transforms/excelwriter/ExcelWriterTransform.java
plugins/transforms/formula/pom.xml

Apache POI upgrade, Excel writer minor changes, Redshift bulk loader fields list #3281 #3310

---

plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/redshift/bulkloader/RedshiftBulkLoader.java
plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/redshift/bulkloader/RedshiftBulkLoaderMeta.java

Redshift bulk loader minor tweaks, updates. #3281

---

docs/hop-user-manual/modules/ROOT/pages/workflow/actions/repeat.adoc

In online documentation, this information about delay in seconds is missing, i add it

Add missing param delay in seconds

---

docs/hop-user-manual/modules/ROOT/pages/variables.adoc

…iables
Update variables.adoc to add more info on fields, parameters, and variables

Update variables.adoc to add more info on fields, parameters, and vars

---

assemblies/plugins/transforms/salesforce/pom.xml
plugins/transforms/salesforce/pom.xml

Update Salesforce libraries to [58.0.0](https://mvnrepository.com/artifact/com.force.api/force-wsc/58.0.0) version

task #2827 Update Salesforce libraries to latest version

---

plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/redshift/bulkloader/RedshiftBulkLoader.java
plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/redshift/bulkloader/RedshiftBulkLoaderData.java

minor code cleanup. #3281

---

engine/src/main/java/org/apache/hop/server/HopServer.java
engine/src/main/java/org/apache/hop/www/RegisterPipelineServlet.java
engine/src/main/java/org/apache/hop/www/RegisterWorkflowServlet.java

Force sending/receiving XML to UTF-8

Remote Work Configurations Won't Work Because of Turkish Characters #3356

---

assemblies/lib-jdbc/pom.xml
docker/integration-tests/Dockerfile.unit-tests

Remove Vertica driver, fixes #3363

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/userdefinedjavaexpression.adoc

Fixes #3369 
We should document where custom jar libraries should be placed.

Fixes #3369 Update userdefinedjavaexpression.adoc

---

docs/hop-user-manual/modules/ROOT/pages/installation-configuration.adoc

Fixes #3369 
Document where custom jar libraries are to be placed by expanding the JDBC Drivers section in installation and configuration.

Fixes #3369 Update installation-configuration.adoc

---

docs/hop-user-manual/modules/ROOT/pages/installation-configuration.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/userdefinedjavaexpression.adoc

The documentation changes done by @thadguidry to master branch to include them in upcoming releases

Cherrypick documentation changes

---

plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/redshift/bulkloader/RedshiftBulkLoader.java

CSV only options moved to CSV. #3281

---

plugins/transforms/databaselookup/src/main/java/org/apache/hop/pipeline/transforms/databaselookup/DatabaseLookup.java

fix #3100 (need to check there's not side effect)

---

assemblies/static/src/main/resources/LICENSE

Update Licenses of bundled resources

---

engine/src/main/java/org/apache/hop/core/reflection/StringSearcher.java
engine/src/main/java/org/apache/hop/core/search/BaseSearchableAnalyser.java
plugins/transforms/databaselookup/src/main/java/org/apache/hop/pipeline/transforms/databaselookup/DatabaseLookupDialog.java

issue #3389 : Just a minor annoyance.  It popped up because someone wanted to see which run configurations were *missing* from the various workflows and pipelines.  This makes those null properties show up in the search results.
issues #3387 : "Database Lookup" component hangs on when editing

Fix for issues #3389, #3387

---

plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsInputMeta.java

fix jsonpath renaming, #3315

---

plugins/transforms/httppost/src/main/java/org/apache/hop/pipeline/transforms/httppost/HttpPost.java

#3404: fix multipart post entity @ httppost transfomer

---

engine/src/main/java/org/apache/hop/www/WebServer.java

disable shutdown listener for Hop Server, fixes #3367

---

engine/src/main/java/org/apache/hop/execution/local/FileExecutionInfoLocation.java

scan subfolders to reduce exec info perspective loading time #2845

---

docs/hop-user-manual/modules/ROOT/pages/database/databases/googlebigquery.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-rest/index.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/copyrowstoresult.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getvariable.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/tableinput.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/writetolog.adoc
docs/hop-user-manual/modules/ROOT/pages/variables.adoc
docs/hop-user-manual/modules/ROOT/pages/workflow/actions/repeat.adoc
docs/hop-user-manual/modules/ROOT/pages/workflow/actions/writetolog.adoc
engine/src/main/java/org/apache/hop/execution/local/FileExecutionInfoLocation.java

updated doc headings, var references and other minor issues #3434

---

docs/hop-dev-manual/modules/ROOT/pages/hopweb/index.adoc
engine/src/main/java/org/apache/hop/execution/local/FileExecutionInfoLocation.java

instructions to update hop script classpaths #3323

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java
plugins/misc/projects/src/main/java/org/apache/hop/projects/project/ProjectDialog.java
plugins/misc/projects/src/main/java/org/apache/hop/projects/util/ProjectsUtil.java
plugins/misc/projects/src/main/resources/org/apache/hop/projects/project/messages/messages_en_US.properties
plugins/misc/projects/src/main/resources/org/apache/hop/projects/project/messages/messages_it_IT.properties

fix #3041 Changing project's home path is not possible
fix #3427 Project's name chang is not possible

fix #3041, fix #3427

---

ui/src/main/resources/org/apache/hop/ui/hopgui/messages/messages_it_IT.properties

[ITA-TRANS] Fixed Italian Translations

---

docs/hop-user-manual/modules/ROOT/pages/database/databases/oracle.adoc

[DOCS] Updated Oracle driver's documentation by adding a missing detail

---

assemblies/lib-jdbc/pom.xml

Add correct monetdb jdbc to dristribution, #3263

---

plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/redshift/bulkloader/RedshiftBulkLoader.java
plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/redshift/bulkloader/RedshiftBulkLoaderMeta.java

additional checks to skip file + copy on empty stream #3469

---

assemblies/static/src/main/resources/config/projects/samples/loops/child-workflow-executor.hwf

[SAMPLES] fix broken sample

---

plugins/actions/ftp/src/main/java/org/apache/hop/workflow/actions/ftpput/ActionFtpPut.java

process binaryMode option in FTP put. fixes #3499

---

docs/hop-user-manual/modules/ROOT/pages/getting-started/hop-tools.adoc

I added hyperlinks to relevant documentation from the Getting Started -> Tools section to the expanded documentation on each.
To make clear that you license your contribution under the [Apache License Version 2.0, January …

#3522 Add documentation cross references from Getting Started - Hop Tools to other documentation

---

core/src/main/java/org/apache/hop/core/database/Database.java
plugins/databases/doris/src/main/java/org/apache/hop/databases/doris/DorisDatabaseMeta.java

1.Database getQueryFieldsFromDatabaseMetaData set comments from remarks
2.Doris dataTypes mapping（doris not support text）

Set Database Fields comment  and Doris dataTypes mapping 

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getrecordsfromstream.adoc
engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransformMeta.java
plugins/transforms/rowsfromresult/src/main/java/org/apache/hop/pipeline/transforms/recordsfromstream/RecordsFromStreamMeta.java
plugins/transforms/rowsfromresult/src/main/java/org/apache/hop/pipeline/transforms/rowsfromresult/RowsFromResult.java

- Reinforcement of Transform and Data class creation code with reflection to better signal errors
- Removed reflection to create RecordsFromStreamData
- Deprecated transform RecordsFromStream

Fix multiple pipeline executors inside pipeline causes error #3503

---

Jenkinsfile

I never contributed to your project but receive Jenkins mails if a build failure happens.

Update Jenkinsfile to avoid Jenkins mail spam

---

Jenkinsfile.daily
pom.xml

[BUILD] fix sonar scan

---

plugins/transforms/randomvalue/src/main/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValue.java
plugins/transforms/stringoperations/src/main/java/org/apache/hop/pipeline/transforms/stringoperations/StringOperations.java

This transformation works with and without input row

Transform "Generate random value" throw NPE if no input row #3592

---

docs/hop-dev-manual/modules/ROOT/pages/porting-kettle-plugins.adoc
pom.xml

Fix to issue https://github.com/apache/hop/issues/3637

Changed jandex version from 3.0.5 to 3.1.6

---

plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/javafilter/JavaFilter.java

Uses exactly the same logic as FilterRows

Java filter: Fix to make destinations optional #3136

---

plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/AwsSqsReader.java
plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/SqsReader.java
plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/SqsReaderDialog.java
plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/SqsReaderMeta.java
plugins/tech/aws/src/main/resources/org/apache/hop/pipeline/transforms/aws/sqs/messages/messages_en_US.properties

fixed former platform references. #3602

---

NOTICE
assemblies/plugins/transforms/snowflake/src/assembly/assembly.xml
assemblies/static/src/main/resources/LICENSE
engine/src/main/java/org/apache/hop/www/PrepareExecutionPipelineServlet.java
plugins/transforms/tableoutput/src/main/java/org/apache/hop/pipeline/transforms/tableoutput/TableOutput.java

revert #3510, and some release changes

---

assemblies/lib-jdbc/pom.xml
plugins/databases/duckdb/pom.xml

I updated the pom.xml for assemblies and lib-jdbc to update to the latest stable release of DuckDB.  All of the integration tests succeeded.

Addresses Upgrade DuckDB to v0.10.0 stable #3682

---

integration-tests/transforms/datasets/golden-data-schemamapping.csv
plugins/transforms/schemamapping/src/main/java/org/apache/hop/pipeline/transforms/schemamapping/SchemaMapping.java

fix #3707 - SchemaMapping transform's tests fails

fix #3707 - SchemaMapping transform's tests fails

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getdatafromxml.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/textfileinput.adoc

Corrected information about metadata injection

[Fix #3709] Update getdatafromxml.adoc

---

docs/hop-dev-manual/antora.yml
docs/hop-tech-manual/antora.yml
docs/hop-user-manual/antora.yml

[RELEASE] update documentation version

---

plugins/actions/mssqlbulkload/src/main/java/org/apache/hop/workflow/actions/mssqlbulkload/ActionMssqlBulkLoad.java

Fix Action Bulk load into MSSQL to support native connection #3693

---

plugins/actions/zipfile/src/main/java/org/apache/hop/workflow/actions/zipfile/ActionZipFile.java

added missing isEvaluation method. fixes #3735

---

integration-tests/neo4j/datasets/golden-action-constraint.csv

[IT] fix neo4j IT test

---

plugins/transforms/javascript/src/main/resources/org/apache/hop/pipeline/transforms/javascript/jsFunctionHelp.xml

fix typos in function help. fixes #3755

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java

Add metadata an variables to projec texport, fixes#3770

---

plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/fileinput/text/messages/messages_en_US.properties

[MISSING LABELS] Added missing labels

[MISSING LABELS] Added missing labels

---

docs/hop-user-manual/modules/ROOT/pages/workflow/actions/repeat.adoc

Update repeat.adoc re: repeating pipeline bug

---

docs/hop-dev-manual/modules/ROOT/pages/setup-dev-environment.adoc

[DOC UPDATE] Upon renaming master branch to main

---

plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/redshift/bulkloader/RedshiftBulkLoader.java

removed padding from Redshift bulk loader. fixes #3823

---

assemblies/plugins/tech/neo4j/pom.xml
plugins/tech/neo4j/pom.xml

neo4j driver upgrade. fixes #3842

---

.github/workflows/pr_assign_milestone.yml
.github/workflows/self_assign.yml

[INFRA] add issues and PR to milestones

---

docker/integration-tests/Dockerfile.unit-tests
integration-tests/scripts/run-tests-docker.sh
plugins/tech/avro/src/main/samples/transforms/avro-file-input.hpl

failing test and test environment, fixes #3869

---

Jenkinsfile.daily
docker/integration-tests/Dockerfile.unit-tests
docker/integration-tests/integration-tests-azure.yaml
docker/integration-tests/integration-tests-base-spark.yaml
docker/integration-tests/integration-tests-base.yaml
docker/integration-tests/integration-tests-cassandra.yaml
docker/integration-tests/integration-tests-database.yaml
docker/integration-tests/integration-tests-flink.yaml
docker/integration-tests/integration-tests-hop_server.yaml
docker/integration-tests/integration-tests-http.yaml
docker/integration-tests/integration-tests-kafka.yaml
docker/integration-tests/integration-tests-mail.yaml
docker/integration-tests/integration-tests-monetdb.yaml
docker/integration-tests/integration-tests-mongo.yaml
docker/integration-tests/integration-tests-neo4j.yaml
docker/integration-tests/integration-tests-snmp.yaml
docker/integration-tests/integration-tests-spark.yaml
docker/integration-tests/integration-tests-vertica.yaml
docker/integration-tests/integration-tests-xml.yaml
integration-tests/scripts/run-tests-docker.sh

docker and jenkins test cleanup, #2548

---

plugins/transforms/fake/src/main/java/org/apache/hop/pipeline/transforms/fake/FakeDialog.java
plugins/transforms/fake/src/main/java/org/apache/hop/pipeline/transforms/fake/FakeMeta.java
plugins/transforms/fake/src/main/samples/transforms/fake-data-generate-person-record.hpl

For now ignore methods that doesn't return type (String, long or Date)

Fake - Add support ValueMetaInteger for methods that return long  #3848

---

integration-tests/snmp/files/.empty

snmp integration test does not work, fixes #3894

---

plugins/tech/google/src/main/resources/org/apache/hop/pipeline/transforms/googleanalytics/messages/messages_en_US.properties
plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/text/TextFileInputMeta.java
ui/src/main/java/org/apache/hop/ui/core/gui/BaseGuiWidgets.java

textfile input improvement, GuiWidget improvement

---

engine/src/main/java/org/apache/hop/core/IProvidesModelerMeta.java
plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/redshift/bulkloader/RedshiftBulkLoaderMeta.java
plugins/transforms/combinationlookup/src/main/java/org/apache/hop/pipeline/transforms/combinationlookup/CombinationLookupMeta.java
plugins/transforms/combinationlookup/src/test/java/org/apache/hop/pipeline/transforms/combinationlookup/CombinationLookupMetaTest.java
plugins/transforms/databaselookup/src/main/java/org/apache/hop/pipeline/transforms/databaselookup/DatabaseLookupMeta.java
plugins/transforms/databaselookup/src/test/java/org/apache/hop/pipeline/transforms/databaselookup/DatabaseLookupMetaTest.java
plugins/transforms/dimensionlookup/src/main/java/org/apache/hop/pipeline/transforms/dimensionlookup/DimensionLookupMeta.java
plugins/transforms/insertupdate/src/main/java/org/apache/hop/pipeline/transforms/insertupdate/InsertUpdateMeta.java
plugins/transforms/insertupdate/src/test/java/org/apache/hop/pipeline/transforms/insertupdate/InsertUpdateMetaTest.java
plugins/transforms/tableoutput/src/main/java/org/apache/hop/pipeline/transforms/tableoutput/TableOutputMeta.java
plugins/transforms/tableoutput/src/test/java/org/apache/hop/pipeline/transforms/tableoutput/TableOutputMetaTest.java
plugins/transforms/verticabulkloader/src/main/java/org/apache/hop/pipeline/transforms/vertica/bulkloader/VerticaBulkLoaderMeta.java

Move some db creation in try catch block
Fix a set method name in VerticaBulkLoaderMeta class

Deprecate IProvidesModelerMeta interface #3902

---

integration-tests/transforms/0073-json-output-enhanced-split-files-3871.hpl
integration-tests/transforms/0073-json-output-enhanced-split-files-validation-3871.hpl
integration-tests/transforms/main-0073-json-output-enhanced-split-files-3871.hwf
plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutput.java

fix for split files in json output enhanced. fixes #3871

---

docker/integration-tests/integration-tests-snmp.yaml
integration-tests/snmp/001-check-log.hpl
integration-tests/snmp/main-001-snmp-trap-test.hwf

fix snmp integration test, #3894

---

assemblies/lib-jdbc/pom.xml
assemblies/static/src/main/resources/LICENSE
plugins/databases/duckdb/pom.xml

This update simply bumps up the version of the duckdb.jar file that provides database support for this component. 

[Task]: Update duckdb dependency to 0.10.2 #3918

---

plugins/transforms/mapping/src/main/java/org/apache/hop/pipeline/transforms/mapping/SimpleMappingDialog.java
pom.xml

- Revert Jetty changes as the serve no longer works

SimpleMapping transform dialog is broken

---

assemblies/lib-jdbc/pom.xml
assemblies/plugins/tech/aws/pom.xml
plugins/tech/aws/pom.xml
plugins/transforms/redshift/pom.xml

update redshift jdbc driver, fixes #3939

---

.gitignore
plugins/transforms/metainject/src/main/samples/files/person-info-1.csv
plugins/transforms/metainject/src/main/samples/files/person-info-2.csv
plugins/transforms/metainject/src/main/samples/metadata-injection/process-files-with-mdi-template.hpl
plugins/transforms/metainject/src/main/samples/metadata-injection/process-files-with-mdi.hpl

additional metadata injection sample #2237

---

integration-tests/database/0013-synchronize-after-merge.hpl
plugins/transforms/insertupdate/src/main/java/org/apache/hop/pipeline/transforms/insertupdate/InsertUpdateMeta.java
plugins/transforms/synchronizeaftermerge/src/main/java/org/apache/hop/pipeline/transforms/synchronizeaftermerge/SynchronizeAfterMerge.java
plugins/transforms/synchronizeaftermerge/src/main/java/org/apache/hop/pipeline/transforms/synchronizeaftermerge/SynchronizeAfterMergeDialog.java
plugins/transforms/synchronizeaftermerge/src/main/java/org/apache/hop/pipeline/transforms/synchronizeaftermerge/SynchronizeAfterMergeMeta.java
plugins/transforms/synchronizeaftermerge/src/test/java/org/apache/hop/pipeline/transforms/synchronizeaftermerge/SynchronizeAfterMergeMetaInjectionTest.java
plugins/transforms/synchronizeaftermerge/src/test/java/org/apache/hop/pipeline/transforms/synchronizeaftermerge/SynchronizeAfterMergeMetaTest.java
plugins/transforms/synchronizeaftermerge/src/test/java/org/apache/hop/pipeline/transforms/synchronizeaftermerge/SynchronizeAfterMergeTest.java

+ a small fix in InsertUpdateMeta to create database

Synchronize After Merge - specify connection through variables #3839

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/salesforce-connection.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/salesforceinput.adoc

URL notes and a link to Salesforce documentation to help with troubleshooting 'restricted domain' errors when using otherwise valid usernames and tokens.

Add info about My Domain URLs for Salesforce cxns #3945

---

integration-tests/samples/read-samples-build-hop-run.hpl

exclude MDI template from samples IT #2237

---

docs/hop-user-manual/modules/ROOT/pages/vfs/azure-blob-storage-vfs.adoc

add a comment about hierarchical namespaces, fixes #3154

---

.github/workflows/pr_assign_milestone.yml

[BUILD] remove milestones from PR's

---

docs/hop-user-manual/modules/ROOT/pages/hop-usps.adoc

Fixed typos in hop-usps.adoc

---

docs/hop-user-manual/modules/ROOT/pages/hop-usps.adoc

* Fixed typos in hop-usps.adoc
* Replaced transformations with pipelines

Fixed typos in hop-usps.adoc (#3952)

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/getting-started-with-beam.adoc
integration-tests/samples/read-samples-build-hop-run.hpl

updated beam versions #3291

---

assemblies/client/pom.xml
pom.xml

- org.eclipse.platform 3.123.0 -> 3.125.0
- org.eclipse.commands 3.9.600 -> 3.12.0
- org.eclipse.equinox 3.10.600 -> 3.19.0
Tested on Windows only
! RAP not tested !

Bump org.eclipse.platform to the last version #4004

---

docs/hop-user-manual/modules/ROOT/pages/variables.adoc

Fixed typo!

---

docs/hop-user-manual/modules/ROOT/pages/workflow/actions/setvariables.adoc
plugins/actions/setvariables/src/main/samples/actions/variable_substitution.hwf
plugins/actions/setvariables/src/main/samples/files/properties_file.properties

Adapted "Set Variables" documentation.
Sample is added here as suggested by @hansva
[samples.zip](https://github.com/apache/hop/files/15445159/samples.zip)

Fix #3321 improved documentation

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/uniquerowsbyhashset.adoc
plugins/transforms/uniquerowsbyhashset/src/main/java/org/apache/hop/pipeline/transforms/uniquerowsbyhashset/UniqueRowsByHashSetMeta.java

Use compare using values by default in Unique rows hashset #3908

---

core/src/main/java/org/apache/hop/core/config/HopConfig.java
plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java

export hop-config.json, fixes #4023

---

core/pom.xml
engine/pom.xml
plugins/actions/pom.xml
plugins/databases/cockroachdb/pom.xml
plugins/databases/cratedb/pom.xml
plugins/databases/greenplum/pom.xml
plugins/databases/pom.xml
plugins/databases/postgresql/pom.xml
plugins/databases/redshift/pom.xml
plugins/tech/pom.xml
plugins/transforms/pom.xml
pom.xml
ui/pom.xml

update maven dependencies + cleanup, fixes #4026

update maven dependencies + cleanup, fixes #4026

---

integration-tests/samples/read-samples-build-hop-run.hpl
plugins/actions/eval/src/main/samples/workflows/javascript_parse_action_logs.hwf

additional sample for log parsing in javascript action. #2238

---

docs/hop-user-manual/modules/ROOT/pages/hop-gui/shortcuts.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/script.adoc

add nashorn installation steps to Script transform docs. fixes #4038

---

core/src/main/java/org/apache/hop/core/Condition.java
core/src/main/java/org/apache/hop/core/Const.java
core/src/main/java/org/apache/hop/core/Result.java
core/src/main/java/org/apache/hop/core/ResultFile.java
core/src/main/java/org/apache/hop/core/RowMetaAndData.java
core/src/main/java/org/apache/hop/core/database/Database.java
core/src/main/java/org/apache/hop/core/database/DatabaseMeta.java
core/src/main/java/org/apache/hop/core/injection/InjectionTypeConverter.java
core/src/main/java/org/apache/hop/core/plugins/PluginRegistry.java
core/src/main/java/org/apache/hop/core/row/SpeedTest.java
core/src/main/java/org/apache/hop/core/row/ValueDataUtil.java
core/src/main/java/org/apache/hop/core/row/value/ValueMetaAvroRecord.java
core/src/main/java/org/apache/hop/core/row/value/ValueMetaBase.java
core/src/main/java/org/apache/hop/core/row/value/ValueMetaConverter.java
core/src/main/java/org/apache/hop/core/row/value/ValueMetaInternetAddress.java
core/src/main/java/org/apache/hop/core/row/value/ValueMetaTimestamp.java

[SONAR] do some cleanup

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/streamschemamerge.adoc

updated Stream Schema Merge transform documentation. #4049

---

pom.xml

upgraded swt dependency. fixes #4066

---

plugins/transforms/mapping/src/main/java/org/apache/hop/pipeline/transforms/mapping/MappingIODefinition.java
plugins/transforms/mapping/src/main/java/org/apache/hop/pipeline/transforms/mapping/MappingParameters.java
plugins/transforms/mapping/src/main/java/org/apache/hop/pipeline/transforms/mapping/SimpleMapping.java
plugins/transforms/mapping/src/main/java/org/apache/hop/pipeline/transforms/mapping/SimpleMappingDialog.java
plugins/transforms/mapping/src/main/java/org/apache/hop/pipeline/transforms/mapping/SimpleMappingMeta.java

Simple mapping transform improvements

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/calculator.adoc

* Fix #4025 - Update calculator.adoc
Added descriptions for Metadata Injection as suggested, and "Metadata Injection support" paragraph 
Added rows for 6 undocumented functions in Calculator (last 6 in the table) 
Beware that ROUND_CUSTOM_1 and ROUND_CUSTOM_2 seem not to be actually implemented!

Fix #4025 - Update calculator.adoc (#1)

---

core/src/main/java/org/apache/hop/core/Condition.java

Fix BigNumber issue in filter rows, fixes #4020

---

engine/src/main/java/org/apache/hop/core/IProvidesDatabaseConnectionInformation.java
plugins/transforms/pgbulkloader/src/main/java/org/apache/hop/pipeline/transforms/pgbulkloader/PGBulkLoader.java
plugins/transforms/pgbulkloader/src/main/java/org/apache/hop/pipeline/transforms/pgbulkloader/PGBulkLoaderDialog.java
plugins/transforms/pgbulkloader/src/main/java/org/apache/hop/pipeline/transforms/pgbulkloader/PGBulkLoaderMeta.java
plugins/transforms/pgbulkloader/src/test/java/org/apache/hop/pipeline/transforms/pgbulkloader/PGBulkLoaderTest.java

fix #3837 - PG Bulkloader - specify connection through variables

fix #3837 - PG Bulkloader - specify connection through variables

---

plugins/transforms/orabulkloader/src/main/java/org/apache/hop/pipeline/transforms/orabulkloader/OraBulkLoader.java
plugins/transforms/orabulkloader/src/main/java/org/apache/hop/pipeline/transforms/orabulkloader/OraBulkLoaderDialog.java
plugins/transforms/orabulkloader/src/main/java/org/apache/hop/pipeline/transforms/orabulkloader/OraBulkLoaderMeta.java

fix #3836 - Oracle Bulk Loader - specify connection through variables

fix #3836 - Oracle Bulk Loader - specify connection through variables

---

plugins/transforms/combinationlookup/src/main/java/org/apache/hop/pipeline/transforms/combinationlookup/CombinationLookup.java
plugins/transforms/combinationlookup/src/main/java/org/apache/hop/pipeline/transforms/combinationlookup/CombinationLookupDialog.java
plugins/transforms/combinationlookup/src/main/java/org/apache/hop/pipeline/transforms/combinationlookup/CombinationLookupMeta.java

fix #3833 - CombinationLookup - specify connection through variables

fix #3833 - CombinationLookup - specify connection through variables

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopGuiFileDefaultFolder.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/PipelineExecutionViewer.java

Fix typo in log message for another HopGuiExtensionPoin

HopGuiFileDefaultFolder create wrong path on Windows #4073 

---

docs/hop-user-manual/modules/ROOT/pages/database/databases.adoc
docs/hop-user-manual/modules/ROOT/pages/database/databases/oracle.adoc

updated database documentation and minor updates. fixes #3548

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/calculator.adoc

calculator doc updates. fixes #3545

---

docs/hop-dev-manual/modules/ROOT/pages/hopweb/index.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/cratedb-bulkloader.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/filterrows.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getvariable.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/writetolog.adoc
docs/hop-user-manual/modules/ROOT/pages/workflow/actions/setvariables.adoc

various minor doc updates. fixes #4097

---

plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleImportDialog.java

added variables resolution for text var fields. fixes #4105

---

docs/hop-dev-manual/modules/ROOT/pages/hopweb/index.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-gui/hop-web.adoc

updated hop web status information. fixes #4132

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/replacestring.adoc
docs/hop-user-manual/modules/ROOT/pages/variables.adoc

[DOC] add hex info for string replacement

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/replacestring.adoc
docs/hop-user-manual/modules/ROOT/pages/variables.adoc

[DOC] fix references in docs

---

pom.xml

publish hop-client again, #4172

---

Jenkinsfile

fix jenkinsfile, #4114

---

engine/src/main/java/org/apache/hop/base/AbstractMeta.java
engine/src/main/java/org/apache/hop/core/search/HopServerSearchableAnalyser.java
engine/src/main/java/org/apache/hop/execution/remote/RemoteExecutionInfoLocation.java
engine/src/main/java/org/apache/hop/pipeline/engines/remote/HopServerTypeMetadata.java
engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineEngine.java
engine/src/main/java/org/apache/hop/run/HopRun.java
engine/src/main/java/org/apache/hop/server/HopServerMeta.java
engine/src/main/java/org/apache/hop/workflow/engines/remote/HopServerTypeMetadata.java
engine/src/main/java/org/apache/hop/workflow/engines/remote/RemoteWorkflowEngine.java
engine/src/main/java/org/apache/hop/www/HopServer.java
engine/src/main/java/org/apache/hop/www/HopServerConfig.java
engine/src/main/java/org/apache/hop/www/HopServerSingleton.java
engine/src/main/java/org/apache/hop/www/WebServer.java
engine/src/test/java/org/apache/hop/core/metadata/SerializableMetadataProviderTest.java
engine/src/test/java/org/apache/hop/server/HopServerTest.java
engine/src/test/java/org/apache/hop/www/WebServerTest.java
plugins/transforms/serverstatus/src/main/java/org/apache/hop/pipeline/transforms/serverstatus/GetServerStatus.java
ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowRunDelegate.java
ui/src/main/java/org/apache/hop/ui/server/HopServerEditor.java

Rename org.apache.hop.server.HopServer to HopServerMeta #4150

---

engine/pom.xml
plugins/databases/mssql/pom.xml
plugins/databases/mysql/pom.xml
plugins/databases/postgresql/pom.xml
plugins/transforms/textfile/pom.xml

fix missing test-jars , #4114

---

plugins/transforms/drools/pom.xml
plugins/transforms/formula/pom.xml
plugins/transforms/formula/src/assembly/assembly.xml
plugins/transforms/tika/pom.xml

remove duplicate log4j, fixes #4183

---

engine-beam/pom.xml
plugins/engines/beam/src/assembly/assembly.xml
ui/pom.xml
ui/src/assembly/assembly.xml

move SWT to compile so plugins don't need to add it, fixes #4187

---

core/src/main/java/org/apache/hop/core/Const.java
core/src/test/java/org/apache/hop/core/ConstTest.java
core/src/test/java/org/apache/hop/server/HttpUtilTest.java
engine/src/test/java/org/apache/hop/pipeline/PipelineMetaTest.java
engine/src/test/java/org/apache/hop/www/BaseHopServerPluginTest.java
plugins/actions/mail/src/test/java/org/apache/hop/workflow/actions/mail/WorkflowEntryTest.java
plugins/actions/shell/src/test/java/org/apache/hop/workflow/actions/shell/WorkflowActionShellTest.java
plugins/databases/sapdb/src/test/java/org/apache/hop/databases/sapdb/SAPDBDatabaseMetaTest.java
plugins/misc/testing/src/main/java/org/apache/hop/testing/xp/PipelineMetaModifier.java
plugins/transforms/insertupdate/src/test/java/org/apache/hop/pipeline/transforms/insertupdate/InsertUpdateTestLazyConversionTest.java
plugins/transforms/mailinput/src/test/java/org/apache/hop/pipeline/transforms/mailinput/BatchFolderIteratorNameTest.java
plugins/transforms/memgroupby/src/test/java/org/apache/hop/pipeline/transforms/memgroupby/MemoryGroupByAggregationTest.java
plugins/transforms/memgroupby/src/test/java/org/apache/hop/pipeline/transforms/memgroupby/MemoryGroupByNewAggregateTest.java
plugins/transforms/mergejoin/src/test/java/org/apache/hop/pipeline/transforms/mergejoin/MergeJoinMetaInjectionTransformTest.java
plugins/transforms/mongodb/src/test/java/org/apache/hop/mongo/AuthContextTest.java
plugins/transforms/mongodb/src/test/java/org/apache/hop/mongo/MongoPropToOptionTest.java
plugins/transforms/mongodb/src/test/java/org/apache/hop/mongo/wrapper/HopMongoUtilLoggerTest.java
plugins/transforms/mongodb/src/test/java/org/apache/hop/mongo/wrapper/MongoClientWrapperFactoryTest.java
plugins/transforms/mongodb/src/test/java/org/apache/hop/mongo/wrapper/MongoFieldTest.java
plugins/transforms/mongodb/src/test/java/org/apache/hop/mongo/wrapper/NoAuthMongoClientWrapperTest.java
plugins/transforms/mongodb/src/test/java/org/apache/hop/mongo/wrapper/collection/DefaultMongoCollectionWrapperTest.java
plugins/transforms/mongodb/src/test/java/org/apache/hop/mongo/wrapper/field/MongodbInputDiscoverFieldsImplTest.java
plugins/transforms/mongodb/src/test/java/org/apache/hop/pipeline/transforms/mongodbinput/BaseMongoDbTransformTest.java
plugins/transforms/nullif/src/test/java/org/apache/hop/pipeline/transforms/nullif/NullIfTest.java
plugins/transforms/setvalueconstant/src/test/java/org/apache/hop/pipeline/transforms/setvalueconstant/SetValueConstantTest.java
plugins/transforms/stringoperations/src/test/java/org/apache/hop/pipeline/transforms/stringoperations/StringOperationsTest.java
plugins/transforms/update/src/test/java/org/apache/hop/pipeline/transforms/update/PDI_11152_Test.java

[SONAR] cleanup issues, fix some tests

---

plugins/databases/oracle/src/main/java/org/apache/hop/databases/oracle/OracleDatabaseMeta.java
plugins/databases/oracle/src/test/java/org/apache/hop/databases/oracle/OracleDatabaseMetaTest.java
plugins/databases/oracle/src/test/java/org/apache/hop/databases/oracle/OracleValueMetaBaseTest.java

enable boolean and timestamp by default for oracle, fixes #4201

---

plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/WriteToLogDialog.java

dialog fixes for write to log fields. fixes #4197

---

plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_de_DE.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_es_AR.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_es_ES.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_fr_FR.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_it_IT.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_ja_JP.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_ko_KR.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_nl_NL.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_no_NO.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_pl_PL.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_pt_BR.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_pt_PT.properties
plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/metadatatype/messages/messages_zh_CN.properties

[TRANS] add empty files

---

docs/hop-user-manual/modules/ROOT/pages/best-practices/index.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/governance.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/logging.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/loops.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/mappings.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/metadata-injection.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/naming-conventions.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/performance-basics.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/size-matters.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/variables.adoc

best practices updates. fixes #4204

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/config/ProjectsConfigOptionPlugin.java

remove i18n for hop-conf project options. fixes #4216

---

plugins/transforms/cratedbbulkloader/src/test/java/org/apache/hop/pipeline/transforms/cratedbbulkloader/http/CrateDBBulkImportTest.java

add condition to skip test when docker is not available, fixes #4226

---

core/src/test/java/org/apache/hop/core/row/value/ValueMetaFactoryTest.java
engine/src/test/java/org/apache/hop/core/row/ValueDataUtilTest.java
plugins/databases/monetdb/src/test/java/org/apache/hop/databases/monetdb/MonetDBDatabaseMetaTest.java
plugins/transforms/calculator/src/test/java/org/apache/hop/pipeline/transforms/calculator/CalculatorUnitTest.java
plugins/transforms/janino/src/test/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassMetaInjectionTest.java
plugins/transforms/javascript/src/test/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesMetaInjectionTest.java
plugins/transforms/json/src/test/java/org/apache/hop/pipeline/transforms/jsonoutput/JsonOutputTest.java
plugins/transforms/mailinput/src/test/java/org/apache/hop/pipeline/transforms/mailinput/ParseMailInputTest.java
plugins/transforms/selectvalues/src/test/java/org/apache/hop/pipeline/transforms/selectvalues/SelectValuesTest.java
plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/TextFileInput.java
plugins/transforms/textfile/src/test/java/org/apache/hop/pipeline/transforms/fileinput/text/PDI_2875_Test.java
plugins/transforms/textfile/src/test/java/org/apache/hop/pipeline/transforms/textfileinput/PDI_2875_Test.java

[SONAR] cleanup deprecated methods

---

plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/javafilter/JavaFilter.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/javafilter/JavaFilterDialog.java

Add option to block execution of specific code. fixes #4238

---

plugins/misc/async/src/main/java/org/apache/hop/www/async/AsyncWebServiceEditor.java
ui/src/main/java/org/apache/hop/ui/core/widget/MetaSelectionLine.java

Add method addListener to MEtaSeleciionLine widget

Cannot save web service when editing run configuration #4258

---

lib/pom.xml

Upgrade POI, fixes #4272

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/javascript.adoc

added how to create custom json string i.e. as a REST-POST-Body

add creating custom json string

---

docs/hop-tech-manual/modules/ROOT/pages/hop-logo-and-icons.adoc

provide more context about logo vs icon in the tech docs. fixes #4284

---

integration-tests/cratedb/disabled.txt

Disable crateDB integration tests, fixes #4292

---

plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/editor/FormulaEditor.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/Janino.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/JaninoDialog.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/JaninoMetaFunction.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/editor/FormulaEditor.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/editor/util/CompletionProposal.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/function/FunctionDescription.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/function/FunctionExample.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/function/FunctionLib.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/function/HopFunctions.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/function/JaninoFunction.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/javafilter/JavaFilterDialog.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/util/JaninoCheckerUtil.java
plugins/transforms/janino/src/main/resources/org/apache/hop/pipeline/transforms/javafilter/messages/messages_en_US.properties
ui/src/main/java/org/apache/hop/ui/core/widget/StyledTextComp.java

siwtch to annotation based functions, extra features to editor, #4257
some sonar cleanup, #4257
Add editor to java filter , #4257

Add Function dialog, way to add functions to the UDJE transform, #4257

---

ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/file/types/text/BaseTextExplorerFileTypeHandler.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java

Fix save button when editing text files, fixes #4290

---

core/src/main/java/org/apache/hop/core/row/RowMeta.java
core/src/main/java/org/apache/hop/core/row/value/ValueMetaBase.java
engine/src/main/java/org/apache/hop/core/util/KeyValue.java
engine/src/main/java/org/apache/hop/pipeline/PipelineHopMeta.java
plugins/actions/mail/src/main/java/org/apache/hop/workflow/actions/mail/ActionMail.java
plugins/misc/projects/src/main/java/org/apache/hop/projects/environment/ManageEnvironmentsOptionPlugin.java
plugins/tech/cassandra/src/main/java/org/apache/hop/databases/cassandra/metadata/CassandraConnectionEditor.java
plugins/tech/cassandra/src/main/java/org/apache/hop/databases/cassandra/util/CqlUtils.java
plugins/tech/cassandra/src/main/java/org/apache/hop/pipeline/transforms/cassandrainput/CassandraInputMeta.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/logging/util/LoggingCore.java
plugins/transforms/ifnull/src/main/java/org/apache/hop/pipeline/transforms/ifnull/IfNullDialog.java
plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesDialog.java
plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapConnection.java
plugins/transforms/mail/src/main/java/org/apache/hop/pipeline/transforms/mail/MailDialog.java
plugins/transforms/mongodb/src/main/java/org/apache/hop/mongo/wrapper/field/MongoArrayExpansion.java
plugins/transforms/mongodb/src/main/java/org/apache/hop/mongo/wrapper/field/MongoField.java
plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodbdelete/MongoDbDeleteData.java
plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodboutput/MongoDbOutputData.java
plugins/transforms/script/src/main/java/org/apache/hop/pipeline/transforms/script/Script.java
plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/TextFileInput.java
plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/TextFileInputMeta.java
plugins/transforms/webservices/src/main/java/org/apache/hop/pipeline/transforms/webservices/wsdl/Wsdl.java
ui/src/main/java/org/apache/hop/ui/core/dialog/BaseDialog.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java

[SONAR] cleanup

---

docs/hop-user-manual/modules/ROOT/pages/how-to-guides/run-hop-in-apache-airflow.adoc

add update from #4300 to main. fixes #4301

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopGuiFileReplaceHomeVariable.java
ui/src/main/java/org/apache/hop/ui/core/vfs/HopVfsFileDialog.java

variable resolving of project home in VFS dialog, fixes #4318

---

docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/metadata-types/azure-authentication.adoc
plugins/misc/static-schema/src/main/java/org/apache/hop/staticschema/metadata/SchemaDefinition.java
plugins/tech/azure/src/main/java/org/apache/hop/vfs/azure/metadatatype/AzureMetadataType.java

add documentation and fix schema definition documentation, #4062

---

.gitignore
lib/pom.xml
plugins/engines/beam/pom.xml
plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/BeamPipelineEngine.java
pom.xml

initial beam upgrade, ITs WiP. #4314

---

plugins/databases/as400/src/main/java/org/apache/hop/databases/as400/AS400DatabaseMeta.java
plugins/databases/as400/src/test/java/org/apache/hop/databases/as400/AS400DatabaseMetaTest.java
plugins/databases/cache/src/main/java/org/apache/hop/databases/cache/CacheDatabaseMeta.java
plugins/databases/cache/src/test/java/org/apache/hop/databases/cache/CacheDatabaseMetaTest.java
plugins/databases/clickhouse/src/main/java/org/apache/hop/databases/clickhouse/ClickhouseDatabaseMeta.java
plugins/databases/cratedb/src/main/java/org/apache/hop/databases/cratedb/CrateDBDatabaseMeta.java
plugins/databases/cratedb/src/test/java/org/apache/hop/databases/cratedb/CrateDBDatabaseMetaTest.java
plugins/databases/db2/src/main/java/org/apache/hop/databases/db2/DB2DatabaseMeta.java
plugins/databases/db2/src/test/java/org/apache/hop/databases/db2/DB2DatabaseMetaTest.java

A first pull request as an example for you how I would update and homogenize schema generation of all database implementations in the next weeks.
If you see any need to do that differently please let me know, otherwise I would continue work after this has been accepted/merged.

updated database schema generations für AS400, Cache, Clickhouse, CrateDB and DB2 from #4268

---

engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransformMeta.java

Marked loadXML() and getXML() deprecated

---

docs/hop-dev-manual/antora.yml
docs/hop-dev-manual/modules/ROOT/pages/apache-release/creating-a-release.adoc
docs/hop-tech-manual/antora.yml
docs/hop-user-manual/antora.yml
pom.xml

[RELEASE] update doc version, fix pom, update release guide

---

docs/hop-dev-manual/modules/ROOT/pages/apache-release/creating-a-release.adoc
docs/hop-dev-manual/modules/ROOT/pages/apache-release/promoting-a-release.adoc

Update Release documentation

---

plugins/tech/parquet/pom.xml

updated parquet. fixes #3819

---

ui/src/main/java/org/apache/hop/ui/hopgui/context/metadata/MetadataContextHandler.java

fixed missing translations in context dialog, fixes #4403

---

core/src/main/java/org/apache/hop/core/xml/XmlHandler.java

remove false positive detection, #4401

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java

Allow placing the zip in the home folder, fixes #4393

---

plugins/misc/git/src/main/java/org/apache/hop/git/GitGuiPlugin.java
plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapProtocol.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java

Refresh explorer when switching perspective and git pull, fixes #3619

---

lib-jdbc/pom.xml
plugins/databases/duckdb/pom.xml

Update DuckDB 1.1.1 and Snowflake 3.19 JDBC
- [x ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [x ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable.
you have to acknowledge this by using the following …

Update DuckDB 1.1.1 and Snowflake 3.19 JDBC

---

docs/hop-user-manual/modules/ROOT/pages/hop-server/index.adoc
engine/src/main/java/org/apache/hop/www/HopServer.java

removed kill references for hop server from docs and CLI. fixes #4420

---

docs/hop-user-manual/modules/ROOT/pages/getting-started/hop-download-install.adoc

updated java version requirement. #4437

---

docs/hop-user-manual/modules/ROOT/assets/images/transforms/icons/detectlanguage.svg
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/detectlanguage.adoc
plugins/transforms/detectlanguage/src/main/java/org/apache/hop/pipeline/transforms/language/DetectLanguageDialog.java
plugins/transforms/detectlanguage/src/main/java/org/apache/hop/pipeline/transforms/language/DetectLanguageMeta.java
plugins/transforms/detectlanguage/src/main/resources/org/apache/hop/pipeline/transforms/language/messages/messages_en_US.properties

Adapt dialog constructor method
Add support for MDI
Add basic documentation

Fix layout for Detect language transform #4444

---

plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/Rest.java

fix truststore issue in rest

---

.asf.yaml

Set discussions mail address

---

plugins/databases/duckdb/pom.xml
plugins/transforms/detectlanguage/src/assembly/assembly.xml
plugins/transforms/stanfordnlp/src/assembly/assembly.xml

Revert DuckDB Upgrade, #4430

---

docs/hop-user-manual/modules/ROOT/pages/plugins/plugins.adoc
docs/hop-user-manual/modules/ROOT/pages/variables.adoc

- [x ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [x ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
- [x ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. …

added internal vaiables pipelines workflows copynr. #2642

---

core/src/main/java/org/apache/hop/metadata/serializer/xml/XmlMetadataUtil.java
pom.xml

Add Lombok #4468 and support for double values in HopMetadataProperty #4469, 

---

engine/src/test/java/org/apache/hop/base/LoadSaveBase.java
engine/src/test/java/org/apache/hop/pipeline/transforms/loadsave/LoadSaveTester.java
engine/src/test/java/org/apache/hop/workflow/action/loadsave/LoadSaveTester.java
engine/src/test/java/org/apache/hop/workflow/action/loadsave/WorkflowActionLoadSaveTestSupport.java
plugins/actions/ping/src/main/java/org/apache/hop/workflow/actions/ping/ActionPing.java
plugins/actions/ping/src/main/java/org/apache/hop/workflow/actions/ping/ActionPingDialog.java
plugins/actions/ping/src/test/java/org/apache/hop/workflow/actions/ping/WorkflowActionPingTest.java

I made the cleanup for Ping action.

[Task]: Cleanup XML of action Ping #1985

---

integration-tests/xml/main-0001-xml-join-test.hwf
lib/pom.xml
plugins/actions/xml/pom.xml
plugins/actions/xml/src/assembly/assembly.xml
plugins/engines/beam/pom.xml
plugins/engines/beam/src/assembly/assembly.xml
plugins/tech/azure/pom.xml
plugins/tech/azure/src/assembly/assembly.xml
plugins/tech/cassandra/src/assembly/assembly.xml
plugins/tech/google/src/assembly/assembly.xml
plugins/transforms/drools/src/assembly/assembly.xml
plugins/transforms/edi2xml/src/assembly/assembly.xml
plugins/transforms/script/src/assembly/assembly.xml
plugins/transforms/xml/pom.xml
plugins/transforms/xml/src/assembly/assembly.xml

Remove some duplicate libraries

---

plugins/transforms/drools/src/assembly/assembly.xml

fix missing dependency

---

docs/hop-user-manual/modules/ROOT/pages/variables.adoc

updated differences in values and descriptions. #4479

---

plugins/tech/cassandra/src/main/java/org/apache/hop/workflow/actions/execcql/ExecCql.java

Cleanup XML of action Execute CQL, fixes #2009

---

plugins/actions/webserviceavailable/src/main/java/org/apache/hop/workflow/actions/webserviceavailable/ActionWebServiceAvailable.java
plugins/actions/webserviceavailable/src/main/java/org/apache/hop/workflow/actions/webserviceavailable/ActionWebServiceAvailableDialog.java
plugins/actions/webserviceavailable/src/test/java/org/apache/hop/workflow/actions/webserviceavailable/WorkflowActionWebServiceAvailableTest.java

Cleanup XML of action WebService Available, fixes #2001

---

plugins/actions/unzip/src/main/java/org/apache/hop/workflow/actions/unzip/ActionUnZip.java
plugins/actions/unzip/src/main/java/org/apache/hop/workflow/actions/unzip/ActionUnZipDialog.java
plugins/actions/unzip/src/main/java/org/apache/hop/workflow/actions/unzip/FileExistsEnum.java
plugins/actions/unzip/src/test/java/org/apache/hop/workflow/actions/unzip/WorkflowActionUnZipTest.java

Cleanup XML of action Unzip, fixes #1998

---

plugins/actions/repeat/src/main/java/org/apache/hop/workflow/actions/repeat/Repeat.java

fix error in XML cleanup of Repeat action, #1987

---

integration-tests/json/0006-enhanced-json-output-json-fragment.hpl
integration-tests/json/datasets/golden-enhanced-json-fragment.csv
integration-tests/json/main-0006-enhanced-json-output-json-fragment.hwf
integration-tests/json/metadata/dataset/golden-enhanced-json-fragment.json
integration-tests/json/metadata/unit-test/0006-enhanced-json-output-json-fragment UNIT.json
plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutput.java

Ignore isblank check when looking at json fragments, fixes #3577

---

plugins/actions/sql/src/main/java/org/apache/hop/workflow/actions/sql/ActionSqlDialog.java
plugins/actions/waitforsql/src/main/java/org/apache/hop/workflow/actions/waitforsql/ActionWaitForSqlDialog.java
plugins/transforms/databasejoin/src/main/java/org/apache/hop/pipeline/transforms/databasejoin/DatabaseJoinDialog.java
plugins/transforms/dynamicsqlrow/src/main/java/org/apache/hop/pipeline/transforms/dynamicsqlrow/DynamicSqlRowDialog.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassDialog.java
plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesDialog.java
plugins/transforms/script/src/main/java/org/apache/hop/pipeline/transforms/script/ScriptDialog.java
plugins/transforms/sql/src/main/java/org/apache/hop/pipeline/transforms/sql/ExecSqlDialog.java
plugins/transforms/tableinput/src/main/java/org/apache/hop/pipeline/transforms/tableinput/TableInputDialog.java
ui/src/main/java/org/apache/hop/ui/core/widget/JavaScriptStyledTextComp.java
ui/src/main/java/org/apache/hop/ui/core/widget/JavaStyledTextComp.java
ui/src/main/java/org/apache/hop/ui/core/widget/SQLStyledTextComp.java
ui/src/main/java/org/apache/hop/ui/core/widget/ScriptStyledTextComp.java
ui/src/main/java/org/apache/hop/ui/core/widget/TextComposite.java
ui/src/main/java/org/apache/hop/ui/core/widget/highlight/GenericCodeHighlight.java
ui/src/main/java/org/apache/hop/ui/core/widget/highlight/JavaHighlight.java
ui/src/main/java/org/apache/hop/ui/core/widget/highlight/JavaScriptHighlight.java
ui/src/main/java/org/apache/hop/ui/core/widget/highlight/SQLValuesHighlight.java
ui/src/main/java/org/apache/hop/ui/core/widget/highlight/ScriptEngine.java

Fixes #4386 
Major changes, all of them visible from GUI, but not on Hop Web, due to incompatibility of some RAP widgets:
Transforms:
- `Table Input`, `Database Join`,` Dynamic SQL Row`, `Exec SQL`: highlight of SQL reserved words + vendor keywords + functions/procedures
-  `Script`: support for Python and Groovy reserved words
- `JavaScript`: support for JS reserved words
- `User Defined Java Class`: Java keywords
Actions:
- `SQL`,`Wait for SQL` : like all the SQL transforms above mentioned, highlight of SQL reserved words + vendor keywords + functions/procedures
To make clear that you license your contribution under the [Apache License Version 2.0, …

Enable Code Highlighting

---

CONTRIBUTING.md
README.md
assemblies/static/src/main/resources/README.txt
docs/hop-tech-manual/modules/ROOT/pages/hop-vs-kettle/if-you-know-kettle.adoc

[DOC] remove mattermost references

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/rowdenormaliser.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/rownormaliser.adoc

Updates in Row normalizer and Row denormalizer documentation pages, see #4494

Documentation update - see #4494

---

plugins/actions/sql/src/main/java/org/apache/hop/workflow/actions/sql/ActionSqlDialog.java
plugins/actions/waitforsql/src/main/java/org/apache/hop/workflow/actions/waitforsql/ActionWaitForSqlDialog.java
plugins/transforms/databasejoin/src/main/java/org/apache/hop/pipeline/transforms/databasejoin/DatabaseJoinDialog.java
plugins/transforms/dynamicsqlrow/src/main/java/org/apache/hop/pipeline/transforms/dynamicsqlrow/DynamicSqlRowDialog.java
plugins/transforms/sql/src/main/java/org/apache/hop/pipeline/transforms/sql/ExecSqlDialog.java
plugins/transforms/tableinput/src/main/java/org/apache/hop/pipeline/transforms/tableinput/TableInputDialog.java
ui/src/main/java/org/apache/hop/ui/core/widget/ConditionEditor.java
ui/src/main/java/org/apache/hop/ui/core/widget/highlight/GenericCodeHighlight.java
ui/src/main/java/org/apache/hop/ui/core/widget/highlight/JavaHighlight.java
ui/src/main/java/org/apache/hop/ui/core/widget/highlight/JavaScriptHighlight.java
ui/src/main/java/org/apache/hop/ui/core/widget/highlight/SQLValuesHighlight.java

Do not load keywords when no connection, #4387

---

ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java

Only hide and disable the project metadata folder, fixes #4515

---

plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/text/TextFileInputDialog.java

fix text file input button size, fixes #4526

---

integration-tests/mdi/0011-data-grid-parent.hpl
plugins/transforms/datagrid/src/main/java/org/apache/hop/pipeline/transforms/datagrid/DataGridDataMeta.java

fix MDI for datagrid, fixes #4525

---

engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransform.java

fix transform status when FinishedListener is triggered, fixes #3675

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc

Update formula transform documentation, #3777

---

core/src/main/java/org/apache/hop/core/row/value/ValueMetaBase.java
plugins/databases/mysql/src/main/java/org/apache/hop/databases/mysql/MySqlDatabaseMeta.java
plugins/transforms/combinationlookup/src/main/java/org/apache/hop/pipeline/transforms/combinationlookup/CombinationLookupDialog.java
plugins/transforms/combinationlookup/src/main/java/org/apache/hop/pipeline/transforms/combinationlookup/CombinationLookupMeta.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java

couple of fixes, #3699, #3759, #4541

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/workflow-executor.adoc

added row grouping tab specifications in workflow execution …

added row grouping tab specifications in workflow execution. fixes #2594

---

plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/split/SplitGraphMeta.java

XML cleanup for Neo4j Split Graph transform. fixes #2014

---

plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/loginfo/GetLoggingInfo.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/loginfo/GetLoggingInfoDialog.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/loginfo/GetLoggingInfoField.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/loginfo/GetLoggingInfoMeta.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/loginfo/GetLoggingInfoTypes.java

XML cleanup for Neo4j Logging Info transform #2012

---

plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/gencsv/GenerateCsvMeta.java

XML cleanup and doc link fix for Neo4j Generate CSVs. fixes #2011

---

core/src/main/java/org/apache/hop/core/Const.java
core/src/main/java/org/apache/hop/core/xml/XmlParserFactoryProducer.java
integration-tests/xml/files/xml-with-dtd.dtd
integration-tests/xml/files/xml-with-dtd.xml
integration-tests/xml/files/xml-with-internal-dtd.xml
integration-tests/xml/main-0005-dtd-validator-external-file-test.hwf
integration-tests/xml/main-0006-dtd-validator-internal-dtd-test.hwf
integration-tests/xml/main-0007-xml-well-formed-test.hwf
plugins/actions/xml/src/main/java/org/apache/hop/workflow/actions/xml/dtdvalidator/DtdValidator.java
plugins/actions/xml/src/main/java/org/apache/hop/workflow/actions/xml/dtdvalidator/DtdValidatorDialog.java
plugins/actions/xml/src/main/java/org/apache/hop/workflow/actions/xml/xmlwellformed/XmlWellFormed.java
plugins/actions/xml/src/main/java/org/apache/hop/workflow/actions/xml/xmlwellformed/XmlWellFormedDialog.java
plugins/actions/xml/src/main/java/org/apache/hop/workflow/actions/xml/xmlwellformed/XmlWellFormedField.java
plugins/actions/xml/src/main/java/org/apache/hop/workflow/actions/xml/xsdvalidator/XsdValidator.java
plugins/actions/xml/src/main/java/org/apache/hop/workflow/actions/xml/xsdvalidator/XsdValidatorDialog.java
plugins/actions/xml/src/main/java/org/apache/hop/workflow/actions/xml/xslt/Xslt.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/loginfo/GetLoggingInfoDialog.java

XML Cleanup for XML, XSD, XSL, DTD actions #2005 #2744

---

plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/RestDialog.java

write parameter info to meta. fixes #4546

---

plugins/transforms/datagrid/src/main/java/org/apache/hop/pipeline/transforms/datagrid/DataGridDialog.java
ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java

fix strange behaviour on grids, fixes #3801

---

integration-tests/xml/hop-config.json

Add XML_ALLOW_DOCTYPE_DECL to IT test config , #2744

---

lib-jdbc/pom.xml

database upgrades. #4567

---

plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/WriteToLogDialog.java

remove remove all rows from fields table. fixes #4577

---

docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-import.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/workflow-executor.adoc
docs/hop-user-manual/modules/ROOT/pages/plugins/import/kettle-import.adoc

Added fields table to the Import from Kettle page
- [x ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [x ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
- [x ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable.
you have to acknowledge this by using the …

 updated documentation for the Import from Kettle form.fixes #2550

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/pipeline-executor.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/workflow-executor.adoc

Pipeline & workflow executor - added the field description: Run configuration
you have to …

added Run configuration field - pipeline and workflow executor.fixes #4587

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/regexeval.adoc

Documentation update based on #4585

RegEx Evaluation - Documentation update based on #4585

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/beambigtableinput.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/pipeline-executor.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/workflow-executor.adoc

- [x ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [x ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
- [x ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. …

Beam Bigtable Input - added missing fields.fixes  #4588

---

engine/src/main/java/org/apache/hop/core/gui/BasePainter.java
engine/src/main/java/org/apache/hop/pipeline/PipelineMeta.java
engine/src/main/java/org/apache/hop/pipeline/PipelinePainter.java
engine/src/main/java/org/apache/hop/workflow/WorkflowPainter.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopGuiAbstractGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/DragViewZoomBase.java

Improve navigation, selection and move elements in graph #4617, #4598, #4620

---

docs/hop-user-manual/modules/ROOT/assets/images/transforms/icons/stanfordnlp.svg
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/detectlanguage.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/stanfordnlp.adoc
lib/pom.xml
plugins/databases/clickhouse/pom.xml
plugins/engines/beam/pom.xml
plugins/engines/beam/src/assembly/assembly.xml
plugins/tech/parquet/pom.xml
plugins/transforms/detectlanguage/pom.xml
plugins/transforms/detectlanguage/src/assembly/assembly.xml
pom.xml

[RELEASE] dependency upgrades

---

ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java

content is lost when adding a new row during edit, fixes #4642

---

plugins/tech/neo4j/pom.xml

minor neo4j java driver upgrade. fixes #4647

---

docs/hop-dev-manual/antora.yml
docs/hop-tech-manual/antora.yml
docs/hop-user-manual/antora.yml
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/regexeval.adoc
pom.xml

[RELEASE] doc version and pom formatting

---

docs/hop-tech-manual/modules/ROOT/pages/hop-vs-kettle/hop-import.adoc

remove :documentationpath: from hop-import.adoc

---

docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-import.adoc

[DOCS] remove broken links

---

plugins/engines/beam/src/main/java/org/apache/hop/beam/transforms/io/BeamInputMeta.java
plugins/engines/beam/src/main/java/org/apache/hop/beam/transforms/io/BeamOutputMeta.java

fix documentation links for beam inputs, fixes #4663

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/pipeline-executor.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/workflow-executor.adoc

Pipeline Executor and Workflow Executor + RESULT ROWS TAB - RESULT FILES TAB fields missing.fixes  #4610

---

plugins/misc/reflection/src/main/java/org/apache/hop/reflection/pipeline/xp/PipelineStartLoggingXp.java
plugins/misc/reflection/src/main/java/org/apache/hop/reflection/workflow/xp/WorkflowStartLoggingXp.java
plugins/misc/testing/src/main/java/org/apache/hop/testing/gui/TestingGuiPlugin.java

add parent to logging pipeline, fixes #4690

---

ui/src/main/java/org/apache/hop/ui/core/dialog/PreviewRowsDialog.java
ui/src/main/java/org/apache/hop/ui/core/widget/ColumnInfo.java
ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/PipelineExecutionViewer.java

- Set ValueMeta icon to preview  dialog
- Set ValueMeta icon to preview data in pipeline execution viewer
Tested under Windows 11 only, must be tested with other OS.

Add a property to the ColumnInfo class to define an image #4651

---

pom.xml

Bump Eclipse Platform from 3.127.0 to 3.128.0

---

.asf.yaml
.github/workflows/pr_build_code.yml

update github action cache, fixes #4693 & remove some GitHub Discussions mails #4695

---

docs/hop-user-manual/modules/ROOT/pages/how-to-guides/joins-lookups.adoc
docs/hop-user-manual/modules/ROOT/pages/workflow/workflows.adoc

fix doc headings. fixes #4702

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/abort.adoc

ABORT transform + Options section incomplete.fixes  #4709

---

assemblies/plugins/pom.xml
docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/database/databases/cloudera-impala.adoc
plugins/databases/impala/pom.xml
plugins/databases/impala/src/assembly/assembly.xml
plugins/databases/impala/src/main/java/org/apache/hop/databases/impala/ImpalaDatabaseMeta.java
plugins/databases/impala/src/main/resources/org/apache/hop/databases/impala/messages/messages_en_US.properties
plugins/databases/impala/src/main/resources/version.xml
plugins/databases/pom.xml
plugins/tech/avro/src/main/java/org/apache/hop/avro/transforms/avroinput/AvroFileInput.java

Fix for issue #4714 (Minor Avro Input fix)
Implementation of issue #4715 (Database wrapper for Cloudera Impala)

Issues #4714 and #4715

---

docs/hop-dev-manual/modules/ROOT/pages/apache-release/creating-a-release.adoc
pom.xml

disable assemblies and test during release, fixes #4759

---

plugins/transforms/databaselookup/src/main/java/org/apache/hop/pipeline/transforms/databaselookup/DatabaseLookupMeta.java
plugins/transforms/databaselookup/src/test/java/org/apache/hop/pipeline/transforms/databaselookup/readallcache/ReadAllCacheTest.java

Similar to issue #3699 the connection field wasn't copied in the copy constructor causing the remote execution bug.

Issue #4793 (and fixing some warnings)

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/salesforceinput.adoc

salesforce input - added delete example case.fixes  #4481

---

integration-tests/http/0017-rest-metadata-type.hpl
integration-tests/http/main-0017-rest-metadata-type.hwf
integration-tests/http/metadata/restconnection/castlemock.json
plugins/misc/rest/src/main/java/org/apache/hop/metadata/rest/RestConnection.java
plugins/misc/rest/src/main/java/org/apache/hop/metadata/rest/RestConnectionEditor.java
plugins/misc/rest/src/test/java/org/apache/hop/metadata/rest/RestTest.java
plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/Rest.java
plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/RestDialog.java

rest metadata type and client fixes #4369

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms.adoc

[DOCS] fix broken website link

---

plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/Rest.java

fix connection fetch, #4369

---

core/src/main/java/org/apache/hop/core/variables/resolver/VariableResolver.java
docs/hop-user-manual/modules/ROOT/pages/metadata-types/variable-resolver/pipeline-variable-resolver.adoc
plugins/actions/sql/src/main/java/org/apache/hop/workflow/actions/sql/ActionSqlDialog.java
plugins/actions/waitforsql/src/main/java/org/apache/hop/workflow/actions/waitforsql/ActionWaitForSqlDialog.java
plugins/transforms/databasejoin/src/main/java/org/apache/hop/pipeline/transforms/databasejoin/DatabaseJoinDialog.java
plugins/transforms/dynamicsqlrow/src/main/java/org/apache/hop/pipeline/transforms/dynamicsqlrow/DynamicSqlRowDialog.java
plugins/transforms/sql/src/main/java/org/apache/hop/pipeline/transforms/sql/ExecSqlDialog.java
plugins/transforms/tableinput/src/main/java/org/apache/hop/pipeline/transforms/tableinput/TableInputDialog.java

use databaseMeta.getReservedWords() and fix variable resolver images/url

---

plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesAddedFunctions.java
plugins/transforms/javascript/src/main/resources/org/apache/hop/pipeline/transforms/javascript/jsFunctionHelp.xml

Simple extra function for JavaScript to resolve variable expressions : `resolveVariable()`, with GUI help and sample.

Fix for issue #4460

---

integration-tests/transforms/0004-concat-fields.hpl
plugins/actions/http/src/main/java/org/apache/hop/workflow/actions/http/ActionHttp.java
plugins/transforms/concatfields/src/main/java/org/apache/hop/pipeline/transforms/concatfields/ConcatField.java
plugins/transforms/concatfields/src/main/java/org/apache/hop/pipeline/transforms/concatfields/ConcatFields.java
plugins/transforms/concatfields/src/main/java/org/apache/hop/pipeline/transforms/concatfields/ConcatFieldsMeta.java
plugins/transforms/concatfields/src/main/java/org/apache/hop/pipeline/transforms/concatfields/ExtraFields.java
plugins/transforms/concatfields/src/test/java/org/apache/hop/pipeline/transforms/concatfields/ConcatFieldsMetaTest.java
plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/LogField.java
plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/WriteToLogDialog.java
plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/WriteToLogMeta.java

minor fixes to concatfield - #4818, write to log fix #4850, proxy fix for http action #4768

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/tableinput.adoc

updated table input docs. #4117

---

Jenkinsfile
Jenkinsfile.daily
plugins/transforms/cratedbbulkloader/src/test/java/org/apache/hop/pipeline/transforms/cratedbbulkloader/http/BulkImportClientIT.java
plugins/transforms/cratedbbulkloader/src/test/java/org/apache/hop/pipeline/transforms/cratedbbulkloader/http/CrateDBBulkImportTest.java

Fix testcontainers in Jenkins, fixes #4889

---

pom.xml

temporary override json-smart, fixes #4898

---

pom.xml

remove temp fix, #4898

---

engine/src/main/java/org/apache/hop/pipeline/TransformWithMappingMeta.java
plugins/actions/pipeline/src/main/java/org/apache/hop/workflow/actions/pipeline/ActionPipeline.java
plugins/transforms/excel/src/test/java/org/apache/hop/pipeline/transforms/excelinput/ExcelInputMetaTest.java
plugins/transforms/pipelineexecutor/src/main/java/org/apache/hop/pipeline/transforms/pipelineexecutor/PipelineExecutor.java
plugins/transforms/pipelineexecutor/src/main/java/org/apache/hop/pipeline/transforms/pipelineexecutor/PipelineExecutorData.java
plugins/transforms/pipelineexecutor/src/main/java/org/apache/hop/pipeline/transforms/pipelineexecutor/PipelineExecutorDialog.java
plugins/transforms/pipelineexecutor/src/main/java/org/apache/hop/pipeline/transforms/pipelineexecutor/PipelineExecutorMeta.java
plugins/transforms/pipelineexecutor/src/main/java/org/apache/hop/pipeline/transforms/pipelineexecutor/PipelineExecutorResultRows.java
plugins/transforms/pipelineexecutor/src/test/java/org/apache/hop/pipeline/transforms/pipelineexecutor/PipelineExecutorMetaTest.java
plugins/transforms/pipelineexecutor/src/test/resources/pipeline-executor-transform.xml

add HopMetadataProperty to pipelineExecutor, fixes #1889

---

plugins/transforms/workflowexecutor/src/main/java/org/apache/hop/pipeline/transforms/workflowexecutor/WorkflowExecutor.java
plugins/transforms/workflowexecutor/src/main/java/org/apache/hop/pipeline/transforms/workflowexecutor/WorkflowExecutorDialog.java
plugins/transforms/workflowexecutor/src/main/java/org/apache/hop/pipeline/transforms/workflowexecutor/WorkflowExecutorMeta.java
plugins/transforms/workflowexecutor/src/main/java/org/apache/hop/pipeline/transforms/workflowexecutor/WorkflowExecutorResultRows.java
plugins/transforms/workflowexecutor/src/test/java/org/apache/hop/pipeline/transforms/workflowexecutor/WorkflowExecutorMetaTest.java
plugins/transforms/workflowexecutor/src/test/resources/workflow-executor-transform.xml

add HopMetadataProperty to workflow executor, fixes #1948

---

plugins/actions/shell/src/main/java/org/apache/hop/workflow/actions/shell/ActionShell.java
plugins/actions/shell/src/main/java/org/apache/hop/workflow/actions/shell/ActionShellDialog.java
plugins/actions/shell/src/test/java/org/apache/hop/workflow/actions/shell/WorkflowActionShellLoadSaveTest.java
plugins/actions/shell/src/test/resources/shell-action.xml

add HopMetadataProperty to shell action, fixes #1990

---

plugins/actions/dostounix/src/main/java/org/apache/hop/workflow/actions/dostounix/ActionDosToUnix.java
plugins/actions/dostounix/src/main/java/org/apache/hop/workflow/actions/dostounix/ActionDosToUnixDialog.java
plugins/actions/dostounix/src/test/java/org/apache/hop/workflow/actions/dostounix/WorkflowActionDosToUnixTest.java
plugins/actions/dostounix/src/test/resources/dos-unix-converter-action.xml

add HopMetadataProperty to DOS 2 Unix action, fixes #1967

---

plugins/actions/mysqlbulkfile/src/main/java/org/apache/hop/workflow/actions/mysqlbulkfile/ActionMysqlBulkFile.java
plugins/actions/mysqlbulkfile/src/main/java/org/apache/hop/workflow/actions/mysqlbulkfile/ActionMysqlBulkFileDialog.java
plugins/actions/mysqlbulkfile/src/test/java/org/apache/hop/workflow/actions/mysqlbulkfile/WorkflowActionMysqlBulkFileLoadSaveTest.java
plugins/actions/mysqlbulkfile/src/test/resources/mysql-bulkfile-action.xml

add HopMetadataProperty to MySQL Bulk File action, fixes #1982

---

plugins/actions/mysqlbulkload/src/main/java/org/apache/hop/workflow/actions/mysqlbulkload/ActionMysqlBulkLoad.java
plugins/actions/mysqlbulkload/src/main/java/org/apache/hop/workflow/actions/mysqlbulkload/ActionMysqlBulkLoadDialog.java
plugins/actions/mysqlbulkload/src/test/java/org/apache/hop/workflow/actions/mysqlbulkload/WorkflowActionMysqlBulkLoadLoadSaveTest.java
plugins/actions/mysqlbulkload/src/test/resources/mysql-bulkloader-action.xml

add HopMetadataProperty to MySQL Bulk loader action, fixes #1983

---

docs/hop-dev-manual/antora.yml
docs/hop-tech-manual/antora.yml
docs/hop-user-manual/antora.yml

[RELEASE] Update doc version

---

plugins/transforms/joinrows/pom.xml

fix dependency version in pom , fixes #4949

---

docs/hop-user-manual/modules/ROOT/pages/concepts.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/hop-concepts/data-types.adoc

added data type docs. fixes #4921

---

docs/hop-user-manual/modules/ROOT/pages/vfs/google-drive-vfs.adoc
plugins/engines/beam/pom.xml
plugins/engines/beam/src/assembly/assembly.xml
plugins/tech/google/pom.xml
plugins/tech/google/src/assembly/assembly.xml

fix googledrive implementation, fixes #2524

---

plugins/databases/mssql/src/main/java/org/apache/hop/databases/mssql/MsSqlServerDatabaseMeta.java
plugins/databases/mssqlnative/src/main/java/org/apache/hop/databases/mssqlnative/MsSqlServerNativeDatabaseMeta.java

add quotes for table, fixes #4002

---

docker/Dockerfile.web
ui/src/main/java/org/apache/hop/ui/core/widget/ControlSpaceKeyAdapter.java

fix ctrl + space bug when not selecting an item, fixes #4817

---

lib/pom.xml
plugins/engines/beam/pom.xml
plugins/tech/google/pom.xml
plugins/tech/google/src/assembly/assembly.xml

fix google sheets caused by googledrive, #2524

---

plugins/transforms/sqlfileoutput/src/main/java/org/apache/hop/pipeline/transforms/sqlfileoutput/SQLFileOutputDialog.java
plugins/transforms/sqlfileoutput/src/main/java/org/apache/hop/pipeline/transforms/sqlfileoutput/SQLFileOutputMeta.java

bug in creating new sql file output, #1935

---

docs/hop-user-manual/modules/ROOT/pages/database/databases/access.adoc
plugins/databases/access/pom.xml
plugins/databases/access/src/assembly/assembly.xml
plugins/databases/access/src/main/java/org/apache/hop/databases/access/AccessDatabaseMeta.java
plugins/databases/access/src/main/java/org/apache/hop/pipeline/transforms/accessoutput/AccessFileFormat.java
plugins/databases/access/src/main/java/org/apache/hop/pipeline/transforms/accessoutput/AccessOutput.java
plugins/databases/access/src/main/java/org/apache/hop/pipeline/transforms/accessoutput/AccessOutputData.java
plugins/databases/access/src/main/java/org/apache/hop/pipeline/transforms/accessoutput/AccessOutputDialog.java
plugins/databases/access/src/main/java/org/apache/hop/pipeline/transforms/accessoutput/AccessOutputMeta.java

fix and upgrade provided access plugins, fixes #4918

---

assemblies/debug/pom.xml
core/src/main/java/org/apache/hop/core/Const.java
core/src/main/java/org/apache/hop/core/logging/LogChannel.java
core/src/main/java/org/apache/hop/core/logging/LoggingBuffer.java
core/src/main/java/org/apache/hop/core/logging/LoggingRegistry.java
docs/hop-user-manual/modules/ROOT/pages/variables.adoc
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiLogBrowser.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineGridDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineLogDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineRunDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowGridDelegate.java
ui/src/main/resources/org/apache/hop/ui/hopgui/messages/messages_en_US.properties

fix some inconsistencies in logging

---

engine/src/main/java/org/apache/hop/workflow/WorkflowMeta.java
engine/src/main/java/org/apache/hop/workflow/action/IAction.java
engine/src/main/resources/org/apache/hop/workflow/messages/messages_en_US.properties

- Add a check if an action is not used in a workflow
- Rename method "countEntries"  to "countActions"
- Remove unsused constant STRING_SPECIAL_ERROR and STRING_SPECIAL_OK

Add a check if an action is not used in a workflow #4930

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml

Add type to issues

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/task.yml

Remove our own tags when creating issues

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/util/ProjectsUtil.java
ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditorDialog.java

force metadata editor to foreground, fixes #5012

---

plugins/actions/filesexist/src/main/java/org/apache/hop/workflow/actions/filesexist/ActionFilesExist.java
plugins/actions/filesexist/src/main/java/org/apache/hop/workflow/actions/filesexist/ActionFilesExistDialog.java
plugins/actions/filesexist/src/main/java/org/apache/hop/workflow/actions/filesexist/FileItem.java
plugins/actions/filesexist/src/main/resources/org/apache/hop/workflow/actions/filesexist/messages/messages_de_DE.properties
plugins/actions/filesexist/src/main/resources/org/apache/hop/workflow/actions/filesexist/messages/messages_en_US.properties
plugins/actions/filesexist/src/main/resources/org/apache/hop/workflow/actions/filesexist/messages/messages_es_AR.properties
plugins/actions/filesexist/src/main/resources/org/apache/hop/workflow/actions/filesexist/messages/messages_es_ES.properties
plugins/actions/filesexist/src/main/resources/org/apache/hop/workflow/actions/filesexist/messages/messages_fr_FR.properties
plugins/actions/filesexist/src/main/resources/org/apache/hop/workflow/actions/filesexist/messages/messages_it_IT.properties
plugins/actions/filesexist/src/main/resources/org/apache/hop/workflow/actions/filesexist/messages/messages_ja_JP.properties
plugins/actions/filesexist/src/main/resources/org/apache/hop/workflow/actions/filesexist/messages/messages_ko_KR.properties
plugins/actions/filesexist/src/main/resources/org/apache/hop/workflow/actions/filesexist/messages/messages_pt_BR.properties
plugins/actions/filesexist/src/main/resources/org/apache/hop/workflow/actions/filesexist/messages/messages_zh_CN.properties
plugins/actions/filesexist/src/test/java/org/apache/hop/workflow/actions/filesexist/WorkflowActionFilesExistTest.java
plugins/actions/filesexist/src/test/resources/files-exist-action.xml

Redesigned user interface for ActionFilesExist #5032

---

assemblies/debug/pom.xml
core/src/main/java/org/apache/hop/core/gui/plugin/GuiRegistry.java
core/src/main/java/org/apache/hop/core/gui/plugin/toolbar/GuiToolbarElement.java
core/src/main/java/org/apache/hop/core/gui/plugin/toolbar/GuiToolbarItem.java
plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java
ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
ui/src/main/java/org/apache/hop/ui/core/gui/GuiToolbarWidgets.java

Add option to make toolbar COMBO read-only, fixes #5040

---

docs/hop-user-manual/modules/ROOT/pages/database/databases/snowflake.adoc
lib-jdbc/pom.xml

update snowflake driver, fixes #5044

---

docs/hop-user-manual/modules/ROOT/pages/hop-server/index.adoc
engine/src/main/java/org/apache/hop/server/HopServerMeta.java

added missing Hop Server XML options. fixes #5054

---

plugins/actions/columnsexist/src/main/java/org/apache/hop/workflow/actions/columnsexist/ActionColumnsExist.java
plugins/actions/columnsexist/src/main/resources/org/apache/hop/workflow/actions/columnsexist/messages/messages_en_US.properties

Verify action ColumnExists throw NoSuchMethodException #5071

---

plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutputMeta.java
plugins/transforms/propertyoutput/src/main/java/org/apache/hop/pipeline/transforms/propertyoutput/PropertyOutputMeta.java
plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/textfileoutput/TextFileOutputMeta.java
plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/WriteToLogMeta.java
plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/xmloutput/XmlOutputMeta.java

fix extension/extention issue after kettle import #3821 & fix logLevel issue #5076

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/project/ProjectDialog.java
plugins/transforms/pipelineexecutor/src/main/java/org/apache/hop/pipeline/transforms/pipelineexecutor/PipelineExecutorDialog.java

Experiment with Scrollable in dialog for smaller screens, fixes #5078

---

engine/pom.xml
lib/pom.xml
plugins/engines/beam/pom.xml
plugins/engines/beam/src/assembly/assembly.xml
plugins/tech/azure/src/assembly/assembly.xml
plugins/tech/cassandra/src/assembly/assembly.xml
plugins/tech/google/pom.xml
plugins/tech/google/src/assembly/assembly.xml
plugins/tech/neo4j/pom.xml
plugins/tech/parquet/pom.xml
plugins/transforms/kafka/pom.xml
plugins/transforms/languagemodelchat/pom.xml
plugins/transforms/languagemodelchat/src/assembly/assembly.xml
pom.xml

Update dependencies and remove some duplicates, fixes #5102

---

assemblies/static/src/main/resources/LICENSE
lib/pom.xml
plugins/engines/beam/src/assembly/assembly.xml
plugins/tech/aws/src/assembly/assembly.xml
plugins/tech/azure/src/assembly/assembly.xml
plugins/tech/cassandra/src/assembly/assembly.xml
plugins/tech/dropbox/src/assembly/assembly.xml
plugins/tech/neo4j/src/assembly/assembly.xml
plugins/tech/parquet/pom.xml
plugins/transforms/filemetadata/src/assembly/assembly.xml
plugins/transforms/kafka/src/assembly/assembly.xml
plugins/transforms/languagemodelchat/src/assembly/assembly.xml
plugins/transforms/xml/src/assembly/assembly.xml

More dependency cleanup, #5102

---

lib/pom.xml
plugins/tech/avro/src/main/samples/transforms/avro-encode-decode-basic.hpl

fix dependency and test, #5102

---

ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditor.java
ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataManager.java
ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiKeyHandler.java

fix copy paste to jdbc metadata item, fixes #2967

---

assemblies/debug/pom.xml
docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/metadata-types/google-storage-authentication.adoc
docs/hop-user-manual/modules/ROOT/pages/metadata-types/index.adoc
plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageFileName.java
plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageFileObject.java
plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageFileProvider.java
plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageFileSystem.java
plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageFileSystemConfigBuilder.java
plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageVfsPlugin.java
plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/config/GoogleCloudConfig.java
plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/config/GoogleCloudConfigPlugin.java
plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/metadatatype/GoogleStorageCredentialsType.java
plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/metadatatype/GoogleStorageMetadataType.java
plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/metadatatype/GoogleStorageMetadataTypeEditor.java
plugins/tech/google/src/main/resources/org/apache/hop/vfs/gs/metadatatype/messages/messages_en_US.properties
ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiKeyHandler.java

Add support for multiple GCS locations, fixes #4655

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/pipeline-unit-testing.adoc
docs/hop-user-manual/modules/ROOT/pages/projects/projects-environments.adoc

updated unit testing documentation. fixes 5127

---

core/src/main/java/org/apache/hop/core/plugins/BasePluginTypeExposer.java
core/src/main/java/org/apache/hop/core/plugins/SupplementalPlugin.java
core/src/main/java/org/apache/hop/core/row/value/ValueMetaConverter.java
core/src/main/java/org/apache/hop/metadata/serializer/json/JsonMetadataParser.java
core/src/main/java/org/apache/hop/metadata/serializer/json/JsonMetadataSerializer.java
engine/src/main/java/org/apache/hop/core/metadata/SerializableMetadataProvider.java
plugins/tech/aws/src/test/java/org/apache/hop/vfs/s3/vfs/S3FileNameParserIT.java
plugins/tech/aws/src/test/java/org/apache/hop/vfs/s3/vfs/S3FileNameTest.java
plugins/tech/aws/src/test/java/org/apache/hop/vfs/s3/vfs/S3FileObjectTest.java
plugins/tech/aws/src/test/java/org/apache/hop/vfs/s3/vfs/S3NFileNameTest.java
plugins/tech/aws/src/test/java/org/apache/hop/vfs/s3/vfs/S3NFileObjectTest.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java

do not fail on missing metadata objects, some cleanup, fixes #5148

---

lib/pom.xml
plugins/engines/beam/src/assembly/assembly.xml
plugins/tech/azure/src/assembly/assembly.xml

dependency cleanup for reactor-core, fixes #5161

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/project/ProjectDialog.java

minor improvements to project dialog, fixes #5138

---

assemblies/debug/pom.xml
plugins/transforms/blockuntiltransformsfinish/src/main/java/org/apache/hop/pipeline/transforms/blockuntiltransformsfinish/BlockUntilTransformsFinishDialog.java

Only show valid transforms to block in blockingtransform, fixes #5166

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
plugins/transforms/formula/src/main/resources/org/apache/hop/pipeline/transforms/formula/function/functions.xml

Remove urlencode from formula list, fixes #5108

---

docs/hop-dev-manual/antora.yml
docs/hop-tech-manual/antora.yml
docs/hop-user-manual/antora.yml
docs/hop-user-manual/modules/ROOT/pages/logging/logging-reflection.adoc
docs/hop-user-manual/modules/ROOT/pages/metadata-types/pipeline-log.adoc
docs/hop-user-manual/modules/ROOT/pages/metadata-types/workflow-log.adoc
integration-tests/kafka/disabled.txt
plugins/misc/reflection/src/main/java/org/apache/hop/reflection/pipeline/meta/PipelineLog.java
plugins/misc/reflection/src/main/java/org/apache/hop/reflection/workflow/meta/WorkflowLog.java

change pipeline/workflow logging defaults, update docs, fixes #5199

---

ui/src/main/java/org/apache/hop/ui/core/widget/TreeMemory.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java

Reduce flicker by restoring folders expanded before setRedraw(true)

Bring back to front a tab of an already open file #5184

---

plugins/actions/abort/src/test/java/org/apache/hop/workflow/actions/abort/ActionAbortTest.java
plugins/actions/abort/src/test/java/org/apache/hop/workflow/actions/abort/WorkflowActionAbortLoadSaveTest.java
plugins/actions/addresultfilenames/src/test/java/org/apache/hop/workflow/actions/addresultfilenames/WorkflowActionAddResultFilenamesLoadSaveTest.java
plugins/actions/as400command/src/test/java/org/apache/hop/workflow/actions/as400command/ActionAs400CommandLoadSaveTest.java
plugins/actions/checkdbconnection/src/test/java/org/apache/hop/workflow/actions/checkdbconnection/ActionCheckDbConnectionsTest.java
plugins/actions/checkfilelocked/src/test/java/org/apache/hop/workflow/actions/checkfilelocked/ActionCheckFilesLockedTest.java
plugins/actions/columnsexist/src/test/java/org/apache/hop/workflow/actions/columnsexist/ActionColumnsExistTest.java
plugins/actions/copyfiles/src/test/java/org/apache/hop/workflow/actions/copyfiles/WorkflowActionCopyFilesLoadSaveTest.java
plugins/actions/copyfiles/src/test/java/org/apache/hop/workflow/actions/copyfiles/WorkflowActionCopyFilesTest.java
ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditor.java
ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataManager.java
ui/src/main/java/org/apache/hop/ui/core/vfs/HopVfsFileDialog.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java
ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/metadata/messages/messages_en_US.properties

cleanup and metadata item fixes, #4969

---

docs/hop-dev-manual/modules/ROOT/nav.adoc

update nav for creating your own plugin. fixes #5190

---

plugins/databases/access/src/main/java/org/apache/hop/databases/access/AccessDatabaseMeta.java
plugins/databases/access/src/main/java/org/apache/hop/pipeline/transforms/accessoutput/AccessOutputMeta.java
plugins/databases/access/src/test/java/org/apache/hop/databases/access/AccessDatabaseMetaTest.java

fix access connection, fixes #5217

---

plugins/transforms/workflowexecutor/src/main/java/org/apache/hop/pipeline/transforms/workflowexecutor/WorkflowExecutor.java

allow variables in "field to use" of workflow executor, fixes #5196

---

assemblies/static/src/main/resources/hop-gui.sh

The default shell is sh on FreeBSD.

Fixed #5235 Support FreeBSD for HopGUI

---

core/src/main/java/org/apache/hop/core/gui/plugin/GuiRegistry.java
docs/hop-tech-manual/modules/ROOT/nav.adoc
docs/hop-tech-manual/modules/ROOT/pages/disable-ui-elements.adoc
ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiEnvironment.java

add ability to disable UI elements, fixes #5238

---

ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java

Fix #5241 Adjust the width of table column with icon or sorted icon

---

ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiLogBrowser.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineGridDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowGridDelegate.java

Don't should refresh Metrics tableView after executed the pipeline execution

Fixed #5240 leak thread on timer of HopGuiXxxDelegate

---

core/src/main/java/org/apache/hop/core/logging/HopLogStore.java
core/src/main/java/org/apache/hop/core/util/ExecutorUtil.java
engine/src/main/java/org/apache/hop/execution/caching/CachingFileExecutionInfoLocation.java
engine/src/main/java/org/apache/hop/pipeline/Pipeline.java
engine/src/main/java/org/apache/hop/pipeline/engines/local/LocalPipelineEngine.java
engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineEngine.java
engine/src/main/java/org/apache/hop/workflow/engines/local/LocalWorkflowEngine.java
engine/src/main/java/org/apache/hop/www/HopServerSingleton.java
plugins/engines/beam/src/main/java/org/apache/hop/beam/core/transform/TransformBatchTransform.java
plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/BeamPipelineEngine.java
plugins/misc/async/src/main/java/org/apache/hop/www/async/xp/PeriodicPipelineStatusUpdateExtensionPoint.java
plugins/misc/reflection/src/main/java/org/apache/hop/reflection/pipeline/xp/PipelineStartLoggingXp.java
plugins/misc/reflection/src/main/java/org/apache/hop/reflection/workflow/xp/WorkflowStartLoggingXp.java
plugins/tech/azure/src/main/java/org/apache/hop/pipeline/transforms/eventhubs/listen/AzureListener.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiLogBrowser.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineGridDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowGridDelegate.java

Thread resources cann't be released if don't call Timer.purge

Release thread resources of timer

---

engine/src/main/java/org/apache/hop/pipeline/PipelinePainter.java
engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineEngine.java
engine/src/main/java/org/apache/hop/pipeline/transform/TransformStatus.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java

- Visualizing a paused pipeline, all unfinished transformations with a pause icon.
- When executing a remote pipeline, provide status feedback and log text.
- A little code cleanup + Lombok

Improve visual rendering of pipeline execution #5250

---

plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/text/TextFileInputDialog.java
plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/text/TextFileInputMeta.java

add missing line to textfile input metadata, fixes #5256

---

assemblies/plugins/pom.xml
docs/hop-user-manual/modules/ROOT/pages/metadata-types/elastic-location-type.adoc
docs/hop-user-manual/modules/ROOT/pages/metadata-types/execution-information-location.adoc
docs/hop-user-manual/modules/ROOT/pages/metadata-types/index.adoc
engine/src/main/java/org/apache/hop/execution/IExecutionInfoLocation.java
engine/src/main/java/org/apache/hop/execution/caching/BaseCachingExecutionInfoLocation.java
engine/src/main/java/org/apache/hop/execution/caching/CacheEntry.java
engine/src/main/java/org/apache/hop/execution/caching/CachingFileExecutionInfoLocation.java
engine/src/main/java/org/apache/hop/execution/caching/DatedId.java
engine/src/main/java/org/apache/hop/execution/caching/EntrySummary.java
engine/src/main/java/org/apache/hop/execution/local/FileExecutionInfoLocation.java
engine/src/main/java/org/apache/hop/execution/remote/RemoteExecutionInfoLocation.java
engine/src/main/resources/org/apache/hop/execution/caching/messages/messages_en_US.properties
plugins/engines/beam/pom.xml
plugins/tech/elastic/pom.xml
plugins/tech/elastic/src/assembly/assembly.xml
plugins/tech/elastic/src/main/java/org/apache/hop/execution/elastic/ElasticExecutionInfoLocation.java
plugins/tech/elastic/src/main/resources/org/apache/hop/execution/elastic/messages/messages_en_US.properties
plugins/tech/elastic/src/main/resources/version.xml
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/execution/NeoExecutionInfoLocation.java
plugins/tech/pom.xml
ui/src/main/java/org/apache/hop/ui/core/gui/GuiCompositeWidgets.java
ui/src/main/java/org/apache/hop/ui/core/gui/IGuiPluginCompositeButtonsListener.java
ui/src/main/java/org/apache/hop/ui/execution/ExecutionInfoLocationEditor.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/PipelineExecutionViewer.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/WorkflowExecutionViewer.java

A new execution information location for Elastic, along with code cleanup for the caching execution location.

Issue #4914

---

core/src/main/java/org/apache/hop/core/database/Database.java

Skip the real data scans on oracle if only get output fields.
If supportsPreparedStatementMetadataRetrieval=false on some database,
Slow sql: executeQuery method will be called in getQueryFieldsFallback, and all params are null

Improve getQueryFields performance by sql condition: 1=2

---

plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/text/TextFileInputDialog.java
plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/fileinput/messages/messages_en_US.properties
plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/fileinput/text/messages/messages_en_US.properties
ui/src/main/java/org/apache/hop/ui/core/dialog/EnterNumberDialog.java
ui/src/main/java/org/apache/hop/ui/core/dialog/EnterNumberDialogResult.java

Add option form-to on show file content, text file input, fixes #5264

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java

Deleting environment does not reset variables, fixes #5267

---

docs/hop-user-manual/modules/ROOT/pages/workflow/actions/sftp.adoc
docs/hop-user-manual/modules/ROOT/pages/workflow/actions/sftpput.adoc

added documentation for unsafe key types in SFTP get and put. #5269

---

ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopDataOrchestrationPerspective.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java

NPE and some other dispose errors, fixes #5280

---

docker/integration-tests/Dockerfile.unit-tests
docker/integration-tests/integration-tests-mail.yaml

fix IT tests, fix #5295

---

plugins/misc/git/src/main/java/org/apache/hop/git/GitGuiPlugin.java
plugins/misc/git/src/main/java/org/apache/hop/git/info/GitInfoExplorerFileTypeHandler.java
plugins/misc/git/src/main/java/org/apache/hop/git/model/UIFile.java

Improve git status colors in file explorer #5299

---

docs/hop-dev-manual/antora.yml
docs/hop-tech-manual/antora.yml
docs/hop-user-manual/antora.yml

[RELEASE] update docs

---

assemblies/static/src/main/resources/LICENSE
plugins/transforms/janino/pom.xml

Upgrade Janino from 3.1.11 to 3.1.12 #5333

---

plugins/actions/abort/src/main/java/org/apache/hop/workflow/actions/abort/ActionAbortDialog.java
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsInputDialog.java
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsOutputDialog.java
plugins/tech/google/src/main/java/org/apache/hop/vfs/googledrive/ui/GoogleAuthorizationDialog.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/perspective/HopNeo4jPerspective.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/cypherbuilder/CypherBuilderDialog.java
plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/editor/FormulaEditor.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/editor/FormulaEditor.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassDialog.java
plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesDialog.java
plugins/transforms/orabulkloader/src/main/java/org/apache/hop/pipeline/transforms/orabulkloader/OraBulkLoaderDialog.java
plugins/transforms/regexeval/src/main/java/org/apache/hop/pipeline/transforms/regexeval/RegexEvalDialog.java
plugins/transforms/script/src/main/java/org/apache/hop/pipeline/transforms/script/ScriptDialog.java
plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/getxmldata/GetXmlDataDialog.java
ui/src/main/java/org/apache/hop/ui/core/dialog/EnterListDialog.java
ui/src/main/java/org/apache/hop/ui/core/vfs/HopVfsFileDialog.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/ExecutionPerspective.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/PipelineExecutionViewer.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/WorkflowExecutionViewer.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java

method list:
* SashForm.setWeights
* DragSource.setTransfer
* SelectionListener.widgetSelectedAdapter
* Browser.addCloseWindowListener
* CTabFolder.setSimple(removed)

Fix #5325 Compatibility issues with the RWT API

---

plugins/misc/mail/src/main/java/org/apache/hop/mail/workflow/actions/mail/ActionMail.java
plugins/misc/mail/src/main/java/org/apache/hop/mail/workflow/actions/mail/ActionMailDialog.java

fixed ui options for mail attachments. #5338

---

plugins/actions/snowflake/pom.xml
plugins/transforms/delete/pom.xml
plugins/transforms/synchronizeaftermerge/pom.xml

Fix the name in the POM.XML of the:
- Delete transformation
- Synchronize After Merge transformation
- Snowflake Warehouse Manager action

Fix the name in the POM.XML

---

engine/src/main/java/org/apache/hop/pipeline/PipelineMeta.java
engine/src/main/java/org/apache/hop/pipeline/transform/TransformMeta.java
engine/src/main/java/org/apache/hop/pipeline/transform/copy/CopyContext.java
engine/src/main/java/org/apache/hop/pipeline/transform/copy/DefaultTransformMetaCopyFactory.java
engine/src/main/java/org/apache/hop/pipeline/transform/copy/ITransformMetaCopyFactory.java
engine/src/main/java/org/apache/hop/workflow/action/ActionMeta.java
engine/src/main/java/org/apache/hop/workflow/action/copy/DefaultActionCopyFactory.java
engine/src/main/java/org/apache/hop/workflow/action/copy/IActionCopyFactory.java
engine/src/test/java/org/apache/hop/pipeline/transform/copy/DefaultTransformMetaCopyFactoryTest.java
engine/src/test/java/org/apache/hop/workflow/action/copy/DefaultActionCopyFactoryTest.java
plugins/actions/delay/src/main/java/org/apache/hop/workflow/actions/delay/ActionDelay.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineTransformDelegate.java

Use copy factory to clone metadata, fixes #5053

---

docs/hop-user-manual/modules/ROOT/pages/workflow/actions/writetolog.adoc

removed transform notes from write to log action. fixes #5375

---

docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/pipeline-metrics.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/run-preview-debug-pipeline.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/pipeline-metrics-table.adoc

updated pipeline execution metrics. fixes #5415

---

assemblies/plugins/pom.xml
docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/database/databases/databricks.adoc
plugins/tech/databricks/pom.xml
plugins/tech/databricks/src/assembly/assembly.xml
plugins/tech/databricks/src/main/java/org/apache/hop/database/databricks/DatabricksDatabaseMeta.java
plugins/tech/databricks/src/main/resources/version.xml

databricks dialect initial version. fixes #5480

---

assemblies/client/src/assembly/assembly.xml
docker/Dockerfile.web

fix missing samples in Hop Web , fixes #5476

---

plugins/transforms/stringcut/src/test/java/org/apache/hop/pipeline/transforms/stringcut/StringCutTest.java

Add tests to stringcut, #4624

---

docker/Dockerfile
docker/resources/load-and-execute.sh

Simply added the ability to pass in a StartAction value for the docker image
https://github.com/apache/hop/issues/5547

Add StartAction to Docker Image

---

docs/hop-user-manual/modules/ROOT/pages/workflow/actions/filesexist.adoc

Update filesexist.adoc - fix #4488

---

assemblies/static/src/main/resources/LICENSE
docs/hop-user-manual/modules/ROOT/pages/database/databases/clickhouse.adoc
lib-jdbc/pom.xml
lib/pom.xml

update dependencies and license file, fixes #5564

---

docs/hop-dev-manual/antora.yml
docs/hop-tech-manual/antora.yml
docs/hop-user-manual/antora.yml
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineGridDelegate.java

refresh timer hardening, #5475

---

docs/hop-user-manual/modules/ROOT/pages/database/databases/databricks.adoc
plugins/tech/databricks/src/main/java/org/apache/hop/database/databricks/DatabricksDatabaseMeta.java

updated catalog name in url, added note to docs. fixes #5607

---

docs/hop-user-manual/modules/ROOT/pages/concepts.adoc
docs/hop-user-manual/modules/ROOT/pages/metadata-driven-architecture.adoc

Hop metadata driven architecture .fixes #2640

---

engine/src/main/java/org/apache/hop/workflow/Workflow.java

Change order of the logging in a workflow, fixes #5671

---

plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/AwsSqsReader.java

remove logging the API key when connecting to SqS, fixes #5677

---

core/src/main/java/org/apache/hop/core/row/RowMeta.java
core/src/main/java/org/apache/hop/core/util/StringUtil.java
plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/Formula.java
plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/FormulaPoi.java
plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/util/FormulaFieldsExtractor.java
plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/util/FormulaParser.java
plugins/transforms/formula/src/test/java/org/apache/hop/pipeline/transforms/formula/util/FormulaParserTest.java

Hi,
this PR intends to make using formula faster, there are several changes - not sure all are interesting for hop but I'm proposing them, at least it can maybe help somebody else:
* (most important one) use HSS POI impementation instead of XSS to bypass xmlbeans, this has the limitation of the column number but is way faster
* (important) do not recreate the row per evaluation, this invalidates the formula cell cache (parsing) which is slow
* (medium) do not copy (and even worse synchronize) the variable substitution since it is done in a safe context (the param is thread safe) and read only
* (less important) do not compare variable with equalsIgnoreCase since they are lower cased before (the java impl is faster)
* (not important) parse only once for all lines all variables in the …

Minor improvement over formula plugin

---

core/src/main/java/org/apache/hop/core/config/HopConfig.java
docker/integration-tests/integration-tests-opensearch.yaml
integration-tests/vertica/disabled.txt
plugins/tech/avro/src/main/java/org/apache/hop/avro/transforms/avrooutput/AvroOutput.java

Also a fix that is happening in some of our custom code, caused by not using strict types in HopConfig.java

fix broken IT tests, fixes #5691

---

docker/integration-tests/integration-tests-mail.yaml
integration-tests/mail/datasets/test.txt
integration-tests/mail/main-0009-mail-with-zip.hwf
plugins/misc/mail/src/main/java/org/apache/hop/mail/workflow/actions/mail/ActionMail.java

Mail Action - Empty mail attachment

---

engine/src/main/java/org/apache/hop/pipeline/transform/ITransformMeta.java

Add a new method to calculate and retrieve extra dependencies

Add getResourceMetaDataDependencies method to ITransformMeta interface

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/execsql.adoc

[DOCS] specify input processing behavior. #3909

[DOCS] specify input processing behavior. #3909

---

.asf.yaml

[INFRA] Only allow squash merge on PR's

---

core/src/main/java/org/apache/hop/core/database/BaseDatabaseMeta.java
core/src/main/java/org/apache/hop/core/database/DatabaseMeta.java
core/src/main/java/org/apache/hop/core/database/IDatabase.java
plugins/tech/databricks/src/main/java/org/apache/hop/database/databricks/DatabricksDatabaseMeta.java
ui/src/main/java/org/apache/hop/ui/core/database/DatabaseMetaEditor.java
ui/src/main/java/org/apache/hop/ui/core/gui/GuiCompositeWidgets.java
ui/src/main/resources/org/apache/hop/ui/core/database/messages/messages_en_US.properties

hide rdbms editor fields #5699

---

integration-tests/http/0002-http-client-test-empty-parameters.hpl
integration-tests/http/main-0002-http-client.hwf
plugins/transforms/http/src/main/java/org/apache/hop/pipeline/transforms/http/Http.java
plugins/transforms/http/src/main/java/org/apache/hop/pipeline/transforms/http/HttpData.java
plugins/transforms/http/src/main/java/org/apache/hop/pipeline/transforms/http/HttpMeta.java
plugins/transforms/http/src/test/java/org/apache/hop/pipeline/transforms/http/HttpDataTest.java
plugins/transforms/http/src/test/java/org/apache/hop/pipeline/transforms/http/HttpMetaTest.java
plugins/transforms/http/src/test/java/org/apache/hop/pipeline/transforms/http/HttpTest.java

fix #5759, allow empty parameters in http client

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java
plugins/misc/projects/src/main/resources/org/apache/hop/projects/gui/messages/messages_en_US.properties
ui/src/main/java/org/apache/hop/ui/core/widget/FileTree.java

Refactor dialog layout management.
Prevent the zip file from including itself.

Fix file paths in "Export current project to zip" #5662

---

core/src/main/java/org/apache/hop/core/config/ConfigFileSerializer.java
core/src/main/java/org/apache/hop/core/json/HopJson.java

Add newline to json Arrays in hop-config, fixes #5769

---

docs/hop-user-manual/modules/ROOT/pages/hop-server/web-service.adoc
engine/src/main/java/org/apache/hop/www/WebServiceServlet.java
engine/src/main/java/org/apache/hop/www/service/WebService.java
ui/src/main/java/org/apache/hop/ui/www/service/WebServiceEditor.java
ui/src/main/java/org/apache/hop/ui/www/service/WebServiceGuiPlugin.java
ui/src/main/resources/org/apache/hop/ui/www/service/messages/messages_en_US.properties

Webservice improvements, fixes #5425 ,#4692, #4277 and #2673 
