- archive-transformation-steps/src/main/resources/engine/steps/delay/messages/messages_pt_BR.properties
- ui/src/main/resources/org/apache/hop/ui/i18n/editor/messages/messages_pt_BR.properties
Hi Matt , 
how about hop in portugues from Brazil?
> Add translate pt_BR files for Hop Project

- ui/src/main/java/org/apache/hop/ui/core/dialog/ContextDialog.java
* Fixed scrolling and vertical scroll bar
* Fixed a paint problem when a client area was off screen
* Fixed error: "Widget is disposed"
* Flicker suppression when mouse moves
* Add key PAGE_UP and PAGE_DOWN
* Add key HOME and END
* Listener with lambda or private method
* Enlarge ToolTip on 3 lines
> HOP-180 Fix scrolling + ContextDialog improvement

- ui/src/main/java/org/apache/hop/ui/core/database/DatabaseMetaDialog.java
Connection work with this fix but there is yet another problem with the Test button and GuiElement
> HOP-206 Fix database connection

- plugins/actions/xml/src/main/doc/dtdvalidator.adoc
- plugins/actions/xml/src/main/doc/xmlwellformed.adoc
- plugins/actions/xml/src/main/doc/xsdvalidator.adoc
- plugins/actions/xml/src/main/doc/xslt.adoc
- plugins/engines/beam/src/main/doc/beambigqueryinput.adoc
- plugins/engines/beam/src/main/doc/beambigqueryoutput.adoc
- plugins/engines/beam/src/main/doc/beampublisher.adoc
- plugins/engines/beam/src/main/doc/beamsubscriber.adoc
Additional xml action and beam trans docs:
- dtdvalidator
- xmlwellformed
- xsdvalidator
- xslt
- beambigqueryinput
- beambigqueryoutput
- beampublisher
- beamsubscriber
> HOP-214: xml actions and beam trans

- plugins/actions/xml/src/main/doc/dtdvalidator.adoc
- plugins/actions/xml/src/main/doc/xmlwellformed.adoc
- plugins/actions/xml/src/main/doc/xsdvalidator.adoc
- plugins/actions/xml/src/main/doc/xslt.adoc
- plugins/engines/beam/src/main/doc/beamconsume.adoc
- plugins/engines/beam/src/main/doc/beaminput.adoc
- plugins/engines/beam/src/main/doc/beamoutput.adoc
- plugins/engines/beam/src/main/doc/beamproduce.adoc
- plugins/engines/beam/src/main/doc/beampublisher.adoc
- plugins/engines/beam/src/main/doc/beamsubscriber.adoc
- plugins/engines/beam/src/main/doc/beamtimestamp.adoc
- plugins/engines/beam/src/main/doc/beamwindow.adoc
Remaining Beam transforms, updated paths.
> HOP-214: remaining beam transforms and updated xml paths

- engine/src/main/java/org/apache/hop/pipeline/PipelinePainter.java
- engine/src/main/java/org/apache/hop/workflow/WorkflowPainter.java
Related to
https://github.com/HiromuHota/rap/commit/cc13fbdb6d6d537747f7fb
https://bugs.eclipse.org/bugs/show_bug.cgi?id=529704#c5
> HOP-13: porting HiromuHota/pentaho-kettle#99

- ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiFileDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopPipelineFileType.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopWorkflowFileType.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowRunDelegate.java
HOP-582 saving pipeline issue
- fix error when trying to run pipeline/workflow without filename
- move 'save' audit track in IHopFileTypeHandler.save
- move 'open' audit track in HopPipelineFileType.open and HopWorkflowFileType.open
Hop-514
- move enforce file extension in IHopFileTypeHandler.saveAs
> HOP-582,  Hop-514

- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInputMeta.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapoutput/LdapOutputDialog.java
"static" base class members should not be accessed via derived types (java:S3252)
**After code change:**
```
[INFO] Hop Plugins Transforms LDAP ........................ SUCCESS [  4.842 s]
[INFO] Hop Plugins Transforms LDIF Input .................. SUCCESS [  4.476 s]
[INFO] Hop Plugins Transforms Mail ........................ SUCCESS [  4.592 s]
.
.
.
[INFO] Hop Assemblies Plugins Transforms JSON ............. SUCCESS [  0.681 s]
[INFO] Hop Assemblies Plugins Transforms Kafka ............ SUCCESS [  0.087 s]
[INFO] Hop Assemblies Plugins Transforms LDAP ............. SUCCESS [  0.095 s]
[INFO] Hop Assemblies Plugins Transforms LDIF Input ....... SUCCESS [  0.107 s]
[INFO] Hop Assemblies Plugins Transforms Filter Rows ...... SUCCESS [  0.084 s]
[INFO] Hop Assemblies Plugins Transforms …
```
> Following Sonar S3252 - static base class members should not be accessed via derived types

- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapConnection.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInput.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapProtocol.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapSslProtocol.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/store/CustomSocketFactory.java
- plugins/transforms/ldap/src/test/java/org/apache/hop/pipeline/transforms/ldapinput/LdapMockProtocol.java
"throws" declarations should not be superfluous (java:S1130)
Local variable and method parameter names should comply with a naming convention (java:S117)
Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used (java:S1149)
Methods should not return constants (java:S3400)
Remove the declaration of thrown exception 'org.apache.hop.core.exception.HopException', as it cannot be thrown from method's body.
Collection.isEmpty() should be used to test for emptiness (java:S1155)
Local variables should not shadow class fields (java:S1117)
Unused assignments should be removed (java:S1854)
> Sonar issues

- core/src/main/java/org/apache/hop/core/Condition.java
Resource	Date	Description
Condition.java	null	Replace the synchronized class "Hashtable" by an unsynchronized one such as "HashMap".
Condition.java	null	Use a StringBuilder instead.
Condition.java	null	Use isEmpty() to check whether the collection is empty or not.
> Sonar Issues - Condition.java

- engine/src/main/java/org/apache/hop/history/AuditEvent.java
- engine/src/main/java/org/apache/hop/history/AuditList.java
- engine/src/main/java/org/apache/hop/history/AuditManager.java
- engine/src/main/java/org/apache/hop/history/AuditState.java
- engine/src/main/java/org/apache/hop/history/AuditStateMap.java
- engine/src/main/java/org/apache/hop/history/IAuditManager.java
- engine/src/main/java/org/apache/hop/history/local/LocalAuditManager.java
Commands used to create this PR
```
git checkout spotless # to get the pom.xml from another PR
git rebase master
git diff master..spotless  > spotless.diff
git checkout -b prepwork_with_formatting
git apply spotless.diff
cd engine
mvn spotless:apply -DspotlessFiles=.*/history/.*.java #For some reason this line expects Java 11. I thought its OK for now and used Java11.
git status
git add *.java
git commit -m 'Just formatting using spotless and google-java-format'
git push mookkiah prepwork_with_formatting
```
> Just formatting using spotless and google-java-format

- engine/src/main/java/org/apache/hop/history/AuditEvent.java
- engine/src/main/java/org/apache/hop/history/AuditList.java
- engine/src/main/java/org/apache/hop/history/AuditManager.java
- engine/src/main/java/org/apache/hop/history/AuditState.java
- engine/src/main/java/org/apache/hop/history/AuditStateMap.java
- engine/src/main/java/org/apache/hop/history/IAuditManager.java
- engine/src/main/java/org/apache/hop/history/local/LocalAuditManager.java
- engine/src/test/java/org/apache/hop/history/AuditManagerTest.java
This PR contains formatted code using spotless with google-java-format.
For actual changes see [here](https://github.com/mookkiah/hop/compare/prepwork_with_formatting...mookkiah:unit_test_for_history?expand=1) or review after accepting PR #294 
Here the steps performed for making this contribution.
```
git checkout -b unit_test_for_history prepwork_with_formatting # from #PR 294
#code
mvn spotless:apply -DspotlessFiles=.*/history/.*.java
git add *.java
git commit -m 'Unit test for AuditManager'
git push --set-upstream mookkiah unit_test_for_history
```
> Unit test for history

- engine/src/main/java/org/apache/hop/history/AuditManager.java
- engine/src/main/java/org/apache/hop/history/IAuditManager.java
- engine/src/main/java/org/apache/hop/history/local/LocalAuditManager.java
- engine/src/test/java/org/apache/hop/history/AuditManagerTest.java
More unit tests.
Added clearEvents method to support unit test requirement - prepare, test and then cleanup.
> More JUnit test cases and clearEvents method

- plugins/transforms/metainject/src/main/metainject.adoc
Documentation for:
- metainject
> HOP-2110: add documentation for MetaInject transform

- plugins/transforms/streamschemamerge/src/main/doc/streamschemamerge.adoc
Documentation for:
- streamschemamerge
> HOP-2111: add documentation for StreamSchemeMeta transform

- plugins/transforms/concatfields/src/main/concatfields.adoc
Documentation for:
- concatfields
> HOP-2112: add documentation for ConcatFields transform

- pom.xml
This PR to demonstrate the spotless maven plugin and get feedback
> Added spotless maven plugin

- plugins/transforms/ldap/README.md
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/ILdapMeta.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapConnection.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInput.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInputData.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInputDialog.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInputField.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInputMeta.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapProtocol.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapProtocolFactory.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapSslProtocol.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapTlsProtocol.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/store/CustomSocketFactory.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/store/HopTrustManager.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/store/TrustAlwaysManager.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapoutput/LdapOutput.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapoutput/LdapOutputData.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapoutput/LdapOutputDialog.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapoutput/LdapOutputMeta.java
- plugins/transforms/ldap/src/test/java/org/apache/hop/pipeline/transforms/ldapinput/LdapConnectionTest.java
- plugins/transforms/ldap/src/test/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInputMetaTest.java
- plugins/transforms/ldap/src/test/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInputTest.java
- plugins/transforms/ldap/src/test/java/org/apache/hop/pipeline/transforms/ldapinput/LdapMockProtocol.java
- plugins/transforms/ldap/src/test/java/org/apache/hop/pipeline/transforms/ldapinput/LdapProtocolFactoryTest.java
- plugins/transforms/ldap/src/test/java/org/apache/hop/pipeline/transforms/ldapoutput/LdapOutputMetaTest.java
- pom.xml
Change for one full module.
This PR has changes from below commands.
```console
$ cd plugins/transforms/ldap/
$ mvn spotless:apply
```
Let us take time to review before accepting this PR.
> Spotless applied only on ldap transformation plugin

- pom.xml
As per [conversation](https://chat.project-hop.org/hop/pl/xs5tqzmdd3ndue8zoxspx8dgxh)
> Unwanted project.version removed

- core/src/main/java/org/apache/hop/core/plugins/BasePluginType.java
- engine/src/main/java/org/apache/hop/pipeline/transform/RowDistributionPluginType.java
Child class fields should not shadow parent class fields
Constructors of an "abstract" class should not be declared "public"
Collapsible "if" statements should be merged
Local variables should not shadow class fields
SonarCloud links for review
- [BasePluginType.java](https://sonarcloud.io/code?id=hop&selected=hop%3Acore%2Fsrc%2Fmain%2Fjava%2Forg%2Fapache%2Fhop%2Fcore%2Fplugins%2FBasePluginType.java)
- [RowDistributionPluginType.java](https://sonarcloud.io/code?id=hop&selected=hop%3Aengine%2Fsrc%2Fmain%2Fjava%2Forg%2Fapache%2Fhop%2Fpipeline%2Ftransform%2FRowDistributionPluginType.java)
> SonarQube issues - Refactored as per sonar recommendation.

- plugins/transforms/randomvalue/src/main/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValue.java
- plugins/transforms/randomvalue/src/main/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValueData.java
- plugins/transforms/randomvalue/src/main/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValueDialog.java
- plugins/transforms/randomvalue/src/main/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValueMeta.java
- plugins/transforms/randomvalue/src/main/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValueMetaFunction.java
- plugins/transforms/randomvalue/src/test/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValueMetaTest.java
No code change.
Cleaning up the format before other changes.
> spotless applied - no code change

- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/context/HopGuiWorkflowContext.java
- ui/src/main/java/org/apache/hop/ui/hopgui/search/HopGuiSearchLocation.java
- ui/src/main/java/org/apache/hop/ui/hopgui/search/HopGuiSearchLocationIterator.java
Rename method Job to Workflow
Rename class HopGUiSearchLocationIterator > HopGuiSearchLocationIterator
> Simple rename method and class

- plugins/transforms/randomvalue/src/main/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValue.java
- plugins/transforms/randomvalue/src/main/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValueData.java
- plugins/transforms/randomvalue/src/main/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValueDialog.java
- plugins/transforms/randomvalue/src/main/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValueMeta.java
This PR only removes some code smells which are safe and needs less testing. For other issue, we need to either cover unit test of create pipeline to do integration test.
For code review refer [sonarcloud](https://sonarcloud.io/code?id=hop&selected=hop%3Aplugins%2Ftransforms%2Frandomvalue%2Fsrc%2Fmain%2Fjava%2Forg%2Fapache%2Fhop%2Fpipeline%2Ftransforms%2Frandomvalue)
Signed-off-by: Mahendran Mookkiah <mahendran.mookkiah@gmail.com>
> Sonar issues from randomvalue transformation resolved

- core/src/main/java/org/apache/hop/core/gui/plugin/toolbar/GuiToolbarElement.java
- core/src/main/java/org/apache/hop/core/gui/plugin/toolbar/GuiToolbarElementType.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/gui/TestingGuiPlugin.java
- ui/src/main/java/org/apache/hop/ui/core/gui/GuiToolbarWidgets.java
Nice on Windows, test on other OS
> HOP-1740 Use CLabel to align text vertically in toolbar

- plugins/transforms/excelinput/src/main/java/org/apache/hop/pipeline/transforms/excelinput/WorkbookFactory.java
- plugins/transforms/excelinput/src/main/java/org/apache/hop/pipeline/transforms/excelinput/staxpoi/StaxPoiSheet.java
- plugins/transforms/excelinput/src/main/java/org/apache/hop/pipeline/transforms/excelinput/staxpoi/StaxPoiWorkbook.java
- plugins/transforms/excelinput/src/main/java/org/apache/hop/pipeline/transforms/excelinput/staxpoi/StaxUtil.java
- plugins/transforms/excelinput/src/test/java/org/apache/hop/pipeline/transforms/excelinput/staxpoi/StaxPoiSheetTest.java
- plugins/transforms/replacestring/src/main/java/org/apache/hop/pipeline/transforms/replacestring/ReplaceString.java
- plugins/transforms/replacestring/src/main/java/org/apache/hop/pipeline/transforms/replacestring/ReplaceStringDialog.java
- plugins/transforms/replacestring/src/main/java/org/apache/hop/pipeline/transforms/replacestring/ReplaceStringMeta.java
- plugins/transforms/replacestring/src/test/java/org/apache/hop/pipeline/transforms/replacestring/ReplaceStringTest.java
- plugins/transforms/sort/src/main/java/org/apache/hop/pipeline/transforms/sort/SortRows.java
- plugins/transforms/sort/src/main/java/org/apache/hop/pipeline/transforms/sort/SortRowsData.java
- plugins/transforms/sort/src/main/java/org/apache/hop/pipeline/transforms/sort/SortRowsMeta.java
Sonar issues in excelinput, replacestring, sort transformation fixed.
> SonarQube issues fix

- engine/src/main/java/org/apache/hop/history/local/LocalAuditManager.java
- engine/src/test/java/org/apache/hop/history/AuditManagerTest.java
Bug fix for HOP-2146
Signed-off-by: Mahendran Mookkiah <mahendran.mookkiah@gmail.com>
> HOP-2146 Using JUnit Rule TemporaryFolder to avoid file system dependency

- plugins/misc/git/src/main/java/org/apache/hop/git/HopGitPerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopPipelineFileType.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopWorkflowFileType.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/EmptyHopPerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/IHopPerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopDataOrchestrationPerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/pluginexplorer/HopPluginExplorePerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/search/HopSearchPerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/search/HopGuiPipelineSearchable.java
- ui/src/main/java/org/apache/hop/ui/hopgui/search/HopGuiWorkflowSearchable.java
- IPerspective return Control not Composite 
- HopDataOrchestrationPerspective.addWorkflow don't need Composite param
- HopDataOrchestrationPerspective.addPipeline don't need Composite param
> HOP-3129 IPerspective return Control not Composite

- plugins/transforms/fieldschangesequence/src/main/java/org/apache/hop/pipeline/transforms/fieldschangesequence/FieldsChangeSequenceDialog.java
- plugins/transforms/stringoperations/src/main/java/org/apache/hop/pipeline/transforms/stringoperations/StringOperationsDialog.java
This PR is for single-sourcing between SWT and RAP/RWT.
Display.getDefault() cannot be used in non-UI thread with RAP/RWT.
See https://www.eclipse.org/forums/index.php/t/805303/
> HOP-13 Display.getDefault() cannot be used in non-UI thread with RAP/RWT

- ui/src/main/java/org/apache/hop/ui/util/EnvironmentUtils.java
- ui/src/test/java/org/apache/hop/ui/util/EnvironmentUtilsTest.java
This PR adds an utility function that tells if the client is Hop Web or Hop Gui.
> Add isWeb() to tell if the client is Hop Web

- core/src/main/java/org/apache/hop/core/extension/HopExtensionPoint.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java
Please feel free to fix my english
> HOP-2242 Add ExtensionPoint after project is enabled

- plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java
- ui/src/main/java/org/apache/hop/ui/core/bus/HopGuiEvent.java
- ui/src/main/java/org/apache/hop/ui/core/bus/HopGuiEvents.java
- ui/src/main/java/org/apache/hop/ui/core/bus/HopGuiEventsHandler.java
- ui/src/main/java/org/apache/hop/ui/core/bus/IHopGuiEventListener.java
- ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataManager.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
- ui/src/main/java/org/apache/hop/ui/hopgui/dialog/MetadataExplorerDialog.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java
- ui/src/test/java/org/apache/hop/ui/core/bus/HopGuiEventsHandlerTest.java
First version of an events handler for the Hop GUI.
It's a simple listener system with which you can be informed of changes elsewhere in the code.
This PR contains the unit tests for the functionality of the handler as well as a first use-case for the new metadata perspective.
> HOP-2256 : Create a GUI events handler

- ui/src/main/java/org/apache/hop/ui/core/database/DatabaseMetaEditor.java
- ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditor.java
- ui/src/main/java/org/apache/hop/ui/pipeline/config/PipelineRunConfigurationEditor.java
Just a first little bit of code cleanup
> HOP-2260 : Metadata perspective: code cleanup

- .gitignore
- Dockerfile.unit-tests
- Jenkinsfile
- Jenkinsfile.daily
- integration-tests/scripts/run-tests.sh
> HOP-2122: add integration tests to Hop

- README.md
> HOP-2270 - Readme update with badges

- integration-tests/scripts/run-tests.sh
> HOP-2122: add CDATA blocks around logs

- integration-tests/scripts/run-tests.sh
> HOP-2122: remove empty line

- integration-tests/scripts/run-tests.sh
> HOP-2122: fix cleanup

- integration-tests/scripts/run-tests.sh
Allow both main_ and main- in workflow names …
> HOP-2122: add a bit more flexibility

- assemblies/plugins/transforms/javascript/src/assembly/assembly.xml
- assemblies/plugins/transforms/javascript/src/main/resources/dependencies.xml
- assemblies/plugins/transforms/mailinput/src/assembly/assembly.xml
- assemblies/plugins/transforms/mailinput/src/main/resources/dependencies.xml
- assemblies/plugins/transforms/syslog/src/assembly/assembly.xml
- assemblies/plugins/transforms/syslog/src/main/resources/dependencies.xml
> HOP-2273 Replace duplicate Hop jar files with dependencies.xml

- engine/src/main/java/org/apache/hop/pipeline/transforms/dummy/DummyMeta.java
- engine/src/main/java/org/apache/hop/workflow/actions/start/ActionStart.java
> HOP-2286 : Images not found for Dummy and Start actions

- assemblies/plugins/engines/beam/pom.xml
- core/pom.xml
- plugins/engines/beam/pom.xml
> HOP-2133 : Update Apache Beam API to 2.26.0

- core/src/main/java/org/apache/hop/core/database/DatabaseMeta.java
- core/src/main/java/org/apache/hop/metadata/api/HopMetadata.java
- core/src/main/java/org/apache/hop/metadata/plugin/MetadataPluginType.java
- engine/src/main/java/org/apache/hop/partition/PartitionSchema.java
- engine/src/main/java/org/apache/hop/pipeline/config/PipelineRunConfiguration.java
- engine/src/main/java/org/apache/hop/server/HopServer.java
- engine/src/main/java/org/apache/hop/workflow/config/WorkflowRunConfiguration.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/metadata/FileDefinition.java
- plugins/misc/git/src/main/java/org/apache/hop/git/model/repository/GitRepository.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/DataSet.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/PipelineUnitTest.java
- ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditor.java
- ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataManager.java
- ui/src/main/java/org/apache/hop/ui/core/widget/MetaSelectionLine.java
- ui/src/main/java/org/apache/hop/ui/hopgui/context/metadata/MetadataContextHandler.java
- ui/src/main/java/org/apache/hop/ui/hopgui/dialog/MetadataExplorerDialog.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java
> HOP-2283 Rename annotation HopMetadata.iconImage > image

- plugins/actions/mail/src/main/java/org/apache/hop/workflow/actions/mail/ActionMail.java
- plugins/actions/mail/src/main/java/org/apache/hop/workflow/actions/mail/ActionMailDialog.java
- plugins/transforms/mail/src/main/java/org/apache/hop/pipeline/transforms/mail/Mail.java
- plugins/transforms/mail/src/main/java/org/apache/hop/pipeline/transforms/mail/MailDialog.java
Added support to TLS 1.2 wherever required in MailAction and MailTransform
> [HOP2306] - Add support for TLS 1.2

- plugins/transforms/rowsfromresult/src/main/resources/org/apache/hop/pipeline/transforms/rowsfromresult/messages/messages_en_US.properties
- ui/src/main/java/org/apache/hop/ui/workflow/dialog/WorkflowDialog.java
HOP-2218 : Copy rows to result should be renamed
HOP-2145 : "Synchronise name with" option doesn't work (Workflow properties)
> Resolved HOP-2218, HOP-2145

- plugins/misc/testing/src/main/java/org/apache/hop/testing/transforms/exectests/ExecuteTestsMeta.java
- plugins/misc/testing/src/main/resources/executetests.svg
Add new icon for transform execution tests in plugin folder
> HOP-2294 Move the plugin image to its folder (new icon for transform execution tests)

- docker/Dockerfile
- docker/README.md
- docker/resources/get-hop.sh
- docker/resources/load-and-execute.sh
- docker/resources/run.sh
> hop-2287 - initial move from hop-docker necessary files

- assemblies/plugins/databases/redshift-assemblies/pom.xml
- assemblies/plugins/databases/redshift-assemblies/src/assembly/assembly.xml
- plugins/databases/redshift/pom.xml
HOP-2346 : Removed mulesoft redshift jdbc dependency.
> [HOP-2346]

- pom.xml
> HOP-2350: show failed files in maven output

- ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataManager.java
- ui/src/main/java/org/apache/hop/ui/hopgui/context/GuiContextUtil.java
- ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiContextDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
> HOP-2354: Fix GuiContextUtil not to share ContextDialog

- archive-pipeline-transforms/src/main/java/ui/steps/script/ScriptDialog.java
- archive-pipeline-transforms/src/main/java/ui/steps/simplemapping/SimpleMappingDialog.java
- archive-pipeline-transforms/src/main/java/ui/steps/textfileinput/TextFileInputDialog.java
- plugins/transforms/concatfields/src/main/java/org/apache/hop/pipeline/transforms/concatfields/ConcatFieldsDialog.java
- plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassDialog.java
- plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesMetaModDialog.java
- plugins/transforms/kafka/src/main/java/org/apache/hop/pipeline/transforms/kafka/consumer/KafkaConsumerInputDialog.java
- plugins/transforms/kafka/src/main/java/org/apache/hop/pipeline/transforms/kafka/producer/KafkaProducerOutputDialog.java
- plugins/transforms/mapping/src/main/java/org/apache/hop/pipeline/transforms/mapping/SimpleMappingDialog.java
- plugins/transforms/metainject/src/main/java/org/apache/hop/pipeline/transforms/metainject/MetaInjectDialog.java
- plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodbinput/MongoDbInputDialog.java
- plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodboutput/MongoDbOutputDialog.java
- plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/TextFileInputDialog.java
- plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/text/TextFileInputDialog.java
- plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/textfileoutput/TextFileOutputDialog.java
- plugins/transforms/tokenreplacement/src/main/java/org/apache/hop/pipeline/transforms/tokenreplacement/TokenReplacementDialog.java
- ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
- ui/src/main/java/org/apache/hop/ui/core/dialog/EnterOptionsDialog.java
- ui/src/main/java/org/apache/hop/ui/pipeline/config/PipelineRunConfigurationEditor.java
- ui/src/main/java/org/apache/hop/ui/pipeline/dialog/PipelineDialog.java
- ui/src/main/java/org/apache/hop/ui/pipeline/transforms/pipelineexecutor/PipelineExecutorDialog.java
- ui/src/main/java/org/apache/hop/ui/pipeline/transforms/workflowexecutor/WorkflowExecutorDialog.java
> HOP-2366: Do no use CTabFolder.setSimple()

- Jenkinsfile
- Jenkinsfile.daily
> INFRA: switch JDK to see if it resolved build issues

- plugins/transforms/memgroupby/src/main/java/org/apache/hop/pipeline/transforms/memgroupby/MemoryGroupByMeta.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiKeyHandler.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopGuiAbstractGraph.java
HOP-2356 : Fixed incorrect display of result for MemoryGroupBy when COUNT argument is string
> Various fixes and improvements

- Jenkinsfile
- Jenkinsfile.daily
> INFRA: switch back to latest

- plugins/transforms/excelinput/src/test/java/org/apache/hop/pipeline/transforms/excelinput/ExcelInputContentParsingTest.java
> HOP-2358: re-enable XLS test

- ui/src/main/java/org/apache/hop/ui/core/dialog/ShowHelpDialog.java
Browser in RAP does not implement back() and forward() …
> HOP-2369: Wrap here with isWeb() as Browser in RAP does not implement back() and forward()

- ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
> HOP-2368: Wrap here with isWeb() as RAP does not allow painting on Image

- ui/src/main/java/org/apache/hop/ui/core/widget/CheckBoxToolTip.java
> HOP-1491: Initialize message with an empty string otherwise an error happens on Hop Web

- ui/src/main/java/org/apache/hop/ui/core/widget/OsHelper.java
> HOP-2373 HOP-2374

- engine/src/main/java/org/apache/hop/core/file/TextFileInputField.java
https://sonarcloud.io/organizations/apache/issues?open=AXXSUfifHNgm4sakNVBr&projects=apache_incubator-hop&resolved=false&rules=java%3AS3252 …
> sonarqube issue - "static" base class members should not be accessed via derived types

- assemblies/core/lib/pom.xml
- assemblies/debug/pom.xml
- assemblies/lib/pom.xml
- assemblies/static/pom.xml
- plugins/actions/pom.xml
- plugins/databases/pom.xml
- plugins/engines/beam/pom.xml
- plugins/misc/debug/pom.xml
- plugins/misc/git/pom.xml
- plugins/misc/projects/pom.xml
- plugins/misc/testing/pom.xml
- plugins/transforms/kafka/pom.xml
- plugins/transforms/mongodb/pom.xml
- plugins/transforms/pom.xml
- plugins/vfs/pom.xml
- rcp/pom.xml
- ui/pom.xml
Once we have hop-ui-rcp and hop-ui-rap modules, it'd be better to rename hop-ui-swt to hop-ui to avoid a confusion.
hop-ui-swt was formerly known as kettle-ui-swt. The postfix (-swt) was added to differentiate from kettle-ui-swing and kettle-ui-gwt.
Since Hop only support SWT, we can safely rename hop-ui-swt to hop-ui.
Trivial changes …
> HOP-2371: Rename hop-ui-swt to hop-ui

- plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassDialog.java
- plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesMetaModDialog.java
- rcp/src/main/java/org/apache/hop/ui/hopgui/TextSizeUtilFacadeImpl.java
- ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
- ui/src/main/java/org/apache/hop/ui/core/gui/GuiToolbarWidgets.java
- ui/src/main/java/org/apache/hop/ui/core/widget/TableDraw.java
- ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
- ui/src/main/java/org/apache/hop/ui/hopgui/TextSizeUtilFacade.java
> HOP-2379: Use TextSizeUtilFacade.textExtent instead of dummyGC.textExtent

- ui/src/main/java/org/apache/hop/ui/core/gui/BaseGuiWidgets.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
SonarQube issue. - https://sonarcloud.io/project/issues?id=apache_incubator-hop&issues=AXXSUf-VHNgm4sakNV-k&open=AXXSUf-VHNgm4sakNV-k …
> sonarqube issue - static members should be accessed statically

- ui/src/main/java/org/apache/hop/ui/core/gui/GuiResource.java
- ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiEnvironment.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiLogBrowser.java
This PR is for single-sourcing.
This PR does not introduce any behavioural change for Hop Gui.
If this is your first contribution, you have to read the …
> HOP-1491: Integrate Hop Web codes

- pom.xml
- rap/pom.xml
- rap/src/main/java/org/apache/hop/ui/core/gui/GuiResourceImpl.java
- rap/src/main/java/org/apache/hop/ui/hopgui/CanvasFacadeImpl.java
- rap/src/main/java/org/apache/hop/ui/hopgui/CanvasListenerImpl.java
- rap/src/main/java/org/apache/hop/ui/hopgui/Clipboard.java
- rap/src/main/java/org/apache/hop/ui/hopgui/ClipboardListener.java
- rap/src/main/java/org/apache/hop/ui/hopgui/DownloadServiceHandler.java
- rap/src/main/java/org/apache/hop/ui/hopgui/HopGuiImpl.java
- rap/src/main/java/org/apache/hop/ui/hopgui/HopWeb.java
- rap/src/main/java/org/apache/hop/ui/hopgui/HopWebEntryPoint.java
- rap/src/main/java/org/apache/hop/ui/hopgui/HopWebServletContextListener.java
- rap/src/main/java/org/apache/hop/ui/hopgui/ServerPushSessionFacadeImpl.java
- rap/src/main/java/org/apache/hop/ui/hopgui/TextSizeUtilFacadeImpl.java
- rap/src/main/java/org/apache/hop/ui/hopgui/context/GuiContextUtilImpl.java
- rap/src/main/java/org/eclipse/jface/window/DefaultToolTip.java
- rap/src/main/java/org/eclipse/jface/window/ToolTip.java
- rap/src/main/resources/org/apache/hop/ui/hopgui/canvas.js
- rap/src/main/resources/org/apache/hop/ui/hopgui/clipboard.js
This PR
- Copies `rap/` folder from my web branch
- Modify `./pom.xml` to build the hop-ui-rap module
- Does not touch assemblies just yet …
> HOP-2386: Add RAP fragment to the master branch

- assemblies/client/pom.xml
- assemblies/client/src/assembly/assembly.xml
- assemblies/lib/pom.xml
1. Check that JFace is not included in hop-assemblies-libs (`unzip -t assemblies/lib/target/hop-assemblies-libs-0.60-SNAPSHOT.zip | grep jface`)
2. Unzip `hop-client-0.60-SNAPSHOT.zip` and check that this PR does not change the set of jars at `lib/` folder.
Trivial changes like typos do not require a JIRA issue (javadoc, comments...). …
> HOP-2389: Move RCP's JFace from hop-assemblies-libs to hop-client

- ui/src/main/java/org/apache/hop/ui/core/dialog/ContextDialog.java
RAP's Canvas is not scrollable.
Put the Canvas inside a ScrolledComposite as suggested in https://www.eclipse.org/forums/index.php/t/205006/
If this is your …
> HOP-2357: Wrap Canvas in ScrolledComposite at ContextDialog

- ui/src/main/java/org/apache/hop/ui/core/widget/ConditionEditor.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/shared/SwtGc.java
- ui/src/main/java/org/apache/hop/ui/util/SwtSvgImageUtil.java
> HOP-1491: Fill the gap for single-sourcing

- plugins/transforms/abort/src/main/java/org/apache/hop/pipeline/transforms/abort/AbortMeta.java
> HOP-2397: change abort default to stop with error

- ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/IHopFileType.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopPipelineFileType.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopWorkflowFileType.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopDataOrchestrationPerspective.java
- Add CAPABILITY_EXPORT_TO_SVG for pipeline and workflow
- Add keyboard Ctrl+Shift+W to "File > Close all" menu
- Disabled "File > Close all" menu when no file is active
- Refresh file type capabilities when DataOrch perspective is activated
In this case, …
> HOP-2352 Fixed issues in the file menu

- assemblies/client/pom.xml
- assemblies/client/src/assembly/assembly.xml
- assemblies/lib/pom.xml
This PR:
- Exclude Jetty jars from hop-assemblies-libs and include them in hop-client (Hop Web does not require them)
- Exclude geronimo-servlet from both of them as it is redundant if javax.servlet-api exists.
In this case, just format the pull request …
> HOP-2396: Optimize jars

- engine/src/main/java/org/apache/hop/core/gui/AreaOwner.java
- engine/src/main/java/org/apache/hop/pipeline/PipelinePainter.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- Fix display tooltip when transformation failed
- Remove unused AreaType TRANSFORM_ERROR_ICON replaced by TRANSFORM_FAILURE_ICON
> HOP-2419 Fix display tooltip when transformation failed

- plugins/misc/projects/src/main/java/org/apache/hop/projects/environment/LifecycleEnvironmentDialog.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/project/ProjectDialog.java
- Fix show all files
- Fix alignment of widgets
- Add SWT.BORDER to files table
> HOP-2421 "Open file" dialog does not show expected files

- core/src/main/java/org/apache/hop/core/database/DatabaseFactory.java
- integration-tests/parameters_and_variables/0002-pipeline.hpl
- plugins/actions/repeat/src/main/java/org/apache/hop/workflow/actions/repeat/Repeat.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/actions/runtests/RunPipelineTests.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/util/UnitTestUtil.java
- ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditor.java
One line fixes for the test button in the relational database connection dialog/screen and for detecting a create vs update scenario in the metadata manager.
> HOP-2431, HOP-2433

- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiLogBrowser.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineLogDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowLogDelegate.java
> HOP-2349: Replace the use of StyledText with Text at HopGuiLogBrowser

- Jenkinsfile
- docker/README.md
https://www.jenkins.io/doc/pipeline/steps/pipeline-utility-steps/#readmavenpom-read-a-maven-project-file
Sample Run and Output : https://ci-builds.apache.org/job/Hop/job/Hop/job/master/180/consoleFull#:~:text=mvn%20help:evaluate,SNAPSHOT
```
[Pipeline] sh
+ mvn help:evaluate -Dexpression=project.version -q -DforceStdout
[Pipeline] }
[Pipeline] // script
[Pipeline] echo
The version fo the pom is: 0.60-SNAPSHOT
[Pipeline] }
```
is to …
> getting pom version as per Jenkins Pipleline docs recommendation

- assemblies/plugins/transforms/json/src/assembly/assembly.xml
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsoninput/JsonInputDialog.java
- ui/src/main/java/org/apache/hop/ui/core/dialog/MessageDialogWithToggle.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
HOP-2437 : JSON Input: Select Fields button doesn't do anything
Since this functionality was missing I implemented an optimistic streaming JSON parser which populates all possible paths in the fields list.
Please note that jackson-core was removed as a library since it's already present in the /lib folder of Hop. 
HOP-2418 : Split hop does not work :  single line fix 
HOP-2441 : Variables not applied when set in the Run Options dialog (Pipeline Execution Configuration Dialog)
> HOP-2437, HOP-2418, HOP-2441

- Jenkinsfile
> Disable deploy for non master branch

- ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
- ui/src/main/java/org/apache/hop/ui/core/dialog/EnterOptionsDialog.java
- ui/src/main/java/org/apache/hop/ui/core/vfs/HopVfsFileDialog.java
- ui/src/main/resources/org/apache/hop/ui/core/dialog/messages/messages_en_US.properties
Simple straightforward usability tweak.
> HOP-2444 : Implement global bookmarks for the file dialogs

- ui/src/main/java/org/apache/hop/ui/core/gui/GuiResource.java
> HOP-2376: change icon size for macos

- plugins/transforms/json/src/main/doc/enhancedjsonoutput.adoc
- plugins/transforms/json/src/main/resources/org/apache/hop/pipeline/transforms/jsonoutputenhanced/messages/messages_en_US.properties
HOP-2384 : Added documentation for Enhanced JSON Output
> HOP-2384 + Other

- plugins/misc/import/src/main/java/org/apache/hop/imports/HopImport.java
https://sonarcloud.io/organizations/apache/issues?open=AXcLIqGtQSlARQbF4J1I&projects=apache_incubator-hop&resolved=false&rules=java%3AS2209 …
> sonarqube issue - Change this instance-reference to a static reference

- ui/src/main/java/org/apache/hop/ui/core/dialog/ContextDialog.java
This fixes the issue on Windows but also hardens the case of resizing the window itself.
> HOP-2403 : Context dialog has problems when using the scrollbar

- ui/src/main/java/org/apache/hop/ui/core/widget/MetaSelectionLine.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
- ui/src/main/java/org/apache/hop/ui/hopgui/context/metadata/MetadataContextHandler.java
- ui/src/main/resources/org/apache/hop/ui/hopgui/context/metadata/messages/messages_en_US.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/messages/messages_en_US.properties
> Hop-2449 Add tool to clear database cache

- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleImport.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopImportMigratedFiles.java
> HOP-2452 escaped backslashes in windows paths

- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsoninput/JsonInputDialog.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutput/JsonOutputDialog.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutputDialog.java
HOP-2459 : JSON Output still uses file system dialog
HOP-2448 : Enhanced JSON Output still uses file system dialog
HOP-2442 : JSON Input still uses file system dialog
> Various fixes and changes

- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/getxmldata/GetXmlDataDialog.java
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/xmlinputstream/XmlInputStreamDialog.java
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/xmloutput/XmlOutputDialog.java
HOP-2461 : XML Input Stream still uses file system dialog
HOP-2462 : Get Data from XML still uses file system dialog
HOP-2460 : XML Output still uses file system dialog
> Various fixes and enhancements

- core/src/main/java/org/apache/hop/core/database/BaseDatabaseMeta.java
- core/src/main/java/org/apache/hop/core/database/GenericDatabaseMeta.java
- core/src/main/java/org/apache/hop/core/gui/plugin/BaseGuiElements.java
- core/src/main/java/org/apache/hop/core/gui/plugin/GuiElements.java
- core/src/main/java/org/apache/hop/core/gui/plugin/GuiWidgetElement.java
- core/src/main/java/org/apache/hop/core/gui/plugin/menu/GuiMenuElement.java
- core/src/main/java/org/apache/hop/core/gui/plugin/menu/GuiMenuItem.java
- core/src/main/java/org/apache/hop/core/gui/plugin/toolbar/GuiToolbarElement.java
- core/src/main/java/org/apache/hop/core/gui/plugin/toolbar/GuiToolbarItem.java
- core/src/main/java/org/apache/hop/core/plugins/BaseFragmentType.java
- core/src/main/java/org/apache/hop/core/plugins/BasePluginType.java
- engine/src/main/java/org/apache/hop/pipeline/engines/local/LocalPipelineRunConfiguration.java
- engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineRunConfiguration.java
- engine/src/main/java/org/apache/hop/workflow/engines/local/LocalWorkflowRunConfiguration.java
- engine/src/main/java/org/apache/hop/workflow/engines/remote/RemoteWorkflowRunConfiguration.java
- plugins/databases/informix/src/main/java/org/apache/hop/databases/informix/InformixDatabaseMeta.java
- plugins/databases/mssql/src/main/java/org/apache/hop/databases/mssql/MsSqlServerDatabaseMeta.java
- plugins/databases/mssqlnative/src/main/java/org/apache/hop/databases/mssqlnative/MsSqlServerNativeDatabaseMeta.java
- plugins/databases/mysql/src/main/java/org/apache/hop/databases/mysql/MySqlDatabaseMeta.java
- plugins/databases/snowflake/src/main/java/org/apache/hop/databases/snowflake/SnowflakeDatabaseMeta.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineGridDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineLogDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowLogDelegate.java
- ui/src/main/java/org/apache/hop/ui/i18n/BundlesStore.java
- ui/src/main/java/org/apache/hop/ui/i18n/editor/Translator.java
- ui/src/main/resources/org/apache/hop/ui/hopgui/messages/messages_fr_FR.properties
> HOP-2456, HOP-2483

- core/src/main/java/org/apache/hop/core/database/SqlScriptParser.java
https://sonarcloud.io/organizations/apache/issues?languages=java&open=AXXSUeEXHNgm4sakNRo7&projects=apache_incubator-hop&resolved=false&rules=java%3AS127
If this …
> sonarqube issue -Refactor the code in order to not assign to this loop counter from within the loop body.

- core/pom.xml
- core/src/main/java/org/apache/hop/core/hash/ByteArrayHashMap.java
- core/src/main/java/org/apache/hop/core/util/DateDetector.java
- core/src/test/java/org/apache/hop/core/util/DateDetectorTest.java
- engine/pom.xml
- engine/src/main/java/org/apache/hop/core/ConcurrentMapProperties.java
- engine/src/main/java/org/apache/hop/core/util/AddClosureArrayList.java
- engine/src/main/java/org/apache/hop/core/util/Assert.java
- engine/src/main/java/org/apache/hop/core/util/CollectionPredicates.java
- engine/src/main/java/org/apache/hop/core/util/KeyValueSet.java
- engine/src/main/java/org/apache/hop/core/util/PluginPropertyHandler.java
- engine/src/test/java/org/apache/hop/concurrency/WorkflowMapConcurrencyTest.java
- engine/src/test/java/org/apache/hop/concurrency/WorkflowTrackerConcurrencyTest.java
- plugins/transforms/datagrid/src/main/java/org/apache/hop/pipeline/transforms/datagrid/DataGridDialog.java
- plugins/transforms/mailinput/src/main/java/org/apache/hop/pipeline/transforms/mailinput/MailInput.java
- plugins/transforms/sort/src/main/java/org/apache/hop/pipeline/transforms/sort/SortRows.java
- ui/pom.xml
Bump commons-collections version 3.2.2 to commons-collections4version 4.4
> HOP-2489 Bump commons-collections to commons-collections4

- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
https://sonarcloud.io/organizations/apache/issues?languages=java&open=AXcLIqGMQSlARQbF4J0M&projects=apache_incubator-hop&resolved=false&rules=java%3AS3878
If …
> sonarqube issue - Remove this array creation and simply pass the elements.

- core/src/main/java/org/apache/hop/core/logging/Slf4jLoggingEventListener.java
https://sonarcloud.io/project/issues?id=hop&languages=java&open=AW6ThKTMMj3rolYBEQdv&resolved=false&rules=java%3AS1611
If this is your first contribution, you …
> sonarqube issue - Remove the parentheses around the "objId" parameter

- core/src/main/java/org/apache/hop/core/Result.java
- engine/src/main/java/org/apache/hop/core/injection/bean/BeanLevelInfo.java
- engine/src/main/java/org/apache/hop/pipeline/Pipeline.java
- engine/src/main/java/org/apache/hop/pipeline/PipelineProfileFactory.java
- engine/src/main/java/org/apache/hop/pipeline/transforms/groupby/Aggregation.java
- engine/src/main/java/org/apache/hop/pipeline/transforms/groupby/GroupBy.java
- engine/src/main/java/org/apache/hop/pipeline/transforms/groupby/GroupByMeta.java
- engine/src/main/java/org/apache/hop/run/HopRun.java
- engine/src/main/java/org/apache/hop/server/HopServer.java
- engine/src/main/java/org/apache/hop/workflow/Workflow.java
- engine/src/main/java/org/apache/hop/www/HopServerSingleton.java
- engine/src/main/resources/org/apache/hop/pipeline/transforms/groupby/messages/messages_en_US.properties
- plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopRunCalculateFilenameExtensionPoint.java
- plugins/transforms/metainject/src/main/java/org/apache/hop/pipeline/transforms/metainject/MetaInject.java
- plugins/transforms/tableoutput/src/main/java/org/apache/hop/pipeline/transforms/tableoutput/TableOutput.java
- plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/csvinput/messages/messages_en_US.properties
- ui/src/main/java/org/apache/hop/ui/core/widget/ComboVar.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
- ui/src/main/java/org/apache/hop/ui/pipeline/transforms/groupby/GroupByDialog.java
HOP-2504 : Metadata Injection: Logging levels are not propagating …
HOP-2505 : Group By : add support for metadata injection
> HOP-2504, HOP-2505

- core/src/main/java/org/apache/hop/core/row/IValueMetaConverter.java
- core/src/main/java/org/apache/hop/core/row/value/ValueMetaConverter.java
A problem occurred during the last PR
> HOP-2477 Move interface IValueMetaConverter

- ui/src/main/java/org/apache/hop/ui/core/dialog/ShowHelpDialog.java
- ui/src/main/resources/ui/laf.properties
- Fix toolbar layout with unique toolbar
- Fix documentationUrl for Home button
- Ordered tool items like VfsFileDialog
- Simplify listeners
> HOP-2507 Fix ShowHelpDialog layout + documentationUrl

- plugins/transforms/pom.xml
> HOP-2508: add coalesce to pom

- plugins/transforms/coalesce/src/main/java/org/apache/hop/pipeline/transforms/coalesce/Coalesce.java
- plugins/transforms/coalesce/src/main/java/org/apache/hop/pipeline/transforms/coalesce/CoalesceMeta.java
- plugins/transforms/coalesce/src/main/java/org/apache/hop/pipeline/transforms/coalesce/CoalesceTransform.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutputMeta.java
- plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodbinput/MongoDbInputMeta.java
- plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodboutput/MongoDbOutputMeta.java
> Hop-2508 Fix some smell codes

- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
> HOP-2514, HOP-2515 - Kettle import element type fixes

- plugins/transforms/combinationlookup/src/main/doc/combinationlookup.adoc
> HOP-2516 replaced reference to Project Hop

- engine/src/main/java/org/apache/hop/config/HopConfig.java
https://sonarcloud.io/organizations/apache/issues?languages=java&open=AXXSUfyBHNgm4sakNVkC&projects=apache_incubator-hop&resolved=false&rules=java%3AS1450
If …
> Private fields only used as local variables in methods should become local variables

- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleImport.java
> HOP-2520 remove connection elements from workflow root

- engine/src/main/java/org/apache/hop/run/HopRun.java
- ui/src/main/java/org/apache/hop/ui/core/widget/ComboVar.java
- ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
HOP-2532 : Hop Run: variables in environment or project are not applied
HOP-2533 : Workflow Executor: NPE in dialog
> HOP-2532, HOP-2533

- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsoninput/JsonInputDialog.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
HOP-2538 : Add "View output" as a context action option
HOP-2539 : JSON Input dialog: get fields shows white text on white background
> HOP-2538, HOP-2539

- core/src/main/java/org/apache/hop/core/BlockingBatchingRowSet.java
https://sonarcloud.io/organizations/apache/issues?languages=java&open=AXXSUeH7HNgm4sakNRzy&projects=apache_incubator-hop&resolved=false&rules=java%3AS1659
If …
> Multiple variables should not be declared on the same line

- ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
> HOP-2542: Display.isSystemDarkTheme is not available in RAP

- ui/src/main/java/org/apache/hop/ui/pipeline/transforms/groupby/GroupByDialog.java
> HOP-2549 updated incorrect column index in agg table

- docker/Dockerfile.web
- docker/create_hop_web_container.sh
- ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
> HOP-2529, HOP-2562

- assemblies/static/src/main/resources/static/images/cleanup.svg
- assemblies/static/src/main/resources/static/images/close.svg
- assemblies/static/src/main/resources/static/images/view.svg
- docker/Dockerfile
- docker/resources/load-and-execute.sh
- engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineEngine.java
- engine/src/main/java/org/apache/hop/www/PrepareExecutionPipelineServlet.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/BeamPipelineEngine.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/gui/HopBeamGuiPlugin.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/run/MainBeam.java
HOP-2557 : Spark runner : not finishing application
HOP-2558 : Remote pipeline engine: improve logging
HOP-2559 : Hop Server: broken icons in web interface
HOP-2561 : Docker container: Make port configurable
HOP-2565 : Beam: add a main class for executing using Spark Submit 
HOP-2566 : Docker: libraries like snappy need libc-compat
> Docker & Spark improvements

- plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java
- plugins/misc/projects/src/main/resources/export.svg
- plugins/misc/projects/src/main/resources/org/apache/hop/projects/gui/messages/messages_en_US.properties
> HOP-2204 export current project to zip, initial version

- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/pipeline/meta/PipelineLogEditor.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/gui/DataProbeGuiPlugin.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/meta/DataProbeLocation.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/meta/PipelineProbe.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/meta/PipelineProbeEditor.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/transform/PipelineDataProbe.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/transform/PipelineDataProbeData.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/transform/PipelineDataProbeDialog.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/transform/PipelineDataProbeMeta.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/xp/PipelineDataProbeXp.java
- plugins/misc/reflection/src/main/resources/org/apache/hop/reflection/pipeline/meta/messages/messages_en_US.properties
- plugins/misc/reflection/src/main/resources/org/apache/hop/reflection/probe/meta/messages/messages_en_US.properties
- plugins/misc/reflection/src/main/resources/org/apache/hop/reflection/probe/transform/messages/messages_en_US.properties
- ui/src/main/java/org/apache/hop/ui/core/metadata/IMetadataEditor.java
- ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditor.java
- ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
HOP-2569 : Bring back space while mousing over transform
HOP-2570 : Allow a metadata editor to be set to changed or not from outside the editor
HOP-2571 : Expose getter/setter for metadata in IMetadataEditor
HOP-2572 : TableView: when a row is inserted the view is not flagged as modified
HOP-2567 : Allow output rows from any transform to be streamed to another pipeline
> HOP-2567, HOP-2569, HOP-2570, HOP-2571, HOP-2572

- plugins/misc/reflection/src/main/resources/org/apache/hop/reflection/pipeline/transform/messages/messages_en_US.properties
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiKeyHandler.java
HOP-2574 : Keyboard shortcuts are not handled correctly
HOP-2567 : reflection plugin i18n fix
> Couple of tweaks

- core/src/main/java/org/apache/hop/core/ProgressNullMonitorListener.java
https://sonarcloud.io/organizations/apache/issues?languages=java&open=AXXSUeHQHNgm4sakNRxZ&projects=apache_incubator-hop&resolved=false&rules=java%3AS1186
If …
> Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation.

- docker/Dockerfile.web
- ui/src/main/java/org/apache/hop/ui/core/vfs/HopVfsFileDialog.java
> HOP-2564: Resolve filterPath to resolve ${HOP_CONFIG_FOLDER}

- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/workflow/transform/WorkflowLogging.java
> HOP-2585 : Workflow Logging transform output row misses fields

- assemblies/static/src/main/resources/THIRD-PARTY.txt
> HOP-2605: Add new 3rd Party dependencies

- integration-tests/neo4j/tests/neo4j-cypher-returns/main-neo4j-cypher-returns.hwf
Remove ping test to help this run in the IT docker container
> HOP-2606 : Port Neo4j integration tests (fix)

- plugins/misc/neo4j/src/main/doc/neo4j-connection.adoc
- plugins/misc/neo4j/src/main/doc/neo4j-graphmodel.adoc
- plugins/misc/neo4j/src/main/doc/neo4j-info.adoc
> HOP-2605 : Include the Neo4j plugins (small doc fixes)

- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
- plugins/transforms/googleanalytics/src/main/java/org/apache/hop/pipeline/transforms/googleanalytics/GoogleAnalyticsMeta.java
> HOP-2621, HOP-2622: small fixes in Google Analytics and importer

- assemblies/plugins/dist/pom.xml
- assemblies/plugins/transforms/googlesheets/pom.xml
- assemblies/plugins/transforms/googlesheets/src/assembly/assembly.xml
- assemblies/plugins/transforms/googlesheets/src/main/resources/version.xml
- assemblies/plugins/transforms/pom.xml
- plugins/transforms/googlesheet/pom.xml
- plugins/transforms/googlesheet/src/main/doc/google-sheets-input.adoc
- plugins/transforms/googlesheet/src/main/doc/google-sheets-output.adoc
- plugins/transforms/googlesheet/src/main/java/org/apache/hop/pipeline/transforms/googlesheet/GoogleSheetsPluginCredentials.java
- plugins/transforms/googlesheet/src/main/java/org/apache/hop/pipeline/transforms/googlesheet/GoogleSheetsPluginInput.java
- plugins/transforms/googlesheet/src/main/java/org/apache/hop/pipeline/transforms/googlesheet/GoogleSheetsPluginInputData.java
- plugins/transforms/googlesheet/src/main/java/org/apache/hop/pipeline/transforms/googlesheet/GoogleSheetsPluginInputDialog.java
- plugins/transforms/googlesheet/src/main/java/org/apache/hop/pipeline/transforms/googlesheet/GoogleSheetsPluginInputFields.java
- plugins/transforms/googlesheet/src/main/java/org/apache/hop/pipeline/transforms/googlesheet/GoogleSheetsPluginInputMeta.java
- plugins/transforms/googlesheet/src/main/java/org/apache/hop/pipeline/transforms/googlesheet/GoogleSheetsPluginOutput.java
- plugins/transforms/googlesheet/src/main/java/org/apache/hop/pipeline/transforms/googlesheet/GoogleSheetsPluginOutputData.java
- plugins/transforms/googlesheet/src/main/java/org/apache/hop/pipeline/transforms/googlesheet/GoogleSheetsPluginOutputDialog.java
- plugins/transforms/googlesheet/src/main/java/org/apache/hop/pipeline/transforms/googlesheet/GoogleSheetsPluginOutputMeta.java
- plugins/transforms/googlesheet/src/main/resources/GoogleSheetsPluginInput.svg
- plugins/transforms/googlesheet/src/main/resources/GoogleSheetsPluginOutput.svg
- plugins/transforms/googlesheet/src/main/resources/org/apache/hop/pipeline/transforms/googlesheet/messages/messages_en_FR.properties
- plugins/transforms/googlesheet/src/main/resources/org/apache/hop/pipeline/transforms/googlesheet/messages/messages_en_US.properties
- plugins/transforms/pom.xml
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/search/HopSearchPerspective.java
- ui/src/main/java/org/apache/hop/ui/i18n/BundlesStore.java
- ui/src/main/java/org/apache/hop/ui/i18n/MessagesSourceCrawler.java
- ui/src/main/java/org/apache/hop/ui/i18n/editor/Translator.java
HOP-2619 : Translator doesn't save files in the right location
HOP-2620 : Search to allow for multi-selection
HOP-1964 : Add Google Sheets Input and Output transforms
> HOP-1964, HOP-2619, HOP-2620

- ui/src/test/java/org/apache/hop/ui/i18n/MessagesSourceCrawlerTest.java
> HOP-2619: fix translator test

- NOTICE
- assemblies/plugins/tech/google/pom.xml
- assemblies/plugins/tech/google/src/assembly/assembly.xml
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/probe/xp/PipelineDataProbeXp.java
- plugins/tech/google/pom.xml
- plugins/tech/google/src/main/doc/google-info.adoc
- plugins/tech/google/src/main/java/org/apache/hop/vfs/googledrive/config/GoogleDriveConfig.java
- plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageFileName.java
- plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageFileObject.java
- plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageFileProvider.java
- plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageFileSystem.java
- plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageFileSystemConfigBuilder.java
- plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/GoogleStorageVfsPlugin.java
- plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/ReadChannelInputStream.java
- plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/WriteChannelOutputStream.java
- plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/config/GoogleCloudConfig.java
- plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/config/GoogleCloudConfigPlugin.java
- plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/config/GoogleCloudConfigSingleton.java
HOP-2628 : Implement a Google Storage VFS driver
HOP-2629 : NPE when previewing a transform in a new unsaved pipeline
> HOP-2628 and HOP-2629

- assemblies/plugins/transforms/mqtt/pom.xml
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutputMeta.java
- plugins/transforms/mqtt/pom.xml
- plugins/transforms/mqtt/src/main/java/org/apache/hop/pipeline/transforms/mqtt/publisher/MQTTPublisher.java
- plugins/transforms/mqtt/src/main/java/org/apache/hop/pipeline/transforms/mqtt/publisher/MQTTPublisherDialog.java
- plugins/transforms/mqtt/src/main/java/org/apache/hop/pipeline/transforms/mqtt/publisher/MQTTPublisherMeta.java
- plugins/transforms/mqtt/src/main/java/org/apache/hop/pipeline/transforms/mqtt/subscriber/MQTTSubscriber.java
- plugins/transforms/mqtt/src/main/java/org/apache/hop/pipeline/transforms/mqtt/subscriber/MQTTSubscriberMeta.java
- plugins/transforms/mqtt/src/main/resources/org/apache/hop/pipeline/transforms/mqtt/subscriber/messages/messages_en_US.properties
HOP-2599 - Updated PAHO libraries to version 1.2.5 in MQTT Transform
HOP-2614 - MQTT transform does not save content of form
HOP 2615 - MQTT Incoming field not working
Minor fix to Enhanced JSON Output transform to update i18n to new approach
> Various fixes to MQTT transform

- assemblies/plugins/dist/pom.xml
- assemblies/plugins/transforms/pom.xml
- assemblies/plugins/transforms/splunk/pom.xml
- assemblies/plugins/transforms/splunk/src/assembly/assembly.xml
- assemblies/plugins/transforms/splunk/src/main/resources/version.xml
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/BeamPipelineEngine.java
- plugins/tech/azure/src/main/java/org/apache/hop/vfs/azure/config/AzureConfigPlugin.java
- plugins/transforms/pom.xml
- plugins/transforms/splunk/pom.xml
- plugins/transforms/splunk/src/main/doc/splunkinput.adoc
- plugins/transforms/splunk/src/main/java/org/apache/hop/pipeline/transforms/splunkinput/ReturnValue.java
- plugins/transforms/splunk/src/main/java/org/apache/hop/pipeline/transforms/splunkinput/SplunkInput.java
- plugins/transforms/splunk/src/main/java/org/apache/hop/pipeline/transforms/splunkinput/SplunkInputData.java
- plugins/transforms/splunk/src/main/java/org/apache/hop/pipeline/transforms/splunkinput/SplunkInputDialog.java
- plugins/transforms/splunk/src/main/java/org/apache/hop/pipeline/transforms/splunkinput/SplunkInputMeta.java
- plugins/transforms/splunk/src/main/java/org/apache/hop/splunk/SplunkConnection.java
- plugins/transforms/splunk/src/main/java/org/apache/hop/splunk/SplunkConnectionEditor.java
- plugins/transforms/splunk/src/main/resources/org/apache/hop/pipeline/transforms/splunkinput/messages/messages_en_US.properties
- plugins/transforms/splunk/src/main/resources/org/apache/hop/splunk/messages/messages_en_US.properties
- plugins/transforms/splunk/src/main/resources/splunk.svg
The Splunk Input transform and 2 minor fixes
> HOP-2636, HOP-2638, HOP-2639

- engine/src/main/java/org/apache/hop/workflow/actions/pipeline/pipeline.adoc
- engine/src/main/java/org/apache/hop/workflow/actions/workflow/workflow.adoc
- plugins/actions/simpleeval/src/main/doc/simpleeval.adoc
- plugins/tech/neo4j/src/main/doc/neo4j-cypher.adoc
- plugins/tech/neo4j/src/main/doc/neo4j-cypherscript.adoc
- plugins/transforms/dynamicsqlrow/src/main/doc/dynamicsqlrow.adoc
- plugins/transforms/filterrows/src/main/doc/filterrows.adoc
- plugins/transforms/metainject/src/main/metainject.adoc
- plugins/transforms/replacestring/src/main/doc/replacestring.adoc
- plugins/transforms/sql/src/main/doc/sql.adoc
- plugins/transforms/terafast/src/main/doc/terafast.adoc
> HOP-2641 escaped incorrect asciidoc parameter, variable evaluations

- plugins/misc/projects/src/main/doc/projects.adoc
- plugins/transforms/dropbox/src/main/doc/dropboxinput.adoc
- plugins/transforms/dropbox/src/main/doc/dropboxoutput.adoc
- plugins/transforms/dynamicsqlrow/src/main/doc/dynamicsqlrow.adoc
- plugins/transforms/filterrows/src/main/doc/filterrows.adoc
- plugins/transforms/metainject/src/main/doc/metainject.adoc
- plugins/transforms/sql/src/main/doc/sql.adoc
> HOP-2641 escape variable references, heading updates

- plugins/misc/projects/src/main/doc/projects.adoc
> HOP-2641 added var placeholders

- assemblies/static/src/main/resources/THIRD-PARTY.txt
- docker/integration-tests/docker-compose-ci.yaml
- pom.xml
> HOP-2668,HOP-2674

- assemblies/static/src/main/resources/THIRD-PARTY.txt
> HOP-2674: remove dependencies from list

- ui/src/main/java/org/apache/hop/ui/workflow/dialog/WorkflowDialog.java
> HOP-2701 : Workflows: option to sync name with filename doesn't work

- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleImport.java
- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleImportDialog.java
> HOP-2657, HOP-2658, HOP-2453

- core/src/main/java/org/apache/hop/core/gui/plugin/GuiRegistry.java
- core/src/main/java/org/apache/hop/core/util/TranslateUtil.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/config/ProjectsConfigOptionPlugin.java
- ui/src/main/java/org/apache/hop/ui/core/dialog/EnterOptionsDialog.java
HOP-2666 - Fix hardcoded strings in ProjectsConfigOptionPlugin
Little refactoring to introduce a new class TranslateUtil to support translation in annotation by using the i18n:: tag
> HOP-2666 - Fix hardcoded strings in ProjectsConfigOptionPlugin

- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
This PR allows client-side canvas drawing on Hop Web, and eventually fixes HOP-2715.
I tested on Hop GUI as well to make sure that this PR did not affect it.
If …
> [HOP-2715] Client-side canvas drawing on Hop Web

- assemblies/static/src/main/resources/hop-search.bat
- assemblies/static/src/main/resources/hop-search.sh
- core/src/main/java/org/apache/hop/core/config/plugin/ConfigPlugin.java
- core/src/main/java/org/apache/hop/core/search/ISearchablesLocation.java
- core/src/main/java/org/apache/hop/core/search/SearchableAnalyserPluginType.java
- engine/src/main/java/org/apache/hop/search/HopSearch.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/config/ProjectsOptionPlugin.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/config/ProjectsSearchOptionPlugin.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/search/ProjectSearchablesIterator.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/search/ProjectsSearchablesLocation.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/search/HopSearchPerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/search/HopGuiSearchLocation.java
Pretty straightforward simple utility.
> HOP-2662 : Add CLI search tool

- ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopDataOrchestrationPerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/pluginexplorer/HopPluginExplorePerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/search/HopSearchPerspective.java
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/dataorch/messages/messages_en_US.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/dataorch/messages/messages_it_IT.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/explorer/messages/messages_en_US.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/explorer/messages/messages_it_IT.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/metadata/messages/messages_en_US.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/metadata/messages/messages_it_IT.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/pluginexplorer/messages/messages_en_US.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/pluginexplorer/messages/messages_it_IT.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/search/messages/messages_en_US.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/search/messages/messages_it_IT.properties
HOP-2693 - Fix hardcoded strings in HopPluginExplorerPerspective
HOP-2695 - Fix hardcoded strings in HopSearchPerspective
HOP-2696 - Fix hardcoded strings in ExplorerPerspective
HOP-2697 - Fix hardcoded strings in MetadataPerspective
HOP-2698 - Fix hardcoded strings in HopDataOrchestrationPerspective
> Various fixes removeing hardcoded strings

- assemblies/static/src/main/resources/THIRD-PARTY.txt
> HOP-2547: update 3rd party

- plugins/misc/git/src/main/java/org/apache/hop/git/GitGuiPlugin.java
- plugins/misc/git/src/main/resources/org/apache/hop/git/messages/messages_it_IT.properties
- ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiContextDelegate.java
- ui/src/main/resources/org/apache/hop/ui/hopgui/delegates/messages/messages_en_US.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/delegates/messages/messages_it_IT.properties
HOP-2717 - Fixed hardcoded strings in GitGuiPlugin
HOP-2725 - Fixed hardcoded strings in HopGuiContextDelegate
HOP-2330 - Improved Italian Translations
> Various fixes

- ui/src/main/java/org/apache/hop/ui/core/widget/ConditionEditor.java
> HOP-2735: Wrap methods that are not supported by RAP

- rap/src/main/java/org/apache/hop/ui/hopgui/HopWeb.java
> HOP-2739: Use logo_icon.svg as favicon

- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
> HOP-2740: Use Server Push to update the UI after executing workflow/pipeline

- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
> HOP-2747, HOP-2748

- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
> HOP-2750 fixed transform type, step references

- assemblies/web/src/assembly/assembly.xml
- core/src/main/java/org/apache/hop/core/config/plugin/ConfigPlugin.java
- core/src/main/java/org/apache/hop/metadata/serializer/json/JsonMetadataSerializer.java
- engine/src/main/java/org/apache/hop/core/search/BaseMetadataSearchableAnalyser.java
- engine/src/main/java/org/apache/hop/core/search/BaseSearchableAnalyser.java
- engine/src/main/java/org/apache/hop/core/search/DatabaseMetaSearchableAnalyser.java
- engine/src/main/java/org/apache/hop/core/search/HopServerSearchableAnalyser.java
- engine/src/main/java/org/apache/hop/core/search/PartitionSchemaSearchableAnalyser.java
- engine/src/main/java/org/apache/hop/core/search/PipelineRunConfigurationSearchableAnalyser.java
- engine/src/main/java/org/apache/hop/core/search/WorkflowRunConfigurationSearchableAnalyser.java
- plugins/tech/cassandra/src/main/java/org/apache/hop/pipeline/transforms/cassandraoutput/CassandraOutputDialog.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/model/GraphModelSearchableAnalyser.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/shared/NeoConnectionSearchableAnalyser.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/search/HopGuiMetadataSearchable.java
HOP-2752 : Search: matching metadata doesn't have type nor filename
HOP-2753 : Add search analyzers for Neo4j connections and graph models
HOP-2762 : GTK-Warning in Cassandra Output dialog
HOP-2763 : Switching projects doesn't always remember open files correctly
HOP-2765 : Samples are not included in Hop Web
> Small improvements & fixes

- assemblies/plugins/actions/getpop/src/assembly/assembly.xml
- assemblies/plugins/actions/mail/src/assembly/assembly.xml
- assemblies/plugins/transforms/mail/src/assembly/assembly.xml
- plugins/actions/getpop/pom.xml
- plugins/actions/mail/pom.xml
> HOP-2764: add missing dependency

- plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/search/ProjectSearchablesIterator.java
- plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassMeta.java
HOP-2776 : Search: harden against invalid XML in .hpl/.hwf
HOP-2782 : Import: Incorrect translation of ${Internal.Job.Filename.D...
> More Kettle import fixes

- plugins/transforms/rowsfromresult/src/main/java/org/apache/hop/pipeline/transforms/rowsfromresult/RowsFromResult.java
> HOP-2803 : NPE in Rows From Result

- .github/workflows/pr_build_code.yml
- .github/workflows/pr_build_docs.yml
> HOP-2805: improve github actions

- docs/hop-user-manual/modules/ROOT/nav.adoc
> removed temporary nav item

- .github/workflows/pr_build_code.yml
> HOP-2805: avoid code build when changing docs

- Jenkinsfile
> HOP-2804: fix stage triggers

- README.md
- assemblies/static/src/main/resources/README.txt
> HOP-2469: add encyption disclaimer to readme

- Jenkinsfile
> HOP-2837: exclude integration-tests from jenkins build

- integration-tests/database/main-0007-input-lookup.hwf
> HOP-2837: non functional change to test build

- assemblies/plugins/dist/pom.xml
- integration-tests/database/0006-insert-update-update.hpl
- integration-tests/database/0007-database-lookup.hpl
- integration-tests/database/0009-database-join-normal.hpl
- integration-tests/database/0009-database-join-outer.hpl
- integration-tests/database/0009-database-join-parameter.hpl
- integration-tests/database/0010-execute-sql-row.hpl
- integration-tests/database/main-0005-check-table.hwf
- integration-tests/database/main-0006-insert-update-delete.hwf
- integration-tests/database/main-0008-table-input.hwf
- integration-tests/database/main-0009-database-join.hwf
- integration-tests/database/main-0010-execute-sql-row.hwf
- integration-tests/database/scripts/script1.sql
- integration-tests/database/scripts/script2.sql
- integration-tests/scripts/run-tests.sh
- plugins/transforms/groupby/src/main/resources/org/apache/hop/pipeline/transforms/groupby/messages/messages_en_US.properties
> HOP-2838, HOP-2837, HOP-2836: more integration tests and minor fixes

- integration-tests/database/main-0009-database-join.hwf
> HOP-2837: fix missing run configuration error in integration test

- Jenkinsfile.daily
- integration-tests/jacoco/jacoco.xml
> It coverage

- Jenkinsfile.daily
> HOP-2844: switch to jacoco over jacocoAdapter

- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineGridDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineLogDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowGridDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowLogDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowRunDelegate.java
- Remove an unsightly border on Windows
- Rename some prefix 'job' to 'workflow'
Please check on other OS
> HOP-2843 Remove an unsightly border on Windows

- plugins/transforms/randomvalue/src/main/resources/org/apache/hop/pipeline/transforms/randomvalue/messages/messages_fr_FR.properties
Tootip is displayed in Context dialog and are too long
> Switch i18n LongDesc and TooltipDesc

- plugins/transforms/monetdbbulkloader/src/main/java/org/apache/hop/pipeline/transforms/monetdbbulkloader/MonetDbBulkLoader.java
> HOP-2671: execute "connection sql" on bulk load

- ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
- ui/src/main/java/org/apache/hop/ui/core/widget/TextVar.java
> HOP-2772: Text.showSelection is not implemented in RWT

- integration-tests/actions/hop-config.json
- integration-tests/transforms/0012-fuzzymatch.hpl
- integration-tests/transforms/main-0012-fuzzymatch.hwf
- integration-tests/transforms/metadata/unit-test/0011-calculator-dates UNIT.json
- integration-tests/transforms/metadata/unit-test/0012-fuzzymatch UNIT.json
> [FIX] : fix integration test numbering and environment

- plugins/transforms/monetdbbulkloader/src/main/java/org/apache/hop/pipeline/transforms/monetdbbulkloader/MonetDbBulkLoader.java
> HOP-2671: add parameter resolve

- plugins/transforms/monetdbbulkloader/src/main/java/org/apache/hop/pipeline/transforms/monetdbbulkloader/MonetDbBulkLoader.java
> HOP-2862: fix password resolve in monetdb bulkloader

- docs/hop-user-manual/modules/ROOT/pages/getting-started/hop-download-install.adoc
> HOP-2869 - removed reference to development builds

- engine/src/main/java/org/apache/hop/pipeline/transforms/dummy/DummyMeta.java
- engine/src/main/java/org/apache/hop/pipeline/transforms/injector/InjectorMeta.java
- ui/src/main/java/org/apache/hop/ui/pipeline/transforms/dummy/DummyDialog.java
- ui/src/main/java/org/apache/hop/ui/pipeline/transforms/injector/InjectorDialog.java
A better solution than previous
> HOP-2875 Move doc url to annotation

- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineGridDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineLogDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowGridDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowLogDelegate.java
Put close and min/max button to the upper right corner of tabfolder execution results
> HOP-2069 Close and min/max button to the upper right corner 

- engine/src/main/java/org/apache/hop/pipeline/PipelinePainter.java
- engine/src/main/java/org/apache/hop/pipeline/PipelinePainterExtension.java
- engine/src/main/java/org/apache/hop/pipeline/PipelineSvgPainter.java
- plugins/engines/beam/src/main/samples/beam/pipelines/input-process-output.hpl
- plugins/engines/beam/src/main/samples/metadata/unit-test/input-process-output UNIT.json
- plugins/misc/testing/src/main/java/org/apache/hop/testing/gui/TestingGuiPlugin.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/util/DataSetConst.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/util/UnitTestUtil.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/xp/DrawGoldenDataSetOnTransformExtensionPoint.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/xp/DrawInputDataSetOnTransformExtensionPoint.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/xp/HopGuiPipelineAfterClose.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/xp/HopGuiUpdateStateMapExtensionPoint.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/xp/LocationMouseDoubleClickExtensionPoint.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/xp/ValidatePipelineUnitTestExtensionPoint.java
- ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditorDialog.java
- ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiExtensionPoint.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineClipboardDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineTransformDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/extension/HopGuiPipelineFinishedExtension.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowActionDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowClipboardDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopGuiAbstractGraph.java
HOP-2899 : Unit tests are incorrectly reported as successful
HOP-2895 : Snap icons to grid when adding new transforms or actions
> HOP-2895, HOP-2899 

- ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
some extra cleanup of the code …
> HOP-2879: values are now saved on macos in TableView

- ui/src/main/java/org/apache/hop/ui/core/vfs/HopVfsFileDialog.java
Please test the removal of the forced white background from the toolbar under Linux / Max with and without dark mode.
> HOP-2909 VFS dialog small improvements

- docker/Dockerfile
- docker/integration-tests/Dockerfile.unit-tests
- docker/integration-tests/integration-tests-base.yaml
- docker/integration-tests/integration-tests-database.yaml
- also includes first split in multiple integration-test environments …
> HOP-2839: add gcompat to docker images

- docker/Dockerfile
> HOP-2839: (revert) gcompat was already included in image

- integration-tests/neo4j/metadata/unit-test/neo4j-graph-output-validation.json
- plugins/actions/pipeline/src/main/java/org/apache/hop/workflow/actions/pipeline/ActionPipelineDialog.java
HOP-2921 : SWT Error while running unit tests (cleaned up tests)
HOP-2922 : Error in Action Pipeline Dialog
> HOP-2921, HOP-2922

- docker/integration-tests/integration-tests-neo4j.yaml
> HOP-2938: change healthcheck on neo4j container

- plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopImportMigratedFiles.java
Moved error handling to per file level and added logging name of file that was causing the error.  Some way of sending a notification of errors back to GUI would be useful still.
- [X ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/HOP) filed 
- [X ] Each commit in the pull request should have a meaningful subject line and body.
- [X ] Format the pull request title like `[HOP-XXX] - Fixes bug in SessionManager`,
where you replace `HOP-XXX` with the appropriate JIRA issue. Best …
> [HOP-2941] Output import error filename and continue processing

- docker/integration-tests/Dockerfile.unit-tests
- integration-tests/scripts/run-tests-docker.sh
> HOP-2944: add parquet-tools to image

- docker/integration-tests/integration-tests-base.yaml
- docker/integration-tests/integration-tests-cassandra.yaml
- docker/integration-tests/integration-tests-database.yaml
- docker/integration-tests/integration-tests-mongo.yaml
- docker/integration-tests/integration-tests-neo4j.yaml
> HOP-2944: add correct compose version to files

- README.md
- docs/hop-dev-manual/modules/ROOT/pages/apache-release/creating-a-release.adoc
- docs/hop-dev-manual/modules/ROOT/pages/apache-release/promoting-a-release.adoc
> Add maven version to readme

- integration-tests/actions/project-config.json
- integration-tests/cassandra/hop-config.json
- integration-tests/cassandra/project-config.json
- integration-tests/database/hop-config.json
- integration-tests/database/project-config.json
- integration-tests/header-env-conf.json
- integration-tests/mdi/hop-config.json
- integration-tests/mdi/project-config.json
- integration-tests/mongo/hop-config.json
- integration-tests/mongo/project-config.json
- integration-tests/neo4j/hop-config.json
- integration-tests/neo4j/project-config.json
- integration-tests/parameters_and_variables/hop-config.json
- integration-tests/parameters_and_variables/project-config.json
- integration-tests/partitioning/hop-config.json
- integration-tests/partitioning/project-config.json
- integration-tests/scripting/hop-config.json
- integration-tests/scripting/project-config.json
- integration-tests/sort_and_unique/hop-config.json
- integration-tests/sort_and_unique/project-config.json
- integration-tests/spreadsheet/hop-config.json
- integration-tests/spreadsheet/project-config.json
- integration-tests/transforms/hop-config.json
- integration-tests/transforms/project-config.json
- integration-tests/xml/hop-config.json
- integration-tests/xml/project-config.json
- ui/src/main/java/org/apache/hop/ui/core/widget/MetaSelectionLine.java
HOP-2958 : Setting tooltip on menu item causes exeption in Hop Web
HOP-2959 : Unrecognized variables field in project
> HOP-2958, HOP-2959

- integration-tests/transforms/0029-parquet-input.hpl
- integration-tests/transforms/0029-parquet-output.hpl
- plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/output/ParquetOutput.java
- plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/output/ParquetOutputDialog.java
- plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/output/ParquetOutputMeta.java
- plugins/tech/parquet/src/main/resources/org/apache/hop/parquet/transforms/output/messages/messages_en_US.properties
Straigtforward fix with modified integration test: saving in non-existing parent folders which need to be created.
> HOP-2951 : Parquet File Output: add option to create parent folders

- plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/output/ParquetOutputDialog.java
> HOP-2949: remove shell variable

- plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/input/ParquetInputDialog.java
> HOP-2962: remove shell variable to avoid NPE in macos

- docker/create_hop_web_container.sh
- integration-tests/database/0014-1-setup-before.hpl
- integration-tests/database/0014-1-setup-before.hwf
- integration-tests/database/0014-2-fail-transactional.hwf
- integration-tests/database/0014-2-overwrite.hpl
- integration-tests/database/0014-3-validate.hpl
- integration-tests/database/main-0014-transactional.hwf
- integration-tests/database/metadata/pipeline-run-configuration/transactional.json
- integration-tests/database/metadata/workflow-run-configuration/transactional.json
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
Minor usability fix for Hop Web 
Extra integration test for a database transaction across a workflow
> HOP-2541, HOP-2955

- integration-tests/transforms/0017-database-lookup.hpl
- integration-tests/transforms/main-0017-database-lookup.hwf
> HOP-2918: replace filter transform

- core/src/main/java/org/apache/hop/core/vfs/HopVfs.java
- docs/hop-user-manual/modules/ROOT/pages/vfs/aws-s3-vfs.adoc
- plugins/misc/projects/src/main/java/org/apache/hop/projects/environment/LifecycleEnvironmentDialog.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/environment/ManageEnvironmentsOptionPlugin.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/project/Project.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/project/ProjectConfig.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/project/ProjectDialog.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/search/ProjectSearchablesIterator.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/util/ProjectsUtil.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/var/ManageConfigFileOptionPlugin.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopGuiFileReplaceHomeVariable.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopImportDbConnections.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java
HOP-2967 : Non-local folders for projects are not working
HOP-2968 : S3 VFS driver shows size warning
> HOP-2967, HOP-2968

- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java
> HOP-2967 : Non-local folders for projects are not working

- docs/hop-dev-manual/modules/ROOT/pages/apache-release/checking-a-release.adoc
In the name of some files, changed the text from rcX to src …
> File name adjustments

- docs/hop-dev-manual/modules/ROOT/pages/apache-release/checking-a-release.adoc
> HOP-2974 apache-rat:check instead of apache-rat:rat

- core/src/main/java/org/apache/hop/core/database/BaseDatabaseMeta.java
- core/src/main/java/org/apache/hop/core/database/DatabaseMeta.java
- core/src/main/java/org/apache/hop/core/database/IDatabase.java
- engine/src/main/java/org/apache/hop/pipeline/Pipeline.java
- plugins/actions/pipeline/src/main/java/org/apache/hop/workflow/actions/pipeline/ActionPipeline.java
- plugins/databases/generic/src/main/java/org/apache/hop/databases/generic/GenericDatabaseMeta.java
> HOP-2937, HOP-2954

- docker/integration-tests/integration-tests-cassandra.yaml
- docker/integration-tests/integration-tests-database.yaml
- docker/integration-tests/integration-tests-mongo.yaml
- docker/integration-tests/integration-tests-neo4j.yaml
> HOP-2999: increase timeouts on container creation

- engine/src/main/java/org/apache/hop/imp/ImportPluginType.java
- ui/src/main/java/org/apache/hop/ui/core/dialog/ContextDialog.java
HOP-2661 : add CLI import tool (doc URL update)
HOP-2736 : It is not efficient to generate 200 icon images and transf… …
> HOP-2661, HOP-2736

- core/src/main/java/org/apache/hop/core/svg/SvgCache.java
- docker/Dockerfile.web
- docker/create_hop_web_container.sh
- plugins/transforms/addsequence/src/main/java/org/apache/hop/pipeline/transforms/addsequence/AddSequenceMeta.java
- rap/src/main/java/org/apache/hop/ui/hopgui/HopWeb.java
- rap/src/main/resources/org/apache/hop/ui/hopgui/dark-mode.css
- rap/src/main/resources/org/apache/hop/ui/hopgui/light-mode.css
HOP-2892 : Add keywords to transforms and actions metadata
HOP-3000 : Hop Web: add support for themes
> HOP-2892, HOP-3000

- core/src/main/java/org/apache/hop/core/database/Database.java
- ui/src/main/java/org/apache/hop/ui/core/database/dialog/DatabaseExplorerDialog.java
- ui/src/main/java/org/apache/hop/ui/core/database/dialog/SqlEditor.java
- ui/src/main/java/org/apache/hop/ui/core/dialog/SqlStatementsDialog.java
- ui/src/main/java/org/apache/hop/ui/core/gui/GuiResource.java
- ui/src/main/java/org/apache/hop/ui/hopgui/shared/SwtGc.java
> HOP-2950 Sorting table and schema names in Database explorer and fix

- ui/src/main/java/org/apache/hop/ui/core/widget/ControlSpaceKeyAdapter.java
> HOP-2992: change sorting and fix ctrl+space on macOs

- ui/src/main/java/org/apache/hop/ui/core/vfs/HopVfsFileDialog.java
- ui/src/main/resources/org/apache/hop/ui/core/vfs/messages/messages_en_US.properties
FIXME: the keyboard shortcut does not work on Windows, I will try to fix in 2 weeks. 
@GuiKeyboardShortcut(key = SWT.F2)
> HOP-2997 Add delete and rename options in VFS dialog

- docs/hop-user-manual/modules/ROOT/pages/pipeline/metadata-injection.adoc
- integration-tests/scripting/0002-udjc-get-MDI-transforms.hpl
> [DOC] add list with supported MDI transforms, add hpl to generate list

- docker/integration-tests/Dockerfile.unit-tests
- integration-tests/beam_directrunner/0001-generate-rows.hpl
- integration-tests/beam_directrunner/0002-switch-case.hpl
- integration-tests/beam_directrunner/datasets/customers-noheader-1k.txt
- integration-tests/beam_directrunner/dev-env-config.json
- integration-tests/beam_directrunner/hop-config.json
- integration-tests/beam_directrunner/main-0001-generate-rows.hwf
- integration-tests/beam_directrunner/main-0002-switch-case.hwf
- integration-tests/beam_directrunner/metadata/dataset/customers-input.json
- integration-tests/beam_directrunner/metadata/file-definition/Customers.json
- integration-tests/beam_directrunner/metadata/pipeline-run-configuration/local.json
- integration-tests/beam_directrunner/metadata/rdbms/testdb.json
- integration-tests/beam_directrunner/metadata/workflow-run-configuration/local.json
- integration-tests/beam_directrunner/project-config.json
> HOP-3023: add directrunner integration tests

- helm/README.md
- helm/hop-server/.helmignore
- helm/hop-server/Chart.yaml
- helm/hop-server/templates/_helpers.tpl
- helm/hop-server/templates/hop-config.yaml
- helm/hop-server/templates/hop-deployment.yaml
- helm/hop-server/templates/hop-service.yaml
- helm/hop-server/templates/tests/test-connection.yaml
- helm/hop-server/values.yaml
> helm chart hop server

- docs/hop-user-manual/modules/ROOT/pages/pipeline/pipeline-run-configurations/beam-spark-pipeline-engine.adoc
> HOP-3032: fix table layout

- integration-tests/database/0006-insert-table-output.hpl
- plugins/transforms/tableoutput/src/main/java/org/apache/hop/pipeline/transforms/tableoutput/TableOutputField.java
- plugins/transforms/tableoutput/src/test/java/org/apache/hop/pipeline/transforms/tableoutput/TableOutputMetaTest.java
> HOP-3088: fix persistance of data and unit-test

- ui/src/main/java/org/apache/hop/ui/core/dialog/ContextDialog.java
I would test tomorrow with multiple monitors, but if anyone can test on Linux / Max / WebHop
> HOP-3013 Adapt ContextDialog position to monitor

- assemblies/plugins/transforms/mongodb/pom.xml
- assemblies/plugins/transforms/mongodb/src/assembly/assembly.xml
- plugins/transforms/mongodb/pom.xml
Rename without the S like other plugins 
From hop-transforms-mongodb to hop-transform-mongodb
> Rename artifactId hop-transform-mongodb

- ui/src/main/resources/org/apache/hop/ui/partition/messages/messages_en_US.properties
- ui/src/main/resources/org/apache/hop/ui/partition/messages/messages_pt_BR.properties
Add new file translate,  partition translate for pt_BR
> Hop-3040 - add partition translate for pt_BR

- integration-tests/database/0017-postgresql-bulkloader.hpl
- integration-tests/database/main-0016-delete-generic-driver.hwf
- integration-tests/database/main-0017-postgresql-bulkloader.hwf
- plugins/transforms/pgbulkloader/src/main/java/org/apache/hop/pipeline/transforms/pgbulkloader/PGBulkLoader.java
- plugins/transforms/pgbulkloader/src/main/java/org/apache/hop/pipeline/transforms/pgbulkloader/PGBulkLoaderMeta.java
> HOP-3092,HOP-2065: cleanup code fix test

- core/src/main/java/org/apache/hop/metadata/serializer/xml/XmlMetadataUtil.java
- rap/src/main/resources/org/apache/hop/ui/hopgui/dark-mode.css
- ui/src/main/java/org/apache/hop/ui/core/dialog/CheckResultDialog.java
- ui/src/main/java/org/apache/hop/ui/hopgui/dialog/CheckPipelineProgressDialog.java
> HOP-3000, HOP-3009, HOP-3010

- plugins/transforms/databaselookup/src/main/samples/transforms/databaselookup.hpl
- plugins/transforms/insertupdate/src/main/samples/transforms/insertupdate-basic.hpl
- plugins/transforms/tableinput/src/main/samples/transforms/tableinput-accept-input.hpl
- plugins/transforms/tableinput/src/main/samples/transforms/tableinput-basic.hpl
- plugins/transforms/tableinput/src/main/samples/transforms/tableinput-variables.hpl
- plugins/transforms/tableoutput/src/main/samples/metadata/rdbms/hop-samples.json
- plugins/transforms/tableoutput/src/main/samples/transforms/tableoutput-basic.hpl
> HOP-2391 first batch of samples for rdbms transforms

- assemblies/plugins/actions/ftp/src/assembly/assembly.xml
- assemblies/plugins/tech/parquet/src/assembly/assembly.xml
- core/pom.xml
> HOP-3102: add commons-net dependency to lib

- plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValues.java
- plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesAddedFunctions.java
- plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesData.java
- plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesDummy.java
- plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesMeta.java
- plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesMetaDialog.java
- plugins/transforms/javascript/src/test/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesMetaInjectionTest.java
- plugins/transforms/javascript/src/test/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesMetaTest.java
- plugins/transforms/javascript/src/test/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesTest.java
- ui/src/main/java/org/apache/hop/ui/core/widget/StyledTextComp.java
- Fix StyledTextComposite layout
- Rename classes  ScriptValuesModXXX -> ScriptValuesXXX
> HOP-3101 StyledTextComposite layout + rename class ScriptValuesMod

- docs/hop-user-manual/modules/ROOT/pages/plugins/plugins.adoc
- docs/hop-user-manual/modules/ROOT/pages/technology/google/index.adoc
> [DOC] remove broken links

- docs/hop-user-manual/modules/ROOT/pages/pipeline/metadata-injection.adoc
> [DOC] update metadata-injection page

- docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/getting-started-with-beam.adoc
> HOP-3133 : Documentation: add Getting started with Beam guide

- .asf.yaml
> Update asf.yaml to send PR mails to commits@..

- assemblies/plugins/engines/beam/pom.xml
- assemblies/plugins/engines/beam/src/assembly/assembly.xml
- assemblies/plugins/vfs/s3/pom.xml
- plugins/engines/beam/pom.xml
- plugins/transforms/kafka/src/main/samples/transforms/kafka-consumer-read-pokemon-data-child.hpl
- plugins/transforms/kafka/src/main/samples/transforms/kafka-consumer-read-pokemon-data.hpl
- plugins/transforms/kafka/src/main/samples/transforms/kafka-producer-create-pokemon-data.hpl
- plugins/vfs/s3/pom.xml
- pom.xml
Pretty straightforward inclusion of Apache and AWS Java SDK libraries
> HOP-3135 : Beam: include AWS S3 support libraries (and S3 VFS libs sync)

- plugins/transforms/joinrows/src/main/java/org/apache/hop/pipeline/transforms/joinrows/JoinRowsDialog.java
> HOP-3138: fix main transform to read from

- docs/hop-user-manual/modules/ROOT/pages/pipeline/pipeline-run-configurations/beam-dataflow-pipeline-engine.adoc
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/dataflow/BeamDataFlowPipelineRunConfiguration.java
Just a few extra options for the Dataflow pipeline run configurations
> HOP-3139 : Beam Dataflow: add the ability to specify a network and/or subnetwork

- engine/src/main/java/org/apache/hop/pipeline/PipelineMeta.java
- integration-tests/transforms/run-all.hpl
- plugins/tech/cassandra/src/main/java/org/apache/hop/pipeline/transforms/cassandrasstableoutput/SSTableOutputDialog.java
- ui/src/main/java/org/apache/hop/ui/core/dialog/EnterSelectionDialog.java
- ui/src/main/java/org/apache/hop/ui/core/widget/ConditionEditor.java
> HOP-3141,HOP-3128,HOP-3129

- core/src/test/java/org/apache/hop/core/svg/HopSvgGraphics2DTest.java
> HOP-3130: disable test for windows CR vs CRLF difference

- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/transform/TransformBatchTransform.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/transform/TransformTransform.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/BeamPipelineEngine.java
- plugins/transforms/tableoutput/src/main/java/org/apache/hop/pipeline/transforms/tableoutput/TableOutput.java
- ui/src/main/java/org/apache/hop/ui/core/database/DatabaseMetaEditor.java
HOP-3161 : Table Output doesn't commit all records in Beam pipeline
HOP-3160 : Beam : variables are not passed correctly to initializing … …
HOP-3162 : Relational Database Connection is not flagged as changed w… …
> Fixing edge cases

- assemblies/static/src/main/resources/hop-conf.sh
- assemblies/static/src/main/resources/hop-gui.sh
- assemblies/static/src/main/resources/hop-import.sh
- assemblies/static/src/main/resources/hop-run.sh
- assemblies/static/src/main/resources/hop-search.sh
- assemblies/static/src/main/resources/hop-server.sh
- assemblies/static/src/main/resources/hop-translator.sh
> HOP-2377: change startup scripts to detect java architecture

- docs/hop-tech-manual/modules/ROOT/pages/hop-vs-kettle/if-you-know-kettle.adoc
- docs/hop-user-manual/modules/ROOT/nav.adoc
- docs/hop-user-manual/modules/ROOT/pages/getting-started/hop-gui-pipelines.adoc
- docs/hop-user-manual/modules/ROOT/pages/hop-run/index.adoc
- docs/hop-user-manual/modules/ROOT/pages/pipeline/create-pipeline.adoc
- ui/src/main/java/org/apache/hop/ui/core/gui/GuiResource.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
- ui/src/main/java/org/apache/hop/ui/i18n/editor/Translator.java
> HOP-3151, HOP-3167

- Jenkinsfile
- docs/hop-dev-manual/modules/ROOT/pages/apache-release/promoting-a-release.adoc
> HOP-3169: add ARM build for docker web

- Jenkinsfile
> HOP-3169: add buildx creation

- Jenkinsfile
> HOP-3169: remove image cleanup

- core/src/main/java/org/apache/hop/core/Condition.java
- engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransform.java
- plugins/tech/azure/src/main/java/org/apache/hop/vfs/azure/config/AzureConfig.java
- AzureConfig: Fix useless self-assignment
- Condition: Remove the boxing to "Boolean"
- BaseTransform: Remove useless casting
> HOP-3202 Code cleanup and Sonar issues

- assemblies/plugins/databases/googlebigquery-assemblies/pom.xml
- assemblies/plugins/engines/beam/pom.xml
- assemblies/static/src/main/resources/THIRD-PARTY.txt
- core/src/main/java/org/apache/hop/i18n/GlobalMessageUtil.java
- docs/hop-dev-manual/modules/ROOT/pages/setup-dev-environment.adoc
- docs/hop-user-manual/modules/ROOT/pages/metadata-types/neo4j/neo4j-connection.adoc
- docs/hop-user-manual/modules/ROOT/pages/technology/google/index.adoc
- engine/src/main/java/org/apache/hop/pipeline/Pipeline.java
- engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransform.java
- engine/src/main/java/org/apache/hop/workflow/Workflow.java
- engine/src/main/java/org/apache/hop/workflow/action/ActionBase.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/handler/BeamGenericTransformHandler.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/transforms/bq/BQField.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/transforms/bq/BeamBQInput.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/transforms/bq/BeamBQInputData.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/transforms/bq/BeamBQInputMeta.java
- plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesAddedFunctions.java
> Minor fixes and code-hardening

- plugins/tech/pom.xml
> HOP-2961: fix missing module in pom

- engine/src/test/java/org/apache/hop/history/AuditManagerTest.java
- plugins/misc/git/src/test/java/org/apache/hop/git/model/UIGitTest.java
- plugins/tech/cassandra/src/test/java/org/apache/hop/pipeline/transforms/cassandrasstableoutput/writer/Cql3SsTableWriterTest.java
- plugins/transforms/calculator/src/test/java/org/apache/hop/pipeline/transforms/calculator/CalculatorMetaFunctionTest.java
- plugins/transforms/checksum/src/test/java/org/apache/hop/pipeline/transforms/checksum/CheckSumTest.java
- pom.xml
- ui/src/test/java/org/apache/hop/ui/core/dialog/PreviewRowsDialogTest.java
> HOP-3206: fix/disable failing tests on windows

- plugins/transforms/metainject/src/main/java/org/apache/hop/pipeline/transforms/metainject/MetaInjectDialog.java
Fixes for the tree and the field mapper
> HOP-3208 : MDI dialog: show all transforms, not only the used ones

- core/src/main/java/org/apache/hop/core/BlockingRowSet.java
https://sonarcloud.io/project/issues?id=hop&languages=java&open=AW6ThK-UMj3rolYBEQ8f&resolved=false
If this is your first contribution, you have to read the …
> Catches should be combined

- plugins/actions/abort/src/main/java/org/apache/hop/workflow/actions/abort/ActionAbort.java
- plugins/actions/abort/src/main/java/org/apache/hop/workflow/actions/abort/ActionAbortDialog.java
> HOP-3189: switch back to message and small cleanup

- core/src/main/java/org/apache/hop/core/logging/LoggingObject.java
- engine/src/main/java/org/apache/hop/base/AbstractMeta.java
- engine/src/main/java/org/apache/hop/pipeline/Pipeline.java
- engine/src/main/java/org/apache/hop/pipeline/PipelineMeta.java
- engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineEngine.java
- engine/src/main/java/org/apache/hop/workflow/Workflow.java
- engine/src/main/java/org/apache/hop/workflow/WorkflowMeta.java
- engine/src/main/java/org/apache/hop/www/AddPipelineServlet.java
- engine/src/main/java/org/apache/hop/www/AddWorkflowServlet.java
- engine/src/main/java/org/apache/hop/www/BaseWorkflowServlet.java
- engine/src/main/java/org/apache/hop/www/jaxrs/PipelineResource.java
- engine/src/main/java/org/apache/hop/www/jaxrs/WorkflowResource.java
- engine/src/test/java/org/apache/hop/base/AbstractMetaTest.java
- engine/src/test/java/org/apache/hop/history/AuditManagerTest.java
- engine/src/test/java/org/apache/hop/pipeline/PipelineTest.java
- engine/src/test/java/org/apache/hop/pipeline/transform/BaseTransformTest.java
- engine/src/test/java/org/apache/hop/workflow/WorkflowTest.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/BeamPipelineEngine.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/direct/BeamDirectPipelineEngine.java
- plugins/tech/azure/src/main/java/org/apache/hop/pipeline/transforms/eventhubs/listen/AzureListenerMeta.java
- plugins/transforms/dbproc/src/main/java/org/apache/hop/pipeline/transforms/dbproc/DBProcMeta.java
- plugins/transforms/metainject/src/main/java/org/apache/hop/pipeline/transforms/metainject/MetaInjectMeta.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineRunDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
Further removing state from workflow and pipeline metadata
> HOP-3212 : Workflow/Pipeline contains logging level state

- integration-tests/actions/0001-abort.hwf
- integration-tests/actions/project-config.json
- plugins/transforms/excelinput/src/main/java/org/apache/hop/pipeline/transforms/excelinput/ExcelInputMeta.java
- pom.xml
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineHopDelegate.java
> [CLEANUP], HOP-3189, HOP-3217, HOP-3215

- assemblies/plugins/tech/google/pom.xml
- core/pom.xml
- core/src/test/java/org/apache/hop/core/row/value/ValueMetaBaseTest.java
- engine/pom.xml
- engine/src/test/java/org/apache/hop/history/AuditManagerTest.java
- plugins/databases/greenplum/src/test/java/org/apache/hop/databases/greenplum/GreenplumValueMetaBaseTest.java
- plugins/databases/mariadb/src/test/java/org/apache/hop/databases/mariadb/MariaDBDatabaseMetaTest.java
- plugins/databases/mysql/src/test/java/org/apache/hop/databases/mysql/MySqlDatabaseMetaTest.java
- plugins/databases/netezza/src/test/java/org/apache/hop/core/row/value/NettezaValueMetaBaseTest.java
- plugins/databases/oracle/src/test/java/org/apache/hop/databases/oracle/OracleValueMetaBaseTest.java
- plugins/databases/sqlite/src/test/java/org/apache/hop/core/row/value/SQLiteValueMetaBaseTest.java
- plugins/databases/teradata/src/test/java/org/apache/hop/databases/teradata/TeradataValueMetaBaseTest.java
- plugins/engines/beam/src/test/java/org/apache/hop/beam/engines/direct/BeamDirectPipelineEngineTest.java
- plugins/engines/beam/src/test/java/org/apache/hop/beam/engines/spark/BeamSparkPipelineEngineTest.java
- plugins/tech/google/pom.xml
- plugins/transforms/insertupdate/src/test/java/org/apache/hop/pipeline/transforms/insertupdate/InsertUpdateTestLazyConversion.java
- plugins/transforms/javascript/pom.xml
- plugins/transforms/javascript/src/test/java/org/apache/hop/pipeline/transforms/javascript/ScriptValueAddFunctions_SetVariableScopeTest.java
- plugins/transforms/javascript/src/test/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesMetaTest.java
> HOP-3248, HOP-3249

- ui/src/main/resources/org/apache/hop/ui/hopgui/file/messages/messages_pt_BR.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/file/pipeline/messages/messages_pt_BR.properties
- ui/src/main/resources/org/apache/hop/ui/imp/messages/messages_pt_BR.properties
Add new file translate (files pipeline, imp, exp pipeline)  from for pt_BR
> Hop-3040 - Translate files pipeline, imp, exp pipeline from pt_BR

- core/src/main/java/org/apache/hop/core/vfs/HopVfs.java
- engine/src/main/java/org/apache/hop/pipeline/Pipeline.java
- engine/src/main/java/org/apache/hop/workflow/Workflow.java
- engine/src/test/java/org/apache/hop/history/AuditManagerTest.java
- integration-tests/beam_directrunner/0003-pipeline-with-error.hpl
- integration-tests/beam_directrunner/0003-pipeline-without-error.hpl
- integration-tests/beam_directrunner/main-0003-pipeline-action.hwf
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/BeamPipelineEngine.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
Small but important fix to make child pipelines see that the parent was stopped.
> HOP-3240, HOP-3251, HOP-3255

- Jenkinsfile
> [BUILD] add override parameter

- docs/hop-user-manual/modules/ROOT/nav.adoc
- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/beambigqueryoutput.adoc
- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/beambigtableinput.adoc
- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/beambigtableoutput.adoc
- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/postgresbulkloader.adoc
- plugins/engines/beam/src/main/java/org/apache/hop/beam/transforms/bigtable/BeamBigtableInputMeta.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/transforms/bigtable/BeamBigtableOutputMeta.java
> HOP-3260, HOP-3254, HOP-3211

- docs/hop-user-manual/modules/ROOT/pages/variables.adoc
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/model/GraphModelEditor.java
- ui/src/main/java/org/apache/hop/ui/core/database/DatabaseMetaEditor.java
- ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditor.java
Just a few lines of code hardening...
> HOP-3256, HOP-3105, HOP-3112, HOP-3152

- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/cypher/Cypher.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/output/Neo4JOutput.java
- add variable support to Neo4j Cypher Transform
- add variable support to Neo4j Output Transform
> HOP-3263: add variable support to neo4j connections

- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineTransformDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowActionDelegate.java
> HOP-3275, HOP-3276

- core/src/main/java/org/apache/hop/core/util/Utils.java
- core/src/test/java/org/apache/hop/core/util/UtilsTest.java
The algorithm is simple enough to re-write
Added unit tests
> HOP-3186 : Re-implement Damerau Levenshtein distance calculation

- docs/hop-user-manual/modules/ROOT/pages/hop-gui/index.adoc
> HOP-3289 removed experimental reference to Hop Web

- core/src/main/java/org/apache/hop/core/Result.java
- core/src/main/java/org/apache/hop/core/ResultFile.java
- engine/src/main/java/org/apache/hop/www/GetPipelineStatusServlet.java
- engine/src/main/java/org/apache/hop/www/GetWorkflowStatusServlet.java
- engine/src/main/java/org/apache/hop/www/HopServerPipelineStatus.java
- engine/src/main/java/org/apache/hop/www/HopServerWorkflowStatus.java
- engine/src/main/resources/org/apache/hop/www/messages/messages_en_US.properties
HOP-3294 : JSON of hop server pipeline /workflow status has bad date formats
HOP-3300 : JSON Serialization of Result leads to Jackson errors
> HOP-3294, HOP-3300 : Hop Server JSON improvements

- assemblies/core/lib/pom.xml
- assemblies/plugins/engines/beam/src/assembly/assembly.xml
- assemblies/plugins/misc/import/pom.xml
- assemblies/plugins/misc/import/src/assembly/assembly.xml
- assemblies/plugins/tech/azure/src/assembly/assembly.xml
- assemblies/plugins/tech/cassandra/pom.xml
- assemblies/plugins/tech/cassandra/src/assembly/assembly.xml
- assemblies/plugins/transforms/fake/src/assembly/assembly.xml
- core/pom.xml
- plugins/misc/import/pom.xml
- plugins/tech/cassandra/pom.xml
- pom.xml
HOP-3292 : Align apache commons lang3 library versions
> HOP-3292 : Align apache commons lang3 library versions

- plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/TransformClassBase.java
- plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClass.java
- plugins/transforms/janino/src/main/samples/transforms/user-defined-java-class-calculate-date-of-easter.hpl
- plugins/transforms/janino/src/main/samples/transforms/user-defined-java-class-variables.hpl
HOP-3307 : User Defined Java Class: init method is broken
HOP-2391 : Samples for various transforms and actions (UDJC)
> UDJC: HOP-2391, HOP-3307

- docker/Dockerfile.web
> HOP-3308: change container to tomcat 9

- docker/integration-tests/integration-tests-http.yaml
- integration-tests/http/0001-http-post.hpl
- integration-tests/http/dev-env-config.json
- integration-tests/http/hop-config.json
- integration-tests/http/main-0001-http-post.hwf
- integration-tests/http/metadata/pipeline-run-configuration/local.json
- integration-tests/http/metadata/workflow-run-configuration/local.json
- integration-tests/http/project-config.json
- plugins/transforms/httppost/src/main/java/org/apache/hop/pipeline/transforms/httppost/HttpPostDialog.java
> HOP-3203, HOP-3314

- core/src/main/java/org/apache/hop/core/Counter.java
- core/src/main/java/org/apache/hop/core/config/ConfigFileSerializer.java
- core/src/main/java/org/apache/hop/core/database/Database.java
- core/src/main/java/org/apache/hop/core/database/SqlScriptParser.java
- core/src/main/java/org/apache/hop/core/fileinput/FileInputList.java
- core/src/main/java/org/apache/hop/core/gui/plugin/GuiRegistry.java
- core/src/main/java/org/apache/hop/core/logging/LogChannel.java
- core/src/main/java/org/apache/hop/core/logging/LoggingRegistry.java
- core/src/main/java/org/apache/hop/core/plugins/JarCache.java
- core/src/main/java/org/apache/hop/core/plugins/PluginRegistry.java
- core/src/main/java/org/apache/hop/core/row/value/ValueMetaBase.java
- core/src/main/java/org/apache/hop/core/row/value/ValueMetaInternetAddress.java
- core/src/main/java/org/apache/hop/core/row/value/ValueMetaTimestamp.java
- core/src/main/java/org/apache/hop/core/util/StringUtil.java
- core/src/main/java/org/apache/hop/core/vfs/HopVfs.java
- core/src/main/java/org/apache/hop/core/xml/XmlHandler.java
- engine/src/main/java/org/apache/hop/core/gui/WorkflowTracker.java
- plugins/transforms/joinrows/src/main/java/org/apache/hop/pipeline/transforms/joinrows/JoinRowsData.java
> [SONAR] some further cleanup

- core/src/main/java/org/apache/hop/core/action/GuiContextActionFilter.java
- core/src/main/java/org/apache/hop/core/gui/plugin/GuiRegistry.java
- core/src/main/java/org/apache/hop/core/gui/plugin/action/GuiActionFilter.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/gui/TestingGuiPlugin.java
- ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiEnvironment.java
- ui/src/main/java/org/apache/hop/ui/hopgui/context/BaseGuiContextHandler.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/context/HopGuiPipelineHopContext.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopGuiAbstractGraph.java
HOP-3290 : Scroll wheel not working in field selection combo on Win 10
HOP-3304 : Make actions context sensitive
HOP-3319 : Scrolling using the mouse wheel is too fast
HOP-3320 : Moving a transform on multiple pages pipelines immediately…
(could be I mixed up commit messages for 19 and 20)
> HOP-3290, HOP-3304, HOP-3319, HOP-3320

- plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/fatjar/FatJarBuilder.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/gencsv/CsvFile.java
- plugins/transforms/kafka/src/main/java/org/apache/hop/pipeline/transforms/kafka/consumer/KafkaConsumerInputMeta.java
- plugins/transforms/mongodb/src/main/java/org/apache/hop/mongo/wrapper/field/MongoField.java
- plugins/transforms/tableoutput/src/main/java/org/apache/hop/pipeline/transforms/tableoutput/TableOutputMeta.java
> [SONAR] suppress transient warnings in sonar

- core/src/main/java/org/apache/hop/core/config/plugin/ConfigPlugin.java
- core/src/main/java/org/apache/hop/core/extension/HopExtensionPoint.java
- core/src/main/java/org/apache/hop/metadata/serializer/multi/MultiMetadataProvider.java
- core/src/main/java/org/apache/hop/metadata/util/HopMetadataUtil.java
- engine/src/main/java/org/apache/hop/config/HopConfig.java
- engine/src/main/java/org/apache/hop/imp/HopImport.java
- engine/src/main/java/org/apache/hop/imp/HopImportBase.java
- engine/src/main/java/org/apache/hop/imp/IHopImport.java
- engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransform.java
- engine/src/main/java/org/apache/hop/run/HopRun.java
- engine/src/main/java/org/apache/hop/search/HopSearch.java
- engine/src/main/java/org/apache/hop/www/AddPipelineServlet.java
- engine/src/main/java/org/apache/hop/www/AddWorkflowServlet.java
- engine/src/main/java/org/apache/hop/www/BaseWorkflowServlet.java
- engine/src/main/java/org/apache/hop/www/GetStatusServlet.java
- engine/src/main/java/org/apache/hop/www/HopServer.java
- engine/src/main/java/org/apache/hop/www/HopServerConfig.java
- engine/src/main/java/org/apache/hop/www/HopServerPipelineStatus.java
- engine/src/main/java/org/apache/hop/www/HopServerWorkflowStatus.java
- engine/src/main/java/org/apache/hop/www/StartWorkflowServlet.java
- engine/src/main/java/org/apache/hop/www/WebServiceServlet.java
- engine/src/main/java/org/apache/hop/www/jaxrs/PipelineResource.java
- engine/src/main/java/org/apache/hop/www/jaxrs/WorkflowResource.java
- engine/src/test/java/org/apache/hop/www/HopServerPipelineStatusTest.java
- engine/src/test/java/org/apache/hop/www/HopServerWorkflowStatusTest.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/config/ProjectsServerOptionPlugin.java
- plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopServerCalculateFilenameExtensionPoint.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/gui/TestingGuiPlugin.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
HOP-3334 : On server without display, Hop Server throws error in status
HOP-3336 : Import: support boolean/timestamp" flags aren't migrated
HOP-3342 : Hop server pipeline status: start/end dates are not serial…
HOP-3341 : Query hop server status from the command line
> HOP-3334, HOP-3336, HOP-3342, HOP-3341

- docs/hop-user-manual/modules/ROOT/pages/hop-server/index.adoc
HOP-3343 : Hop Server: I want to enable a project or environment at startup (docs)
> HOP-3341 : Query hop server status from the command line (docs)

- docs/hop-user-manual/modules/ROOT/pages/getting-started/hop-gui-pipelines.adoc
> (DOC) - simplify grammar and update transform count

- docs/hop-user-manual/modules/ROOT/pages/getting-started/hop-concepts.adoc
> (DOC) - Fix grammar in concept sentences (pluralization)

- docker/Dockerfile.web
Explicitly declares and passes HOP variables to tomcat plus some cleaning …
> HOP-3337 - Conform Dockerfile.web to the other scripts

- integration-tests/http/0001-http-post-test-body.hpl
- integration-tests/http/0001-http-post-test-headers.hpl
- integration-tests/http/0001-http-post-test-query.hpl
- integration-tests/http/0002-http-client-test-headers.hpl
- integration-tests/http/0002-http-client-test-parameters.hpl
- integration-tests/http/0002-http-client.hpl
- integration-tests/http/0003-rest-client-test-headers.hpl
- integration-tests/http/0003-rest-client-test-parameters.hpl
- integration-tests/http/0003-rest-client.hpl
- integration-tests/http/0004-webservice-available.hpl
- integration-tests/http/0005-http-action-check-header.hpl
- integration-tests/http/main-0002-http-client.hwf
- integration-tests/http/main-0003-rest-client.hwf
- integration-tests/http/main-0004-webservice-available.hwf
- integration-tests/http/main-0005-http-action.hwf
> HOP-3203: test all http transforms

- core/src/main/java/org/apache/hop/core/plugins/BasePluginType.java
- core/src/main/java/org/apache/hop/core/plugins/HopURLClassLoader.java
Everything seems to work fine with Java 8 and Java 11 without warning, but just a POC if someone else wants to test
> HOP-2229 HopURLClassLoader simplification

- plugins/transforms/groupby/src/main/java/org/apache/hop/pipeline/transforms/groupby/GroupByMeta.java
- plugins/transforms/groupby/src/main/resources/org/apache/hop/pipeline/transforms/groupby/messages/messages_en_US.properties
- fix missing MDI translation
- add keyword aggregation
> HOP-3348 Missing MDI translations for GroupBy transform

- plugins/actions/as400command/src/main/java/org/apache/hop/workflow/actions/as400command/ActionAs400Command.java
- plugins/actions/as400command/src/main/java/org/apache/hop/workflow/actions/as400command/ActionAs400CommandDialog.java
- plugins/actions/as400command/src/main/resources/org/apache/hop/workflow/actions/as400command/messages/messages_en_US.properties
- plugins/actions/as400command/src/test/java/org/apache/hop/workflow/actions/as400command/ActionAs400CommandLoadSaveTest.java
Replace getXml with HopMetadataProperty
> HOP-3349 Cleanup Action AS/400 CL Commands

- docs/hop-tech-manual/README.md
> (DOC) - Fix typos in README.md for technical documentation

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/blockingtransform.adoc
> (DOC) - Add note about Blocking transform not 100%

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/blockingtransform.adoc
> [DOC] fix broken link in blockingtransform docs

- Jenkinsfile
> HOP-3363: switch main build to java 11

- engine/src/main/resources/hop-variables.xml
> HOP-HOP-3501 : Avoid formatting hop-variables.xml

- ui/src/main/java/org/apache/hop/ui/core/widget/StyledTextComp.java
Not perfect because of some other events issue in RAP but at least it's not bombing out anymore and getting really close.
> HOP-3478 : NoSuchMethodError opening Tableinput transform in hop-web

- rap/pom.xml
- rap/src/main/resources/org/apache/hop/ui/hopgui/dark-mode.css
- rap/src/main/resources/org/apache/hop/ui/hopgui/light-mode.css
- ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
- ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
- ui/src/main/java/org/apache/hop/ui/util/EnvironmentUtils.java
Also some code hardening for fixed width fonts on the various platforms and other minor color tweaks in the themes.
> HOP-3479 : Hop Web white on white colors in combo

- assemblies/plugins/dist/pom.xml
- assemblies/plugins/misc/async/pom.xml
- assemblies/plugins/misc/async/src/assembly/assembly.xml
- assemblies/plugins/misc/async/src/main/resources/version.xml
- core/src/main/java/org/apache/hop/core/extension/HopExtensionPoint.java
- docs/hop-user-manual/modules/ROOT/pages/hop-server/async-web-service.adoc
- docs/hop-user-manual/modules/ROOT/pages/hop-server/index.adoc
- docs/hop-user-manual/modules/ROOT/pages/hop-server/rest-api.adoc
- docs/hop-user-manual/modules/ROOT/pages/metadata-types/index.adoc
- plugins/misc/async/pom.xml
- plugins/misc/async/src/main/java/org/apache/hop/www/AsyncGuiPlugin.java
- plugins/misc/async/src/main/java/org/apache/hop/www/AsyncRunServlet.java
- plugins/misc/async/src/main/java/org/apache/hop/www/AsyncStatus.java
- plugins/misc/async/src/main/java/org/apache/hop/www/AsyncStatusServlet.java
- plugins/misc/async/src/main/java/org/apache/hop/www/AsyncWebService.java
- plugins/misc/async/src/main/java/org/apache/hop/www/AsyncWebServiceEditor.java
- plugins/misc/async/src/main/java/org/apache/hop/www/Defaults.java
- plugins/misc/async/src/main/java/org/apache/hop/www/xp/ActionLogIconClickedExtensionPoint.java
- plugins/misc/async/src/main/java/org/apache/hop/www/xp/DrawAsyncLoggingIconExtensionPoint.java
- plugins/misc/async/src/main/java/org/apache/hop/www/xp/MarkAsyncWorkflowActionExtensionPoint.java
- plugins/misc/async/src/main/java/org/apache/hop/www/xp/PeriodicPipelineStatusUpdateExtensionPoint.java
- plugins/misc/async/src/main/resources/org/apache/hop/www/messages/messages_en_US.properties
- plugins/misc/async/src/main/resources/server.svg
- plugins/misc/pom.xml
- ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
HOP-3524 : Icon log.svg is not correctly contrasted in dark mode
HOP-3450 : Port the Asynchronous Web Service plugins to Hop
> HOP-3524, HOP-3450

- assemblies/plugins/dist/pom.xml
- assemblies/plugins/transforms/filesfromresult/pom.xml
- assemblies/plugins/transforms/filesfromresult/src/assembly/assembly.xml
- assemblies/plugins/transforms/filesfromresult/src/main/resources/version.xml
- assemblies/plugins/transforms/filestoresult/pom.xml
- assemblies/plugins/transforms/filestoresult/src/assembly/assembly.xml
- assemblies/plugins/transforms/filestoresult/src/main/resources/version.xml
- assemblies/plugins/transforms/pom.xml
> HOP-3519: Files from/to result transform missing

- docs/hop-dev-manual/modules/ROOT/pages/hopweb/index.adoc
- docs/hop-tech-manual/modules/ROOT/pages/hop-vs-kettle/hop-vs-kettle.adoc
> [FIX] link to hop-web

- plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/fatjar/FatJarBuilder.java
- plugins/transforms/addsequence/src/main/java/org/apache/hop/pipeline/transforms/addsequence/AddSequenceMeta.java
- plugins/transforms/standardizephonenumber/src/main/java/org/apache/hop/pipeline/transforms/standardizephonenumber/StandardizePhoneNumberMeta.java
- ui/src/main/java/org/apache/hop/ui/core/gui/GuiCompositeWidgets.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopGuiAbstractGraph.java
> fixed some sonar issues

- core/src/main/java/org/apache/hop/core/logging/Metrics.java
- core/src/main/java/org/apache/hop/core/svg/SvgImage.java
- plugins/misc/async/src/main/java/org/apache/hop/www/AsyncRunServlet.java
> fixed the sonar issue that is making builds to fail.

- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/xmljoin/XmlJoin.java
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/xmljoin/XmlJoinMeta.java
> HOP-3530 fixed sourceXmlTransform and targetXmlTransform references

- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/types/JsonExplorerFileTypeHandler.java
> HOP-3544 : Unable to edit json files in file explorer

- docs/hop-user-manual/modules/ROOT/pages/hop-server/index.adoc
- engine/src/main/java/org/apache/hop/server/HopServer.java
- engine/src/main/java/org/apache/hop/www/WebServer.java
- engine/src/test/java/org/apache/hop/server/HopServerTest.java
HOP-3555 : Hop server startup error with SSL
With added support for querying on the command line over https://
> HOP-3555 : Hop server startup error with SSL

- core/src/main/java/org/apache/hop/i18n/GlobalMessages.java
- core/src/main/java/org/apache/hop/i18n/LanguageChoice.java
> HOP-3547: add Beta indicator to languages and switch to EN

- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/file/types/base/BaseExplorerFileType.java
> HOP-1496 : Duplicate files displayed in the file explorer tabs

- docs/hop-user-manual/modules/ROOT/nav.adoc
- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms.adoc
> HOP-3373 : Add transform to query Hop Metadata objects

- integration-tests/mdi/main-0015-apache-tika.hwf
HOP-3373 : Add transform to query Hop Metadata objects (IT timezone fix III) …
> HOP-3373 : Add transform to query Hop Metadata objects (IT timezone fix III)

- plugins/transforms/textfile/src/main/samples/transforms/csvinput-basic.hpl
- plugins/transforms/textfile/src/main/samples/transforms/csvinput-huge-file.hpl
- plugins/transforms/textfile/src/main/samples/transforms/textfileinput-basic.hpl
> HOP-3546: change note and wording on textfile input samples

- plugins/misc/git/src/main/java/org/apache/hop/git/GitGuiPlugin.java
- plugins/transforms/processfiles/src/main/java/org/apache/hop/pipeline/transforms/processfiles/ProcessFiles.java
> HOP-3282, HOP-3521

- docs/hop-dev-manual/modules/ROOT/pages/apache-release/creating-a-release.adoc
- docs/hop-tech-manual/modules/ROOT/pages/docker-container.adoc
- docs/hop-tech-manual/modules/ROOT/pages/hop-vs-kettle/if-you-know-kettle.adoc
- docs/hop-tech-manual/modules/ROOT/pages/hop-vs-kettle/import-kettle-projects.adoc
- docs/hop-user-manual/modules/ROOT/pages/best-practices/index.adoc
- docs/hop-user-manual/modules/ROOT/pages/getting-started/index.adoc
- docs/hop-user-manual/modules/ROOT/pages/index.adoc
- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/combinationlookup.adoc
- ui/src/main/java/org/apache/hop/ui/hopgui/dialog/AboutDialog.java
> HOP-3563 removed references to Incubator and Incubating, except for urls

- ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiAuditDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiFileDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/config/ExplorerPerspectiveConfig.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/config/ExplorerPerspectiveConfigPlugin.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/config/ExplorerPerspectiveConfigSingleton.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/file/types/base/BaseExplorerFileType.java
First stab at it but it seems to be working OK
> HOP-3574 : Implement lazy loading for file browsing

- plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/types/CsvExplorerFileType.java
- plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/types/LogExplorerFileType.java
- plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/types/TextExplorerFileType.java
- plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/types/TextExplorerFileTypeHandler.java
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/types/XmlExplorerFileType.java
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/types/XmlExplorerFileTypeHandler.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/file/types/log/LogExplorerFileType.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/file/types/log/LogExplorerFileTypeHandler.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/file/types/noext/NoExtensionExplorerFileType.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/file/types/noext/NoExtensionExplorerFileTypeHandler.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/file/types/text/BaseTextExplorerFileType.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/file/types/text/BaseTextExplorerFileTypeHandler.java
HOP-3577 : Explorer perspective should allow editing of all text files types
HOP-3578 : Open a couple of special files as editable text
> HOP-3577, HOP-3578

- plugins/misc/projects/src/main/java/org/apache/hop/projects/gui/ProjectsGuiPlugin.java
> HOP-3436 use project base folder as zip root

- plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/output/ParquetOutput.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsoninput/reader/FastJsonReader.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutput/JsonOutput.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutput/JsonOutputData.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutput/JsonOutputDialog.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutput/JsonOutputField.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutput/JsonOutputMeta.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutput.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutputDialog.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutputMeta.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/types/JsonExplorerFileType.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/types/JsonExplorerFileTypeHandler.java
- plugins/transforms/json/src/test/java/org/apache/hop/pipeline/transforms/TransformRowsCollector.java
- plugins/transforms/json/src/test/java/org/apache/hop/pipeline/transforms/jsoninput/JsonInputMetaTest.java
- plugins/transforms/json/src/test/java/org/apache/hop/pipeline/transforms/jsonoutput/JsonOutputTest.java
> HOP-3500, HOP-3550

- README.md
> [GRADUATION] update readme

- Jenkinsfile
> make build work

- plugins/databases/generic/src/test/java/org/apache/hop/databases/generic/GenericDatabaseMetaTest.java
> HOP-3606: Disable Generic Database tests

- Jenkinsfile
- Jenkinsfile.daily
> fix docker images

- docker/Dockerfile
- docker/Dockerfile.web
> HOP-3658: update images to java 11

- Jenkinsfile
- Jenkinsfile.daily
> fix branch name in sonar analysis

- assemblies/core/lib/pom.xml
- assemblies/plugins/engines/beam/pom.xml
- assemblies/plugins/engines/beam/src/assembly/assembly.xml
- assemblies/plugins/tech/aws/pom.xml
- assemblies/plugins/tech/google/src/assembly/assembly.xml
- assemblies/plugins/transforms/json/pom.xml
- core/pom.xml
- docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/getting-started-with-beam.adoc
- docs/hop-user-manual/modules/ROOT/pages/pipeline/pipeline-run-configurations/beam-flink-pipeline-engine.adoc
- docs/hop-user-manual/modules/ROOT/pages/pipeline/pipeline-run-configurations/beam-spark-pipeline-engine.adoc
- plugins/engines/beam/pom.xml
- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/transform/TransformTransform.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/flink/BeamFlinkPipelineRunConfiguration.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/spark/BeamSparkPipelineRunConfiguration.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/HopPipelineMetaToBeamPipelineConverter.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/run/MainBeam.java
- plugins/engines/beam/src/test/java/org/apache/hop/beam/engines/spark/BeamSparkPipelineEngineTest.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/xp/ChangePipelineMetaPriorToExecutionExtensionPoint.java
- plugins/tech/aws/pom.xml
- plugins/transforms/json/pom.xml
- pom.xml
HOP-3599 : Improve documentation of the Apache Flink pipeline configuration
HOP-3600 : Beam Flink Run causes Hadoop classpath error
HOP-3601 : The Flink pipeline run configuration always runs embedded 
HOP-3603 : Update the Beam flink runner to 1.13
HOP-3604 : Spark runner throws CNFE
Trivial changes like typos do not require a JIRA …
> HOP-3599, HOP-3600, HOP-3601, HOP-3603, HOP-3604

- NOTICE
> [NEW YEAR] Update year in NOTICE

- assemblies/plugins/engines/beam/src/assembly/assembly.xml
- assemblies/plugins/tech/cassandra/src/assembly/assembly.xml
- docker/Dockerfile
- docker/resources/load-and-execute.sh
- docker/resources/run.sh
- plugins/transforms/databaselookup/src/main/java/org/apache/hop/pipeline/transforms/databaselookup/DatabaseLookup.java
- plugins/transforms/databaselookup/src/main/java/org/apache/hop/pipeline/transforms/databaselookup/DatabaseLookupData.java
HOP-3661 : Docker: make project and environment name settings optional
HOP-3669 : Database Lookup performance degraded
HOP-3671 : Beam: failing integration test …
> HOP-3661, HOP-3669, HOP-3671

- plugins/transforms/tableinput/src/main/java/org/apache/hop/pipeline/transforms/tableinput/TableInputDialog.java
- plugins/transforms/tableinput/src/main/java/org/apache/hop/pipeline/transforms/tableinput/TableInputMeta.java
- Fix update of TransformIOMeta
- Remove unused method: checkCancel and variable: changedInDialog
> HOP-3586 Unable to remove "Insert data from transform" from TableInput

- integration-tests/transforms/0038-getfilenames-fromfield.hpl
> HOP-3579: fix integration test

- docs/hop-user-manual/modules/ROOT/pages/pipeline/pipeline-run-configurations/beam-dataflow-pipeline-engine.adoc
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/dataflow/BeamDataFlowPipelineRunConfiguration.java
HOP-3675 : Add service account option to the Beam Dataflow pipeline options 
HOP-3676 : Beam Dataflow add tooltips for the various options 
HOP-3677 : Beam Dataflow: add service options
In this case, just format the pull request title like `(DOC) - Add …
> HOP-3675, HOP-3676, HOP-3677

- assemblies/static/src/main/resources/LICENSE
- assemblies/static/src/main/resources/licenses/LICENSE-BOUNCY
- assemblies/static/src/main/resources/licenses/LICENSE-UNRAR
> [RELEASE] Update LICENSE FILE

- docs/hop-user-manual/antora.yml
> [DOCS] fix latest reference

- docs/hop-user-manual/modules/ROOT/pages/how-to-guides/apache-hop-web-services-docker.adoc
> HOP-3667 replace & by &amp; to avoid website build errors

- docs/hop-user-manual/modules/ROOT/pages/how-to-guides/apache-hop-web-services-docker.adoc
> HOP-3667 escape entire url to avoid parsing issues

- docs/hop-user-manual/modules/ROOT/pages/database/databases/oracle.adoc
> HOP-3702: Oracle TIP

- docs/hop-dev-manual/modules/ROOT/pages/setup-dev-environment.adoc
> HOP-3703 Improve the setup-dev-environment doc

- assemblies/plugins/transforms/json/pom.xml
- assemblies/plugins/transforms/json/src/assembly/assembly.xml
- plugins/transforms/json/pom.xml
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsoninput/JsonInput.java
https://issues.apache.org/jira/browse/HOP-3704 …
> [HOP-3704] remove poi dependency from jsoninput

- assemblies/plugins/transforms/xml/pom.xml
- assemblies/plugins/transforms/xml/src/assembly/assembly.xml
- plugins/transforms/xml/pom.xml
- plugins/transforms/xml/src/test/java/org/apache/hop/pipeline/transforms/xml/xsdvalidator/XsdValidatorIntTest.java
https://issues.apache.org/jira/browse/HOP-3705 …
> [HOP-3705] remove poi dependency from xml plugin

- assemblies/plugins/transforms/tika/src/assembly/assembly.xml
- assemblies/static/src/main/resources/LICENSE
(jar name change for poi 5 - but tika uses poi 4) …
> HOP-3706: use correct name of poi-ooxml-schemas jar

- plugins/transforms/addsequence/src/main/resources/org/apache/hop/pipeline/transforms/addsequence/messages/messages_pt_BR.properties
> HOP-1877 - update file translate from pt_BR report

- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineClipboardDelegate.java
> HOP-3242 RuntimeException copying & pasting a step

- plugins/misc/testing/src/main/java/org/apache/hop/testing/DataSetCsvUtil.java
> HOP-1857 Data set: Show error if filename or path is wrong

- Jenkinsfile
- docker/Dockerfile
> HOP-3708: add arm support to hop image

- Jenkinsfile
> HOP-3708: reactivate regular build

- plugins/databases/generic/src/test/java/org/apache/hop/databases/generic/GenericDatabaseMetaTest.java
- plugins/transforms/janino/pom.xml
- plugins/transforms/janino/src/test/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/FieldHelperTest.java
- plugins/transforms/mongodb/src/test/java/org/apache/hop/pipeline/transforms/mongodboutput/MongoDbOutputDataTest.java
- plugins/transforms/rest/src/test/java/org/apache/hop/pipeline/transforms/rest/RestTest.java
- plugins/transforms/tableoutput/src/test/java/org/apache/hop/pipeline/transforms/tableoutput/TableOutputTest.java
HOP-3650 Powermock upgrade
HOP-3655 HOP-3656 mockito matcher fix
HOP-3654 PowermockRunner compatibility + mock Rest object with answer RETURN_DEFAULTS strategy
HOP-3653 mocikto fixed matcher and deprecated assertions fix
HOP-3657 Already working test
> [HOP-3606] Disabled java 11 tests

- assemblies/client/pom.xml
- assemblies/client/src/assembly/assembly.xml
- assemblies/static/src/main/resources/hop-conf.sh
- assemblies/static/src/main/resources/hop-gui.sh
- assemblies/static/src/main/resources/hop-import.sh
- assemblies/static/src/main/resources/hop-run.sh
- assemblies/static/src/main/resources/hop-search.sh
- assemblies/static/src/main/resources/hop-server.sh
- assemblies/static/src/main/resources/hop-translator.sh
> HOP-3708: add arm swt for linux

- assemblies/static/src/main/resources/LICENSE
- pom.xml
https://issues.apache.org/jira/browse/HOP-3722 …
> [HOP-3722] upgrade batik to 1.14

- assemblies/plugins/transforms/excelinput/pom.xml
- assemblies/plugins/transforms/excelwriter/pom.xml
- assemblies/static/src/main/resources/LICENSE
- plugins/transforms/excelinput/pom.xml
- plugins/transforms/excelwriter/pom.xml
- pom.xml
https://issues.apache.org/jira/browse/HOP-3721 …
> [HOP-3721] upgrade xerces to 2.12.2

- docs/hop-user-manual/modules/ROOT/pages/hop-server/rest-api.adoc
> [DOC] update sniffTransform docs

- docs/hop-dev-manual/antora.yml
- docs/hop-tech-manual/antora.yml
- docs/hop-user-manual/antora.yml
> [DOC] version change

- docs/hop-dev-manual/antora.yml
- docs/hop-tech-manual/antora.yml
- docs/hop-user-manual/antora.yml
This reverts commit b8d8115ab591a708fdb3084afd89b791a4aaa442. …
> Revert "[DOC] version change"

- CONTRIBUTING.md
**As https://opensource.guide/ it is best practices to have a CONTRIBUTING.md file, I got the one that we have on the website and I have converted it to .md. I hope it is helpful. :)
If you also click here https://github.com/apache/hop/community you will see that github is pointing out this.**
Trivial changes like typos do not require …
> (Docs) Create CONTRIBUTING.md

- docs/hop-dev-manual/antora.yml
- docs/hop-tech-manual/antora.yml
- docs/hop-user-manual/antora.yml
> [DOC] change version number

- pom.xml
> [HOP-3733] update httpclient due to cve

- assemblies/plugins/databases/postgresql-assemblies/pom.xml
- plugins/databases/postgresql/pom.xml
- plugins/transforms/pgbulkloader/pom.xml
> [HOP-3734] upgrade postgres driver due to security issue

- docs/hop-user-manual/modules/ROOT/pages/hop-server/rest-api.adoc
> [DOC] add Register Pipeline example

- docs/hop-dev-manual/antora.yml
- docs/hop-tech-manual/antora.yml
- docs/hop-user-manual/antora.yml
[DOC] change pre-release version …
> [DOC] change pre-release version

- core/src/main/java/org/apache/hop/core/Const.java
> HOP-3737: fix documentation url for snapshot

- core/pom.xml
- engine/pom.xml
- plugins/misc/git/pom.xml
> [HOP-3733] another reference to old httpclient

- assemblies/core/lib/pom.xml
- core/pom.xml
- pom.xml
> [HOP-3732] standardise on xerces 2.12.2

- Jenkinsfile
> Disable docker Development tag push

- assemblies/debug/pom.xml
- assemblies/lib/pom.xml
- assemblies/static/src/main/resources/LICENSE
> [HOP-3742] upgrade to xmlgraphics-commons 2.7

- assemblies/plugins/misc/git/pom.xml
- core/pom.xml
- engine/pom.xml
- plugins/misc/git/pom.xml
- pom.xml
> HOP-3733 fix stray ref to 4.5.12

- docs/hop-user-manual/modules/ROOT/pages/hop-server/rest-api.adoc
> [DOC] fix typo

- docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/running-the-beam-samples.adoc
> HOP-3748 removed scala, fixed og:description typo

- docs/hop-user-manual/modules/ROOT/pages/installation-configuration.adoc
> HOP-3754 fixed xref: typo

- core/src/test/java/org/apache/hop/core/BlockingQueueCpuLoadTest.java
- engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransform.java
- engine/src/main/java/org/apache/hop/pipeline/transform/DynamicWaitTimes.java
- engine/src/test/java/org/apache/hop/pipeline/transform/DynamicWaitTimesTest.java
Replace [PR-1305](https://github.com/apache/hop/pull/1305).
> HOP-3713 Fixed BlockingRowSet high cpu, support dynamic timeout when get row from InputRowSet

- ui/src/main/java/org/apache/hop/ui/core/vfs/HopVfsFileDialog.java
Reacts like a native dialog box, if a folder is selected, and you select the OK button, you navigate to the folder.
> Hop-3749 HopVfsFileDialog browsing for files and selecting a folder

- assemblies/plugins/transforms/kafka/pom.xml
> HOP-3739: switch to https for maven repository

- docs/hop-user-manual/modules/ROOT/pages/installation-configuration.adoc
> HOP-3754 added Microsoft OpenJDK build as alternative JRE option

- assemblies/plugins/tech/dropbox/pom.xml
- docs/hop-user-manual/modules/ROOT/pages/vfs/dropbox-vfs.adoc
- plugins/tech/dropbox/pom.xml
- plugins/tech/dropbox/src/main/java/org/apache/hop/vfs/dropbox/DropboxFileName.java
- plugins/tech/dropbox/src/main/java/org/apache/hop/vfs/dropbox/DropboxFileNameParser.java
- plugins/tech/dropbox/src/main/java/org/apache/hop/vfs/dropbox/DropboxFileObject.java
- plugins/tech/dropbox/src/main/java/org/apache/hop/vfs/dropbox/DropboxFileProvider.java
- plugins/tech/dropbox/src/main/java/org/apache/hop/vfs/dropbox/config/DropboxConfig.java
- plugins/tech/dropbox/src/main/java/org/apache/hop/vfs/dropbox/config/DropboxConfigSingleton.java
- Upgrade Dropbox API to version 5.0.0
- Better error handling
- Root uri with only 2 slashs Dropbox://
- Fix file upload
> HOP-3756 Dropbox VFS Improvement

- integration-tests/transforms/0041-properties-file-input-invalid-file-required-no.hpl
- integration-tests/transforms/0041-properties-file-input-invalid-file-required-yes.hpl
- integration-tests/transforms/0041-properties-file-input-valid-file.hpl
- integration-tests/transforms/datasets/golden-properties-file.csv
- integration-tests/transforms/files/properties-test.properties
- integration-tests/transforms/main-0041-properties-file-input.hwf
- integration-tests/transforms/metadata/dataset/golden-properties-input.json
- integration-tests/transforms/metadata/unit-test/0041-properties-file-input-valid-file UNIT.json
- plugins/transforms/propertyinput/src/main/java/org/apache/hop/pipeline/transforms/propertyinput/PropertyInput.java
- plugins/transforms/propertyinput/src/main/java/org/apache/hop/pipeline/transforms/propertyinput/PropertyInputMeta.java
- plugins/transforms/propertyinput/src/test/java/org/apache/hop/pipeline/transforms/propertyinput/BasePropertyParsingTest.java
> HOP-3582 : Properties Input always requires a file

- assemblies/static/src/main/resources/hop-conf.sh
- assemblies/static/src/main/resources/hop-gui.sh
- assemblies/static/src/main/resources/hop-import.sh
- assemblies/static/src/main/resources/hop-run.sh
- assemblies/static/src/main/resources/hop-search.sh
- assemblies/static/src/main/resources/hop-server.sh
- assemblies/static/src/main/resources/hop-translator.sh
> HOP-3708: update scripts to avoid bash

- core/src/main/java/org/apache/hop/core/Props.java
- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/metainject.adoc
- engine/src/main/java/org/apache/hop/core/injection/bean/BeanInjector.java
- engine/src/test/java/org/apache/hop/core/injection/MetaAnnotationInjectionTest.java
- plugins/transforms/metainject/src/main/java/org/apache/hop/pipeline/transforms/metainject/MetaInject.java
- rap/src/main/java/org/apache/hop/ui/hopgui/HopWeb.java
- ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
- ui/src/main/java/org/apache/hop/ui/core/dialog/EnterOptionsDialog.java
- ui/src/main/java/org/apache/hop/ui/core/gui/GuiResource.java
- ui/src/main/java/org/apache/hop/ui/core/gui/GuiToolbarWidgets.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopDataOrchestrationPerspective.java
HOP-2864 : Preference settings are reset on startup
HOP-3243 : Error when using metadata injection with Neo4j Output action
HOP-3698 : Environment files seems to not be editable because they are white text over white background
HOP-3746 : Injected pipeline does not contain values specified by variable
[HOP-3761 : Disable dark mode option on non-Windows systems]
is to use the JIRA issue title in the pull request title and in the first …
> HOP-3243, HOP-3746, HOP-2864, HOP-3698, HOP-3761

- plugins/transforms/http/src/main/java/org/apache/hop/pipeline/transforms/http/Http.java
> HOP-3745: fix query parameters in http client

- assemblies/static/src/main/resources/hop-conf.sh
- assemblies/static/src/main/resources/hop-gui.sh
- assemblies/static/src/main/resources/hop-import.sh
- assemblies/static/src/main/resources/hop-run.sh
- assemblies/static/src/main/resources/hop-search.sh
- assemblies/static/src/main/resources/hop-server.sh
- assemblies/static/src/main/resources/hop-translator.sh
> HOP-3763: change java for commands

- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
> HOP-3409 NPE when creating an hop

- ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditor.java
- ui/src/main/resources/org/apache/hop/ui/core/metadata/messages/messages_en_US.properties
> HOP-3214 Check the name of a metadata

- plugins/databases/oracle/src/main/java/org/apache/hop/databases/oracle/OracleDatabaseMeta.java
> HOP-3770: fix object quoting for oracle connections

- ui/src/main/java/org/apache/hop/ui/i18n/editor/Translator.java
* Fix current selected row always drifts when the line number is greater than the count of visible lines
> HOP-3776 Optimized Hop-Translator

- assemblies/static/src/main/resources/hop-server.sh
- docker/resources/load-and-execute.sh
- engine/pom.xml
- engine/src/main/java/org/apache/hop/www/HopServer.java
> HOP-3778: fix argument passing with spaces

- plugins/tech/azure/src/main/java/org/apache/hop/vfs/azure/AzureFileProvider.java
- plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/text/TextFileInputDialog.java
> HOP-3780, HOP-3781

- plugins/transforms/pgbulkloader/src/main/java/org/apache/hop/pipeline/transforms/pgbulkloader/PGBulkLoaderMeta.java
> HOP-3073: fix Postgresql bulkload serialisation

- engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransform.java
Fix small checking condition, it is inconsistent with the comment above
> Fix wrong condition for partition mode of transform

- docs/hop-tech-manual/modules/ROOT/pages/docker-container.adoc
> HOP-3767: update docker documentation

- plugins/transforms/databasejoin/src/main/java/org/apache/hop/pipeline/transforms/databasejoin/DatabaseJoin.java
- plugins/transforms/update/src/main/java/org/apache/hop/pipeline/transforms/update/Update.java
HOP-3785 Update transform: minor cleanup to dispose method
HOP-3786 DatabaseJoin: prepared statement not closed when transform finishes processing
- [ x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/HOP) filed 
- [ x] Each commit in the pull request should have a meaningful subject line and body.
- [x ] Format the pull request title like `[HOP-XXX] - Fixes bug in SessionManager`,
is to use the JIRA issue …
> HOP-3785, HOP-3786

- docs/hop-tech-manual/modules/ROOT/pages/docker-container.adoc
> [DOC] fix xref mistake

- integration-tests/partitioning/main-0006-partitioned-when-stream-lookup-should-fail.hwf
> [IT] : Adjust message to new error message

- docker/integration-tests/integration-tests-mongo.yaml
> [IT] give mongo more time to start

- core/src/main/java/org/apache/hop/core/logging/LogLevel.java
- engine/src/main/java/org/apache/hop/pipeline/Pipeline.java
- engine/src/main/java/org/apache/hop/pipeline/PipelineExecutionConfiguration.java
- engine/src/main/java/org/apache/hop/pipeline/engine/PipelineEngineFactory.java
- engine/src/main/java/org/apache/hop/workflow/WorkflowExecutionConfiguration.java
- engine/src/main/java/org/apache/hop/workflow/engine/WorkflowEngineFactory.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
> HOP-3736 Remember the "Log level" of the last run.

- core/src/main/java/org/apache/hop/core/logging/LogLevel.java
- engine/src/main/java/org/apache/hop/pipeline/Pipeline.java
- engine/src/main/java/org/apache/hop/pipeline/PipelineExecutionConfiguration.java
- engine/src/main/java/org/apache/hop/pipeline/engine/PipelineEngineFactory.java
- engine/src/main/java/org/apache/hop/workflow/WorkflowExecutionConfiguration.java
- engine/src/main/java/org/apache/hop/workflow/engine/WorkflowEngineFactory.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
This reverts commit a1150ce10c2da6dc711fe82aced34d95f5623fd6. …
> Revert "Merge pull request #1390 from gvdutra/HOP-3736"

- plugins/transforms/pipelineexecutor/src/main/java/org/apache/hop/pipeline/transforms/pipelineexecutor/PipelineExecutor.java
- plugins/transforms/pipelineexecutor/src/main/java/org/apache/hop/pipeline/transforms/pipelineexecutor/PipelineExecutorData.java
> Revert HOP-3789

- plugins/tech/cassandra/pom.xml
> [HOP-3812] upgrade cassandra jars due to CVE

- assemblies/plugins/databases/postgresql-assemblies/pom.xml
- assemblies/static/src/main/resources/LICENSE
- plugins/databases/postgresql/pom.xml
- plugins/transforms/pgbulkloader/pom.xml
> [HOP-3813] postgresql 43.3.3

- README.md
> [DOC] update readme

- assemblies/plugins/transforms/excelinput/pom.xml
- assemblies/plugins/transforms/excelwriter/pom.xml
- assemblies/static/src/main/resources/LICENSE
- plugins/transforms/excelinput/pom.xml
- plugins/transforms/excelwriter/pom.xml
> [HOP-3817] poi 5.2.1

- docs/hop-dev-manual/modules/ROOT/pages/apache-release/checking-a-release.adoc
> [DOC] update release check document

- docs/hop-dev-manual/modules/ROOT/pages/apache-release/promoting-a-release.adoc
> [DOC] update release docs

- core/src/main/java/org/apache/hop/core/row/IValueMetaConverter.java
- core/src/main/java/org/apache/hop/core/row/value/ValueMetaConversionException.java
- core/src/test/java/org/apache/hop/core/fileinput/FileInputListTest.java
- core/src/test/java/org/apache/hop/core/parameters/DuplicateParamExceptionTest.java
- core/src/test/java/org/apache/hop/core/parameters/NamedParamsExceptionTest.java
- core/src/test/java/org/apache/hop/core/parameters/UnknownParamExceptionTest.java
- core/src/test/java/org/apache/hop/core/row/value/ValueMetaConverterTest.java
- engine/src/test/java/org/apache/hop/core/util/HopVariablesListTest.java
- plugins/transforms/memgroupby/src/test/java/org/apache/hop/pipeline/transforms/memgroupby/MemoryGroupByDataTest.java
- plugins/transforms/mongodb/src/main/java/org/apache/hop/mongo/wrapper/HopMongoUtilLogger.java
- plugins/transforms/mongodb/src/main/java/org/apache/hop/mongo/wrapper/MongoWrapperClientFactory.java
- plugins/transforms/mongodb/src/main/java/org/apache/hop/mongo/wrapper/field/MongodbInputDiscoverFieldsImpl.java
- plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodbinput/DiscoverFieldsCallback.java
- plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodbinput/MongoDbInputDiscoverFields.java
- plugins/transforms/mongodb/src/test/java/org/apache/hop/mongo/wrapper/HopMongoUtilLoggerTest.java
- plugins/transforms/pgbulkloader/src/test/java/org/apache/hop/pipeline/transforms/pgbulkloader/PGBulkLoaderMetaTest.java
- plugins/transforms/replacestring/src/test/java/org/apache/hop/pipeline/transforms/replacestring/ReplaceStringMetaInjectionTest.java
- plugins/transforms/setvalueconstant/src/test/java/org/apache/hop/pipeline/transforms/setvalueconstant/SetValueConstantMetaInjectionTest.java
- plugins/transforms/xml/src/test/java/org/apache/hop/pipeline/transforms/xml/xmljoin/XmlJoinMetaInjectionTest.java
- ui/src/main/java/org/apache/hop/ui/core/FileDialogOperation.java
- ui/src/main/java/org/apache/hop/ui/core/GetFieldsDialogOperation.java
- ui/src/main/java/org/apache/hop/ui/core/dialog/DetailsDialog.java
- ui/src/main/java/org/apache/hop/ui/core/widget/ColumnsResizer.java
- ui/src/main/java/org/apache/hop/ui/core/widget/text/Format.java
- ui/src/main/java/org/apache/hop/ui/core/widget/text/FormatRule.java
- ui/src/main/java/org/apache/hop/ui/core/widget/text/TextFormatter.java
- ui/src/main/java/org/apache/hop/ui/core/widget/text/UrlFormatRule.java
- ui/src/main/java/org/apache/hop/ui/core/widget/tree/TreeNode.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/ISelectedTransformListener.java
- ui/src/test/java/org/apache/hop/ui/core/widget/text/TextFormatterTest.java
> HOP-3202 Removing unnecessary code comments

- ui/src/main/java/org/apache/hop/ui/i18n/BundleFile.java
Properties don't sort when call store method.
> HOP-3832 Always sort message keys when saving bundle files

- plugins/actions/repeat/src/main/java/org/apache/hop/workflow/actions/repeat/RepeatDialog.java
- plugins/actions/repeat/src/main/resources/org/apache/hop/workflow/actions/repeat/messages/messages_en_US.properties
Add message key: Repeat.LogFileUpdateInterval.Label
> HOP-3846 Fixed wrong label text for log file update interval in RepeatDialog

- plugins/transforms/sqlfileoutput/src/main/java/org/apache/hop/pipeline/transforms/sqlfileoutput/SQLFileOutput.java
Close output file on end of process.
> HOP-3847 SQLFileOutput does not close file

- core/src/test/java/org/apache/hop/core/row/value/ValueMetaBaseLenientStringConversionTest.java
> HOP-3613 testStrToIntStrict

- docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-conf/hop-conf-projects.adoc
> documentation - correction

- docs/hop-user-manual/modules/ROOT/pages/getting-started/hop-download-install.adoc
> [DOC] java 11

- pom.xml
> [HOP-3872] upgrade jackson due to CVE-2020-36518

- docs/hop-dev-manual/modules/ROOT/pages/upgrading-to-20.adoc
If someone can review my very bad English
> HOP-3262 Simplify the APIs of transforms doc

- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/Dom4JUtil.java
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/getxmldata/GetXmlData.java
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/getxmldata/LoopNodesImportProgressDialog.java
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/getxmldata/XmlInputFieldsImportProgressDialog.java
> HOP-3202 fixing sonar vulnerability issue

- plugins/transforms/kafka/src/main/java/org/apache/hop/pipeline/transforms/kafka/producer/KafkaProducerOutputDialog.java
- plugins/transforms/kafka/src/main/java/org/apache/hop/pipeline/transforms/kafka/shared/KafkaDialogHelper.java
> HOP-3864 added null rowmeta checks

- plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/Rest.java
> HOP-3202 Fix Sonar vulnerability issue

- docs/hop-user-manual/modules/ROOT/pages/hop-server/rest-api.adoc
> [DOC] add extra options for pipelineStatus and WorkflowStatus

- core/src/main/java/org/apache/hop/core/Const.java
- docs/hop-user-manual/modules/ROOT/pages/pipeline/pipeline-run-configurations/native-local-pipeline-engine.adoc
- engine/src/main/java/org/apache/hop/pipeline/engines/local/LocalPipelineRunConfiguration.java
- engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransform.java
- engine/src/main/java/org/apache/hop/pipeline/transform/DynamicWaitTimes.java
- engine/src/test/java/org/apache/hop/pipeline/transform/DynamicWaitTimesTest.java
- integration-tests/transforms/metadata/pipeline-run-configuration/local.json
- plugins/transforms/xml/src/test/java/org/apache/hop/pipeline/transforms/xml/addxml/AddXmlTest.java
- ui/src/main/resources/org/apache/hop/ui/pipeline/config/messages/messages_en_US.properties
> HOP-3865: make DynamicWaitTime configurable and lower the default value

- ui/src/main/java/org/apache/hop/ui/pipeline/dialog/PipelinePreviewProgressDialog.java
> HOP-3866 Hop gets frozen in Row Preview window when an exception occours

- plugins/actions/repeat/src/main/samples/actions/repeat_action.hwf
- plugins/actions/repeat/src/main/samples/actions/repeat_child.hpl
> HOP-2723: add missing headers

- plugins/actions/as400command/src/main/java/org/apache/hop/workflow/actions/as400command/ActionAs400CommandDialog.java
- plugins/actions/copyfiles/src/main/java/org/apache/hop/workflow/actions/copyfiles/ActionCopyFilesDialog.java
- plugins/actions/eval/src/main/java/org/apache/hop/workflow/actions/eval/ActionEvalDialog.java
- plugins/actions/folderscompare/src/main/java/org/apache/hop/workflow/actions/folderscompare/ActionFoldersCompareDialog.java
- plugins/actions/mssqlbulkload/src/main/java/org/apache/hop/workflow/actions/mssqlbulkload/ActionMssqlBulkLoadDialog.java
- plugins/tech/avro/src/main/java/org/apache/hop/avro/transforms/avrodecode/AvroDecodeDialog.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/output/Neo4JOutputDialog.java
- plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/output/ParquetOutputDialog.java
- plugins/transforms/abort/src/main/java/org/apache/hop/pipeline/transforms/abort/AbortDialog.java
- plugins/transforms/calculator/src/main/java/org/apache/hop/pipeline/transforms/calculator/CalculatorDialog.java
- plugins/transforms/coalesce/src/main/java/org/apache/hop/pipeline/transforms/coalesce/CoalesceDialog.java
- plugins/transforms/combinationlookup/src/main/java/org/apache/hop/pipeline/transforms/combinationlookup/CombinationLookupDialog.java
- plugins/transforms/dimensionlookup/src/main/java/org/apache/hop/pipeline/transforms/dimensionlookup/DimensionLookupDialog.java
- plugins/transforms/excelinput/src/main/java/org/apache/hop/pipeline/transforms/excelinput/ExcelInputDialog.java
- plugins/transforms/getfilesrowcount/src/main/java/org/apache/hop/pipeline/transforms/getfilesrowcount/GetFilesRowsCountDialog.java
- plugins/transforms/kafka/src/main/java/org/apache/hop/pipeline/transforms/kafka/consumer/KafkaConsumerInputDialog.java
- plugins/transforms/kafka/src/main/java/org/apache/hop/pipeline/transforms/kafka/producer/KafkaProducerOutputDialog.java
- plugins/transforms/mapping/src/main/java/org/apache/hop/pipeline/transforms/mapping/SimpleMappingDialog.java
- plugins/transforms/monetdbbulkloader/src/main/java/org/apache/hop/pipeline/transforms/monetdbbulkloader/MonetDbBulkLoaderDialog.java
- plugins/transforms/multimerge/src/main/java/org/apache/hop/pipeline/transforms/multimerge/MultiMergeJoinDialog.java
- plugins/transforms/pipelineexecutor/src/main/java/org/apache/hop/pipeline/transforms/pipelineexecutor/PipelineExecutorDialog.java
- plugins/transforms/propertyinput/src/main/java/org/apache/hop/pipeline/transforms/propertyinput/PropertyInputDialog.java
- plugins/transforms/splitfieldtorows/src/main/java/org/apache/hop/pipeline/transforms/splitfieldtorows/SplitFieldToRowsDialog.java
- plugins/transforms/standardizephonenumber/src/main/java/org/apache/hop/pipeline/transforms/standardizephonenumber/StandardizePhoneNumberDialog.java
- plugins/transforms/uniquerows/src/main/java/org/apache/hop/pipeline/transforms/uniquerows/UniqueRowsDialog.java
- plugins/transforms/workflowexecutor/src/main/java/org/apache/hop/pipeline/transforms/workflowexecutor/WorkflowExecutorDialog.java
* Fix missing PropsUI.setLook
* ParquetOoutputDialog
* CombinationLookupDialog
* DimensioonLookupDialog
* Fix auto layout in DimensionLookupDialog
* DimensioonLookupDialog
* Left-align grooup panel
* ExeclInputDialog
* Middle-align label
* ActioonMssqlBulkLoadDialog
* PropertyInputDialog
* SplitFieldToRowsDialog
* ... 
* 20 plugins
> HOP-3901 Middle-align label and a few ui issues in action plugins and transform plugins

- docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-encrypt.adoc
> (DOC) - Fix typo in hop-encrypt cli for server

- docs/hop-user-manual/modules/ROOT/pages/hop-tools/hop-encrypt.adoc
> Fix typo in hop-encrypt cli for server

- integration-tests/database/0008-table-input-with-variable.hpl
> [IT] test was incorrect pre-change

- engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineEngine.java
- engine/src/main/java/org/apache/hop/workflow/engines/remote/RemoteWorkflowEngine.java
- [X ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/HOP) filed 
- [X ] Each commit in the pull request should have a meaningful subject line and body.
- [X ] Format the pull request title like `[HOP-XXX] - Fixes bug in SessionManager`,
- [X ] Write a pull request description that is detailed enough to …
> [HOP-2945] added parsing of parameters from GUI to executionConfigure for Remote Execution Pipeline Engine

- engine/src/main/java/org/apache/hop/workflow/engines/remote/RemoteWorkflowEngine.java
- [X ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/HOP) filed 
- [X ] Each commit in the pull request should have a meaningful subject line and body.
- [X ] Format the pull request title like `[HOP-XXX] - Fixes bug in SessionManager`,
- [X ] Write a pull request description that is detailed enough to …
> [HOP-3228] refactored original fix as it set all variables as parameters

- integration-tests/http/main-0006-https-trustore.hwf
> HOP-3589: incorrect hop in integration test

- assemblies/lib/pom.xml
- core/src/main/java/org/apache/hop/core/vfs/HopVfs.java
> HOP-3906, HOP-3930 add VFS support for SFTP and HDFS

- docs/hop-user-manual/modules/ROOT/pages/installation-configuration.adoc
> (DOC) Change installation-configuration page from java 8 to java 11

- assemblies/lib/pom.xml
- core/src/main/java/org/apache/hop/core/vfs/HopVfs.java
This reverts commit 12fd70ac1379bfd0fa173283f067d80eff7575e4. …
> Revert "HOP-3906: Add hdfs support to hop"

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/avro-decode.adoc
- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/avro-encode.adoc
> [DOC] Fix formatting of docs

- assemblies/plugins/tech/azure/pom.xml
- assemblies/plugins/transforms/json/pom.xml
- assemblies/plugins/transforms/json/src/assembly/assembly.xml
> HOP-3837, HOP-3839, HOP-3840, HOP-3932

- engine/src/main/java/org/apache/hop/www/WebServer.java
> HOP-3940: fix Hop Server

- assemblies/plugins/tech/cassandra/pom.xml
> HOP-3954: downgrade metrics-* dependencies

- docs/hop-user-manual/modules/ROOT/nav.adoc
> [DOC] add formula to index

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/avro-file-output.adoc
> [DOC] small avro output doc update

- assemblies/core/lib/pom.xml
- assemblies/lib/pom.xml
- engine/pom.xml
- integration-tests/http/0007-rest-client-post.hpl
- integration-tests/http/0008-rest-client-put.hpl
- integration-tests/http/0009-rest-client-delete.hpl
- integration-tests/http/0010-rest-client-head.hpl
- integration-tests/http/0011-rest-client-options.hpl
- integration-tests/http/0012-rest-client-patch.hpl
- integration-tests/http/main-0007-rest-client-post.hwf
- integration-tests/http/main-0008-rest-client-put.hwf
- integration-tests/http/main-0009-rest-client-delete.hwf
- integration-tests/http/main-0010-rest-client-head.hwf
- integration-tests/http/main-0011-rest-client-options.hwf
- integration-tests/http/main-0012-rest-client-patch.hwf
- plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/Rest.java
> HOP-3956: fix patch method and add tests

- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/pipeline/meta/PipelineLog.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/pipeline/meta/PipelineLogEditor.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/pipeline/meta/PipelineToLogLocation.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/pipeline/xp/PipelineStartLoggingXp.java
- plugins/misc/reflection/src/main/resources/org/apache/hop/reflection/pipeline/meta/messages/messages_en_US.properties
> HOP-3926 added support for selected pipelines to log

- docs/hop-user-manual/modules/ROOT/nav.adoc
- docs/hop-user-manual/modules/ROOT/pages/supported-jvms.adoc
> HOP-3897 (DOC) New page with supported and unsupported JVMs

- assemblies/plugins/dist/pom.xml
- assemblies/plugins/transforms/formula/src/assembly/assembly.xml
- assemblies/plugins/transforms/pom.xml
> HOP-3480: fix assembly

- integration-tests/http/0010-rest-client-head.hpl
> HOP-3956: fix head test

- plugins/transforms/pom.xml
> HOP-3480 - re-added formula module

- assemblies/static/src/main/resources/LICENSE
> [RELEASE] update included library licenses

- Jenkinsfile.daily
> HOP-3946: add sh step

- Jenkinsfile.daily
> HOP-3946: switch to single quotes as suggested by Jenkins

- engine/src/main/java/org/apache/hop/run/HopRun.java
> HOP-3937: incorrect exit code on pipelines when using Abort transform

- assemblies/static/src/main/resources/hop-encrypt.sh
> HOP-3995 updated classpath

- docs/hop-user-manual/modules/ROOT/pages/installation-configuration.adoc
- docs/hop-user-manual/modules/ROOT/pages/snippets/variables/hop-config-folder.adoc
> HOP-3999 added Hop upgrade instructions

- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/transform/TransformBatchTransform.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/transform/TransformTransform.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/BeamPipelineEngine.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/HopPipelineExecutionOptions.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/HopPipelineMetaToBeamPipelineConverter.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/util/BeamConst.java
> HOP-4002 Fix HopRun's level option don't work in beam engine

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/xmloutput.adoc
> [DOC] fix documentation

- ui/src/main/java/org/apache/hop/ui/core/database/dialog/DatabaseExplorerDialog.java
HOP-3250 Schema name incorrectly set from Database Explorer
HOP-3966 JDBC Clickhouse Retrieving Database Metadata goes wrong
If this is your first contribution, …
> HOP-3966, HOP-3250

- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/cypher/CypherData.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/gencsv/GenerateCsvData.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/graph/GraphOutputData.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/importer/ImporterData.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/output/Neo4JOutputData.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/split/SplitGraphData.java
- plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/input/ParquetInputData.java
- plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/output/ParquetOutputData.java
- plugins/transforms/detectemptystream/src/main/java/org/apache/hop/pipeline/transforms/detectemptystream/DetectEmptyStreamData.java
- plugins/transforms/detectlastrow/src/main/java/org/apache/hop/pipeline/transforms/detectlastrow/DetectLastRowData.java
- plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodboutput/MongoDbOutputData.java
- plugins/transforms/reservoirsampling/src/main/java/org/apache/hop/pipeline/transforms/reservoirsampling/ReservoirSamplingData.java
- plugins/transforms/rowsfromresult/src/main/java/org/apache/hop/pipeline/transforms/recordsfromstream/RecordsFromStreamData.java
- plugins/transforms/selectvalues/src/main/java/org/apache/hop/pipeline/transforms/selectvalues/SelectValuesData.java
- plugins/transforms/serverstatus/src/main/java/org/apache/hop/pipeline/transforms/serverstatus/GetServerStatusData.java
- plugins/transforms/setvalueconstant/src/main/java/org/apache/hop/pipeline/transforms/setvalueconstant/SetValueConstantData.java
- plugins/transforms/splunk/src/main/java/org/apache/hop/pipeline/transforms/splunkinput/SplunkInputData.java
Serious bug introduced in 2.0 with [HOP-3262](https://issues.apache.org/jira/browse/HOP-3262)
The class that extends BaseTransformDate needs a public constructor.
> Hop-4006, Hop-4007

- core/src/main/java/org/apache/hop/core/Const.java
- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/jsoninput.adoc
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsoninput/reader/FastJsonReader.java
- plugins/transforms/json/src/test/java/org/apache/hop/pipeline/transforms/jsoninput/JsonInputTest.java
- plugins/transforms/json/src/test/java/org/apache/hop/pipeline/transforms/jsoninput/reader/FastJsonReaderTest.java
HOP-3991 JSON input step output depends on parsing order
HOP-3992 JSON input step loses row with null value
If this is your first contribution, you have to read …
> HOP-3991, HOP-3992

- ui/src/main/java/org/apache/hop/ui/core/gui/GuiResource.java
Works well with SWT, if someone can test with RAP it should fix the error
> HOP-4015 RAP need a device to create Color

- assemblies/plugins/actions/getpop/pom.xml
- assemblies/plugins/actions/getpop/src/assembly/assembly.xml
- assemblies/plugins/actions/mail/pom.xml
- assemblies/plugins/actions/mail/src/assembly/assembly.xml
- assemblies/plugins/tech/parquet/src/assembly/assembly.xml
- assemblies/plugins/transforms/mail/pom.xml
- assemblies/plugins/transforms/mailinput/pom.xml
- assemblies/plugins/transforms/mailinput/src/assembly/assembly.xml
- assemblies/plugins/transforms/tika/src/assembly/assembly.xml
- plugins/actions/getpop/pom.xml
- plugins/actions/mail/pom.xml
- plugins/transforms/mail/pom.xml
- plugins/transforms/mailinput/pom.xml
> HOP-4014: remove activation-api from distribution bundles

- assemblies/plugins/transforms/mongodb/pom.xml
- plugins/transforms/mongodb/pom.xml
- plugins/transforms/uniquerows/src/main/java/org/apache/hop/pipeline/transforms/uniquerows/UniqueRowsDialog.java
> HOP-4011,HOP-4019

- docs/hop-user-manual/modules/ROOT/nav.adoc
> [DOC] add Beam Kinesis to index

- plugins/misc/async/src/main/java/org/apache/hop/www/async/AsyncWebServiceEditor.java
- plugins/misc/reflection/src/main/java/org/apache/hop/reflection/reader/meta/LogReaderEditor.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/model/GraphModelEditor.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/shared/NeoConnectionEditor.java
- ui/src/main/java/org/apache/hop/ui/core/bus/HopGuiEvents.java
- ui/src/main/java/org/apache/hop/ui/core/database/DatabaseMetaEditor.java
- ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditor.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java
> HOP-4020: HopGuiEvents for metadata are never triggered

- plugins/actions/snowflake/src/main/java/org/apache/hop/workflow/actions/snowflake/WarehouseManager.java
- plugins/actions/snowflake/src/main/java/org/apache/hop/workflow/actions/snowflake/WarehouseManagerDialog.java
- plugins/transforms/snowflake/src/main/java/org/apache/hop/pipeline/transforms/snowflake/bulkloader/SnowflakeBulkLoader.java
- plugins/transforms/snowflake/src/main/java/org/apache/hop/pipeline/transforms/snowflake/bulkloader/SnowflakeBulkLoaderData.java
- plugins/transforms/snowflake/src/main/java/org/apache/hop/pipeline/transforms/snowflake/bulkloader/SnowflakeBulkLoaderDialog.java
- plugins/transforms/snowflake/src/main/java/org/apache/hop/pipeline/transforms/snowflake/bulkloader/SnowflakeBulkLoaderField.java
- plugins/transforms/snowflake/src/main/java/org/apache/hop/pipeline/transforms/snowflake/bulkloader/SnowflakeBulkLoaderMeta.java
> HOP-4003: sonar cleanup

- docs/hop-user-manual/modules/ROOT/pages/workflow/actions/addresultfilenames.adoc
Move `Copy previous results to?` to its own row
> (DOC) fix table

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/xsdvalidator.adoc
> (DOC) make ref from transform to action

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/xsdvalidator.adoc
- docs/hop-user-manual/modules/ROOT/pages/workflow/actions/xsdvalidator.adoc
> [DOC] fix references

- docs/hop-user-manual/modules/ROOT/pages/workflow/actions/workflow.adoc
A couple more fixes to workflow/actions/workflow (see #1563)
- @hansva how to fix the bullets in `You can do this by:` to appear as list items? Maybe that's impossible in a table cell?
> (DOC) more fixes in workflow/actions/workflow

- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
- ui/src/main/resources/org/apache/hop/ui/hopgui/file/workflow/messages/messages_en_US.properties
> HOP-3936: add missing translation

- docker/integration-tests/integration-tests-xml.yaml
- docker/integration-tests/resource/xml/test.xsd
- integration-tests/xml/0002-xsd-validator-test.hpl
- integration-tests/xml/datasets/golden-xsd-validator.csv
- integration-tests/xml/files/wrong-xsd-test.xml
- integration-tests/xml/files/xsd-test.xml
- integration-tests/xml/main-0002-xsd-validator-test.hwf
- integration-tests/xml/metadata/dataset/golden-xsd-validator.json
- integration-tests/xml/metadata/unit-test/0002-xsd-validator-test UNIT.json
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/xsdvalidator/XsdValidator.java
> HOP-4037: NPE when using XSD validator transform with empty XSD file name

- plugins/transforms/execprocess/src/main/java/org/apache/hop/pipeline/transforms/execprocess/ExecProcess.java
- plugins/transforms/execprocess/src/main/resources/org/apache/hop/pipeline/transforms/execprocess/messages/messages_en_US.properties
- plugins/transforms/execprocess/src/main/resources/org/apache/hop/pipeline/transforms/execprocess/messages/messages_zh_CN.properties
- plugins/transforms/execprocess/src/test/java/org/apache/hop/pipeline/transforms/execprocess/ExecProcessTest.java
Capture out/err streams of the process after call waitFor method, or async
> HOP-4030 Kill the exec process when stop ExecProcess transform

- assemblies/web/pom.xml
- pom.xml
- rap/pom.xml
> HOP-4050: update SWT and RAP version

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/http.adoc
> (DOC) - HTTP CLIENT Documentation Table Typo Fix

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/http.adoc
> [DOC] update http.adoc incorrect table lay-out

- plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/Formula.java
- plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/util/FormulaParser.java
> HOP-4047, HOP-4044

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/abort.adoc
> [DOC] change icon size

- docs/hop-user-manual/modules/ROOT/pages/hop-server/index.adoc
> HOP-4062 add Jetty DEBUG options to Hop Server docs

- plugins/actions/abort/src/main/java/org/apache/hop/workflow/actions/abort/ActionAbort.java
- plugins/actions/abort/src/main/java/org/apache/hop/workflow/actions/abort/ActionAbortDialog.java
- plugins/actions/abort/src/main/resources/org/apache/hop/workflow/actions/abort/messages/messages_en_US.properties
- plugins/actions/abort/src/main/resources/org/apache/hop/workflow/actions/abort/messages/messages_zh_CN.properties
- plugins/actions/abort/src/test/java/org/apache/hop/workflow/actions/abort/WorkflowActionAbortLoadSaveTest.java
<del>Only support three level: Error, Minimal and Basic</del>
> [HOP-3921] - Support log level of the message in Abort action

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/salesforce-fields.adoc
> [SYNTAX] colon instead of period in external id syntax

- ui/src/main/java/org/apache/hop/ui/core/widget/ComboVar.java
- ui/src/main/java/org/apache/hop/ui/core/widget/ControlSpaceKeyAdapter.java
- ui/src/main/java/org/apache/hop/ui/core/widget/Tip.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopGuiAbstractGraph.java
> HOP-4048, HOP-4066, HOP-4067

- ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
> HOP-4068: switch background color for Group widget

- docs/hop-user-manual/modules/ROOT/pages/database/databases/mssqlnative.adoc
Added documentation for getting MS SQL integrated security working for Windows users by placing the right DLL in a spot that works. …
> Add information about using Integrated Security

- assemblies/core/lib/pom.xml
- assemblies/lib/pom.xml
- assemblies/plugins/engines/beam/pom.xml
- assemblies/plugins/engines/beam/src/assembly/assembly.xml
- assemblies/plugins/tech/parquet/src/assembly/assembly.xml
- engine/pom.xml
- engine/src/main/java/org/apache/hop/www/HopServer.java
- engine/src/main/java/org/apache/hop/www/WebServer.java
- engine/src/test/java/org/apache/hop/www/HopServerTest.java
- integration-tests/gcp/0004-rest-client-get.hpl
- integration-tests/gcp/main-0004-rest-client.hwf
- integration-tests/http/0001-http-post-test-headers.hpl
- integration-tests/http/0012-rest-client-patch.hpl
- plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/Rest.java
- plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/RestData.java
- plugins/transforms/rest/src/test/java/org/apache/hop/pipeline/transforms/rest/RestTest.java
> HOP-4059: update to jersey 2.x, cleanup and integration test

- assemblies/plugins/transforms/excelinput/src/assembly/assembly.xml
- assemblies/plugins/transforms/excelwriter/src/assembly/assembly.xml
- docker/integration-tests/integration-tests-http.yaml
- docker/integration-tests/resource/http/CastleMockProject.xml
- engine/src/main/java/org/apache/hop/workflow/WorkflowMeta.java
- integration-tests/http/0013-webservice.hpl
- integration-tests/http/dev-env-config.json
- integration-tests/http/main-0013-webservice.hwf
- plugins/transforms/webservices/src/main/java/org/apache/hop/pipeline/transforms/webservices/WebService.java
> HOP-4083, HOP-4085

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/textfileoutput.adoc
updated the append doc
If your …
> HOP-4092 Update Text File Output append in documentation

- ui/src/main/java/org/apache/hop/ui/workflow/dialog/WorkflowDialog.java
> HOP-HOP-4082: Get rid of empty "Settings" tab or fill it

- plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodbdelete/MongoDbDelete.java
Did some cleanup in the code smells but not all.
Replace StringBuffer with StringBuilder
Adding accessor for a private variable
Removed condition for expression always evaluating to true.
Replaced deprecated usage of JSON with BasicDBObject
In this case, …
> Cleanup sonar bugs in MongoDbDelete

- plugins/actions/snowflake/src/main/java/org/apache/hop/workflow/actions/snowflake/WarehouseManagerDialog.java
- plugins/transforms/snowflake/src/main/java/org/apache/hop/pipeline/transforms/snowflake/bulkloader/SnowflakeBulkLoader.java
- plugins/transforms/snowflake/src/main/java/org/apache/hop/pipeline/transforms/snowflake/bulkloader/SnowflakeBulkLoaderDialog.java
Adding try resource to sonar reported files. …
> Fixing Sonar Blockers in plugins/transforms/snowflake

- .gitpod.Dockerfile
- .gitpod.yml
> HOP-4133 update gitpod files

- docs/hop-user-manual/modules/ROOT/nav.adoc
- docs/hop-user-manual/modules/ROOT/pages/how-to-guides/joins-lookups.adoc
> HOP-4123 initial version of joins and lookups page

- docs/hop-dev-manual/modules/ROOT/pages/setup-dev-environment.adoc
> HOP-4133 updated hyperlink

- integration-tests/transforms/main-0011-calculator.hwf
- plugins/transforms/calculator/src/main/java/org/apache/hop/pipeline/transforms/calculator/Calculator.java
- plugins/transforms/calculator/src/main/java/org/apache/hop/pipeline/transforms/calculator/CalculatorMetaFunction.java
- plugins/transforms/calculator/src/main/resources/org/apache/hop/pipeline/transforms/calculator/messages/messages_en_US.properties
> HOP-4126 added base64 encode and decode to calculator transform

- docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/postgresbulkloader.adoc
- plugins/databases/mysql/src/main/java/org/apache/hop/databases/mysql/MySqlDatabaseMeta.java
> HOP-4136: add zeroDateTimeBehaviorValue to mysql

- plugins/engines/beam/src/main/java/org/apache/hop/beam/run/MainBeam.java
> HOP-4143: add named parameters

- integration-tests/transforms/0011-calculator-base64.hpl
- integration-tests/transforms/datasets/golden-calculator-base64.csv
- integration-tests/transforms/metadata/dataset/golden-calculator-base64.json
> HOP-4126 added timezone to encoded/decoded base64 date

- ui/src/main/java/org/apache/hop/ui/core/widget/ControlSpaceKeyAdapter.java
FillLayout can't be used with Tip on the same shell.
Replace it with FormLayout with full size.
> HOP-4155 The layout of the TextVar proposal is broken

- integration-tests/transforms/0011-calculator-base64.hpl
> HOP-4126 add time zone to date before encode/decode

- integration-tests/transforms/0011-calculator-base64.hpl
- integration-tests/transforms/datasets/golden-calculator-base64.csv
- integration-tests/transforms/metadata/dataset/golden-calculator-base64.json
- integration-tests/transforms/metadata/unit-test/0011-calculator-base64 UNIT.json
> HOP-4126 removed date from golden data set

- plugins/tech/avro/src/main/java/org/apache/hop/avro/transforms/avrodecode/AvroDecode.java
HOP-4189: Add handling of float values in avro union type. …
> HOP-4189 Avro decode fails to handle float values in union type

- plugins/transforms/getfilenames/src/main/java/org/apache/hop/pipeline/transforms/getfilenames/GetFileNames.java
Adds a recursive call to processRow() so that the method is called again until an output row has been generated for each matched file.
Tested with the local runner and the Beam-Direct runner.
(I'm not sure it's actually OK to use recursion here, but at first glance it does get the job done.)
Trivial changes like typos do not require a …
> HOP-4191 - Fix for "Get file names" bug on Beam

- engine/src/main/java/org/apache/hop/workflow/Workflow.java
Code hardening fix for integration tests
> HOP-4024 : Create a new execution information platform (IT)

- assemblies/plugins/transforms/excel/pom.xml
- assemblies/plugins/transforms/formula/pom.xml
- assemblies/plugins/transforms/tika/pom.xml
- assemblies/static/src/main/resources/LICENSE
- plugins/transforms/excel/pom.xml
- plugins/transforms/formula/pom.xml
> [HOP-4215] - upgrade to POI 5.2.3

- ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
- ui/src/main/java/org/apache/hop/ui/pipeline/transform/BaseTransformDialog.java
> HOP-4216 Save the properties of the shells in the default name space

- assemblies/plugins/transforms/formula/src/assembly/assembly.xml
- integration-tests/http/0014-rest-client-with-proxy.hpl
- integration-tests/http/0015-http-client-with-proxy.hpl
- integration-tests/transforms/0042-formula-information.hpl
- integration-tests/transforms/datasets/golden-formula-information.csv
- integration-tests/transforms/metadata/dataset/golden-formula-information.json
> [IT] change domain from proxy tests, HOP-4217

- docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/getting-started-with-beam.adoc
- engine/src/main/java/org/apache/hop/pipeline/SingleThreadedPipelineExecutor.java
- integration-tests/gcp/0007-single-thread.hpl
- integration-tests/gcp/metadata/unit-test/0007-single-thread-validation UNIT.json
- plugins/engines/beam/pom.xml
- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/transform/TransformFn.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/transform/TransformTransform.java
- plugins/transforms/excel/src/main/java/org/apache/hop/pipeline/transforms/excelinput/poi/PoiWorkbook.java
- plugins/transforms/excel/src/main/java/org/apache/hop/pipeline/transforms/excelinput/staxpoi/StaxPoiWorkbook.java
- plugins/transforms/excel/src/main/java/org/apache/hop/pipeline/transforms/excelwriter/ExcelWriterTransform.java
HOP-4084 : Transform doesn't release Excel file
HOP-4172 : Forcing to a single thread in Beam doesn't work (fix, IT)
> HOP-4084, HOP-4172 

- core/src/main/java/org/apache/hop/core/Const.java
- plugins/tech/avro/src/main/java/org/apache/hop/avro/transforms/avrodecode/AvroDecodeDialog.java
- plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/input/ParquetInputDialog.java
- plugins/transforms/datagrid/src/main/java/org/apache/hop/pipeline/transforms/datagrid/DataGridDialog.java
- plugins/transforms/fieldsplitter/src/main/java/org/apache/hop/pipeline/transforms/fieldsplitter/FieldSplitterDialog.java
- plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsoninput/JsonInputDialog.java
- plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInputDialog.java
- plugins/transforms/loadfileinput/src/main/java/org/apache/hop/pipeline/transforms/loadfileinput/LoadFileInputDialog.java
- plugins/transforms/regexeval/src/main/java/org/apache/hop/pipeline/transforms/regexeval/RegexEvalDialog.java
- plugins/transforms/salesforce/src/main/java/org/apache/hop/pipeline/transforms/salesforceinput/SalesforceInputDialog.java
- plugins/transforms/sasinput/src/main/java/org/apache/hop/pipeline/transforms/sasinput/SasInputDialog.java
- plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/csvinput/CsvInputDialog.java
- plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/textfileoutput/TextFileOutputDialog.java
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/addxml/AddXmlDialog.java
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/getxmldata/GetXmlDataDialog.java
- plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/xmloutput/XmlOutputDialog.java
- plugins/transforms/yamlinput/src/main/java/org/apache/hop/pipeline/transforms/yamlinput/YamlInputDialog.java
- ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
… shows all formatting options …
> HOP-4208, HOP-4222

- ui/src/main/java/org/apache/hop/ui/core/dialog/ContextDialog.java
Fix the context dialog position to be opened on the same monitor HOP Gui is running
- [ x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/HOP) filed 
- [ x ] Each commit in the pull request should have a meaningful subject line and body.
- [ x ] Format the pull request title like `[HOP-XXX] - Fixes bug in SessionManager`,
is to use the JIRA issue title in the pull request title and in the first line of the …
> [HOP-4241] - Fixes context dialog position

- core/src/main/java/org/apache/hop/core/gui/plugin/GuiElementType.java
- core/src/main/java/org/apache/hop/core/gui/plugin/GuiElements.java
- core/src/main/java/org/apache/hop/core/gui/plugin/GuiRegistry.java
- engine/src/main/java/org/apache/hop/execution/IExecutionInfoLocation.java
- engine/src/main/java/org/apache/hop/execution/local/FileExecutionInfoLocation.java
- engine/src/main/java/org/apache/hop/execution/remote/RemoteExecutionInfoLocation.java
- engine/src/main/java/org/apache/hop/www/DeleteExecutionInfoServlet.java
- integration-tests/beam_directrunner/0007-group-by-validation.hpl
- integration-tests/beam_directrunner/0007-group-by.hpl
- integration-tests/beam_directrunner/datasets/0007-group-by-golden.csv
- integration-tests/beam_directrunner/main-0007-group-by.hwf
- integration-tests/beam_directrunner/metadata/dataset/0007-group-by-golden.json
- integration-tests/beam_directrunner/metadata/unit-test/0007-group-by-validation UNIT.json
- integration-tests/gcp/main-0003-input-bigtable.hwf
- plugins/engines/beam/src/main/java/org/apache/hop/beam/transforms/bigtable/BigtableRowToHopRowFn.java
- plugins/misc/testing/src/main/java/org/apache/hop/testing/gui/TestingGuiPlugin.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/execution/NeoExecutionInfoLocation.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/execution/builder/CypherDeleteBuilder.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/execution/builder/CypherMatchBuilder.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/execution/builder/CypherRelationshipBuilder.java
- plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/execution/messages/messages_en_US.properties
- ui/src/main/java/org/apache/hop/ui/core/gui/GuiCompositeWidgets.java
- ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiEnvironment.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowClipboardDelegate.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/ExecutionPerspective.java
- ui/src/main/java/org/apache/hop/ui/pipeline/config/PipelineRunConfigurationEditor.java
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/execution/messages/messages_en_US.properties
HOP-4024 : Create a new execution information platform (Neo4j Executes relationship goes in wrong direction, delete, bug fixes, neo4j indexes)
HOP-4248 Beam BigTable Input throws Index out of bounds error (IT, also for Group By)
HOP-4247 : HOP-GUI - Unit test remains active after detaching, you have to close and reopen the pipeline to really detach.
> HOP-4024, HOP-4248, HOP-4247

- ui/src/main/java/org/apache/hop/ui/execution/ExecutionInfoLocationEditor.java
> HOP-4252 fixed execution information location editor width, height

- plugins/transforms/metainject/src/main/java/org/apache/hop/pipeline/transforms/metainject/MetaInject.java
MetaInject transform:
* Exit meta-injection when no input rows are received
* Sends the rows asynchronously for RowProducer
> HOP-4232, HOP-4255

- docs/hop-user-manual/modules/ROOT/pages/metadata-types/neo4j/neo4j-location-type.adoc
- ui/src/main/java/org/apache/hop/ui/core/gui/GuiMenuWidgets.java
- ui/src/main/java/org/apache/hop/ui/core/gui/GuiToolbarWidgets.java
HOP-4024 : Create a new execution information platform (doc fix)
HOP-4269 : Hop Gui Metadata perspective doesn't allow saving (attempt 1: minimize change)
> HOP-4024 doc fix

- docs/hop-user-manual/modules/ROOT/pages/metadata-types/execution-information-location.adoc
> HOP-4024 : Create a new execution information platform (doc fix)

- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/fn/HopToBQTableRowFn.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/transform/BeamBQOutputTransform.java
> HOP-4199 - Handle timestamp values in BigQueryOutputTransform

- assemblies/static/src/main/resources/hop-gui.bat
- assemblies/static/src/main/resources/hop-run.bat
- assemblies/static/src/main/resources/hop-server.bat
- docker/integration-tests/integration-tests-hop_server.yaml
- docs/hop-user-manual/modules/ROOT/pages/protips/index.adoc
- docs/hop-user-manual/modules/ROOT/pages/snippets/variables/hop-windows-shell-encoding.adoc
- engine/src/main/java/org/apache/hop/www/BaseHttpServlet.java
- integration-tests/hop_server/0002-test-json-webservice.hpl
- integration-tests/hop_server/main-0002-test-json-webservice.hwf
- integration-tests/hop_server/metadata/web-service/testService.json
- integration-tests/hop_server/testService-pipeline.hpl
- integration-tests/http/disabled-main-0014-rest-client-with-proxy.hwf
- integration-tests/http/disabled-main-0015-http-client-with-proxy.hwf
> HOP-4210, HOP-4236

- engine/src/main/java/org/apache/hop/pipeline/SingleThreadedPipelineExecutor.java
> Fix typo in log message

- engine/src/main/java/org/apache/hop/execution/ExecutionDataBuilder.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/fn/HopToStringFn.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/shared/NeoConnectionUtils.java
- plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/output/Neo4JOutput.java
- plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/csvinput/CsvInputDialog.java
- plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/csvinput/messages/messages_en_US.properties
- ui/src/main/java/org/apache/hop/ui/pipeline/transform/common/IGetFieldsCapableTransformDialog.java
HOP-4055 : Neo4j Output : perform sanity checks before running
HOP-4276 : Neo4j Ouptut : creating indexes doesn't work anymore
HOP-4273 : CSV Input : Get Fields button shows useless dialog
HOP-4274 : NPE thrown in stopped pipeline
HOP-4277 : CSV Input: explain strengths and limitations to user
HOP-4279 : Beam File Output doesn't use enclosure in output file
> HOP-4055, HOP-4273, HOP-4274, HOP-4276, HOP-4277, HOP-4279

- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/fn/BQSchemaAndRecordToHopFn.java
> HOP-4458 - Handle timestamps in BigQueryInput

- plugins/actions/shell/src/main/java/org/apache/hop/workflow/actions/shell/ActionShellDialog.java
> HOP-4443 : Align controls in ActionShellDialog

- ui/src/main/java/org/apache/hop/ui/core/gui/GuiResource.java
HOP-4469 : Hop GUI runs out of handles
> HOP-4469 : Hop GUI runs out of handles

- docs/hop-dev-manual/modules/ROOT/pages/hopweb/index.adoc
Some refactoring, fixing webapps folder and adding export to use variables in child process
If this is your first contribution, you have to read the …
> (DOC) - Hop Web Tomcat Configuration

- docs/hop-user-manual/modules/ROOT/pages/pipeline/metadata-injection.adoc
> HOP-4478: add missing transforms

- plugins/transforms/execprocess/src/test/java/org/apache/hop/pipeline/transforms/execprocess/ExecProcessTest.java
On windows, timeout command does not support output redirection.
so pause command is used to simulate sleep.
> HOP-4461 Unit test fails during build on Windows 10

- core/src/main/java/org/apache/hop/core/extension/HopExtensionPoint.java
- engine/src/main/java/org/apache/hop/pipeline/Pipeline.java
- engine/src/main/java/org/apache/hop/pipeline/engine/IPipelineEngine.java
- engine/src/main/java/org/apache/hop/pipeline/engines/local/LocalPipelineEngine.java
- engine/src/main/java/org/apache/hop/pipeline/engines/localsingle/LocalSinglePipelineEngine.java
- engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineEngine.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/core/transform/TransformFn.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/BeamPipelineEngine.java
- ui/src/main/java/org/apache/hop/ui/core/dialog/ContextDialog.java
HOP-4480 : Beam pipeline status description is not set to finished
HOP-4483 : Beam: not being able to send sample data should not be fatal
HOP-4469 : Hop GUI runs out of handles (context dialog fix)
> HOP-4469, HOP-4480, HOP-4483

- core/src/main/java/org/apache/hop/metadata/serializer/multi/MultiMetadataProvider.java
- core/src/test/java/org/apache/hop/metadata/serializer/multi/MultiMetadataProviderTest.java
- docker/Dockerfile
- docker/resources/dev-build-local-image.sh
- docker/resources/load-and-execute.sh
- docs/hop-tech-manual/modules/ROOT/pages/docker-container.adoc
- docs/hop-user-manual/modules/ROOT/pages/hop-run/index.adoc
- engine/src/main/java/org/apache/hop/core/metadata/SerializableMetadataProvider.java
- engine/src/main/java/org/apache/hop/run/HopRun.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/BeamPipelineEngine.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/spark/BeamSparkPipelineRunConfiguration.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/run/MainBeam.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/BaseExecutionViewer.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/PipelineExecutionViewer.java
- ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/WorkflowExecutionViewer.java
- ui/src/main/resources/org/apache/hop/ui/hopgui/file/pipeline/messages/messages_en_US.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/file/workflow/messages/messages_en_US.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/messages/messages_en_US.properties
- ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/execution/messages/messages_en_US.properties
HOP-4483 : Beam: not being able to send sample data should not be fatal
HOP-4486 : Allow hop-run.sh to accept a metadata export file
HOP-4487 : Execution Information : expose executor and metadata
> HOP-4483, HOP-4486, HOP-4487

- Jenkinsfile
- docker/Dockerfile.dataflowTemplate
- docker/Dockerfile.web-fatjar
- plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/BeamPipelineRunConfiguration.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/HopPipelineMetaToBeamPipelineConverter.java
- plugins/engines/beam/src/main/java/org/apache/hop/beam/run/MainDataflowTemplate.java
> HOP-4144: add support for dataflow templates + extra container builds
