plugins/databases/vertica/src/main/java/org/apache/hop/databases/vertica/VerticaDatabaseMeta.java

it's no big change but is pain in the ass . 
Store data up to 32000000 octets.  supports two long data types:
-     LONG VARBINARY: Variable-length raw-byte data, such as spatial data. LONG VARBINARY values are not extended to the full width of the column.
-     LONG VARCHAR: Variable-length strings, such as log files and unstructured data. LONG VARCHAR values are not extended to the full width of the column.
Use LONG data types only when you need to store data greater than the maximum size of VARBINARY and VARCHAR data types (65 KB). Long data can include unstructured data, online comments or posts, or small log files.

add logn type support

---

plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInput.java
plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapinput/LdapInputField.java
plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapoutput/LdapOutput.java
plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapoutput/LdapOutputData.java
plugins/transforms/ldap/src/main/java/org/apache/hop/pipeline/transforms/ldapoutput/LdapOutputMeta.java

Resolved following sonar issues
- "switch" statements should have at least 3 "case" clauses (java:S1301)
- Static non-final field names should comply with a naming convention (java:S3008)
- Class variable fields should not have public accessibility (java:S1104)
- Unused assignments should be removed (java:S1854)
- Collapsible "if" statements should be merged (java:S1066)
- The diamond operator ("<>") should be used (java:S2293)
- Field names should comply with a naming convention (java:S116)

Sonar Issues - LdapInput.java, LdapInputField.java, LdapOutput.java LdapOutputData.java LdapOutputMeta.java

---

assemblies/static/src/main/resources/hop-conf.bat
assemblies/static/src/main/resources/hop-encrypt.bat
assemblies/static/src/main/resources/hop-gui.bat
assemblies/static/src/main/resources/hop-run.bat
assemblies/static/src/main/resources/hop-server.bat
assemblies/static/src/main/resources/hop-translator.bat

[HOP-562]  **hop-run.bat** was broken on Windows.  It is now fixed to parse command line arguments correctly and pass them into the java application.  There is now a 'help' parameter that outputs a screen for both hop-gui.bat and hop-run.bat that instructs the user on how to use the software and there is a real live example for hop-run.bat which takes a lot of parameters.
[HOP-562]: https://project-hop.atlassian.net/browse/HOP-562

HOP-562 - Add bat files for Windows for the other utilities and improve the ones we have.

---

assemblies/plugins/transforms/ldifinput/pom.xml
plugins/transforms/ldap/pom.xml

Removed unwanted tags which are showing as warnings.
**Warning Messages:**
Overriding managed version 1.7.3 for powermock-module-junit4
Version is duplicate of parent version
**Reference:**
https://www.yawintutor.com/warning-duplicating-managed-version-maven/
https://stackoverflow.com/questions/3428685/maven-duplicated-groupid-artifactid-and-versions-in-submodules
Action Item:
Need to find 
- Is this something worth fixing? What does Apache Maven doc says?
- Is it just eclipse plugin (m2e) consider that as problem/warning? What about other IDE?
- Will this change break maven-release-plugin?

Fix for POM warnings appeared in eclipse IDE

---

assemblies/plugins/engines/beam/pom.xml
assemblies/plugins/vfs/s3/pom.xml
engine/pom.xml
plugins/engines/beam/pom.xml
plugins/transforms/kafka/pom.xml
plugins/vfs/s3/pom.xml
pom.xml

This PR adds checkstyle plugin. To avoid failing CI/CD and not to block other developers it is added in profile called code-quality. 
**What is the purpose:**
To enforce standard coding style across developers using different IDE.
To have only intended change in PR (Avoiding whitespace changes)
To save time in reviewing and gain confident in PR.
This profile is to enforce code quality check. At the time of introducing this profile,
we will not able to use these checks and enforcement at CI/CD (Jenkins). 
**When this profile used:**
To begin with this profile can be activated explicitly using `mvn -Pcode-quality` by developers.
We can resolve the checkstyle issues module by module as and when we work. 
To begin with, we can run following command to format to resolve lot of formatting …

checkstyle plugin added within code-quality profile

---

ui/src/main/java/org/apache/hop/ui/core/dialog/ContextDialog.java

I force a refresh after opening the shell. 
Works well on Windows, but must be tested on another operating system

HOP-2125 Fix ContextDialog scrollbar when opening

---

ui/src/main/java/org/apache/hop/ui/hopgui/dialog/NotePadDialog.java

This is another effort for single-sourcing.
See https://github.com/HiromuHota/pentaho-kettle/wiki/Dev%3A-Antipatterns-in-webSpoon#example-use-of-the-static-modifier-for-session-unique-instances

HOP-13 Avoid use of the static modifier for session-unique instances

---

core/src/main/java/org/apache/hop/i18n/ConstMessages.java
core/src/main/java/org/apache/hop/i18n/MessageContants.java
plugins/transforms/replacestring/src/main/java/org/apache/hop/pipeline/transforms/replacestring/ReplaceStringMeta.java

After the [discussion](https://chat.project-hop.org/hop/pl/edcg4f7s4iypzq9t3cwxgb55zo), Created new constant interface which holds only i18n message related strings. Choosing the package where BaseMessage is present which is being accessed in almost all UI classes.
Not comfortable choosing enum for this case as I don't see option to keep he enum like below and use `.name()` or `.value()` to get the actual string
public static final String SYSTEM_COMBO_YES = "SYSTEM_COMBO_YES";
or
SYSTEM_COMBO_YES("System.Combo.Yes");
or
SYSTEM_COMBO_YES("SYSTEM_COMBO_YES");
After reviewing, we can choose the best option and fix all the [sonarqube issues](https://sonarcloud.io/project/issues?id=hop&issues=AXMjPuw3tNti-jTiWHbA&open=AXMjPuw3tNti-jTiWHbA) reporting the same string and other similar strings. …

Creating Constants for i18n messages

---

ui/src/main/java/org/apache/hop/ui/core/widget/ConditionEditor.java

As reported [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569046), a menuitem with `SWT.CASCADE` w/o a submenu is NOT clickable on RAP/RWT.
For the purpose of single-sourcing, please change them to `SWT.PUSH`.
This is 0.40-20201024.141657-74:
As can been seen, these menuitems do not have a submenu; hence they can simply be `SWT.PUSH`.
This is the patched one:
They look and work same as before.

Use SWT.PUSH instead of SWT.CASCADE for a menuitem w/o a submenu

---

Jenkinsfile

This PR targeting to a docker-implementation branch.
@hansva I want to get your review before running this is Jenkins.
This will use the token `dockerhub-hop` which will deploy the docker image to apache/incubator-hop.
Is it OK to push snapshot release through Jenkins to apache/incubator-hop?

hop-2287 - using project credential and repo for docker build and push

---

engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransform.java

- Set private linesRead, linesWritten, linesInput, linesOutput, linesUpdated, linesSkipped, linesRejected
- Remove this unused "rowDistributionCode" private field.

HOP-2387 Make deprecated variables private in BaseTransform

---

engine/src/main/java/org/apache/hop/core/gui/WorkflowTracker.java
engine/src/main/java/org/apache/hop/workflow/ActionResult.java
engine/src/main/java/org/apache/hop/workflow/DelegationAdapter.java
engine/src/main/java/org/apache/hop/workflow/IDelegationListener.java
engine/src/main/java/org/apache/hop/workflow/Workflow.java
engine/src/main/java/org/apache/hop/workflow/WorkflowConfiguration.java
engine/src/main/java/org/apache/hop/workflow/WorkflowExecutionConfiguration.java
engine/src/main/java/org/apache/hop/workflow/WorkflowHopMeta.java
engine/src/main/java/org/apache/hop/workflow/WorkflowMeta.java
engine/src/main/java/org/apache/hop/workflow/WorkflowPainter.java
engine/src/main/java/org/apache/hop/workflow/action/ActionMeta.java
engine/src/main/java/org/apache/hop/www/AddWorkflowServlet.java
engine/src/main/java/org/apache/hop/www/BaseWorkflowServlet.java
engine/src/test/java/org/apache/hop/concurrency/WorkflowTrackerConcurrencyTest.java
engine/src/test/java/org/apache/hop/core/gui/WorkflowTrackerTest.java
engine/src/test/java/org/apache/hop/workflow/WorkflowMetaTest.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/context/HopGuiWorkflowNoteContext.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowActionDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowRunDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowUndoDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/extension/HopGuiWorkflowGraphExtension.java
ui/src/main/java/org/apache/hop/ui/hopgui/search/HopGuiWorkflowSearchable.java
ui/src/main/java/org/apache/hop/ui/workflow/dialog/WorkflowExecutionConfigurationDialog.java

- Remove notion copy number for Action
- ActionResult: remove deprecated constructor
- WorkflowMeta: remove deprecated methods get/set Arguments
- DelegationAdapter: rename method with 'job' word
- HopGuiWorkflowUndoDelegate: rename method with 'job' word
- HopGuiWorkflowNoteContext : rename method with 'job' word
- HopGuiWorkflowGraphExtension: remove method with 'job' word, same
method with workflow exist

HOP-2446 Workflow and Action code cleanup

---

docker/resources/dev-build-local-image.sh
docker/resources/get-hop.sh
docker/resources/run.sh

I didn't do a full man clean install after doing my changes. I just build a docker image locally and spun up a container testing one of my pipelines which worked successfully.

HOP-2485 - Docker container references wrong deployment folder

---

assemblies/plugins/engines/beam/pom.xml
plugins/engines/beam/pom.xml
plugins/engines/beam/src/main/samples/metadata/pipeline-run-configuration/DataFlow.json

Fairly simple point release update.

HOP-2547 : Update the Beam plugin to version 2.28.0

---

docs/hop-user-manual/modules/ROOT/pages/database/databases/doris.adoc

The port of JDBC url is incorrect [http://hop.apache.org/manual/latest/database/databases/doris.html]
This PR change the port to query port of Frontend in Doris.
The default port is 9030.

[HOP-2784] Change connector doc of Doris

---

assemblies/plugins/engines/beam/src/assembly/assembly.xml
plugins/engines/beam/src/main/java/org/apache/hop/beam/engines/dataflow/DataFlowJvmStart.java
plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/handler/BeamGenericTransformHandler.java
plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesDialog.java

HOP-3115 : Beam BigQuery Output failing because of missing dependency
HOP-3125 : Allow security property jdk.tls.disabledAlgorithms to be set
HOP-3124 : JavaScript transform: edit text area too small (rename of class)
HOP-3126 : Beam: re-add support for batching

Various small fixes

---

engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineRunConfiguration.java
engine/src/main/java/org/apache/hop/workflow/engines/remote/RemoteWorkflowEngine.java
engine/src/main/java/org/apache/hop/workflow/engines/remote/RemoteWorkflowRunConfiguration.java
engine/src/main/java/org/apache/hop/www/BaseWorkflowServlet.java
engine/src/main/java/org/apache/hop/www/StartWorkflowServlet.java
plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopRunCalculateFilenameExtensionPoint.java

HOP-3228, HOP-3252, HOP-3253

---

ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditor.java
ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataFileType.java
ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataFileTypeHandler.java
ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataManager.java
ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiAuditDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java

Fairly small but important bug fixes...
HOP-2435 : Projects: open objects are not remembered in the metadata perspective
HOP-3270 : Widget disposed error on project change

HOP-2435, HOP-3270

---

plugins/transforms/kafka/src/main/java/org/apache/hop/pipeline/transforms/kafka/consumer/KafkaConsumerInput.java

Subpipeline specified by using variables: messages in the log do not display the correct path to the subpipeline because variables are not resolved.

[FIX] Subpipeline specified by using variables

---

plugins/engines/beam/src/main/java/org/apache/hop/beam/core/transform/BeamBQOutputTransform.java

One of the smaller patches but important regardless

HOP-3182 : Beam BQ output Truncating table is not working

---

ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopGuiAbstractGraph.java

HOP-3322 : Allow canvas view to be scrolled by using the middle button
HOP-3318 : Changing the zoom level reposition the canvas to the upper left corner

HOP-3322, HOP-3318

---

plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/fatjar/FatJarBuilder.java

HOP-3333 : Fat jar zip64 format causes problems with Spring Boot framework

HOP-3333 : Fat jar zip64 format causes problems with Spring Boot framework

---

docs/hop-user-manual/modules/ROOT/pages/workflow/workflow-run-configurations/workflow-run-configurations.adoc

---
The workflow run configuration page references "Pipeline run configuration" instead of "Workflow ..."

(DOC) - Trivial fix in user manual, workflow run configuration page

---

docker/Dockerfile
docker/Dockerfile.web
docker/resources/load-and-execute.sh
docker/resources/run-web.sh
docker/resources/run.sh
docs/hop-tech-manual/modules/ROOT/pages/docker-container.adoc
docs/hop-user-manual/modules/ROOT/pages/hop-server/index.adoc
integration-tests/transforms/metadata/unit-test/0037-apache-tika UNIT.json
ui/src/main/java/org/apache/hop/ui/pipeline/dialog/PipelinePreviewProgressDialog.java

HOP-3529 : Add documentation to allow us to configure Hop Server to run with https
HOP-3533 : Ability to set the METADATA_FOLDER in long-lived hop-server
HOP-3548 : Support projects and environments in the long lived docker container
HOP-3549 : Support SSL configurations in long lived container
HOP-3552 : Add docker options for the server logging options 
HOP-3553 : Docker container does not forward exit code
HOP-3554 : The Hop web docker container can't be stopped

HOP-3529, HOP-3533, HOP-3548, HOP-3549, HOP-3552, HOP-3553, HOP-3554

---

assemblies/plugins/databases/h2-assemblies/pom.xml

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-42392

Update H2 Database to 2.0.206 to address CVE-2021-42392.

---

plugins/engines/beam/src/main/java/org/apache/hop/beam/core/coder/HopRowCoder.java
plugins/engines/beam/src/test/java/org/apache/hop/beam/core/coder/HopRowCoderTest.java

Don't encode timestamp field on flink, some data type don't support in HopRowCoder.
* add timestamp type for IValueMeta.TYPE_STRING
* add byte[] type for IValueMeta.TYPE_BINARY
* add InetAddress for IValueMeta.TYPE_INET

HOP-3683: Add support for timestamp and byte[] in HopRowCoder

---

docs/hop-user-manual/modules/ROOT/pages/how-to-guides/apache-hop-web-services-docker.adoc

HOP-3667 escape entire url to avoid parsing issues

---

plugins/engines/beam/src/main/java/org/apache/hop/beam/core/coder/HopRowCoder.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/shared/NeoConnection.java
plugins/transforms/ssh/src/main/java/org/apache/hop/pipeline/transforms/ssh/SshData.java

Sonar cleanup

---

plugins/transforms/checksum/src/main/java/org/apache/hop/pipeline/transforms/checksum/CheckSumMeta.java

To replicate bug easily you can run the test multiple times for example by defining Repeat N (e.g. 100) times option in Intellij Idea Test Runner config
Cause:
During the test the EnumLoadSaveValidator#getTestObject generates random enum value to set checkSumType field in CheckSumMeta object.
Most of the time seems to draws well matched value to pass the test.
However the problem occurs when the validator draws CheckSumMeta.CheckSumType#NONE enum, which has 'code' property value defined as an empty string "".
Next the LoadSaveTester#testXmlRoundTrip creates meta with provided checkSumType to save to and then applies transform xml to meta. 
So when checkSumType==NONE has 'code' defined as "" , the generated transform xml looks just like empty <checksumtype/>. Which means no transform at …

HOP-3711 CheckSumMetaTest.testSerialization fails randomly

---

core/pom.xml
core/src/test/java/org/apache/hop/core/database/DatabaseMetaTest.java
core/src/test/java/org/apache/hop/core/database/DatabaseTest.java
core/src/test/java/org/apache/hop/core/row/value/ValueMetaBaseTest.java
core/src/test/java/org/apache/hop/core/row/value/ValueMetaStringTest.java
engine/src/test/java/org/apache/hop/core/attributes/AttributesUtilTest.java
engine/src/test/java/org/apache/hop/pipeline/PipelineMetaTest.java
engine/src/test/java/org/apache/hop/pipeline/TransformWithMappingMetaTest.java
engine/src/test/java/org/apache/hop/server/HopServerTest.java
engine/src/test/java/org/apache/hop/www/GetWorkflowStatusServletTest.java
plugins/actions/deletefiles/src/test/java/org/apache/hop/workflow/actions/deletefiles/WorkflowEntryDeleteFilesTest.java
plugins/transforms/checksum/src/main/java/org/apache/hop/pipeline/transforms/checksum/CheckSumMeta.java
plugins/transforms/databaselookup/src/test/java/org/apache/hop/pipeline/transforms/databaselookup/DatabaseLookupUTest.java
plugins/transforms/http/pom.xml
plugins/transforms/http/src/test/java/org/apache/hop/pipeline/transforms/http/HttpTest.java
plugins/transforms/httppost/src/test/java/org/apache/hop/pipeline/transforms/httppost/HttpPostTest.java
plugins/transforms/streamlookup/src/test/java/org/apache/hop/pipeline/transforms/streamlookup/StreamLookupTest.java
ui/src/test/java/org/apache/hop/ui/util/EnvironmentUtilsTest.java

Resolves problems with some of ignored tests. Most common case is connected with new mockito argument matchers api which does not allow passing null values anymore using anyType() methods. E.g. anyString() could be replaced with nullable(String.class).
Also fixes problems with javassist incompatibility by upgrading to newest version.
Commits are divided by specific type of problems with tests.
- Fixed mockito matchers, mostly by providing nullable(Class) instead 'anyType' which does not respect argument values anymore. Resolves issues: 
HOP-3607, HOP-3608, HOP-3609, HOP-3610, HOP-3611, HOP-3614, HOP-3612, HOP-3624, HOP-3625, HOP-3646, HOP-3626, HOP-3630, HOP-3632, HOP-3631, HOP-3638, HOP-3639, HOP-3640, HOP-3644, HOP-3646, HOP-3649
- Powermock upgrade Resolves: 
HOP-3648
- Upgraded …

[HOP-3606] Disabled java 11 tests

---

engine/src/test/java/org/apache/hop/pipeline/transforms/mock/TransformMockHelper.java
engine/src/test/java/org/apache/hop/www/GetPipelineStatusServletTest.java
plugins/transforms/fuzzymatch/src/test/java/org/apache/hop/pipeline/transforms/fuzzymatch/FuzzyMatchTest.java
plugins/transforms/mapping/src/test/java/org/apache/hop/pipeline/transforms/mapping/SimpleMappingTest.java
plugins/transforms/memgroupby/pom.xml
plugins/transforms/memgroupby/src/test/java/org/apache/hop/pipeline/transforms/memgroupby/MemoryGroupByAggregationNullsTest.java
plugins/transforms/memgroupby/src/test/java/org/apache/hop/pipeline/transforms/memgroupby/MemoryGroupByMetaGetFieldsTest.java
plugins/transforms/metainject/src/test/java/org/apache/hop/pipeline/transforms/metainject/MetaInjectTest.java

HOP-3633 Restored at leastOnce mode in verifyStatic which was initially used before commit 20da4ef7
HOP-3642 HOP-3643 Powermock upgrade
HOP-3651 HOP-3652 ignore removed - already working tests 
HOP-3647 Added explicit mock of IRowMeta to IRowSet objects - fixes ClassCastException when invoking mocked clone method

HOP-3606 Disabled java 11

---

core/pom.xml
engine/pom.xml
plugins/transforms/excelinput/pom.xml
plugins/transforms/xml/pom.xml

There is two last problem:
1) hop-transform-xml plugin, but I can't find the duplicate modules with the "javax.xml.stream" package.
2) hop-plugins-tech-cassandra plugi, but I can't find the duplicate modules with the "java.util" package.

HOP-3838 "javax.xml.stream" and "org.w3c.dom" packages in more than one module

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml
assemblies/plugins/transforms/xml/pom.xml
assemblies/plugins/transforms/xml/src/assembly/assembly.xml
core/pom.xml
core/src/main/java/org/apache/hop/core/xml/XmlParserFactoryProducer.java
engine/pom.xml
plugins/transforms/excelinput/pom.xml
plugins/transforms/excelwriter/pom.xml
plugins/transforms/xml/pom.xml
plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/Dom4JUtil.java
plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/getxmldata/GetXmlData.java
plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/getxmldata/LoopNodesImportProgressDialog.java
plugins/transforms/xml/src/main/java/org/apache/hop/pipeline/transforms/xml/getxmldata/XmlInputFieldsImportProgressDialog.java
pom.xml

Remove library xml-apis dependency native in JVM 11
Exclude xml-apis from xerces dependency
Exclude stax-api from woodstox dependency
Move libraries dom4j and jaxen from core to transform-xml plugin
Remove some <version> tag from managed dependencies

HOP-3838 package is accessible from more than one module

---

core/src/main/java/org/apache/hop/core/Const.java
docs/hop-user-manual/modules/ROOT/pages/variables.adoc
plugins/tech/aws/src/main/java/org/apache/hop/vfs/s3/s3common/S3HopProperty.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/logging/Defaults.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/logging/util/LoggingCore.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/logging/xp/PipelineLoggingExtensionPoint.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/logging/xp/WorkflowLoggingExtensionPoint.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/perspective/HopNeo4jPerspective.java
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/loginfo/GetLoggingInfo.java

Add missing annotation to plugin variable
- NEO4J_LOGGING_CONNECTION
- HOP_S3_VFS_PART_SIZE
Remove obsolete variable doc
- HOP_PIPELINE_PAN_JVM_EXIT_CODE
- HOP_COMPATIBILITY_DB_IGNORE_TIMEZONE
- HOP_COMPATIBILITY_MERGE_ROWS_USE_REFERENCE_STREAM_WHEN_IDENTICAL
- HOP_COMPATIBILITY_TEXT_FILE_OUTPUT_APPEND_NO_HEADER

HOP-3729 Add missing annotation to plugin variable

---

ui/src/main/java/org/apache/hop/ui/core/widget/StyledTextComp.java

Only change foreground in text control.
Hop-GUI seems to always use the same background when enable value is changed.

HOP-3876 Using contrast color for foreground in text

---

docker/Dockerfile.web

hop-web docker container cannot generate a fat JAR
This is a quick and dirty fix for HOP-3976. After creating this empty directory, the JAR seems to be generated correctly (490MB JAR with all the dependencies in the lib dir, including all the plugins dependencies).
- [X ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

[HOP-3976] hop-web docker container cannot generate a fat JAR

---

plugins/engines/beam/src/main/java/org/apache/hop/beam/gui/HopBeamGuiPlugin.java

Fat JAR generated in hop-web container is missing some dependencies
The fat JAR generated with the docker hop-web container is missing all the JARs included in the `lib` directory of Hop, and it only includes the JARs in the Tomcat `lib` directory, and the plugins JARs.
This change checks if we are running in Tomcat in the docker hop-web container and in that case, it adds all the Hop lib JARs too.
There is an additional small change, related to HOP-3966: if the `libswt` directory does not exist, the plugin does not attempt to import JARs from that directory. Attempting that import makes the fat JAR generation fail.
- [X ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

[HOP-3977] Fat JAR generated in hop-web container is missing some dependencies

---

plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassDialog.java

User-defined Java class transformations lose the name of the transformations in the Info and Target tab

HOP-4000 Fix User-defined Java class transformations

---

docs/hop-user-manual/modules/ROOT/pages/workflow/actions/pipeline.adoc

- I consider this to be a trivial change as it only impacts formatting within documentation. The current table is malformed (link below) and makes interpreting the documentation difficult. I am proposing this correction. There is no change to the content.
[- https://hop.apache.org/manual/latest/workflow/actions/pipeline.html](https://hop.apache.org/manual/latest/workflow/actions/pipeline.html#_parameters_tab)

(DOC) - Fix table formatting in workflow/actions/pipeline Parameters Tab section

---

docs/hop-user-manual/modules/ROOT/pages/workflow/actions/workflow.adoc

Fix numerous typos, in particular `s/pipeline/workflow` several times.
I also think the description of `Copy previous results to parameters?` is wrong (too similar to the previous line) but cannot fix it

(DOC) fix typos in workflow/actions/workflow

---

docs/hop-user-manual/modules/ROOT/pages/workflow/actions/xsdvalidator.adoc

Make a reference from `workflow/actions/xsdvalidator` to `pipeline/transforms/xsdvalidator` (not to itself).
I glimpsed the xref syntax at https://github.com/apache/hop/edit/master/docs/hop-user-manual/modules/ROOT/pages/workflow/workflows.adoc, might be wrong.

(DOC) fix ref from action to transform

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/analyticquery.adoc

- remove extraneous table header
- why is this marked `bash`? is there `source,csv`?

(DOC) remove extraneous table header

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/jsoninput.adoc

- start new row at "Click Browse to navigate to your source file or directory. Click Add to include the source in the Selected files table."
- turn those two into bullets (hope this works! my "adoc" skills are still rudimentary)
- reduce spacing in JSON example
- add lang indicator `json`. Hope this works in backticks (which is a `md` device not `adoc` but maybe adoc also handles it)
- reduce verbiage re `HOP_JSON_INPUT_INCLUDE_NULLS`
- https://issues.apache.org/jira/browse/HOP-4038 is related to this file

(DOC) jsoninput fixes

---

plugins/transforms/fieldsplitter/src/main/java/org/apache/hop/pipeline/transforms/fieldsplitter/FieldSplitter.java
plugins/transforms/fieldsplitter/src/main/java/org/apache/hop/pipeline/transforms/fieldsplitter/FieldSplitterDialog.java
plugins/transforms/fieldsplitter/src/main/resources/org/apache/hop/pipeline/transforms/fieldsplitter/messages/messages_en_US.properties
plugins/transforms/fieldsplitter/src/main/resources/org/apache/hop/pipeline/transforms/fieldsplitter/messages/messages_zh_CN.properties

There is a issue in the split fields plugin that tields are read out of order  when the new fields list is empty .
I don't think it makes sense for the new fields list to be empty and we should check the list can not be empty before submitting.
the example's pictures as below
csv input data :
the flow image:

[HOP-FieldSplit] issue in FieldSplit transform

---

ui/src/main/java/org/apache/hop/ui/core/PropsUi.java

Works on Windows, must be tested on Mac / Linux

HOP-4179 CTabFolder foreground color is not readable

---

docs/hop-user-manual/modules/ROOT/pages/hop-server/rest-api.adoc
engine/src/main/java/org/apache/hop/resource/ResourceUtil.java
engine/src/main/java/org/apache/hop/server/HopServer.java
engine/src/main/java/org/apache/hop/www/BaseHttpServlet.java
engine/src/main/java/org/apache/hop/www/RegisterPipelineServlet.java
engine/src/main/java/org/apache/hop/www/RegisterWorkflowServlet.java

When add pipeline/workflow to hop-server, the xml content maybe could not be parsed using the correct encoding.
Many times, it is difficult to guarantee the same encoding used in http-client and hop-server.
For example, Chinese Windows systems usually use gbk as the default encoding for the system. But hop-server may run on Linux and use UTF-8 as the default encoding.
If there are Chinese characters in the pipeline name, it may only show that there is a problem.
However, if Chinese characters are used in a path (ps: PipelineExecutor's hpl location), the file may not be loaded

HOP-4198, HOP-4005

---

plugins/databases/mysql/src/main/java/org/apache/hop/databases/mysql/MySqlDatabaseMeta.java

This driver class is available in version 8.0.28 provided with Hop.

HOP-4197 MySQL Driver deprecated

---

engine/src/main/java/org/apache/hop/www/BaseHttpServlet.java
engine/src/main/java/org/apache/hop/www/GetPipelineImageServlet.java
engine/src/main/java/org/apache/hop/www/GetPipelineStatusServlet.java
engine/src/main/java/org/apache/hop/www/GetWorkflowImageServlet.java
engine/src/main/java/org/apache/hop/www/GetWorkflowStatusServlet.java
engine/src/main/java/org/apache/hop/www/WebServer.java

SVG and Font both dependency graphic environment.
On macOS, like jvm option: -XstartOnFirstThread, we should load graphic environment at main thread.
GUI environment usually works fine on the default jdk unless the java.desktop module is removed  or custom module list.
Hop-Server as rest api service, maybe the preview feature is better as an optional feature.

HOP-3974: Disable preview feature when hop-server don't support graphic environment

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/metadata-injection.adoc

HOP-4478: fix MDI supported list

---

rap/pom.xml
rap/src/main/resources/org/apache/hop/ui/hopgui/canvas-dark.js
rap/src/main/resources/org/apache/hop/ui/hopgui/canvas-light.js

HOP-4512 : Dragged actions and transform are positioned incorrectly
HOP-4513 : Update Eclipse RAP to version 3.22
HOP-4514 : Transform/Action names are rendered in the wrong color when dragged

HOP-4512, HOP-4513, HOP-4514

---

docker/integration-tests/integration-tests-neo4j.yaml

Have IT Neo4j docker container use version 4.4 and not the latest 5.1.
We'll update that when we implement HOP-4516

Neo4j IT test fix

---

plugins/engines/beam/src/main/java/org/apache/hop/beam/core/fn/MergeJoinAssemblerFn.java
plugins/engines/beam/src/main/java/org/apache/hop/beam/pipeline/handler/BeamMergeJoinTransformHandler.java

HOP-4444:
Changed the BeamMergeJoinTransformHandler to include key values in the value data.
This way we know which keys come from left/right and can also handle Key only joins

HOP-4444: Align Beam join output with Hop output

---

core/src/main/java/org/apache/hop/i18n/LanguageChoice.java

The current localeCodes only contains: language and country information.
[JDK 11 Supported Locales](https://www.oracle.com/java/technologies/javase/jdk11-suported-locales.html)

HOP-4597: Ignore variant value and script code when match default locale

---

integration-tests/hopweb/src/test/java/org/apache/hop/ui/hopgui/HopWebTest.java

HOP-4550: increase wait times again

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/pipeline-unit-testing.adoc

Typo for HOP_UNIT_TESTS_FOLDER in pipeline-unit-testing.adoc

DOC Typo for HOP_UNIT_TESTS_FOLDER

---

integration-tests/neo4j/datasets/golden-action-constraint.csv
integration-tests/neo4j/datasets/golden-action-cypher-script.csv
integration-tests/neo4j/metadata/dataset/golden-action-constraint.json
integration-tests/neo4j/metadata/dataset/golden-action-cypher-script.json
integration-tests/neo4j/metadata/unit-test/neo4j-action-constraint-validate UNIT.json
integration-tests/neo4j/metadata/unit-test/neo4j-action-cypher-script-validate UNIT.json
integration-tests/neo4j/tests/neo4j-action-constraint/main-action-constraint.hwf
integration-tests/neo4j/tests/neo4j-action-constraint/neo4j-action-constraint-validate.hpl
integration-tests/neo4j/tests/neo4j-action-cypher-script/neo4j-action-cypher-script-validate.hpl
integration-tests/neo4j/tests/neo4j-action-cypher-script/neo4j-action-cypher-script.hwf
plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/actions/constraint/Neo4jConstraint.java

Plus a few more integration tests for this and Cypher Script.

Fixes #1856 : Neo4j Constraint action should use 5.0 syntax

---

plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/Rest.java

ApacheConnector in REST client is set to BUFFERED mode HOP-4644
this settings returns client behaviour to be compatible with older servers
as worked in 2.0.0
there is no need to indeterminate length of content as data are already
in memory

fix for HOP-4644

---

integration-tests/database/0012-1-dimension-lookup-update-insert.hwf
integration-tests/database/0012-2-dimension-lookup-update-punch-through.hwf
integration-tests/database/0012-3-dimension-lookup-update-update.hwf
integration-tests/database/0012-dimension-lookup-update-punch-through.hpl
integration-tests/database/0012-dimension-lookup-update-update.hpl
plugins/transforms/dimensionlookup/src/main/java/org/apache/hop/pipeline/transforms/dimensionlookup/DimensionLookup.java
plugins/transforms/dimensionlookup/src/main/java/org/apache/hop/pipeline/transforms/dimensionlookup/DimensionLookupDialog.java
plugins/transforms/dimensionlookup/src/main/java/org/apache/hop/pipeline/transforms/dimensionlookup/DimensionLookupMeta.java

- Fix lost TK field
- Fix folder tab Versioning layout
- Propose the table fields names in key fields column
- Resolve schema and table name when getting a lookup field
- Sort table fields on name
- Replace FocusListener and ModifyListener
- Store DimensionUpdateType has code
- Fix error with DATE_INSERTED, DATE_UPDATED and DATE_INSERTED_UPDATED
- Sequence name can be changed without sequence mode selected

Fix #2021 Dimension lookup transform

---

core/src/main/java/org/apache/hop/core/Condition.java

2110 - Unexpected error evaluation condition on Filter Rows transform
2136 - Filter String comparisons using the = operator do not work, while using IN LIST will. 
2135 - Filter - Fails comparing Boolean using = against Boolean with a True value.

2110, 2135, 2136

---

core/src/main/java/org/apache/hop/core/logging/LogLevel.java
plugins/actions/pipeline/src/main/java/org/apache/hop/workflow/actions/pipeline/ActionPipeline.java
plugins/actions/pipeline/src/main/java/org/apache/hop/workflow/actions/pipeline/ActionPipelineDialog.java
plugins/actions/workflow/src/main/java/org/apache/hop/workflow/actions/workflow/ActionWorkflow.java
plugins/actions/workflow/src/main/java/org/apache/hop/workflow/actions/workflow/ActionWorkflowDialog.java
plugins/actions/workflow/src/main/java/org/apache/hop/workflow/actions/workflow/ActionWorkflowRunner.java
ui/src/main/java/org/apache/hop/ui/core/widget/MetaSelectionLine.java
ui/src/main/java/org/apache/hop/ui/workflow/actions/ActionBaseDialog.java
ui/src/main/resources/org/apache/hop/ui/workflow/actions/messages/messages_en_US.properties

This reverts commit 739b3706514a8a08a33203c342a8386eaa75352d.

Revert "Cleanup XML of action Workflow #2002 and Pipeline #1986"

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/enhancedjsonoutput.adoc

Some spellings were wrong, and the resulting data was not following the configuration provided just before.

enhancedjsonoutput.adoc: Fix grammar and examples

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
plugins/transforms/formula/src/main/resources/org/apache/hop/pipeline/transforms/formula/function/functions.xml

removed parsedate from formula functions and docs. fixes #2077

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/javascript.adoc
plugins/transforms/javascript/src/main/samples/transforms/javascript-field-name-with-spaces.hpl

added docs + sample for field names with spaces. closes #2300

---

assemblies/plugins/databases/mssqlnative-assemblies/pom.xml
assemblies/static/src/main/resources/LICENSE
docs/hop-user-manual/modules/ROOT/pages/database/databases/mssqlnative.adoc

Solves issue #2445 
Apache Hop is shipped with jdbc driver for mssqlnative, version 7.4.1. [The doc](https://hop.apache.org/manual/next/database/databases/mssqlnative.html) says otherwise, not provided.
This commit upgrades the jdbc driver to version 11.2.3 and updates the docs accordingly.

#2445: Upgrading mssqlnative jdbc driver to 11.2.3 and updating the docs

---

ui/src/main/java/org/apache/hop/ui/core/dialog/BaseDialog.java
ui/src/main/java/org/apache/hop/ui/core/dialog/ConfigurationDialog.java
ui/src/main/java/org/apache/hop/ui/core/gui/GuiResource.java
ui/src/main/java/org/apache/hop/ui/core/widget/ComboVar.java
ui/src/main/java/org/apache/hop/ui/core/widget/StyledTextComp.java
ui/src/main/java/org/apache/hop/ui/core/widget/TextVar.java
ui/src/main/java/org/apache/hop/ui/core/widget/TextVarButton.java
ui/src/main/java/org/apache/hop/ui/workflow/dialog/WorkflowExecutionConfigurationDialog.java

- fix variable icon size
- small cleanup

Add variable icon to TabItem in Run Pipeline/Workflow dialog #2471

---

plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesDialog.java

Javascript transform: Couldn't parse Date field [timestamp] with value [20230228161206]

fix #2486 

---

plugins/tech/neo4j/src/test/java/org/apache/hop/neo4j/transforms/cypherbuilder/CypherBuilderMetaTest.java

Updated tests to use platform dependent line endings to match the plugin's code to avoid build failure of the neo4j plugin on Windows.
I haven't ran the RAT check as the file changed already has a header. I'm an ASF Member so have an active ACLA in place.

Updated tests to use platform dependent line endings to match the plugin's code

---

integration-tests/transforms/0037-apache-tika-from-getfilenames.hpl
integration-tests/transforms/main-0037-apache-tika.hwf
integration-tests/transforms/metadata/unit-test/0037-apache-tika-from-getfilenames UNIT.json
plugins/transforms/tika/src/main/java/org/apache/hop/pipeline/transforms/tika/Tika.java

Moved TikaOutput initialisation so it occurs in both standard and dynamic filename mode. Fixes #2339 / HOP-4447.
To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) you have to acknowledge this by using the following check-box.

Moved TikaOutput initialisation so it occurs in both standard and dynamic filename mode

---

plugins/transforms/excel/src/main/java/org/apache/hop/pipeline/transforms/excelwriter/ExcelWriterTransform.java

We've observed that even when a starting-cell is set the transform will continue to skip down to the last row in the Excel where the Excel file has other non-empty rows (values or style) in. This changes sets the start position relative to the cell provided based on the other settings.
I've added this here given this feels like it's behaving not as one would expect, though given this is current behaviour and others may be configuring settings based on it, was thinking it may be better added as parameterised option. Happy to update to this if you would prefer that.
I've ran the existing unit and integration test suite for the transforms project, which all continue to pass.

Updated ExcelWriterTransform to use posY relative to the starting cell provided, where provided.

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopGuiStartProjectLoad.java
ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiAuditDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiFileDelegate.java

Caused by over-writing the files lists in the audit folder while the GUI was re-opening files.

Fix for issue #2766 : Data orchestration perspective doesn't remember tabs

---

docs/hop-user-manual/modules/ROOT/pages/database/databases/oracle.adoc

added different ways of creating an oracle connection. fixes #2791

---

Jenkinsfile
docker/Dockerfile.web-fatjar

Simplify the Hop Web image including beam, fixes #2884

---

plugins/transforms/delete/src/main/java/org/apache/hop/pipeline/transforms/delete/DeleteDialog.java
plugins/transforms/execsqlrow/src/main/java/org/apache/hop/pipeline/transforms/execsqlrow/ExecSqlRowDialog.java
plugins/transforms/insertupdate/src/main/java/org/apache/hop/pipeline/transforms/insertupdate/InsertUpdateDialog.java
plugins/transforms/tableexists/src/main/java/org/apache/hop/pipeline/transforms/tableexists/TableExistsDialog.java
plugins/transforms/tableinput/src/main/java/org/apache/hop/pipeline/transforms/tableinput/TableInputDialog.java
plugins/transforms/update/src/main/java/org/apache/hop/pipeline/transforms/update/UpdateDialog.java
ui/src/main/java/org/apache/hop/ui/pipeline/transform/BaseTransformDialog.java

fix #2953 Unable to close a 'table input' edit window due to incorrect connection name
fix #2952 Unwanted "Invalid connection" message on not existing connections

fix #2953, fix #2952

---

engine/pom.xml

- #2682 HTTPPost repeats jersey warn on every request
- https://github.com/eclipse-ee4j/jersey/pull/5165 addresses it and made fix available in jersey 2.38

bump jersey to 2.38 to suppress repeating WARNs by HTTPPost and others #2682

---

docker/Dockerfile.web

change tomcat user so it's non-root, fixes #2561

---

docs/hop-user-manual/modules/ROOT/pages/how-to-guides/loops-in-apache-hop.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getdatafromxml.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/pipeline-executor.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/workflow-executor.adoc
docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/loops.adoc
docs/hop-user-manual/modules/ROOT/pages/workflow/actions/pipeline.adoc
docs/hop-user-manual/modules/ROOT/pages/workflow/actions/workflow.adoc
plugins/misc/testing/src/main/java/org/apache/hop/testing/gui/TestingGuiPlugin.java
plugins/transforms/xml/src/main/samples/transforms/get-data-from-xml.hpl

rename fixes, get data from xml docs and sample #3083 #3086

---

plugins/actions/telnet/src/main/java/org/apache/hop/workflow/actions/telnet/ActionTelnet.java
plugins/actions/telnet/src/main/java/org/apache/hop/workflow/actions/telnet/ActionTelnetDialog.java
plugins/actions/telnet/src/test/java/org/apache/hop/workflow/actions/telnet/ActionTelnetTest.java
plugins/actions/telnet/src/test/java/org/apache/hop/workflow/actions/telnet/WorkflowActionTelnetLoadSaveTest.java
plugins/actions/telnet/src/test/resources/telnet-action.xml

task #1996 Cleanup XML of action Telnet

---

plugins/transforms/excel/src/main/java/org/apache/hop/pipeline/transforms/excelwriter/ExcelWriterTransform.java
plugins/transforms/excel/src/test/java/org/apache/hop/pipeline/transforms/excelwriter/ExcelWriterTransformTest.java

fix #3058 Excel Writer: inherit date format mask from ValueMeta

fix #3058 Excel Writer: inherit date format mask from ValueMeta

---

plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopGuiFileDefaultFolder.java
ui/src/main/java/org/apache/hop/ui/core/dialog/BaseDialog.java
ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiFileDelegate.java

when using save as point to current file location, fixes #3109

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc

Update formula.adoc with better formatting

---

docs/hop-user-manual/modules/ROOT/pages/hop-server/index.adoc

The sample docker statement to start the Hop Server from docker had the wrong environment variable for the HOP_SERVER_PASS.  This prevented login of the server without first finding the error.
Changed the **password** line from HOP_SERVER_USER to HOP_SERVER_PASS

Fix wrong Docker ENV Var in index.adoc

---

plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleImport.java
plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsInputMeta.java

PDI/kettle importer improvements, minor google sheets input fix #3303 #3315

---

core/src/test/java/org/apache/hop/core/row/value/ValueMetaAvroRecordTest.java

The root issue is that `JSONObject.toJSONString()` use `HashMap` to convert json data into strings. In this case, `toJSONString()` was called on `jvalue` and then the output string is compared to a fixed string.  Because `HashMap` does not guarantee the order of elements returned, the two strings could have the same content but in different order, thus the flakiness. 
This flaky test has been fixed through leveraging the Jackson library, which incorporates the JsonNode and ObjectMapper classes. These components are employed for parsing two JSON strings into tree models, which are subsequently compared node by node when assertion is called. 
To make …

Fixed flaky test

---

core/pom.xml
core/src/test/java/org/apache/hop/core/svg/HopSvgGraphics2DTest.java

The issue is that in test `org.apache.hop.core.svg.HopSvgGraphics2DTest#testNewDocumentXml`
and  `org.apache.hop.core.svg.HopSvgGraphics2DTest#testNewDocumentSimpleXml`, inside `graphics2D.toXml`, `org.apache.batik.svggen.SVGGraphics2D.getRoot`, which uses a `HashMap` iterator to generate the DOM, is called. Since the order of HashMap is unpredictable, the order of elements in generated xml string is nondeterministic. 
This flaky test has been fixed through leveraging the Jackson library, which incorporates the JsonNode and XmlParser classes. These components are employed for parsing two XML strings into tree models, which are subsequently compared node by node when assertion is called. 
I understand this fix introduces a new dependency. If prefered, I'm happy to come up with a fix …

Fixed flaky test in SvgGraphics2DTest

---

plugins/transforms/databaselookup/src/main/java/org/apache/hop/pipeline/transforms/databaselookup/DatabaseLookupMeta.java

`org.apache.hop.pipeline.transforms.databaselookup.DatabaseLookupMetaTest#testProvidesModelerMeta` calls `meta.getDatabaseFields()` and `meta.getStreamFields()` to get the database fields nad streamfields in as a list, and the order in the list is the insertion order in to the lookup. However, inside `meta.getDatabaseFields()` and `meta.getStreamFields()`, a `HashSet` was used to insert the data before returned as an `ArrayList`. However, order in `HashSet` is not predictable when it is converted to `ArrayList` (fist `toArray` is called and the `HashSet` iterator has undeterministic order). Therefore, tests could fail when the fields are checking according to the insertion order.
https://github.com/apache/hop/blob/fbb0eb49e87f471d0ce847f1f92f00c910578dac/plugins/transforms/databaselookup/s …

Fixed flaky test due to use of HashSet in DatabaseLookupMetaTest#testProvidesModelerMeta

---

plugins/transforms/propertyinput/src/test/java/org/apache/hop/pipeline/transforms/propertyinput/BaseParsingTest.java

In the test `org.apache.hop.pipeline.transforms.propertyinput.PropertyInputContentParsingTest#testDefaultOptions`, when `process()` is called, function `openNextFile()` will be called when rows are processed.
https://github.com/apache/hop/blob/45df66294437da0a8dbb1d611b34afda48408d3b/plugins/transforms/propertyinput/src/main/java/org/apache/hop/pipeline/transforms/propertyinput/PropertyInput.java#L331
When then rows are processed, `data.properties` is created and the iterator is a iterator on the keyset of `data.properties`, which is a `Hashtable` as `Properties` object extends `Hashtable`.
https://github.com/apache/hop/blob/45df66294437da0a8dbb1d611b34afda48408d3b/plugins/transforms/propertyinput/src/main/java/org/apache/hop/pipeline/transforms/propertyinput/PropertyInput.java#L464-L466 …

Fixed flaky test in hop-transform-propertyInput

---

engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransformMeta.java
engine/src/main/java/org/apache/hop/pipeline/transform/ITransformMeta.java
engine/src/main/java/org/apache/hop/pipeline/transform/TransformMeta.java
plugins/transforms/abort/src/main/java/org/apache/hop/pipeline/transforms/abort/AbortMeta.java
plugins/transforms/analyticquery/src/main/java/org/apache/hop/pipeline/transforms/analyticquery/AnalyticQueryMeta.java
plugins/transforms/groupby/src/main/java/org/apache/hop/pipeline/transforms/groupby/GroupByMeta.java
plugins/transforms/memgroupby/src/main/java/org/apache/hop/pipeline/transforms/memgroupby/MemoryGroupByMeta.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java

Disable multi-copy execution support for 4 transforms:
- Abort
- Analytic query
- Group by
- Memory group by

Filter "Specify copies" GuiAction if transform doesn't support it #3439

---

plugins/transforms/multimerge/src/main/java/org/apache/hop/pipeline/transforms/multimerge/MultiMergeJoinDialog.java

See #3584 Simply clear the inputfields list once we've set the combo box. Before we would just keep appending to the same list so it would have duplicates and wrong keys from other input streams.

fix duplicate and wrong keys in multiway merge join combobox #3584

---

engine/src/main/java/org/apache/hop/workflow/Workflow.java

Indirectly fix "actionDuration" always null in workflow logging

Record action execution duration #3606

---

core/src/main/java/org/apache/hop/core/database/BaseDatabaseMeta.java
core/src/main/java/org/apache/hop/core/database/IDatabase.java
core/src/main/java/org/apache/hop/core/row/value/ValueMetaBase.java
core/src/test/java/org/apache/hop/core/row/value/ValueMetaBaseSetPreparedStmntValueTest.java
docs/hop-user-manual/modules/ROOT/pages/database/databases/duckdb.adoc
plugins/databases/duckdb/src/main/java/org/apache/hop/databases/duckdb/DuckDBDatabaseMeta.java
plugins/transforms/tableoutput/src/main/java/org/apache/hop/pipeline/transforms/tableoutput/TableOutput.java

fix #3510 DuckDB - if a table output fails, the destination duckdb database file remains locked and can no longer be used.
fix #3512 DuckDB- If you send it a Date some kind of setTimestamp() prepared function fails
fix #3665 DuckDB plugins documentation improvements

fix #3510, fix #3512, fix #3665

---

integration-tests/transforms/0071-concurrent-scripts-3729.hpl
integration-tests/transforms/main-0071-concurrent-scripts-3729.hwf
plugins/transforms/script/src/main/java/org/apache/hop/pipeline/transforms/script/Script.java
plugins/transforms/script/src/main/java/org/apache/hop/pipeline/transforms/script/ScriptDialog.java
plugins/transforms/script/src/main/java/org/apache/hop/pipeline/transforms/script/ScriptUtils.java

fix ConcurrentModificationExceptions in script transforms. #3729

---

core/src/main/java/org/apache/hop/core/database/DatabaseMetaInformation.java
plugins/databases/duckdb/src/main/java/org/apache/hop/databases/duckdb/DuckDBDatabaseMeta.java
ui/src/main/java/org/apache/hop/ui/core/database/dialog/DatabaseExplorerDialog.java

fix #3666 - DuckDB - Explorer shows multiple entries for schemas. Tables and Views not populated in their sections.
fix #3588 - Show layout in database explorer don't work
fix #3738 - DuckDB ALTER COLUMN statement not working

fix #3666, fix #3588, fix #3738

---

engine/src/main/java/org/apache/hop/core/gui/AreaOwner.java
ui/src/main/java/org/apache/hop/ui/core/dialog/ContextDialog.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/DragViewZoomBase.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/PipelineExecutionViewer.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/WorkflowExecutionViewer.java
ui/src/main/java/org/apache/hop/ui/hopgui/shared/BaseExecutionViewer.java

Adapt mouse cursor to context
- Set hand cursor when hover hop or area that support clicking
- Set move cursor when dragging the view or view port
- Set cross cursor when select a region
Edit transform description when clicking on transform info icon 
Edit transform when clicking on hop additional info icon 
Edit transform when clicking on hop stream target/true/false icon 
Cleanup generic in AreaOwner never used
Deprecate some AreaType

Adapt mouse cursor to context #3752

---

plugins/databases/oracle/src/main/java/org/apache/hop/databases/oracle/OracleDatabaseMeta.java
plugins/databases/oracle/src/test/java/org/apache/hop/databases/oracle/OracleDatabaseMetaTest.java

Works with Oracle 12.
Low impact, used only in database explorer.

Oracle databases do support prepared statement metadata retrieval #3515

---

assemblies/lib-jdbc/pom.xml
assemblies/plugins/databases/cratedb-assemblies/pom.xml
assemblies/plugins/databases/cratedb-assemblies/src/assembly/assembly.xml
assemblies/plugins/databases/cratedb-assemblies/src/main/resources/dependencies.xml
assemblies/plugins/databases/cratedb-assemblies/src/main/resources/version.xml
assemblies/plugins/databases/pom.xml
assemblies/plugins/dist/pom.xml
docs/hop-user-manual/modules/ROOT/nav.adoc
docs/hop-user-manual/modules/ROOT/pages/database/databases/cratedb.adoc
plugins/databases/cratedb/pom.xml
plugins/databases/cratedb/src/main/java/org/apache/hop/databases/cratedb/CrateDbDatabaseMeta.java
plugins/databases/cratedb/src/test/java/org/apache/hop/databases/cratedb/CrateDBDatabaseMetaIT.java
plugins/databases/cratedb/src/test/java/org/apache/hop/databases/cratedb/CrateDBDatabaseMetaTest.java
plugins/databases/cratedb/src/test/java/org/apache/hop/databases/cratedb/CrateDBValueMetaBaseTest.java
plugins/databases/cratedb/src/test/java/org/apache/hop/databases/cratedb/ReleaseSavePointTest.java
plugins/databases/pom.xml

3790 - Support CrateDB database plugin

---

core/src/main/java/org/apache/hop/core/row/value/ValueMetaBase.java

fix #3196 Filter Transform - Date filter forces long date format. Impossible to change on the right side after entry.
fix #3200 If you choose a date format mask when entering a value for the filter transform, your value will not be used for compare corrrectly

fix #3196, fix #3200

---

engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineEngine.java
engine/src/main/java/org/apache/hop/workflow/engines/remote/RemoteWorkflowEngine.java

Stop execution with an error and provide an explanation

Remote run configuration refers to itself #3935

---

.dockerignore
Jenkinsfile
docker/Dockerfile.web
docker/create_hop_web_container.sh
docs/hop-dev-manual/modules/ROOT/pages/apache-release/promoting-a-release.adoc

Add jdbc drivers to Hop Web, fixes #4013

---

plugins/actions/movefiles/pom.xml
plugins/actions/movefiles/src/main/java/org/apache/hop/workflow/actions/movefiles/ActionMoveFilesDialog.java
plugins/actions/movefiles/src/test/java/org/apache/hop/workflow/actions/movefiles/AzureMoveFilesIT.java
plugins/actions/movefiles/src/test/java/org/apache/hop/workflow/actions/movefiles/MoveFilesActionHelper.java
plugins/actions/movefiles/src/test/resources/alreadythere.csv
plugins/actions/movefiles/src/test/resources/artists-wildcard1.csv
plugins/actions/movefiles/src/test/resources/artists-wildcard2.csv
plugins/actions/movefiles/src/test/resources/artists.csv
plugins/actions/movefiles/src/test/resources/artists2.csv
plugins/actions/movefiles/src/test/resources/artists3.csv
plugins/actions/movefiles/src/test/resources/artists4.csv
plugins/actions/movefiles/src/test/resources/azure.properties
plugins/actions/movefiles/src/test/resources/canbeoverwritten.csv
plugins/tech/azure/src/main/java/org/apache/hop/vfs/azure/AzureFileNameParser.java
plugins/tech/azure/src/main/java/org/apache/hop/vfs/azure/AzureFileObject.java
plugins/tech/azure/src/main/java/org/apache/hop/vfs/azure/AzureFileProvider.java
plugins/tech/azure/src/test/java/org/apache/hop/vfs/azure/AzureFileNameParserTest.java

Fixes #3988 
The original idea was to use Azurite Testcontainer to mimic the behaviour of Azure.
Unfortunately, the latest version of Azurite is not fully compatible with the latest versions of the Azure Blob Storage Java library (neither the other tries with older version worked, but for different exceptions).
For this reason, we assumed that, sooner or later, such incompatibilities will be fixed, so we provided the possibility to skip testcontainers and test against a real Azure account.
See the instructions in the `azure.properties` file
To make clear that you license your contribution under the [Apache License Version 2.0, January …

Action Move Files - Support of tests against Azurite testcontainer or actual Azure on the cloud

---

plugins/tech/azure/src/main/java/org/apache/hop/vfs/azure/AzureFileObject.java
plugins/tech/azure/src/main/java/org/apache/hop/vfs/azure/BlobInputStream.java

fix #4063 - StorageException while writing large parquet files to ADLSv2

fix #4063 - StorageException while writing large parquet files to ADLSv2

---

plugins/transforms/samplerows/src/main/java/org/apache/hop/pipeline/transforms/samplerows/SampleRowsMeta.java

fix #1927 - Cleanup XML of transform Sample Rows

fix #1927 - Cleanup XML of transform Sample Rows

---

assemblies/static/src/main/resources/hop-conf.sh
assemblies/static/src/main/resources/hop-encrypt.sh
assemblies/static/src/main/resources/hop-gui.sh
assemblies/static/src/main/resources/hop-import.sh
assemblies/static/src/main/resources/hop-run.sh
assemblies/static/src/main/resources/hop-search.sh
assemblies/static/src/main/resources/hop-server.sh
assemblies/static/src/main/resources/hop-translator.sh

The `hop-encrypt.sh`, `hop-gui.sh` and `hop-translator.sh` scripts do not quote the `$@` variable, which causes them to fail if one of their arguments contains spaces ([SC2068](https://www.shellcheck.net/wiki/SC2068)). There are other variables like `BASEDIR`, `ORIGINDIR` and `LIBPATH` that need to be quoted for the same reason.
In this PR I apply these fixes plus a few more found by ShellCheck.

Fix CLI commands on Linux and macOS when variables contain spaces and more ShellCheck fixes

---

engine/src/main/java/org/apache/hop/workflow/action/ActionBase.java
plugins/actions/checkdbconnection/src/main/java/org/apache/hop/workflow/actions/checkdbconnection/ActionCheckDbConnections.java
plugins/actions/columnsexist/src/main/java/org/apache/hop/workflow/actions/columnsexist/ActionColumnsExist.java
plugins/actions/evaluatetablecontent/src/main/java/org/apache/hop/workflow/actions/evaluatetablecontent/ActionEvalTableContent.java
plugins/actions/mssqlbulkload/src/main/java/org/apache/hop/workflow/actions/mssqlbulkload/ActionMssqlBulkLoad.java
plugins/actions/mysqlbulkfile/src/main/java/org/apache/hop/workflow/actions/mysqlbulkfile/ActionMysqlBulkFile.java
plugins/actions/mysqlbulkload/src/main/java/org/apache/hop/workflow/actions/mysqlbulkload/ActionMysqlBulkLoad.java
plugins/actions/sql/src/main/java/org/apache/hop/workflow/actions/sql/ActionSql.java
plugins/actions/waitforsql/src/main/java/org/apache/hop/workflow/actions/waitforsql/ActionWaitForSql.java

Already remove existing internal use, but retain method until 3.0

Deprecate ActionBase.getUsedDatabaseConnections method #2041

---

core/src/main/java/org/apache/hop/core/logging/LogLevel.java
plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/WriteToLog.java
plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/WriteToLogDialog.java
plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/WriteToLogMeta.java

I have a fix for the NPE but for the moment it's not backwards compatible and I haven't found a way in LogLevel or XmlMetadataUtil to use an alias.

Fix transform WriteToLog NPE #4145

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/userdefinedjavaclass.adoc
docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/userdefinedjavaexpression.adoc
plugins/transforms/janino/src/assembly/assembly.xml
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/Janino.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/JaninoDialog.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/JaninoMeta.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/javafilter/JavaFilter.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/FieldHelper.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/TransformDefinition.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClass.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassDef.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassDialog.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassMeta.java
plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/util/JaninoCheckerUtil.java
plugins/transforms/janino/src/main/resources/codeExclusions.xml
plugins/transforms/janino/src/test/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassMetaTest.java

Add option to block execution of specific code. fixes #4238

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/rest.adoc
plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/Rest.java

*) fixes #4195 
*) resolve discrepancies between Hop documentation and behaviour w.r.t. empty/null usernames and password in case of HTTP basic auth

Fix http authentication with proxy

---

core/src/main/java/org/apache/hop/core/svg/HopSvgGraphics2D.java

The DecimalFormat class is not thread-safe, but with an instance by HopSvgGraphics2D I think it won't be a problem.

Locale used by the system generates incorrect SVG syntax #4240

---

pom.xml

Added the cyclonedx maven plugin to generate SBOM files.
Placed the plugin into a profile that will only be executed during our release process.
The SBOM generation does take quite some additional CPU time.

Add Cyclonedx SBOM during release, #4235

---

docs/hop-user-manual/modules/ROOT/assets/files/how-to-guides/apache-airflow/docker-compose.yaml

**Description:**
Added missing volume mounts to `docker-compose.yaml` for Apache Hop.
The `docker-compose.yaml` for Airflow was not working with Apache Hop without this volume mount. Although the documentation mentions this requirement, it was not specified in the file. This fix ensures that the volume is correctly mounted, allowing Airflow to function properly with Apache Hop as intended.

fix: add missing volume mounts to docker-compose.yaml

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/calculator.adoc
plugins/transforms/calculator/src/main/java/org/apache/hop/pipeline/transforms/calculator/Calculator.java
plugins/transforms/calculator/src/main/java/org/apache/hop/pipeline/transforms/calculator/CalculatorMetaFunction.java
plugins/transforms/calculator/src/main/resources/org/apache/hop/pipeline/transforms/calculator/messages/messages_de_DE.properties
plugins/transforms/calculator/src/main/resources/org/apache/hop/pipeline/transforms/calculator/messages/messages_en_US.properties

add encoding for padded base64 data in the calculator transform. Resolves #4255 

add padded base64 calculator function

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/javascript.adoc

added how to create custom json string i.e. as a REST-POST-Body

Cherry pick documentation change

---

docs/hop-user-manual/modules/ROOT/pages/how-to-guides/run-hop-in-apache-airflow.adoc

This pull request updates the `run-hop-in-apache-airflow.adoc` file with more detailed instructions on how to configure Apache Hop to interact with services on the host machine when running in a Docker environment. Specifically, it includes guidance on setting `host.docker.internal` in the Hop connection configuration to allow seamless communication between the Docker container and host services.
**Changes made:**
- Added a note about using `host.docker.internal` for database and service access on the host machine from within Docker containers.
- Clarified interaction with host services in a development environment.
- Ensured the content improves clarity for developers working with Apache Hop and DockerOperator in Airflow.
**Reason for the change:**
This change aims to improve developer …

Improve Documentation for Running Apache Hop in Airflow

---

plugins/misc/git/src/main/java/org/apache/hop/git/GitGuiPlugin.java
plugins/misc/git/src/main/java/org/apache/hop/git/info/GitInfoExplorerFileTypeHandler.java
plugins/misc/git/src/main/java/org/apache/hop/git/model/UIGit.java

Ignored Git files are not correctly detected
Replace deprecated method setName() for RemoteRemoveCommand Add BORDER to TableView in GitInfo

Change the colors in the file explorer when GIT is activated #4316

---

docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/javascript.adoc
plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValues.java
plugins/transforms/javascript/src/main/java/org/apache/hop/pipeline/transforms/javascript/ScriptValuesDialog.java
plugins/transforms/script/src/main/java/org/apache/hop/pipeline/transforms/script/ScriptDialog.java

Fix log message tran_Status -> pipeline_Status
Add constant ABORT_PIPELINE in dialog

TabItem script unreadable in dark mode #4331

---

plugins/transforms/fake/src/main/java/org/apache/hop/pipeline/transforms/fake/FakeDialog.java
plugins/transforms/fake/src/main/java/org/apache/hop/pipeline/transforms/fake/FakeMeta.java

1. NullPointer Exception fix: Changed logging from log.error() to logError() since log is not available in FakeMeta.class.
2. Fix reason for error log: When generating the available Options in FakeDialog.class, private Methods are listed as well. This results into the option, to select a private message and the error, that this method can not be called or is not available. Therefore I added a filter to exclude private Methods from the list of fake topics.
you have to acknowledge this by using the following …

Fix #4341: Use correct logging and hide private Methods as fake data types

---

plugins/actions/xml/src/main/java/org/apache/hop/workflow/actions/xml/xslt/XsltDialog.java

Removed duplicate button, and middle-align label

---

docs/hop-user-manual/modules/ROOT/pages/hop-server/index.adoc

Added ./ to Hop Server commands for Linux/macOS in https://hop.apache.org/manual/latest/hop-server/index.html

added ./ hop server commands linux/macos. fixes #4521

---

plugins/actions/movefiles/src/main/java/org/apache/hop/workflow/actions/movefiles/ActionMoveFiles.java
plugins/actions/movefiles/src/test/java/org/apache/hop/workflow/actions/movefiles/WorkflowActionMoveFilesLocalTest.java

This pull request is meant to fix the movefiles action

HOP-4510: Fix Move Files action error on Windows

---

plugins/actions/ftp/src/main/java/org/apache/hop/workflow/actions/ftp/ActionFtp.java

Added a check to ensure that the FTP file type is set to binary when the binaryMode flag is enabled. This ensures that files are transferred in binary mode, which is necessary for handling non-text files correctly.
- [ X] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [X ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
- [X ] Mention the appropriate issue in your description (for example: …

Fix: Set FTP file type to binary if binaryMode is enabled

---

core/src/main/java/org/apache/hop/metadata/api/HopMetadata.java
core/src/main/java/org/apache/hop/metadata/api/HopMetadataBase.java
core/src/main/java/org/apache/hop/metadata/api/IHopMetadata.java
core/src/main/java/org/apache/hop/metadata/api/IHopMetadataSerializer.java
core/src/main/java/org/apache/hop/metadata/serializer/FileSystemNode.java
core/src/main/java/org/apache/hop/metadata/serializer/json/JsonMetadataSerializer.java
core/src/main/java/org/apache/hop/metadata/serializer/multi/MultiMetadataSerializer.java
core/src/test/java/org/apache/hop/metadata/serializer/json/JsonMetadataSerializerTest.java
plugins/misc/static-schema/src/main/java/org/apache/hop/staticschema/metadata/SchemaDefinition.java
plugins/transforms/excel/src/main/java/org/apache/hop/pipeline/transforms/excelinput/ExcelInputDialog.java
plugins/transforms/excel/src/main/java/org/apache/hop/pipeline/transforms/excelwriter/ExcelWriterTransformDialog.java
plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/csvinput/CsvInputDialog.java
plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/fileinput/text/TextFileInputDialog.java
plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/textfileoutput/TextFileOutputDialog.java
ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataManager.java
ui/src/main/java/org/apache/hop/ui/core/widget/MetaSelectionLine.java
ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
ui/src/main/java/org/apache/hop/ui/hopgui/perspective/metadata/MetadataPerspective.java
ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/metadata/messages/messages_en_US.properties

This PR is linked to [issue #4308](https://github.com/apache/hop/issues/4308), specifically the second point, namely the ability to organise schema definitions in subfolder.
However, this will impact any metadata provider, not just the Static Schema Definition.

Segregate the schema definitions under relevant sub folders

---

.asf.yaml

This reverts commit 54dce3734cac7851d960c5dbc64bf8b773e4272a.

Revert "remove some of the github discussions mails., fixes #4695"

---

assemblies/static/src/main/resources/hop-conf.sh
assemblies/static/src/main/resources/hop-encrypt.sh
assemblies/static/src/main/resources/hop-gui.sh
assemblies/static/src/main/resources/hop-import.sh
assemblies/static/src/main/resources/hop-run.sh
assemblies/static/src/main/resources/hop-search.sh
assemblies/static/src/main/resources/hop-server.sh

Added defensive quoting to XDG_SESSION_TYPE

Added defensive quoting to XDG_SESSION_TYPE #4252

---

core/src/main/java/org/apache/hop/metadata/serializer/json/JsonMetadataSerializer.java

This is a fix for issue #4837, a small regression (caused by the changes for #4779 ). It's seen in the Hop GUI when populating the defined unit tests for a pipeline.

Fix for issue #4837

---

plugins/transforms/denormaliser/src/main/java/org/apache/hop/pipeline/transforms/denormaliser/DenormaliserMeta.java

Again an issue in the clone() method of the metadata.

Fix for issue #4824

---

core/src/main/java/org/apache/hop/core/Condition.java
integration-tests/mdi/0028-join-rows-metadata-parent.hpl
integration-tests/mdi/0028-join-rows-template-child.hpl
integration-tests/mdi/datasets/golden-join-rows.csv
integration-tests/mdi/main-0028-join-rows.hwf
integration-tests/mdi/metadata/dataset/golden-join-rows.json
integration-tests/mdi/metadata/unit-test/0028-join-rows-metadata-parent UNIT.json
plugins/transforms/joinrows/pom.xml
plugins/transforms/joinrows/src/main/java/org/apache/hop/pipeline/transforms/joinrows/JoinRowsDialog.java
plugins/transforms/joinrows/src/main/java/org/apache/hop/pipeline/transforms/joinrows/JoinRowsMeta.java
plugins/transforms/joinrows/src/main/samples/transforms/join_rows.hpl
plugins/transforms/joinrows/src/test/java/org/apache/hop/pipeline/transforms/joinrows/JoinRowsMetaInjectionTest.java
plugins/transforms/joinrows/src/test/java/org/apache/hop/pipeline/transforms/joinrows/JoinRowsMetaTest.java
plugins/transforms/joinrows/src/test/resources/join-rows-transform-with-condition.xml
plugins/transforms/joinrows/src/test/resources/join-rows-transform.xml

add HopMetadataProperty to Mergejoin, fixes #1875

---

plugins/transforms/sqlfileoutput/src/main/java/org/apache/hop/pipeline/transforms/sqlfileoutput/SQLFileOutput.java
plugins/transforms/sqlfileoutput/src/main/java/org/apache/hop/pipeline/transforms/sqlfileoutput/SQLFileOutputDialog.java
plugins/transforms/sqlfileoutput/src/main/java/org/apache/hop/pipeline/transforms/sqlfileoutput/SQLFileOutputMeta.java
plugins/transforms/sqlfileoutput/src/test/java/org/apache/hop/pipeline/transforms/sqlfileoutput/SQLFileOutputMetaTest.java
plugins/transforms/sqlfileoutput/src/test/resources/sql-file-output-transform.xml

add HopMetadataProperty to sql file output, fixes #1935

---

plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsoninput/JsonInput.java
plugins/transforms/json/src/main/resources/org/apache/hop/pipeline/transforms/jsoninput/messages/messages_en_US.properties
plugins/transforms/json/src/main/resources/org/apache/hop/pipeline/transforms/jsoninput/messages/messages_zh_CN.properties

If prev-field is not a json source: 
Receiving multiple rows is not allowed (otherwise: the same json file is loaded repeatedly)

Fix #4876 Always pass field downstream when prev-field isn't a json source(JsonInput)

---

engine/src/main/java/org/apache/hop/pipeline/PipelineMeta.java
plugins/transforms/mergejoin/src/main/java/org/apache/hop/pipeline/transforms/mergejoin/MergeJoinMeta.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineHopDelegate.java
ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/delegates/HopGuiPipelineTransformDelegate.java

Search info&target streams: All hop mets were loaded

Fix #3775 Clean invalid info streams when don't found from previous transforms

---

core/src/main/java/org/apache/hop/core/logging/Slf4jLoggingEventListener.java
core/src/test/java/org/apache/hop/core/logging/Slf4jLoggingEventListenerTest.java
pom.xml

Send general log to SLF4J + cleanup and Junit4 migration, #5198

---

ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataManager.java
ui/src/main/java/org/apache/hop/ui/hopgui/delegates/HopGuiAuditDelegate.java
ui/src/main/java/org/apache/hop/ui/util/SwtErrorHandler.java

TabClosable.closeTab method is calling: disposed some dynamic ui widgets by MetadataPerspective.addEditor method, so should ignore dispose error of swt widgets

Ignore some dispose error of the dynamic ui widgets #3497

---

ui/src/main/java/org/apache/hop/ui/hopgui/context/GuiContextUtil.java

In asynchronous mode, the probability of this dispose error occurring increases.

Ignore the dispose error when Hop-GUI is closed #4042

---

core/src/main/java/org/apache/hop/core/row/value/ValueMetaTimestamp.java

Change the column name to DATA_TYPE
JDK api DatabaseMetaData.getColumns:
1. TABLE_CAT String => table catalog (may be null)
2. TABLE_SCHEM String => table schema (may be null)
3. TABLE_NAME String => table name
4. COLUMN_NAME String => column name
5. DATA_TYPE int => SQL type from java.sql.Types
6. TYPE_NAME String => Data source dependent type name, for a UDT the type name is fully qualified
...

Fix corrected column name by DatabaseMetaData.getColumns api

---

ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiKeyHandler.java

This is just a fix to get it working, but we need to review the key manager

DELETE key is not working in the input fields of metadata #5293

---

plugins/transforms/orabulkloader/src/main/java/org/apache/hop/pipeline/transforms/orabulkloader/OraBulkLoader.java

Fixes #5322
Now using getURL() to retrieve the correct connection string to use in sqlldr command for OracleBulkLoader component.
Previously connection string was empty when using manual connection URL.

#5322: Fix OracleBulkLoader

---

plugins/transforms/dbproc/src/assembly/assembly.xml

The path is set in the ouput directory
```
<baseDirectory>.</baseDirectory>
<files>
<file>
<source>${project.basedir}/src/main/resources/version.xml</source>
<outputDirectory>plugins/transforms/dbproc</outputDirectory>
<filtered>true</filtered>
</file>
</files>
```

Fix base directory assembly.xml of Database Procedure transformation

---

ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java

2.13 switched to using lombok getter and setter annotations in the TableView class. The setter method for the TableViewModifyListener was deleted but the annotation was not added. Causes issues when upgrading from Hop 2.12 with custom plugins which override the default listener behaviour by setting their own.
addresses #5503

Re-add setter for TableViewModifyListener

---

plugins/actions/addresultfilenames/src/main/java/org/apache/hop/workflow/actions/addresultfilenames/ActionAddResultFilenames.java
plugins/transforms/fileexists/src/main/java/org/apache/hop/pipeline/transforms/fileexists/FileExists.java

Switching these plugins to use the correct HopVfs getFileObject method so that the azure/google authentication metadata elements are properly added to the fsm providers map
See before in #5506 
Now these plugins are able to successfully locate the files

Fix Add filenames to result action and File exists transform not finding cloud storage files when using azure/google authentication metadata

---

core/src/main/java/org/apache/hop/core/variables/Variables.java
integration-tests/resolver/0002-pipeline-resolver-test.hpl
integration-tests/resolver/datasets/0002-golden-pipeline-resolver.csv
integration-tests/resolver/metadata/dataset/0002-golden-pipeline-resolver.json
integration-tests/resolver/metadata/unit-test/0002-pipeline-resolver-test UNIT.json

#5602 fix variable resolver substitution failing to preserve other components in string.  Added test to validate in future releases as well.
- [ X ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [ X ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
- [ X ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable.
To make clear that you license your …

#5602 fix variable resolver substitution failing to preserve string

---

pom.xml

This PR updates to Apache POM 35 and set the compiler timestamp for have a clean reproducible build.
- [] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable.

Upgrade to Apache POM 35 and set compiler timestamp for reproducible build

---

core/src/main/java/org/apache/hop/core/Const.java
ui/src/main/java/org/apache/hop/ui/core/database/DatabaseMetaEditor.java
ui/src/main/java/org/apache/hop/ui/core/dialog/MessageBox.java
ui/src/main/java/org/apache/hop/ui/core/dialog/ShowMessageDialog.java
ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditorDialog.java

- Simply displays the result of the database connection check with a different icon, rather than use a specific style.
- Remove core constants SHOW_MESSAGE_DIALOG_DB_TEST_DEFAULT, SHOW_MESSAGE_DIALOG_DB_TEST_SUCCESS.

Fix #5754, propagate style in `ShowMessageDialog` 
